# audiokit.bi -- audiokit for Onyx BASIC (#import audiokit): made by tools/kitbi/kitbi.py from audiokit.abi and the kit's headers;
# not edited by hand. <name> <place> <result> <arguments or -> <C name>; the types: user/Libs/basic/basint.h.
kit audiokit 232
ak_close 26 v p ak_close
ak_control 27 v iii ak_control
ak_f32_to_s16 28 v pppif ak_f32_to_s16
ak_gain_s16 29 v pii ak_gain_s16
ak_info_of 30 v pp ak_info_of
ak_mix_s16 31 v ppii ak_mix_s16
ak_mono_to_stereo 32 v pi ak_mono_to_stereo
ak_note_mhz 33 i i ak_note_mhz
ak_note_name 34 v ip ak_note_name
ak_note_off 35 v ii ak_note_off
ak_note_on 36 i iii ak_note_on
ak_note_parse 37 i s ak_note_parse
ak_notes_off 38 v - ak_notes_off
ak_open 39 l spi ak_open
ak_out_close 40 v - ak_out_close
ak_out_free 41 i - ak_out_free
ak_out_open 42 i ii ak_out_open
ak_out_queued 43 i - ak_out_queued
ak_out_write 44 i pi ak_out_write
ak_pitch_bend 45 v ii ak_pitch_bend
ak_play 46 i si ak_play
ak_play_error 47 s - ak_play_error
ak_play_keep_output 48 v i ak_play_keep_output
ak_play_len_ms 49 l - ak_play_len_ms
ak_play_pause 50 v i ak_play_pause
ak_play_pos_ms 51 l - ak_play_pos_ms
ak_play_seek_ms 52 i i ak_play_seek_ms
ak_play_state 53 i - ak_play_state
ak_play_stop 54 v - ak_play_stop
ak_play_volume 55 i i ak_play_volume
ak_play_wait 56 i i ak_play_wait
ak_program 57 v ii ak_program
ak_read 58 i ppi ak_read
ak_resample 59 i ppipiI ak_resample
ak_resampler_free 60 v p ak_resampler_free
ak_resampler_new 61 l ii ak_resampler_new
ak_seek_ms 62 i pi ak_seek_ms
ak_soundfont_default 63 l pi ak_soundfont_default
ak_soundfont_name 64 s - ak_soundfont_name
ak_synth_free 65 v p ak_synth_free
ak_synth_midi 66 v piiii ak_synth_midi
ak_synth_new 67 l - ak_synth_new
ak_synth_render 68 v ppi ak_synth_render
ak_volume_gain 69 i i ak_volume_gain
ak_wav_header 70 i piii ak_wav_header
ak_wav_save 71 i spii ak_wav_save
ak_chorus_free 206 v p ak_chorus_free
ak_chorus_mute 207 v p ak_chorus_mute
ak_chorus_new 208 l ifff ak_chorus_new
ak_chorus_process 209 v pppFFi ak_chorus_process
ak_fm_instrument 210 i ip ak_fm_instrument
ak_fm_render 211 v pi ak_fm_render
ak_fm_start 212 i iiii ak_fm_start
ak_fm_stop 213 v i ak_fm_stop
ak_note_key 214 i ii ak_note_key
ak_note_octave_mhz 215 i ii ak_note_octave_mhz
ak_reverb_free 216 v p ak_reverb_free
ak_reverb_mute 217 v p ak_reverb_mute
ak_reverb_new 218 l i ak_reverb_new
ak_reverb_process 219 v ppFFi ak_reverb_process
ak_reverb_set 220 v pffff ak_reverb_set
ak_soft_clip 221 f f ak_soft_clip
ak_soundfont_find 222 i spi ak_soundfont_find
ak_soundfont_free 223 v p ak_soundfont_free
ak_soundfont_load 224 l spi ak_soundfont_load
ak_soundfont_prefer 225 v s ak_soundfont_prefer
ak_wav_begin 226 l siii ak_wav_begin
ak_wav_end 227 i p ak_wav_end
ak_wav_write 228 i ppi ak_wav_write
ak_fm_live 229 v i ak_fm_live
ak_fm_silence 230 v - ak_fm_silence
ak_tags_read 231 i sp ak_tags_read
