# filekit.bi -- filekit for Onyx BASIC (#import filekit): made by tools/kitbi/kitbi.py from filekit.abi and the kit's headers;
# not edited by hand. <name> <place> <result> <arguments or -> <C name>; the types: user/Libs/basic/basint.h.
kit filekit 78
adler32 0 u ipi fk_adler32
copy 1 i sscp fk_copy
crc32 2 u ipi fk_crc32
deflate 3 i piiiLI fk_deflate
dos_time_str 4 v ipi fk_dos_time_str
exists 5 i s fk_exists
file_size 6 l s fk_file_size
free 7 v p fk_free
human_size 8 v ipi fk_human_size
inflate 9 i piiiLI fk_inflate
load 10 i sLI fk_load
mkdirs 11 i s fk_mkdirs
move 12 i sscp fk_move
path_ext 13 v spi fk_path_ext
path_folder 14 v spi fk_path_folder
path_join 15 v piss fk_path_join
path_name 16 s s fk_path_name
path_unique 17 v pi fk_path_unique
remove 18 i s fk_remove
save 19 i spi fk_save
tree_size 20 l sII fk_tree_size
zip_close 21 v p fk_zip_close
zip_count 22 i p fk_zip_count
zip_entry 23 i pip fk_zip_entry
zip_error 24 s p fk_zip_error
zip_extract 25 i pis fk_zip_extract
zip_extract_all 26 i psscp fk_zip_extract_all
zip_find 27 i ps fk_zip_find
zip_open 28 l spi fk_zip_open
zip_password 29 v ps fk_zip_password
zip_read 30 i piLI fk_zip_read
zipbuf_add 31 i pspii fk_zipbuf_add
zipbuf_finish 32 i pLI fk_zipbuf_finish
zipbuf_free 33 v p fk_zipbuf_free
zipbuf_new 34 l - fk_zipbuf_new
zipmem_count 35 i pi fk_zipmem_count
zipmem_entry 36 i piipiI fk_zipmem_entry
zipmem_get 37 i pisLI fk_zipmem_get
zipw_add 38 i pss fk_zipw_add
zipw_add_data 39 i pspi fk_zipw_add_data
zipw_close 40 i pcppi fk_zipw_close
zipw_create 41 l s fk_zipw_create
zipw_level 42 v pi fk_zipw_level
arc_add_bytes 44 l ppisii fk_arc_add_bytes
arc_add_conflicts 45 i ppisi fk_arc_add_conflicts
arc_comment 46 s p fk_arc_comment
arc_delete 47 i pscp fk_arc_delete
arc_extract_bytes 48 l ps fk_arc_extract_bytes
arc_extract_with 49 i pp fk_arc_extract_with
arc_format 50 s p fk_arc_format
arc_formats 51 i pi fk_arc_formats
arc_is_name 52 i s fk_arc_is_name
arc_method_name 53 i pipi fk_arc_method_name
arc_new 54 l ss fk_arc_new
arc_new_folder 55 i pscp fk_arc_new_folder
arc_open 56 l spi fk_arc_open
arc_path 57 s p fk_arc_path
arc_probe 58 i spipi fk_arc_probe
arc_rename 59 i psscp fk_arc_rename
arc_test 60 i picp fk_arc_test
arc_writable 61 i p fk_arc_writable
arc_write_empty 62 i p fk_arc_write_empty
fs_basename 63 s s fs_basename
fs_ci_cmp 64 i ss fs_ci_cmp
fs_copy 65 v psi fs_copy
fs_copy_file 66 b ss fs_copy_file
fs_copy_tree 67 b ssi fs_copy_tree
fs_dirname 68 v pis fs_dirname
fs_exists 69 b s fs_exists
fs_is_dir 70 b s fs_is_dir
fs_join 71 v piss fs_join
fs_len 72 i s fs_len
fs_lower 73 b i fs_lower
fs_remove_tree 74 b si fs_remove_tree
fs_skip_dot 75 b s fs_skip_dot
fs_text_fix 76 i pi fs_text_fix
fs_unique_name 77 v pisss fs_unique_name
