// layout_lock.cpp -- GENERATED by tools/libgen/layout.py: the layout lock of the shared library.
// The programs built against the library allocate, derive and read these classes with THESE sizes
// and offsets (wtk/abi.h). A static_assert that fails here means the change breaks every program
// already built: put the new field in the reserve instead (Widget::reserved_ / ext...). Only a class
// ADDED is a reason to regenerate this file (make wtk-layout-update).
#ifdef ONYX_LIB_BUILD
#include "onyxpp.hpp"
#include "wtk/wtk.h"
#include "wtk/abi.h"
#include "wtk/button.h"
#include "wtk/calendar.h"
#include "wtk/canvas.h"
#include "wtk/checkbox.h"
#include "wtk/colorpick.h"
#include "wtk/combobox.h"
#include "wtk/datagrid.h"
#include "wtk/dialog.h"
#include "wtk/dropdown.h"
#include "wtk/font.h"
#include "wtk/global.h"
#include "wtk/groupbox.h"
#include "wtk/icon.h"
#include "wtk/imagebox.h"
#include "wtk/knob.h"
#include "wtk/label.h"
#include "wtk/lang.h"
#include "wtk/layout.h"
#include "wtk/lcd.h"
#include "wtk/listbox.h"
#include "wtk/menu.h"
#include "wtk/numeric.h"
#include "wtk/paint.h"
#include "wtk/panel.h"
#include "wtk/progress.h"
#include "wtk/radio.h"
#include "wtk/richtextbox.h"
#include "wtk/root.h"
#include "wtk/scrollbar.h"
#include "wtk/segmented.h"
#include "wtk/skin.h"
#include "wtk/slider.h"
#include "wtk/splitter.h"
#include "wtk/tabhost.h"
#include "wtk/text.h"
#include "wtk/textarea.h"
#include "wtk/textbox.h"
#include "wtk/theme.h"
#include "wtk/toggle.h"
#include "wtk/toolbar.h"
#include "wtk/treeview.h"
#include "wtk/vpaint.h"
#include "wtk/vumeter.h"
#include "wtk/widget.h"
#include "wtk/wtk.h"

static_assert (sizeof (wtk::Button) == 296, "sizeof (Button) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Calendar) == 256, "sizeof (Calendar) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Canvas) == 56, "sizeof (Canvas) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Checkbox) == 312, "sizeof (Checkbox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ColorDialog) == 272, "sizeof (ColorDialog) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ColorPicker) == 248, "sizeof (ColorPicker) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Combobox) == 1832, "sizeof (Combobox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::DataGrid) == 3960, "sizeof (DataGrid) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::DatePicker) == 272, "sizeof (DatePicker) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Dropdown) == 272, "sizeof (Dropdown) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::FileDialog) == 12968, "sizeof (FileDialog) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Font) == 40, "sizeof (Font) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::GroupBox) == 280, "sizeof (GroupBox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::HSplitter) == 280, "sizeof (HSplitter) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::HorizontalStackPanel) == 240, "sizeof (HorizontalStackPanel) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Icon) == 328, "sizeof (Icon) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ImageBox) == 256, "sizeof (ImageBox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Knob) == 320, "sizeof (Knob) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Label) == 360, "sizeof (Label) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::LcdDisplay) == 352, "sizeof (LcdDisplay) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ListBox) == 280, "sizeof (ListBox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Menu) == 3088, "sizeof (Menu) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::MessageBox) == 256, "sizeof (MessageBox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Modal) == 232, "sizeof (Modal) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::NumericUpDown) == 272, "sizeof (NumericUpDown) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Panel) == 232, "sizeof (Panel) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::PopupMenu) == 592, "sizeof (PopupMenu) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Progress) == 240, "sizeof (Progress) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::RadioButton) == 312, "sizeof (RadioButton) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::RichTextBox) == 312, "sizeof (RichTextBox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Root) == 336, "sizeof (Root) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::RtStyle) == 4, "sizeof (RtStyle) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Scrollbar) == 248, "sizeof (Scrollbar) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::SegmentedControl) == 696, "sizeof (SegmentedControl) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Skin) == 48, "sizeof (Skin) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Slider) == 256, "sizeof (Slider) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Splitter) == 280, "sizeof (Splitter) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::TabHost) == 632, "sizeof (TabHost) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::TextFace) == 8, "sizeof (TextFace) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Textarea) == 296, "sizeof (Textarea) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Textbox) == 776, "sizeof (Textbox) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ToggleSwitch) == 312, "sizeof (ToggleSwitch) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ToolBar) == 344, "sizeof (ToolBar) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::ToolButton) == 320, "sizeof (ToolButton) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::TreeView) == 288, "sizeof (TreeView) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::UniformGridLayout) == 248, "sizeof (UniformGridLayout) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::VPath) == 40, "sizeof (VPath) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::VSplitter) == 280, "sizeof (VSplitter) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::VerticalStackPanel) == 240, "sizeof (VerticalStackPanel) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::VuMeter) == 312, "sizeof (VuMeter) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::Widget) == 224, "sizeof (Widget) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkBarDrag) == 2, "sizeof (WkBarDrag) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkCorner) == 292, "sizeof (WkCorner) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkFaceScope) == 16, "sizeof (WkFaceScope) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkNamedTheme) == 24, "sizeof (WkNamedTheme) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkPalette) == 28, "sizeof (WkPalette) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkTheme) == 44, "sizeof (WkTheme) changed: programs built before break (wtk/abi.h)");
static_assert (sizeof (wtk::WkThumb) == 12, "sizeof (WkThumb) changed: programs built before break (wtk/abi.h)");
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
static_assert (__builtin_offsetof (wtk::Widget, canvas) == 8, "Widget::canvas moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, left) == 64, "Widget::left moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, tag) == 88, "Widget::tag moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, anchor) == 100, "Widget::anchor moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, transparent) == 112, "Widget::transparent moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, tip) == 128, "Widget::tip moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, parent) == 136, "Widget::parent moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, prevHandled) == 176, "Widget::prevHandled moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, ext) == 184, "Widget::ext moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Widget, reserved_) == 192, "Widget::reserved_ moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, px) == 0, "Canvas::px moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, w) == 8, "Canvas::w moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, stride) == 16, "Canvas::stride moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, owns) == 20, "Canvas::owns moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, capH) == 24, "Canvas::capH moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Canvas, ext) == 32, "Canvas::ext moved: programs built before break (wtk/abi.h)");
static_assert (__builtin_offsetof (wtk::Root, bg) == 224, "Root::bg moved: programs built before break (wtk/abi.h)");
#endif
