#!/bin/sh
# build-web.sh -- build Jet, the browser on WebKit (user/Apps/jet: its window on uikit, engine_webkit.cpp on
# WebKit2's C API), against the build of build-webkit.sh, with the POSIX toolchain (aarch64-onyx-elf):
# ONE program that is the window and, started again by WebKit, its web and network processes.
#
#   sh tools/webkit/build-webkit.sh             # libWebKit.a first
#   sh tools/webkit/build-web.sh                # -> $BUILD/bin/web, stripped into sdcard/apps/jet.app/main
#   BUILD=$HOME/webkit-build/webkit-jit sh tools/webkit/build-web.sh     # the package's program: the tree
#                                               # with JavaScriptCore's JIT (docs/08 "The JIT")
#
# The window's toolkit is the shared library SD:/lib/uikit.so, as every app's (since 2026-10-05; it was
# compiled again into the program before): its import side -- the stubs, the bind constructor, the shared
# variables, generated by user/Makefile (`make -C user lib/uikit.imp.a`) -- is compiled here for this
# toolchain. A hosted C++ program: libstdc++'s operator new, not onyxpp.hpp's -- -DONYX_HOSTED_NEW says so
# to that header, which uikit.h includes; without it the whole program, Skia too, allocates on umm.h's
# heap, whose kapi_sbrk is a kernel call an app core may not make: the link is checked. (The library
# allocates through the program's operator new: newlib's malloc.) engine_webkit.cpp is compiled with the command one of WebKit's own sources gets (its
# forwarding headers, its config.h). Variables: as build-wctest.sh; STAGE=0 leaves sdcard/ alone.
#
# Copyright (c) 2026 Stéphane Wegener and the Onyx contributors. MIT licence (see fetch.sh).
set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
ONYX=$(cd "$HERE/../.." && pwd)
if [ -z "${WEBKIT_DIR:-}" ]; then
	if [ -d /home/user ]; then WEBKIT_DIR=/home/user/webkit; else WEBKIT_DIR=$HOME/webkit; fi
fi
: "${BUILD:=$WEBKIT_DIR-build/webcore}"
: "${ONYX_SYSROOT:=$ONYX/out/sysroot-onyx}"
: "${JOBS:=$(nproc)}"
PATH=/opt/toolchains/aarch64-onyx-elf-14.2/bin:$PATH
export PATH
S=$ONYX_SYSROOT
APP=$ONYX/user/Apps/jet
O=$BUILD/web
mkdir -p "$O/uikit" "$BUILD/bin"

[ -f "$BUILD/lib/libWebKit.a" ] || { echo "build-web.sh: no $BUILD/lib/libWebKit.a: sh tools/webkit/build-webkit.sh" >&2; exit 1; }

CXX="aarch64-onyx-elf-g++ -specs=$S/lib/onyx.specs -std=gnu++17 -O2 -mcpu=cortex-a72 -fno-exceptions -fno-rtti -w \
	-ffunction-sections -fdata-sections -DONYX_HOSTED_NEW -I$ONYX/user -I$ONYX/kernel/include"

# ---- uikit: the import side of SD:/lib/uikit.so, for this toolchain ----
echo "web: uikit (the shared library's import side)"
U=$ONYX/user
for f in lib/uikit_stubs.S lib/uikit_bind.cpp; do
	[ -f "$U/$f" ] || { echo "build-web.sh: no $U/$f: make -C user lib/uikit.imp.a (the Arm toolchain) first" >&2; exit 1; }
done
rm -rf "$O/uikit"; mkdir -p "$O/uikit"
aarch64-onyx-elf-gcc -mcpu=cortex-a72 -c "$U/lib/uikit_stubs.S" -o "$O/uikit/stubs.o"
$CXX -c "$U/lib/uikit_bind.cpp" -o "$O/uikit/bind.o"
$CXX -c "$U/uikit/globals.cpp" -o "$O/uikit/globals.o"
rm -f "$O/libuikit.a"
UIKIT="$O/uikit/globals.o $O/uikit/bind.o $O/uikit/stubs.o"

# ---- the window ----
echo "web: the window"
WIN=""
for f in "$APP"/*.cpp; do				# (all but the engines: main, downloads, ...)
	case $(basename "$f") in engine_*) continue ;; esac
	o="$O/$(basename "$f" .cpp).o"
	$CXX -c "$f" -o "$o"
	WIN="$WIN $o"
done

# ---- the engine: the command of one of WebKit's own sources, the file swapped ----
ref=UIProcess/API/C/onyx/WKRunLoop.cpp
cmd=$(cd "$BUILD" && ninja -t commands lib/libWebKit.a | grep -F "$ref" | grep -F -- " -c " | head -n 1)
[ -n "$cmd" ] || { echo "build-web.sh: no compile command for $ref in $BUILD" >&2; exit 1; }
cmd=$(printf '%s' "$cmd" | sed -E 's/ -MD -MT [^ ]+ -MF [^ ]+//; s| -o [^ ]+| -o web/engine_webkit.o|; s| -c [^ ]+| -c '"$APP"'/engine_webkit.cpp|')
echo "web: the engine"
( cd "$BUILD" && sh -c "$cmd" )

# ---- link: the window, uikit's import side, WebKit, the sysroot's libraries ----
WK="-Wl,--start-group $BUILD/lib/libWebKit.a $BUILD/lib/libWebCore.a $BUILD/lib/libPAL.a $BUILD/lib/libJavaScriptCore.a $BUILD/lib/libWTF.a $BUILD/lib/libbmalloc.a -Wl,--end-group"
LIBS=""
for l in skia harfbuzz-icu harfbuzz freetype png16 jpeg webpmux webpdemux webp sharpyuv curl mbedtls mbedx509 mbedcrypto \
	nghttp2 brotlidec xml2 sqlite3 z icui18n icuuc icudata; do
	LIBS="$LIBS $S/lib/lib$l.a"
done
# Skia keeps to the sizes it asks for (skmallocsize.c; SKMALLOCSIZE=0: Skia's own sk_malloc_size, newlib's
# malloc_usable_size -- which /bin/malloctest shows to be right: what crashed Web on the Pi with it is
# not known yet, docs/08-WEBKIT-PORT.md "Step 3")
aarch64-onyx-elf-gcc -specs=$S/lib/onyx.specs -O2 -mcpu=cortex-a72 -c "$HERE/skmallocsize.c" -o "$O/skmallocsize.o"
SKMS="$O/skmallocsize.o -Wl,--wrap=_Z14sk_malloc_sizePvm"
[ "${SKMALLOCSIZE:-1}" = 1 ] || SKMS=""
# The compositor's two C files (WebKit's USE(GRAPHICS_LAYER_ONYX) calls them; they call the kernel through
# appkit.h): the GPU compositing service, built as user/Makefile builds it, and the kernel surfaces.
GPC="$O/gpucomp.o $O/onyxsurface.o $O/onyxcores.o"
aarch64-onyx-elf-gcc -specs=$S/lib/onyx.specs -O3 -mcpu=cortex-a72 -ffp-contract=off -fno-math-errno \
	-I"$ONYX/user" -I"$ONYX/kernel/include" -c "$ONYX/user/gpucomp/gpucomp.c" -o "$O/gpucomp.o"
aarch64-onyx-elf-gcc -specs=$S/lib/onyx.specs -O2 -mcpu=cortex-a72 \
	-I"$ONYX/user" -I"$ONYX/kernel/include" -c "$HERE/onyxsurface.c" -o "$O/onyxsurface.o"
# The tiles rasterised on Onyx's app cores (onyxcores.c: the workers, and core 0's locks, which must not
# sleep while an app core may hold them -- the four entries wrapped here; it uses libonyxposix's
# internals for the workers' TLS).
aarch64-onyx-elf-gcc -specs=$S/lib/onyx.specs -O2 -mcpu=cortex-a72 \
	-I"$ONYX/user" -I"$ONYX/user/libc/posix" -I"$ONYX/kernel/include" -c "$HERE/onyxcores.c" -o "$O/onyxcores.o"
GPC="$GPC -Wl,--wrap=__retarget_lock_acquire -Wl,--wrap=__retarget_lock_acquire_recursive -Wl,--wrap=sem_wait -Wl,--wrap=pthread_mutex_lock -Wl,--wrap=pread -Wl,--wrap=pwrite"
# HEAPCHECK=1: the checking malloc of heapcheck.c in front of newlib's (a hunt for heap corruption);
# HEAPCHECK=2: the same with blocks as large as newlib's and a malloc_usable_size that says so, Skia
# filling them (no skmallocsize.o): what Skia does with the slack, under the canaries
HC=""
if [ "${HEAPCHECK:-0}" != 0 ]; then
	HCD=""
	if [ "$HEAPCHECK" = 2 ]; then HCD=-DHEAPCHECK_SLACK; SKMS=""; fi
	aarch64-onyx-elf-gcc -specs=$S/lib/onyx.specs -O2 -mcpu=cortex-a72 -fno-omit-frame-pointer $HCD -c "$HERE/heapcheck.c" -o "$O/heapcheck.o"
	HC="$O/heapcheck.o"
	for f in malloc free realloc calloc memalign aligned_alloc posix_memalign malloc_usable_size; do HC="$HC -Wl,--wrap=$f"; done
	echo "web: with heapcheck ($HEAPCHECK)"
fi
# Onyx's media library and its codecs (user/av: libvpx, dav1d, opus), which WebKit's media engine
# (MediaPlayerPrivateOnyx, ENABLE_VIDEO) calls: av.mk builds them for this toolchain, what changed only.
AVL=""
if aarch64-onyx-elf-nm "$BUILD/lib/libWebCore.a" 2>/dev/null | grep -q ' U av_player_new'; then
	echo "web: the media library"
	make -s -f "$HERE/av.mk" ONYX="$ONYX" S="$S" O="$O/av" -j"$JOBS"
	AVL="$O/av/libonyxav.a"
fi
echo "web: link"
aarch64-onyx-elf-g++ -mcpu=cortex-a72 -specs="$S/lib/onyx.specs" -L"$S/lib" -Wl,--gc-sections \
	$WIN "$O/engine_webkit.o" $UIKIT $SKMS $HC $GPC $WK $AVL $LIBS -o "$BUILD/bin/web"
aarch64-onyx-elf-size "$BUILD/bin/web"
# The program's allocator is newlib's malloc alone (its _sbrk goes through the app-core RPC): no umm
# heap, whose kapi_sbrk on an app core stops the raster job there and hangs the page (onyxcores.c).
if aarch64-onyx-elf-nm "$BUILD/bin/web" | grep -q ' umm__\| _Z8onyx_newmPv'; then
	echo "build-web.sh: $BUILD/bin/web has onyxpp.hpp's operator new (umm.h over kapi_sbrk): -DONYX_HOSTED_NEW is missing somewhere" >&2
	exit 1
fi
# ... and malloc & co are newlib's own: a weak definition in a header of user/ (user/img/imgload.hpp's,
# over operator new) wins over the C library's in a static link.
weak=$(aarch64-onyx-elf-nm "$BUILD/bin/web" | grep -E ' [WwVv] (malloc|free|calloc|realloc|memalign|_malloc_r|_free_r)$' || true)
if [ -n "$weak" ]; then
	echo "build-web.sh: $BUILD/bin/web has a weak malloc / free / calloc / realloc, not newlib's:" >&2
	echo "$weak" >&2
	exit 1
fi

if [ "${STAGE:-1}" = 1 ]; then
	mkdir -p "$ONYX/sdcard/apps/jet.app"
	aarch64-onyx-elf-strip -o "$ONYX/sdcard/apps/jet.app/main" "$BUILD/bin/web"
	cp "$APP/app.txt" "$APP/start.html" "$ONYX/sdcard/apps/jet.app/"
	ls -l "$ONYX/sdcard/apps/jet.app/main"
fi
