//
// tl.h -- the Telegram app's TL codec: the API's schema (schema.inc, generated by
// tools/telegram/mkschema.py) read once at start, then ANY object of it decoded into a tree of
// values and encoded back -- no code a constructor. A value's fields are found by their names:
//
//   tl::Arena a;  tl::Val v;
//   if (tl::decode (a, buf, len, v) && v.is ("message"))  printf ("%s", v["message"].str ());
//   tl::Val *q = tl::make (a, "messages.getHistory");  q->set ("peer", peer);  q->set ("limit", tl::I (50));
//   tl::Buf b;  tl::encode (b, *q);			(the flags fields made from the fields present)
//
// Everything a decode or a make allocates lives in the Arena: freeing it is one call. The values
// are read only; a missing field (a flag not set, a wrong name) reads as tl::none (0, "", empty).
//
// Portable C++ (newlib or the PC's libc): malloc, memcpy, strcmp only. MIT licence.
//
#ifndef TG_TL_H
#define TG_TL_H

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#include "schema.inc"

// gzip_packed's inflate, given by the platform (tgplat.h): a gzip stream -> malloc'd bytes (*out).
bool tg_gunzip (const unsigned char *in, int n, unsigned char **out, int *outn);

namespace tl {

// ---- the arena -------------------------------------------------------------------------------------

class Arena
{
public:
	Arena () : m_blk (0), m_used (0), m_cap (0) {}
	~Arena () { clear (); }
	void *alloc (unsigned n)
	{
		n = (n + 7) & ~7u;
		if (m_used + n > m_cap)
		{
			unsigned cap = n + 8 > 16384 ? n + 8 : 16384;
			Blk *b = (Blk *) malloc (sizeof (Blk) + cap);
			if (!b) return 0;
			b->next = m_blk; m_blk = b; m_used = 0; m_cap = cap;
		}
		void *p = (char *) (m_blk + 1) + m_used;
		m_used += n;
		return p;
	}
	void *zalloc (unsigned n) { void *p = alloc (n); if (p) memset (p, 0, n); return p; }
	char *dup (const void *s, int n)		// n bytes and a NUL
	{
		char *p = (char *) alloc ((unsigned) n + 1);
		if (!p) return 0;
		if (n) memcpy (p, s, (size_t) n);
		p[n] = 0;
		return p;
	}
	void clear ()
	{
		while (m_blk) { Blk *n = m_blk->next; free (m_blk); m_blk = n; }
		m_used = m_cap = 0;
	}
private:
	struct Blk { Blk *next; unsigned long pad; };
	Blk *m_blk;
	unsigned m_used, m_cap;
	Arena (const Arena &);
	Arena &operator= (const Arena &);
};

// ---- the schema ------------------------------------------------------------------------------------

enum TK : unsigned char
{
	T_INT, T_LONG, T_DOUBLE, T_STRING, T_BYTES, T_BOOL, T_TRUE, T_INT128, T_INT256, T_FLAGS,
	T_VEC,			// Vector<t>: boxed (its id, the count, the items)
	T_BVEC,			// vector<t>: bare (the count, the items)
	T_OBJ,			// a boxed object of any constructor (its id first)
	T_BARE			// a bare object: one constructor, known (no id)
};

struct Ctor;
struct Type { TK k; const Type *elem; const Ctor *bare; };
struct Param { const char *name; const Type *t; short flag; signed char bit; };	// flag: the index of its # field, -1
struct Ctor
{
	uint32_t id;
	const char *name;		// "messages.getHistory"
	const char *type;		// its result type's name ("messages.Messages")
	const Type *result;		// (a function's: how its answer is read)
	bool fn;
	unsigned short np;
	Param *p;
	int field (const char *nm) const
	{
		for (int i = 0; i < np; i++) if (!strcmp (p[i].name, nm)) return i;
		return -1;
	}
};

struct Schema
{
	Arena mem;
	Ctor *ctors;
	int n;
	const Ctor **byId;		// open addressing, ID_SLOTS
	const Ctor **byName;
	int layer;
	enum { ID_SLOTS = 8192 };
	Schema () : ctors (0), n (0), byId (0), byName (0), layer (TL_LAYER) {}
};

inline Schema &schema () { static Schema s; return s; }

inline unsigned strhash (const char *s, int n = -1)
{
	unsigned h = 2166136261u;
	for (int i = 0; n < 0 ? s[i] != 0 : i < n; i++) { h ^= (unsigned char) s[i]; h *= 16777619u; }
	return h;
}

inline const Ctor *by_id (uint32_t id)
{
	Schema &S = schema ();
	if (!S.byId) return 0;
	for (unsigned i = (id * 2654435761u) & (Schema::ID_SLOTS - 1); S.byId[i]; i = (i + 1) & (Schema::ID_SLOTS - 1))
		if (S.byId[i]->id == id) return S.byId[i];
	return 0;
}

inline const Ctor *by_name (const char *name)
{
	Schema &S = schema ();
	if (!S.byName) return 0;
	for (unsigned i = strhash (name) & (Schema::ID_SLOTS - 1); S.byName[i]; i = (i + 1) & (Schema::ID_SLOTS - 1))
		if (!strcmp (S.byName[i]->name, name)) return S.byName[i];
	return 0;
}

// The constructor whose result type is tname (a bare "%Type"): the first one.
inline const Ctor *by_type (const char *tname)
{
	Schema &S = schema ();
	for (int i = 0; i < S.n; i++) if (!S.ctors[i].fn && !strcmp (S.ctors[i].type, tname)) return &S.ctors[i];
	return 0;
}

// A type's text ("Vector<long>", "flags.3?string" without its condition) -> its Type. The bare
// constructors are found after every line is read (fix_bare).
inline const Type *parse_type (const char *s, int n)
{
	Schema &S = schema ();
	Type *t = (Type *) S.mem.zalloc (sizeof (Type));
	struct { const char *nm; TK k; } bi[] = {
		{ "int", T_INT }, { "long", T_LONG }, { "double", T_DOUBLE }, { "string", T_STRING },
		{ "bytes", T_BYTES }, { "Bool", T_BOOL }, { "true", T_TRUE }, { "int128", T_INT128 },
		{ "int256", T_INT256 }, { "#", T_FLAGS } };
	for (unsigned i = 0; i < sizeof bi / sizeof bi[0]; i++)
		if ((int) strlen (bi[i].nm) == n && !memcmp (bi[i].nm, s, (size_t) n)) { t->k = bi[i].k; return t; }
	if ((n > 8 && !memcmp (s, "Vector<", 7)) || (n > 8 && !memcmp (s, "vector<", 7)))
	{
		t->k = s[0] == 'V' ? T_VEC : T_BVEC;
		t->elem = parse_type (s + 7, n - 8);
		return t;
	}
	// a bare constructor: "%Type", or a lowercase name (after its namespace)
	int dot = -1;
	for (int i = 0; i < n; i++) if (s[i] == '.') dot = i;
	char c = s[dot + 1];
	if (s[0] == '%' || (c >= 'a' && c <= 'z'))
	{
		t->k = T_BARE;
		t->bare = (const Ctor *) S.mem.dup (s, n);	// (its name for now: fix_bare)
		return t;
	}
	t->k = T_OBJ;					// Object, !X, X, a boxed type
	return t;
}

// Reads schema.inc's text (once): false if it is broken.
inline bool load ()
{
	Schema &S = schema ();
	if (S.ctors) return true;
	const char *txt = tl_schema_text;
	int lines = 0;
	for (const char *p = txt; *p; p++) if (*p == '\n') lines++;
	S.ctors = (Ctor *) S.mem.zalloc (sizeof (Ctor) * (unsigned) lines);
	S.byId = (const Ctor **) S.mem.zalloc (sizeof (Ctor *) * Schema::ID_SLOTS);
	S.byName = (const Ctor **) S.mem.zalloc (sizeof (Ctor *) * Schema::ID_SLOTS);
	if (!S.ctors || !S.byId || !S.byName) return false;
	const char *p = txt;
	while (*p)
	{
		const char *e = p;
		while (*e && *e != '\n') e++;
		Ctor &c = S.ctors[S.n];
		const char *q = p;
		if (q[0] == 'F' && q[1] == ' ') { c.fn = true; q += 2; }
		uint32_t id = 0;
		while (q < e && *q != ' ')
		{
			char h = *q++;
			id = id * 16 + (uint32_t) (h >= 'a' ? h - 'a' + 10 : h - '0');
		}
		c.id = id;
		q++;
		const char *nm = q;
		while (q < e && *q != ' ') q++;
		c.name = S.mem.dup (nm, (int) (q - nm));
		// the params, up to " = "
		Param tmp[128];
		int np = 0;
		while (q < e)
		{
			while (q < e && *q == ' ') q++;
			if (*q == '=') break;
			const char *ps = q;
			while (q < e && *q != ' ') q++;
			const char *colon = ps;
			while (colon < q && *colon != ':') colon++;
			if (colon >= q || np >= 128) return false;
			Param &pr = tmp[np++];
			pr.name = S.mem.dup (ps, (int) (colon - ps));
			pr.flag = -1; pr.bit = 0;
			const char *ts = colon + 1;
			const char *qm = ts;
			while (qm < q && *qm != '?') qm++;
			if (qm < q)				// flags.3?type
			{
				const char *dt = ts;
				while (dt < qm && *dt != '.') dt++;
				int bit = 0;
				for (const char *d = dt + 1; d < qm; d++) bit = bit * 10 + (*d - '0');
				pr.bit = (signed char) bit;
				for (int k = 0; k < np - 1; k++)
					if ((int) strlen (tmp[k].name) == dt - ts && !memcmp (tmp[k].name, ts, (size_t) (dt - ts))) pr.flag = (short) k;
				if (pr.flag < 0) return false;
				ts = qm + 1;
			}
			pr.t = parse_type (ts, (int) (q - ts));
		}
		if (*q == '=') q++;
		while (q < e && *q == ' ') q++;
		c.type = S.mem.dup (q, (int) (e - q));
		c.result = parse_type (q, (int) (e - q));
		c.np = (unsigned short) np;
		c.p = (Param *) S.mem.alloc (sizeof (Param) * (unsigned) (np ? np : 1));
		memcpy (c.p, tmp, sizeof (Param) * (unsigned) np);
		unsigned i = (id * 2654435761u) & (Schema::ID_SLOTS - 1);
		while (S.byId[i]) i = (i + 1) & (Schema::ID_SLOTS - 1);
		S.byId[i] = &c;
		i = strhash (c.name) & (Schema::ID_SLOTS - 1);
		while (S.byName[i]) i = (i + 1) & (Schema::ID_SLOTS - 1);
		S.byName[i] = &c;
		S.n++;
		p = *e ? e + 1 : e;
	}
	// the bare types' constructors, now that all are known
	for (int i = 0; i < S.n; i++)
		for (int k = 0; k < S.ctors[i].np; k++)
			for (const Type *t = S.ctors[i].p[k].t; t; t = t->elem)
				if (t->k == T_BARE)
				{
					const char *nm = (const char *) t->bare;
					const Ctor *b = nm[0] == '%' ? by_type (nm + 1) : by_name (nm);
					((Type *) t)->bare = b;
				}
	return true;
}

// ---- values ----------------------------------------------------------------------------------------

enum VK : unsigned char { V_NONE, V_INT, V_LONG, V_DOUBLE, V_BYTES, V_BOOL, V_OBJ, V_VEC, V_RAW };

struct Val
{
	VK k;
	int n;				// bytes: the length; an object: its fields; a vector: its items
	const Ctor *c;			// an object's constructor
	union { long long l; double d; const char *s; Val *v; };

	Val () : k (V_NONE), n (0), c (0), l (0) {}

	bool ok () const { return k != V_NONE; }
	bool is (const char *ctor) const { return k == V_OBJ && c && !strcmp (c->name, ctor); }
	const char *name () const { return k == V_OBJ && c ? c->name : ""; }
	long long i () const { return k == V_INT || k == V_LONG || k == V_BOOL ? l : k == V_OBJ && c && c->id == 0x997275b5 ? 1 : 0; }
	bool b () const { return i () != 0; }
	const char *str () const { return k == V_BYTES && s ? s : ""; }
	int len () const { return k == V_BYTES ? n : 0; }
	int count () const { return k == V_VEC ? n : 0; }
	inline const Val &operator[] (const char *field) const;
	inline const Val &operator[] (int i) const;
	// (making a request) a field set by name; false: no such field
	bool set (const char *field, const Val &x)
	{
		if (k != V_OBJ || !c) return false;
		int f = c->field (field);
		if (f < 0) return false;
		v[f] = x;
		return true;
	}
};

inline const Val &none () { static Val z; return z; }
inline const Val &Val::operator[] (const char *field) const
{
	if (k != V_OBJ || !c) return none ();
	int f = c->field (field);
	return f < 0 ? none () : v[f];
}
inline const Val &Val::operator[] (int i) const { return k == V_VEC && i >= 0 && i < n ? v[i] : none (); }

inline Val I (int x) { Val r; r.k = V_INT; r.l = x; return r; }
inline Val L (long long x) { Val r; r.k = V_LONG; r.l = x; return r; }
inline Val D (double x) { Val r; r.k = V_DOUBLE; r.d = x; return r; }
inline Val B (bool x) { Val r; r.k = V_BOOL; r.l = x ? 1 : 0; return r; }
inline Val T () { return B (true); }			// a "true" flag
inline Val S (Arena &a, const void *p, int n) { Val r; r.k = V_BYTES; r.s = a.dup (p, n); r.n = n; return r; }
inline Val S (Arena &a, const char *str) { return S (a, str, (int) strlen (str)); }
inline Val Raw (Arena &a, const void *p, int n) { Val r = S (a, p, n); r.k = V_RAW; return r; }	// encoded as it is
inline Val Vec (Arena &a, int n) { Val r; r.k = V_VEC; r.n = n; r.v = (Val *) a.zalloc (sizeof (Val) * (unsigned) (n ? n : 1)); return r; }
// A new object of that constructor, its fields empty (0 if the name is unknown).
inline Val *make (Arena &a, const char *ctor)
{
	const Ctor *c = by_name (ctor);
	if (!c) return 0;
	Val *r = (Val *) a.zalloc (sizeof (Val));
	r->k = V_OBJ; r->c = c; r->n = c->np;
	r->v = (Val *) a.zalloc (sizeof (Val) * (unsigned) (c->np ? c->np : 1));
	return r;
}
inline Val obj (Arena &a, const char *ctor) { Val *p = make (a, ctor); return p ? *p : none (); }
// A copy whose memory is the arena's (a value kept from another arena's decode).
inline Val copy (Arena &a, const Val &x)
{
	Val r = x;
	if (x.k == V_BYTES || x.k == V_RAW) r.s = a.dup (x.s, x.n);
	else if (x.k == V_OBJ || x.k == V_VEC)
	{
		r.v = (Val *) a.zalloc (sizeof (Val) * (unsigned) (x.n ? x.n : 1));
		for (int i = 0; i < x.n; i++) r.v[i] = copy (a, x.v[i]);
	}
	return r;
}

// ---- the byte buffer (encoding) ----------------------------------------------------------------

class Buf
{
public:
	unsigned char *d;
	int n, cap;
	Buf () : d (0), n (0), cap (0) {}
	~Buf () { free (d); }
	bool room (int m)
	{
		if (n + m <= cap) return true;
		int c = cap ? cap * 2 : 256;
		while (c < n + m) c *= 2;
		unsigned char *x = (unsigned char *) realloc (d, (size_t) c);
		if (!x) return false;
		d = x; cap = c;
		return true;
	}
	void put (const void *p, int m) { if (m > 0 && room (m)) { memcpy (d + n, p, (size_t) m); n += m; } }
	void u32 (uint32_t x) { unsigned char b[4] = { (unsigned char) x, (unsigned char) (x >> 8), (unsigned char) (x >> 16), (unsigned char) (x >> 24) }; put (b, 4); }
	void i64 (long long x) { u32 ((uint32_t) x); u32 ((uint32_t) ((unsigned long long) x >> 32)); }
	void str (const void *p, int m)			// TL's string / bytes
	{
		if (m < 254) { unsigned char l = (unsigned char) m; put (&l, 1); }
		else { unsigned char h[4] = { 254, (unsigned char) m, (unsigned char) (m >> 8), (unsigned char) (m >> 16) }; put (h, 4); }
		put (p, m);
		int tot = m < 254 ? m + 1 : m + 4;
		static const unsigned char z[4] = { 0, 0, 0, 0 };
		if (tot % 4) put (z, 4 - tot % 4);
	}
	void clear () { n = 0; }
	unsigned char *take () { unsigned char *p = d; d = 0; n = cap = 0; return p; }
private:
	Buf (const Buf &);
	Buf &operator= (const Buf &);
};

// ---- encoding --------------------------------------------------------------------------------------

inline bool encode_t (Buf &b, const Val &x, const Type *t);

inline bool encode_fields (Buf &b, const Val &o)
{
	const Ctor *c = o.c;
	for (int i = 0; i < c->np; i++)
	{
		const Param &p = c->p[i];
		if (p.t->k == T_FLAGS)
		{
			uint32_t fl = (uint32_t) (o.v[i].k == V_INT ? o.v[i].l : 0);	// (bits set by hand kept)
			for (int k = i + 1; k < c->np; k++)
			{
				if (c->p[k].flag != i) continue;
				const Val &f = o.v[k];
				bool on = c->p[k].t->k == T_TRUE ? (f.k != V_NONE && f.l != 0) : f.k != V_NONE;
				if (on) fl |= 1u << c->p[k].bit;
			}
			b.u32 (fl);
			continue;
		}
		if (p.flag >= 0)
		{
			const Val &f = o.v[i];
			if (p.t->k == T_TRUE || f.k == V_NONE) continue;	// (in the flags only)
		}
		if (!encode_t (b, o.v[i], p.t)) return false;
	}
	return true;
}

inline bool encode_t (Buf &b, const Val &x, const Type *t)
{
	switch (t->k)
	{
	case T_INT: b.u32 ((uint32_t) x.l); return true;
	case T_LONG: b.i64 (x.l); return true;
	case T_DOUBLE: { long long r; memcpy (&r, &x.d, 8); b.i64 (r); return true; }
	case T_STRING: case T_BYTES: b.str (x.s ? x.s : "", x.k == V_BYTES ? x.n : 0); return true;
	case T_BOOL: b.u32 (x.i () ? 0x997275b5u : 0xbc799737u); return true;
	case T_TRUE: return true;
	case T_INT128: case T_INT256:
	{
		int m = t->k == T_INT128 ? 16 : 32;
		if (x.k != V_BYTES || x.n != m) return false;
		b.put (x.s, m);
		return true;
	}
	case T_FLAGS: b.u32 ((uint32_t) x.l); return true;
	case T_VEC: case T_BVEC:
		if (t->k == T_VEC) b.u32 (0x1cb5c415u);
		b.u32 ((uint32_t) (x.k == V_VEC ? x.n : 0));
		for (int i = 0; x.k == V_VEC && i < x.n; i++) if (!encode_t (b, x.v[i], t->elem)) return false;
		return true;
	case T_OBJ:
		if (x.k == V_RAW) { b.put (x.s, x.n); return true; }
		if (x.k == V_BOOL) { b.u32 (x.l ? 0x997275b5u : 0xbc799737u); return true; }
		if (x.k != V_OBJ || !x.c) return false;
		b.u32 (x.c->id);
		return encode_fields (b, x);
	case T_BARE:
		if (x.k != V_OBJ || !x.c) return false;
		return encode_fields (b, x);
	}
	return false;
}

// An object, boxed (its id first).
inline bool encode (Buf &b, const Val &x)
{
	static const Type obj = { T_OBJ, 0, 0 };
	return encode_t (b, x, &obj);
}

// ---- decoding --------------------------------------------------------------------------------------

struct Reader
{
	const unsigned char *p, *e;
	bool bad;
	Reader (const void *d, int n) : p ((const unsigned char *) d), e ((const unsigned char *) d + n), bad (false) {}
	bool need (int m) { if (bad || e - p < m) { bad = true; return false; } return true; }
	uint32_t u32 ()
	{
		if (!need (4)) return 0;
		uint32_t x = (uint32_t) p[0] | ((uint32_t) p[1] << 8) | ((uint32_t) p[2] << 16) | ((uint32_t) p[3] << 24);
		p += 4;
		return x;
	}
	long long i64 () { uint32_t lo = u32 (); uint32_t hi = u32 (); return (long long) (((unsigned long long) hi << 32) | lo); }
	const unsigned char *raw (int m) { if (!need (m)) return 0; const unsigned char *r = p; p += m; return r; }
	const unsigned char *str (int *m)			// -> the bytes, *m their count
	{
		if (!need (1)) return 0;
		int l = p[0], h = 1;
		if (l == 254) { if (!need (4)) return 0; l = p[1] | (p[2] << 8) | (p[3] << 16); h = 4; }
		else if (l == 255) { bad = true; return 0; }
		if (!need (h + l)) return 0;
		const unsigned char *r = p + h;
		int tot = h + l;
		tot = (tot + 3) & ~3;
		if (e - p < tot) tot = (int) (e - p);
		p += tot;
		*m = l;
		return r;
	}
};

inline bool decode_t (Arena &a, Reader &r, Val &out, const Type *t, int depth);

inline bool decode_fields (Arena &a, Reader &r, Val &out, const Ctor *c, int depth)
{
	out.k = V_OBJ; out.c = c; out.n = c->np;
	out.v = (Val *) a.zalloc (sizeof (Val) * (unsigned) (c->np ? c->np : 1));
	if (!out.v) return false;
	for (int i = 0; i < c->np; i++)
	{
		const Param &p = c->p[i];
		if (p.flag >= 0)
		{
			uint32_t fl = (uint32_t) out.v[p.flag].l;
			if (!(fl & (1u << p.bit))) continue;
			if (p.t->k == T_TRUE) { out.v[i].k = V_BOOL; out.v[i].l = 1; continue; }
		}
		if (!decode_t (a, r, out.v[i], p.t, depth + 1)) return false;
	}
	return true;
}

inline bool decode_obj (Arena &a, Reader &r, Val &out, int depth)
{
	uint32_t id = r.u32 ();
	if (r.bad) return false;
	switch (id)
	{
	case 0x997275b5u: out.k = V_BOOL; out.l = 1; out.c = by_id (id); return true;	// boolTrue / boolFalse
	case 0xbc799737u: out.k = V_BOOL; out.l = 0; out.c = by_id (id); return true;
	case 0x1cb5c415u:					// a vector where an object was: of objects
	{
		static const Type obj = { T_OBJ, 0, 0 };
		int n = (int) r.u32 ();
		if (r.bad || n < 0 || n > (int) (r.e - r.p) / 4 + 1) return false;
		out = Vec (a, n);
		for (int i = 0; i < n; i++) if (!decode_t (a, r, out.v[i], &obj, depth + 1)) return false;
		return true;
	}
	case 0x3072cfa1u:					// gzip_packed packed_data:string
	{
		int m = 0;
		const unsigned char *z = r.str (&m);
		if (!z) return false;
		unsigned char *u = 0; int un = 0;
		if (!tg_gunzip (z, m, &u, &un)) return false;
		char *keep = a.dup (u, un);
		free (u);
		if (!keep) return false;
		Reader in (keep, un);
		return decode_obj (a, in, out, depth + 1);
	}
	}
	const Ctor *c = by_id (id);
	if (!c) { r.bad = true; return false; }
	return decode_fields (a, r, out, c, depth);
}

inline bool decode_t (Arena &a, Reader &r, Val &out, const Type *t, int depth)
{
	if (depth > 64) return false;
	switch (t->k)
	{
	case T_INT: case T_FLAGS: out.k = V_INT; out.l = (int32_t) r.u32 (); break;
	case T_LONG: out.k = V_LONG; out.l = r.i64 (); break;
	case T_DOUBLE: { long long x = r.i64 (); out.k = V_DOUBLE; memcpy (&out.d, &x, 8); break; }
	case T_STRING: case T_BYTES:
	{
		int m = 0;
		const unsigned char *s = r.str (&m);
		if (!s) return false;
		out.k = V_BYTES; out.s = a.dup (s, m); out.n = m;
		break;
	}
	case T_BOOL:
	{
		uint32_t id = r.u32 ();
		out.k = V_BOOL; out.l = id == 0x997275b5u;
		if (id != 0x997275b5u && id != 0xbc799737u) return false;
		break;
	}
	case T_TRUE: out.k = V_BOOL; out.l = 1; break;
	case T_INT128: case T_INT256:
	{
		int m = t->k == T_INT128 ? 16 : 32;
		const unsigned char *s = r.raw (m);
		if (!s) return false;
		out.k = V_BYTES; out.s = a.dup (s, m); out.n = m;
		break;
	}
	case T_VEC: case T_BVEC:
	{
		if (t->k == T_VEC)
		{
			uint32_t id = r.u32 ();
			if (id == 0x3072cfa1u)			// (gzip_packed of a vector)
			{
				int m = 0;
				const unsigned char *z = r.str (&m);
				unsigned char *u = 0; int un = 0;
				if (!z || !tg_gunzip (z, m, &u, &un)) return false;
				char *keep = a.dup (u, un);
				free (u);
				Reader in (keep, un);
				return decode_t (a, in, out, t, depth + 1);
			}
			if (id != 0x1cb5c415u) return false;
		}
		int n = (int) r.u32 ();
		if (r.bad || n < 0 || n > (int) (r.e - r.p) + 1) return false;
		out = Vec (a, n);
		if (!out.v) return false;
		for (int i = 0; i < n; i++) if (!decode_t (a, r, out.v[i], t->elem, depth + 1)) return false;
		break;
	}
	case T_OBJ: return decode_obj (a, r, out, depth);
	case T_BARE: if (!t->bare) return false; return decode_fields (a, r, out, t->bare, depth);
	}
	return !r.bad;
}

// A boxed object from len bytes -> out (its memory the arena's). False: not one the schema knows.
inline bool decode (Arena &a, const void *buf, int len, Val &out)
{
	Reader r (buf, len);
	return decode_obj (a, r, out, 0) && !r.bad;
}
// An answer to a function: read as its result type says (a Vector<long>, an object...).
inline bool decode_result (Arena &a, Reader &r, Val &out, const Ctor *fn)
{
	if (fn && fn->result && fn->result->k != T_OBJ) return decode_t (a, r, out, fn->result, 0);
	return decode_obj (a, r, out, 0);
}

} // namespace tl

#endif
