# installed by tools/pkg/mkrepo.py
[package]
name = media
title = Media Player
version = 1.0.39
category = Multimedia
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, generaluser-gs, audiokit >= 1.232, imagekit >= 1.46, uikit >= 1.949, kapi >= 97
config = 
assoc = mp3=media ogg=media oga=media flac=media wav=media mid=media midi=media kar=media rmi=media m3u=media m3u8=media webm=media mkv=media mp4=media m4v=media mov=media avi=media divx=media mpg=media mpeg=media vob=media ts=media m2ts=media mts=media flv=media wmv=media asf=media ogv=media 3gp=media

[files]
apps/media.app/app.txt = e3d967c49a1d055310bbac4c77b815f450112ee4dc4eb99ef83dbd5ca6561fd6
apps/media.app/icon.bmp = b25763764bc96b2a4d32d425860e4e3f4fad279dd3b2563f52fdb1c7f23ea027
apps/media.app/main = bcf5fde9ac4c447d7299d16a71d6e8db7c98076a9d4138a0bd74802942bcfaa8
apps/media.app/lang/fr.txt = 46545e0ed6c384aaf213dfd3c05aaa3d4759272cfbb6e745962e1d47194c2543
