# installed by tools/pkg/mkrepo.py
[package]
name = rtfview
title = RTF Reader
version = 1.0.34
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 97
config = 

[files]
apps/rtfview.app/app.txt = 3fc2d3abd129ecceb118f1548dae4e2e91f07daaa1da30967b1f0015f2208e83
apps/rtfview.app/icon.bmp = 7d8338ebe94c4ea37aad214408cadf168242ed534f77ec641cda20cf7e616a68
apps/rtfview.app/main = 1e375efb21c4f92003eb903113c22d943e89ae146b8ef5453cec00129a652d4a
