//
// funcs.h -- the functions' table: each one's name, how many arguments, its kind (lifted over arrays,
// lazy, volatile), its category (the Insert Function dialog), its arguments and what it does (the tips
// shown while a formula is typed).
//
#ifndef _sheet_funcs_h
#define _sheet_funcs_h

#include "fn_more.h"

namespace ss {

enum { CAT_MATH, CAT_STAT, CAT_LOGIC, CAT_TEXT, CAT_LOOKUP, CAT_DATE, CAT_INFO, CAT_FIN, CAT_COUNT };
static const char *const CAT_NAMES[CAT_COUNT] = { "Mathematical", "Statistical", "Logical", "Text", "Lookup and Reference", "Date and Time", "Information", "Financial" };

#define L FN_LIFT
#define M 255
static const FnDef FNS[] = {
	// mathematical
	{ "SUM", 1, M, 0, CAT_MATH, f_sum, 0, "number1, [number2], ...", "Adds its arguments." },
	{ "SUMIF", 2, 3, 0, CAT_MATH, f_sumif, 0, "range, criteria, [sum_range]", "Adds the cells that meet a criterion." },
	{ "SUMIFS", 3, M, 0, CAT_MATH, f_sumifs, 0, "sum_range, criteria_range1, criteria1, ...", "Adds the cells that meet several criteria." },
	{ "SUMPRODUCT", 1, M, 0, CAT_MATH, f_sumproduct, 0, "array1, [array2], ...", "Multiplies the arrays element by element, then adds the products." },
	{ "SUMSQ", 1, M, 0, CAT_MATH, f_sumsq, 0, "number1, [number2], ...", "The sum of the squares." },
	{ "PRODUCT", 1, M, 0, CAT_MATH, f_product, 0, "number1, [number2], ...", "Multiplies its arguments." },
	{ "SUBTOTAL", 2, M, 0, CAT_MATH, f_subtotal, 0, "function_num, ref1, ...", "A subtotal (1 AVERAGE, 2 COUNT, 3 COUNTA, 4 MAX, 5 MIN, 6 PRODUCT, 7 STDEV, 8 STDEVP, 9 SUM, 10 VAR, 11 VARP; +100: hidden rows left out)." },
	{ "ABS", 1, 1, L, CAT_MATH, f_abs, 0, "number", "The absolute value." },
	{ "SIGN", 1, 1, L, CAT_MATH, f_sign, 0, "number", "1, 0 or -1: the number's sign." },
	{ "SQRT", 1, 1, L, CAT_MATH, f_sqrt, 0, "number", "The square root." },
	{ "SQRTPI", 1, 1, L, CAT_MATH, f_sqrtpi, 0, "number", "The square root of number x pi." },
	{ "POWER", 2, 2, L, CAT_MATH, f_power, 0, "number, power", "A number raised to a power." },
	{ "EXP", 1, 1, L, CAT_MATH, f_exp, 0, "number", "e raised to the power of the number." },
	{ "LN", 1, 1, L, CAT_MATH, f_ln, 0, "number", "The natural logarithm." },
	{ "LOG", 1, 2, L, CAT_MATH, f_log, 0, "number, [base]", "The logarithm to a base (10 by default)." },
	{ "LOG10", 1, 1, L, CAT_MATH, f_log10, 0, "number", "The base-10 logarithm." },
	{ "PI", 0, 0, 0, CAT_MATH, f_pi, 0, "", "The value of pi, 3.14159265358979." },
	{ "ROUND", 2, 2, L, CAT_MATH, f_round, 0, "number, num_digits", "Rounds to a number of digits." },
	{ "ROUNDUP", 2, 2, L, CAT_MATH, f_roundup, 0, "number, num_digits", "Rounds away from zero." },
	{ "ROUNDDOWN", 2, 2, L, CAT_MATH, f_rounddown, 0, "number, num_digits", "Rounds toward zero." },
	{ "MROUND", 2, 2, L, CAT_MATH, f_mround, 0, "number, multiple", "Rounds to the nearest multiple." },
	{ "INT", 1, 1, L, CAT_MATH, f_int, 0, "number", "Rounds down to an integer." },
	{ "TRUNC", 1, 2, L, CAT_MATH, f_trunc, 0, "number, [num_digits]", "Cuts the decimals off." },
	{ "CEILING", 1, 2, L, CAT_MATH, f_ceiling, 0, "number, [significance]", "Rounds up to a multiple of significance." },
	{ "CEILING.MATH", 1, 3, L, CAT_MATH, f_ceiling_math, 0, "number, [significance], [mode]", "Rounds up to a multiple of significance." },
	{ "FLOOR", 1, 2, L, CAT_MATH, f_floor, 0, "number, [significance]", "Rounds down to a multiple of significance." },
	{ "FLOOR.MATH", 1, 3, L, CAT_MATH, f_floor_math, 0, "number, [significance], [mode]", "Rounds down to a multiple of significance." },
	{ "MOD", 2, 2, L, CAT_MATH, f_mod, 0, "number, divisor", "The remainder of a division." },
	{ "QUOTIENT", 2, 2, L, CAT_MATH, f_quotient, 0, "numerator, denominator", "The integer part of a division." },
	{ "EVEN", 1, 1, L, CAT_MATH, f_even, 0, "number", "Rounds up to an even integer." },
	{ "ODD", 1, 1, L, CAT_MATH, f_odd, 0, "number", "Rounds up to an odd integer." },
	{ "FACT", 1, 1, L, CAT_MATH, f_fact, 0, "number", "The factorial." },
	{ "FACTDOUBLE", 1, 1, L, CAT_MATH, f_factdouble, 0, "number", "The double factorial." },
	{ "COMBIN", 2, 2, L, CAT_MATH, f_combin, 0, "number, number_chosen", "The number of combinations." },
	{ "COMBINA", 2, 2, L, CAT_MATH, f_combina, 0, "number, number_chosen", "The number of combinations with repetitions." },
	{ "PERMUT", 2, 2, L, CAT_MATH, f_permut, 0, "number, number_chosen", "The number of permutations." },
	{ "GCD", 1, M, 0, CAT_MATH, f_gcd, 0, "number1, [number2], ...", "The greatest common divisor." },
	{ "LCM", 1, M, 0, CAT_MATH, f_lcm, 0, "number1, [number2], ...", "The least common multiple." },
	{ "RAND", 0, 0, FN_VOL, CAT_MATH, f_rand, 0, "", "A random number between 0 and 1." },
	{ "RANDBETWEEN", 2, 2, FN_VOL, CAT_MATH, f_randbetween, 0, "bottom, top", "A random integer between two numbers." },
	{ "SIN", 1, 1, L, CAT_MATH, f_sin, 0, "number", "The sine of an angle in radians." },
	{ "COS", 1, 1, L, CAT_MATH, f_cos, 0, "number", "The cosine of an angle in radians." },
	{ "TAN", 1, 1, L, CAT_MATH, f_tan, 0, "number", "The tangent of an angle in radians." },
	{ "COT", 1, 1, L, CAT_MATH, f_cot, 0, "number", "The cotangent of an angle in radians." },
	{ "ASIN", 1, 1, L, CAT_MATH, f_asin, 0, "number", "The arcsine, in radians." },
	{ "ACOS", 1, 1, L, CAT_MATH, f_acos, 0, "number", "The arccosine, in radians." },
	{ "ATAN", 1, 1, L, CAT_MATH, f_atan, 0, "number", "The arctangent, in radians." },
	{ "ATAN2", 2, 2, L, CAT_MATH, f_atan2, 0, "x_num, y_num", "The arctangent of the point (x, y)." },
	{ "SINH", 1, 1, L, CAT_MATH, f_sinh, 0, "number", "The hyperbolic sine." },
	{ "COSH", 1, 1, L, CAT_MATH, f_cosh, 0, "number", "The hyperbolic cosine." },
	{ "TANH", 1, 1, L, CAT_MATH, f_tanh, 0, "number", "The hyperbolic tangent." },
	{ "ASINH", 1, 1, L, CAT_MATH, f_asinh, 0, "number", "The inverse hyperbolic sine." },
	{ "ACOSH", 1, 1, L, CAT_MATH, f_acosh, 0, "number", "The inverse hyperbolic cosine." },
	{ "ATANH", 1, 1, L, CAT_MATH, f_atanh, 0, "number", "The inverse hyperbolic tangent." },
	{ "DEGREES", 1, 1, L, CAT_MATH, f_degrees, 0, "angle", "Radians to degrees." },
	{ "RADIANS", 1, 1, L, CAT_MATH, f_radians, 0, "angle", "Degrees to radians." },
	// statistical
	{ "AVERAGE", 1, M, 0, CAT_STAT, f_average, 0, "number1, [number2], ...", "The average (arithmetic mean)." },
	{ "AVERAGEA", 1, M, 0, CAT_STAT, f_averagea, 0, "value1, [value2], ...", "The average, texts counting 0 and TRUE 1." },
	{ "AVERAGEIF", 2, 3, 0, CAT_STAT, f_averageif, 0, "range, criteria, [average_range]", "The average of the cells that meet a criterion." },
	{ "AVERAGEIFS", 3, M, 0, CAT_STAT, f_averageifs, 0, "average_range, criteria_range1, criteria1, ...", "The average of the cells that meet several criteria." },
	{ "COUNT", 1, M, 0, CAT_STAT, f_count, 0, "value1, [value2], ...", "Counts the numbers." },
	{ "COUNTA", 1, M, 0, CAT_STAT, f_counta, 0, "value1, [value2], ...", "Counts the cells that are not empty." },
	{ "COUNTBLANK", 1, 1, 0, CAT_STAT, f_countblank, 0, "range", "Counts the empty cells." },
	{ "COUNTIF", 2, 2, 0, CAT_STAT, f_countif, 0, "range, criteria", "Counts the cells that meet a criterion." },
	{ "COUNTIFS", 2, M, 0, CAT_STAT, f_countifs, 0, "criteria_range1, criteria1, ...", "Counts the cells that meet several criteria." },
	{ "MAX", 1, M, 0, CAT_STAT, f_max, 0, "number1, [number2], ...", "The largest value." },
	{ "MAXA", 1, M, 0, CAT_STAT, f_maxa, 0, "value1, [value2], ...", "The largest value, texts counting 0." },
	{ "MAXIFS", 3, M, 0, CAT_STAT, f_maxifs, 0, "max_range, criteria_range1, criteria1, ...", "The largest value among the cells that meet criteria." },
	{ "MIN", 1, M, 0, CAT_STAT, f_min, 0, "number1, [number2], ...", "The smallest value." },
	{ "MINA", 1, M, 0, CAT_STAT, f_mina, 0, "value1, [value2], ...", "The smallest value, texts counting 0." },
	{ "MINIFS", 3, M, 0, CAT_STAT, f_minifs, 0, "min_range, criteria_range1, criteria1, ...", "The smallest value among the cells that meet criteria." },
	{ "MEDIAN", 1, M, 0, CAT_STAT, f_median, 0, "number1, [number2], ...", "The median." },
	{ "MODE", 1, M, 0, CAT_STAT, f_mode, 0, "number1, [number2], ...", "The most frequent value." },
	{ "MODE.SNGL", 1, M, 0, CAT_STAT, f_mode, 0, "number1, [number2], ...", "The most frequent value." },
	{ "LARGE", 2, 2, 0, CAT_STAT, f_large, 0, "array, k", "The k-th largest value." },
	{ "SMALL", 2, 2, 0, CAT_STAT, f_small, 0, "array, k", "The k-th smallest value." },
	{ "RANK", 2, 3, 0, CAT_STAT, f_rank, 0, "number, ref, [order]", "A number's rank in a list (0: descending)." },
	{ "RANK.EQ", 2, 3, 0, CAT_STAT, f_rank, 0, "number, ref, [order]", "A number's rank in a list." },
	{ "RANK.AVG", 2, 3, 0, CAT_STAT, f_rank_avg, 0, "number, ref, [order]", "A number's rank, ties averaged." },
	{ "PERCENTILE", 2, 2, 0, CAT_STAT, f_percentile, 0, "array, k", "The k-th percentile (0 to 1)." },
	{ "PERCENTILE.INC", 2, 2, 0, CAT_STAT, f_percentile, 0, "array, k", "The k-th percentile (0 to 1)." },
	{ "PERCENTILE.EXC", 2, 2, 0, CAT_STAT, f_percentile_exc, 0, "array, k", "The k-th percentile, 0 and 1 excluded." },
	{ "QUARTILE", 2, 2, 0, CAT_STAT, f_quartile, 0, "array, quart", "A quartile (0 to 4)." },
	{ "QUARTILE.INC", 2, 2, 0, CAT_STAT, f_quartile, 0, "array, quart", "A quartile (0 to 4)." },
	{ "QUARTILE.EXC", 2, 2, 0, CAT_STAT, f_quartile_exc, 0, "array, quart", "A quartile, 0 and 4 excluded." },
	{ "PERCENTRANK", 2, 3, 0, CAT_STAT, f_percentrank, 0, "array, x, [significance]", "The rank of a value as a percentage." },
	{ "STDEV", 1, M, 0, CAT_STAT, f_stdev, 0, "number1, [number2], ...", "The standard deviation of a sample." },
	{ "STDEV.S", 1, M, 0, CAT_STAT, f_stdev, 0, "number1, [number2], ...", "The standard deviation of a sample." },
	{ "STDEVA", 1, M, 0, CAT_STAT, f_stdeva, 0, "value1, [value2], ...", "The standard deviation of a sample, texts counting 0." },
	{ "STDEVP", 1, M, 0, CAT_STAT, f_stdevp, 0, "number1, [number2], ...", "The standard deviation of a population." },
	{ "STDEV.P", 1, M, 0, CAT_STAT, f_stdevp, 0, "number1, [number2], ...", "The standard deviation of a population." },
	{ "VAR", 1, M, 0, CAT_STAT, f_var, 0, "number1, [number2], ...", "The variance of a sample." },
	{ "VAR.S", 1, M, 0, CAT_STAT, f_var, 0, "number1, [number2], ...", "The variance of a sample." },
	{ "VARA", 1, M, 0, CAT_STAT, f_vara, 0, "value1, [value2], ...", "The variance of a sample, texts counting 0." },
	{ "VARP", 1, M, 0, CAT_STAT, f_varp, 0, "number1, [number2], ...", "The variance of a population." },
	{ "VAR.P", 1, M, 0, CAT_STAT, f_varp, 0, "number1, [number2], ...", "The variance of a population." },
	{ "AVEDEV", 1, M, 0, CAT_STAT, f_avedev, 0, "number1, [number2], ...", "The average of the absolute deviations." },
	{ "DEVSQ", 1, M, 0, CAT_STAT, f_devsq, 0, "number1, [number2], ...", "The sum of the squared deviations." },
	{ "GEOMEAN", 1, M, 0, CAT_STAT, f_geomean, 0, "number1, [number2], ...", "The geometric mean." },
	{ "HARMEAN", 1, M, 0, CAT_STAT, f_harmean, 0, "number1, [number2], ...", "The harmonic mean." },
	{ "CORREL", 2, 2, 0, CAT_STAT, f_correl, 0, "array1, array2", "The correlation coefficient." },
	{ "PEARSON", 2, 2, 0, CAT_STAT, f_correl, 0, "array1, array2", "The Pearson correlation coefficient." },
	{ "RSQ", 2, 2, 0, CAT_STAT, f_rsq, 0, "known_y's, known_x's", "The square of the correlation coefficient." },
	{ "COVAR", 2, 2, 0, CAT_STAT, f_covar, 0, "array1, array2", "The covariance of a population." },
	{ "COVARIANCE.P", 2, 2, 0, CAT_STAT, f_covar, 0, "array1, array2", "The covariance of a population." },
	{ "COVARIANCE.S", 2, 2, 0, CAT_STAT, f_covar_s, 0, "array1, array2", "The covariance of a sample." },
	{ "SLOPE", 2, 2, 0, CAT_STAT, f_slope, 0, "known_y's, known_x's", "The slope of the regression line." },
	{ "INTERCEPT", 2, 2, 0, CAT_STAT, f_intercept, 0, "known_y's, known_x's", "Where the regression line meets the y axis." },
	{ "FORECAST", 3, 3, 0, CAT_STAT, f_forecast, 0, "x, known_y's, known_x's", "A value on the regression line." },
	{ "FORECAST.LINEAR", 3, 3, 0, CAT_STAT, f_forecast, 0, "x, known_y's, known_x's", "A value on the regression line." },
	{ "STEYX", 2, 2, 0, CAT_STAT, f_steyx, 0, "known_y's, known_x's", "The standard error of the regression." },
	{ "NORMDIST", 4, 4, L, CAT_STAT, f_normdist, 0, "x, mean, standard_dev, cumulative", "The normal distribution." },
	{ "NORM.DIST", 4, 4, L, CAT_STAT, f_normdist, 0, "x, mean, standard_dev, cumulative", "The normal distribution." },
	{ "NORMINV", 3, 3, L, CAT_STAT, f_norminv, 0, "probability, mean, standard_dev", "The inverse of the normal distribution." },
	{ "NORM.INV", 3, 3, L, CAT_STAT, f_norminv, 0, "probability, mean, standard_dev", "The inverse of the normal distribution." },
	{ "NORMSDIST", 1, 1, L, CAT_STAT, f_normsdist, 0, "z", "The standard normal distribution." },
	{ "NORM.S.DIST", 2, 2, L, CAT_STAT, f_normsdist, 0, "z, cumulative", "The standard normal distribution." },
	{ "NORMSINV", 1, 1, L, CAT_STAT, f_normsinv, 0, "probability", "The inverse of the standard normal distribution." },
	{ "NORM.S.INV", 1, 1, L, CAT_STAT, f_normsinv, 0, "probability", "The inverse of the standard normal distribution." },
	{ "STANDARDIZE", 3, 3, L, CAT_STAT, f_standardize, 0, "x, mean, standard_dev", "A normalised value." },
	{ "BINOMDIST", 4, 4, L, CAT_STAT, f_binomdist, 0, "number_s, trials, probability_s, cumulative", "The binomial distribution." },
	{ "BINOM.DIST", 4, 4, L, CAT_STAT, f_binomdist, 0, "number_s, trials, probability_s, cumulative", "The binomial distribution." },
	{ "POISSON", 3, 3, L, CAT_STAT, f_poisson, 0, "x, mean, cumulative", "The Poisson distribution." },
	{ "POISSON.DIST", 3, 3, L, CAT_STAT, f_poisson, 0, "x, mean, cumulative", "The Poisson distribution." },
	{ "EXPONDIST", 3, 3, L, CAT_STAT, f_expondist, 0, "x, lambda, cumulative", "The exponential distribution." },
	{ "EXPON.DIST", 3, 3, L, CAT_STAT, f_expondist, 0, "x, lambda, cumulative", "The exponential distribution." },
	// logical
	{ "IF", 1, 3, FN_LAZY, CAT_LOGIC, 0, f_if, "logical_test, [value_if_true], [value_if_false]", "One value if a condition is TRUE, another if it is FALSE." },
	{ "IFS", 2, M, FN_LAZY, CAT_LOGIC, 0, f_ifs, "logical_test1, value_if_true1, ...", "The value of the first condition that is TRUE." },
	{ "IFERROR", 2, 2, FN_LAZY, CAT_LOGIC, 0, f_iferror, "value, value_if_error", "The value, or another when it is an error." },
	{ "IFNA", 2, 2, FN_LAZY, CAT_LOGIC, 0, f_ifna, "value, value_if_na", "The value, or another when it is #N/A." },
	{ "SWITCH", 3, M, FN_LAZY, CAT_LOGIC, 0, f_switch, "expression, value1, result1, ..., [default]", "The result matching the expression's value." },
	{ "AND", 1, M, 0, CAT_LOGIC, f_and, 0, "logical1, [logical2], ...", "TRUE if all its arguments are TRUE." },
	{ "OR", 1, M, 0, CAT_LOGIC, f_or, 0, "logical1, [logical2], ...", "TRUE if any argument is TRUE." },
	{ "XOR", 1, M, 0, CAT_LOGIC, f_xor, 0, "logical1, [logical2], ...", "TRUE if an odd number of arguments are TRUE." },
	{ "NOT", 1, 1, L, CAT_LOGIC, f_not, 0, "logical", "Reverses TRUE and FALSE." },
	{ "TRUE", 0, 0, 0, CAT_LOGIC, f_true, 0, "", "The value TRUE." },
	{ "FALSE", 0, 0, 0, CAT_LOGIC, f_false, 0, "", "The value FALSE." },
	// text
	{ "CONCATENATE", 1, M, 0, CAT_TEXT, f_concatenate, 0, "text1, [text2], ...", "Joins texts." },
	{ "CONCAT", 1, M, 0, CAT_TEXT, f_concat, 0, "text1, [text2], ...", "Joins texts and the cells of ranges." },
	{ "TEXTJOIN", 3, M, 0, CAT_TEXT, f_textjoin, 0, "delimiter, ignore_empty, text1, ...", "Joins texts with a delimiter." },
	{ "LEN", 1, 1, L, CAT_TEXT, f_len, 0, "text", "The number of characters." },
	{ "LEFT", 1, 2, L, CAT_TEXT, f_left, 0, "text, [num_chars]", "The first characters." },
	{ "RIGHT", 1, 2, L, CAT_TEXT, f_right, 0, "text, [num_chars]", "The last characters." },
	{ "MID", 3, 3, L, CAT_TEXT, f_mid, 0, "text, start_num, num_chars", "Characters from the middle of a text." },
	{ "UPPER", 1, 1, L, CAT_TEXT, f_upper, 0, "text", "In capitals." },
	{ "LOWER", 1, 1, L, CAT_TEXT, f_lower, 0, "text", "In small letters." },
	{ "PROPER", 1, 1, L, CAT_TEXT, f_proper, 0, "text", "Each word's first letter in capitals." },
	{ "TRIM", 1, 1, L, CAT_TEXT, f_trim, 0, "text", "The spaces around and doubled taken off." },
	{ "CLEAN", 1, 1, L, CAT_TEXT, f_clean, 0, "text", "The control characters taken off." },
	{ "REPT", 2, 2, L, CAT_TEXT, f_rept, 0, "text, number_times", "A text repeated." },
	{ "SUBSTITUTE", 3, 4, L, CAT_TEXT, f_substitute, 0, "text, old_text, new_text, [instance_num]", "Replaces a text with another." },
	{ "REPLACE", 4, 4, L, CAT_TEXT, f_replace, 0, "old_text, start_num, num_chars, new_text", "Replaces characters at a place." },
	{ "FIND", 2, 3, L, CAT_TEXT, f_find, 0, "find_text, within_text, [start_num]", "Where a text is found (case matters)." },
	{ "SEARCH", 2, 3, L, CAT_TEXT, f_search, 0, "find_text, within_text, [start_num]", "Where a text is found (case ignored, wildcards)." },
	{ "EXACT", 2, 2, L, CAT_TEXT, f_exact, 0, "text1, text2", "TRUE if two texts are exactly the same." },
	{ "CHAR", 1, 1, L, CAT_TEXT, f_char, 0, "number", "The character of a code (Windows-1252)." },
	{ "CODE", 1, 1, L, CAT_TEXT, f_code, 0, "text", "The code of the first character." },
	{ "UNICHAR", 1, 1, L, CAT_TEXT, f_unichar, 0, "number", "The Unicode character of a number." },
	{ "UNICODE", 1, 1, L, CAT_TEXT, f_unicode, 0, "text", "The Unicode number of the first character." },
	{ "VALUE", 1, 1, L, CAT_TEXT, f_value, 0, "text", "A text read as a number." },
	{ "NUMBERVALUE", 1, 3, L, CAT_TEXT, f_numbervalue, 0, "text, [decimal_separator], [group_separator]", "A text read as a number, separators given." },
	{ "TEXT", 2, 2, L, CAT_TEXT, f_text, 0, "value, format_text", "A value formatted as a text." },
	{ "FIXED", 1, 3, L, CAT_TEXT, f_fixed, 0, "number, [decimals], [no_commas]", "A number as a text with its decimals." },
	{ "DOLLAR", 1, 2, L, CAT_TEXT, f_dollar, 0, "number, [decimals]", "A number as a text in the currency format." },
	{ "T", 1, 1, L, CAT_TEXT, f_t, 0, "value", "The value if it is a text, else an empty text." },
	{ "HYPERLINK", 1, 2, 0, CAT_TEXT, f_hyperlink, 0, "link_location, [friendly_name]", "A link's name (the link itself is not followed)." },
	// lookup and reference
	{ "VLOOKUP", 3, 4, 0, CAT_LOOKUP, f_vlookup, 0, "lookup_value, table_array, col_index_num, [range_lookup]", "Looks in the first column of a table, returns a value of the same row." },
	{ "HLOOKUP", 3, 4, 0, CAT_LOOKUP, f_hlookup, 0, "lookup_value, table_array, row_index_num, [range_lookup]", "Looks in the first row of a table, returns a value of the same column." },
	{ "XLOOKUP", 3, 6, 0, CAT_LOOKUP, f_xlookup, 0, "lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]", "Looks in a range, returns the matching item of another." },
	{ "LOOKUP", 2, 3, 0, CAT_LOOKUP, f_lookup, 0, "lookup_value, lookup_vector, [result_vector]", "Looks in a row or column (sorted)." },
	{ "MATCH", 2, 3, 0, CAT_LOOKUP, f_match, 0, "lookup_value, lookup_array, [match_type]", "The position of a value in a range." },
	{ "INDEX", 2, 3, 0, CAT_LOOKUP, f_index, 0, "array, row_num, [column_num]", "The value at a row and column of a range." },
	{ "CHOOSE", 2, M, FN_LAZY, CAT_LOOKUP, 0, f_choose, "index_num, value1, [value2], ...", "A value from a list by its number." },
	{ "OFFSET", 3, 5, FN_VOL, CAT_LOOKUP, f_offset, 0, "reference, rows, cols, [height], [width]", "A reference moved from another." },
	{ "INDIRECT", 1, 2, FN_VOL, CAT_LOOKUP, f_indirect, 0, "ref_text, [a1]", "The reference written in a text." },
	{ "ROW", 0, 1, 0, CAT_LOOKUP, f_row, 0, "[reference]", "The row number." },
	{ "COLUMN", 0, 1, 0, CAT_LOOKUP, f_column, 0, "[reference]", "The column number." },
	{ "ROWS", 1, 1, 0, CAT_LOOKUP, f_rows, 0, "array", "The number of rows." },
	{ "COLUMNS", 1, 1, 0, CAT_LOOKUP, f_columns, 0, "array", "The number of columns." },
	{ "ADDRESS", 2, 5, L, CAT_LOOKUP, f_address, 0, "row_num, column_num, [abs_num], [a1], [sheet_text]", "A cell's address as a text." },
	{ "TRANSPOSE", 1, 1, 0, CAT_LOOKUP, f_transpose, 0, "array", "An array's rows and columns swapped." },
	{ "FORMULATEXT", 1, 1, 0, CAT_LOOKUP, f_formulatext, 0, "reference", "A cell's formula as a text." },
	// date and time
	{ "DATE", 3, 3, L, CAT_DATE, f_date, 0, "year, month, day", "A date's serial number." },
	{ "TIME", 3, 3, L, CAT_DATE, f_time, 0, "hour, minute, second", "A time's serial number." },
	{ "TODAY", 0, 0, FN_VOL, CAT_DATE, f_today, 0, "", "Today's date." },
	{ "NOW", 0, 0, FN_VOL, CAT_DATE, f_now, 0, "", "The date and time now." },
	{ "YEAR", 1, 1, L, CAT_DATE, f_year, 0, "serial_number", "A date's year." },
	{ "MONTH", 1, 1, L, CAT_DATE, f_month, 0, "serial_number", "A date's month (1 to 12)." },
	{ "DAY", 1, 1, L, CAT_DATE, f_day, 0, "serial_number", "A date's day of the month." },
	{ "HOUR", 1, 1, L, CAT_DATE, f_hour, 0, "serial_number", "A time's hour (0 to 23)." },
	{ "MINUTE", 1, 1, L, CAT_DATE, f_minute, 0, "serial_number", "A time's minute." },
	{ "SECOND", 1, 1, L, CAT_DATE, f_second, 0, "serial_number", "A time's second." },
	{ "WEEKDAY", 1, 2, L, CAT_DATE, f_weekday, 0, "serial_number, [return_type]", "The day of the week (1 = Sunday)." },
	{ "WEEKNUM", 1, 2, L, CAT_DATE, f_weeknum, 0, "serial_number, [return_type]", "The week of the year." },
	{ "ISOWEEKNUM", 1, 1, L, CAT_DATE, f_isoweeknum, 0, "date", "The ISO week of the year." },
	{ "EDATE", 2, 2, L, CAT_DATE, f_edate, 0, "start_date, months", "The date some months away." },
	{ "EOMONTH", 2, 2, L, CAT_DATE, f_eomonth, 0, "start_date, months", "The last day of a month some months away." },
	{ "DAYS", 2, 2, L, CAT_DATE, f_days, 0, "end_date, start_date", "The days between two dates." },
	{ "DAYS360", 2, 3, L, CAT_DATE, f_days360, 0, "start_date, end_date, [method]", "The days between two dates, 360 to a year." },
	{ "DATEDIF", 3, 3, L, CAT_DATE, f_datedif, 0, "start_date, end_date, unit", "The years (\"Y\"), months (\"M\") or days (\"D\") between two dates." },
	{ "NETWORKDAYS", 2, 3, 0, CAT_DATE, f_networkdays, 0, "start_date, end_date, [holidays]", "The working days between two dates." },
	{ "WORKDAY", 2, 3, 0, CAT_DATE, f_workday, 0, "start_date, days, [holidays]", "The date some working days away." },
	{ "DATEVALUE", 1, 1, L, CAT_DATE, f_datevalue, 0, "date_text", "A date written as a text, as a serial number." },
	{ "TIMEVALUE", 1, 1, L, CAT_DATE, f_timevalue, 0, "time_text", "A time written as a text, as a serial number." },
	{ "YEARFRAC", 2, 3, L, CAT_DATE, f_yearfrac, 0, "start_date, end_date, [basis]", "The fraction of a year between two dates." },
	// information
	{ "ISBLANK", 1, 1, L, CAT_INFO, f_isblank, 0, "value", "TRUE if the cell is empty." },
	{ "ISNUMBER", 1, 1, L, CAT_INFO, f_isnumber, 0, "value", "TRUE if it is a number." },
	{ "ISTEXT", 1, 1, L, CAT_INFO, f_istext, 0, "value", "TRUE if it is a text." },
	{ "ISNONTEXT", 1, 1, L, CAT_INFO, f_isnontext, 0, "value", "TRUE if it is not a text." },
	{ "ISLOGICAL", 1, 1, L, CAT_INFO, f_islogical, 0, "value", "TRUE if it is TRUE or FALSE." },
	{ "ISERROR", 1, 1, L, CAT_INFO, f_iserror, 0, "value", "TRUE if it is an error." },
	{ "ISERR", 1, 1, L, CAT_INFO, f_iserr, 0, "value", "TRUE if it is an error other than #N/A." },
	{ "ISNA", 1, 1, L, CAT_INFO, f_isna, 0, "value", "TRUE if it is #N/A." },
	{ "ISREF", 1, 1, 0, CAT_INFO, f_isref, 0, "value", "TRUE if it is a reference." },
	{ "ISFORMULA", 1, 1, 0, CAT_INFO, f_isformula, 0, "reference", "TRUE if the cell holds a formula." },
	{ "ISEVEN", 1, 1, L, CAT_INFO, f_iseven, 0, "number", "TRUE if the number is even." },
	{ "ISODD", 1, 1, L, CAT_INFO, f_isodd, 0, "number", "TRUE if the number is odd." },
	{ "NA", 0, 0, 0, CAT_INFO, f_na, 0, "", "The error #N/A." },
	{ "ERROR.TYPE", 1, 1, L, CAT_INFO, f_errortype, 0, "error_val", "An error's number." },
	{ "TYPE", 1, 1, 0, CAT_INFO, f_type, 0, "value", "The type: 1 number, 2 text, 4 logical, 16 error, 64 array." },
	{ "N", 1, 1, L, CAT_INFO, f_n, 0, "value", "The value as a number." },
	{ "SHEET", 0, 1, 0, CAT_INFO, f_sheet, 0, "[value]", "A sheet's number." },
	{ "SHEETS", 0, 1, 0, CAT_INFO, f_sheets, 0, "[reference]", "The number of sheets." },
	// financial
	{ "PMT", 3, 5, L, CAT_FIN, f_pmt, 0, "rate, nper, pv, [fv], [type]", "The payment of a loan." },
	{ "IPMT", 4, 6, L, CAT_FIN, f_ipmt, 0, "rate, per, nper, pv, [fv], [type]", "The interest part of a payment." },
	{ "PPMT", 4, 6, L, CAT_FIN, f_ppmt, 0, "rate, per, nper, pv, [fv], [type]", "The principal part of a payment." },
	{ "FV", 3, 5, L, CAT_FIN, f_fv, 0, "rate, nper, pmt, [pv], [type]", "The future value of an investment." },
	{ "PV", 3, 5, L, CAT_FIN, f_pv, 0, "rate, nper, pmt, [fv], [type]", "The present value of an investment." },
	{ "NPER", 3, 5, L, CAT_FIN, f_nper, 0, "rate, pmt, pv, [fv], [type]", "The number of periods." },
	{ "RATE", 3, 6, L, CAT_FIN, f_rate, 0, "nper, pmt, pv, [fv], [type], [guess]", "The interest rate per period." },
	{ "NPV", 2, M, 0, CAT_FIN, f_npv, 0, "rate, value1, [value2], ...", "The net present value." },
	{ "IRR", 1, 2, 0, CAT_FIN, f_irr, 0, "values, [guess]", "The internal rate of return." },
	{ "SLN", 3, 3, L, CAT_FIN, f_sln, 0, "cost, salvage, life", "Straight-line depreciation." },
	{ "SYD", 4, 4, L, CAT_FIN, f_syd, 0, "cost, salvage, life, per", "Sum-of-years' digits depreciation." },
	{ "DDB", 4, 5, L, CAT_FIN, f_ddb, 0, "cost, salvage, life, period, [factor]", "Double-declining balance depreciation." },
	{ "EFFECT", 2, 2, L, CAT_FIN, f_effect, 0, "nominal_rate, npery", "The effective annual rate." },
	{ "NOMINAL", 2, 2, L, CAT_FIN, f_nominal, 0, "effect_rate, npery", "The nominal annual rate." },
};
#undef L
#undef M
static const int NFNS = (int) (sizeof FNS / sizeof FNS[0]);

static const FnDef *fn_def (int i) { return &FNS[i]; }
static int fn_lookup (const char *name, int n)
{
	for (int i = 0; i < NFNS; i++) if ((int) strlen (FNS[i].name) == n && ascii_ieq (FNS[i].name, name, n)) return i;
	return -1;
}
static const char *fn_name (int i) { return i >= 0 && i < NFNS ? FNS[i].name : "?"; }
static bool fn_volatile (int i) { return i >= 0 && i < NFNS && (FNS[i].fl & FN_VOL); }
static void fn_init () { g_fnSubtotal = fn_lookup ("SUBTOTAL", 8); }

} // namespace ss

#endif
