#!/bin/sh
# user/netsurf/gen-duktape.sh -- regenerate gen/duktape/: NetSurf's JavaScript DOM bindings for
# Duktape, generated by nsgenbind from the .bnd files + the WebIDL
# (third_party/netsurf/content/handlers/javascript/duktape/, .../WebIDL/), plus the two embedded
# scripts (generics.js, polyfill.js -> *.js.inc, as xxd -i). Run after changing a .bnd / .idl /
# .js there. Needs gcc, bison, flex, python3. The generated files include each other by relative
# name ("binding.h"), so gen/duktape/ can live anywhere.
set -e
cd "$(dirname "$0")"
NS=../../third_party/netsurf
GB=../../third_party/nsgenbind
B=$GB/build-host
JS=$NS/content/handlers/javascript

mkdir -p $B
bison -t -d --define=api.prefix={nsgenbind_} -o $B/nsgenbind-parser.c $GB/src/nsgenbind-parser.y 2>/dev/null
bison -t -d --define=api.prefix={webidl_} -o $B/webidl-parser.c $GB/src/webidl-parser.y 2>/dev/null
flex -o $B/nsgenbind-lexer.c --header-file=$B/nsgenbind-lexer.h $GB/src/nsgenbind-lexer.l
flex -o $B/webidl-lexer.c --header-file=$B/webidl-lexer.h $GB/src/webidl-lexer.l
gcc -O1 -w -DYYENABLE_NLS=0 -I$B -I$GB/src -o $B/nsgenbind \
    $(ls $GB/src/*.c) $B/nsgenbind-parser.c $B/nsgenbind-lexer.c $B/webidl-parser.c $B/webidl-lexer.c

T=$(mktemp -d)
HERE=$(pwd)
# (run from NetSurf's root with its relative paths, as its own build: the #line directives)
(cd $NS && "$HERE/$B/nsgenbind" -D -I content/handlers/javascript/WebIDL \
	content/handlers/javascript/duktape/netsurf.bnd $T)
rm -f gen/duktape/*.c gen/duktape/binding.h gen/duktape/private.h gen/duktape/prototype.h
for f in $T/*.c $T/*.h; do sed "s#\"$T/#\"#" "$f" > gen/duktape/$(basename "$f"); done
sed "s#^NSGENBIND_PREFIX:=.*#NSGENBIND_PREFIX:=.#" $T/Makefile > gen/duktape/Makefile
rm -rf "$T"

# the embedded scripts as C arrays (the format of xxd -i)
for s in generics polyfill; do
	python3 - "$JS/duktape/$s.js" "${s}_js" > gen/duktape/$s.js.inc <<'PY'
import sys
d = open(sys.argv[1], "rb").read()
n = sys.argv[2]
print("unsigned char %s[] = {" % n)
rows = [", ".join("0x%02x" % b for b in d[i:i + 12]) for i in range(0, len(d), 12)]
print(",\n".join("  " + r for r in rows))
print("};")
print("unsigned int %s_len = %d;" % (n, len(d)))
PY
done
echo "gen/duktape: $(ls gen/duktape/*.c | wc -l) binding sources"
