//
// lib.h -- Onyx shared libraries, the user side (kapi v83; docs/SHARED-LIBS-PLAN.md, docs/03
// "Shared libraries").
//
// A shared library is position-independent code in SD:/lib/<name>.so. The kernel loads it once for
// the whole system, places it, relocates its data once, and maps it into every process that opens
// it (kapi_lib_open): the code is shared, the data is each process's own. A library publishes its
// entry points in an EXPORT TABLE -- a struct of function pointers, filled when the library is
// loaded -- and a program calls through it, exactly as it calls the kernel through `KT`. The table
// is append-only and versioned as the kapi table is: an entry is never moved, removed or changed;
// a new one goes to the end and the version goes up. So a library is fixed or extended without
// rebuilding the programs that use it.
//
// Every table starts with TLibHeader: its version, its size, and init -- called once by each
// process (the data is per process) with what the library takes from its importer: the allocator,
// so that there is one heap in the process whatever allocates.
//
// A program does not call these by hand: it links the library's bind object (user/<lib>/..._bind,
// generated by tools/libgen), whose constructor -- priority 101: before the program's own -- opens
// the library and sets the pointer the import stubs go through.
//
// ---------------------------------------------------------------------------------------------
// MIT License
//
// Copyright (c) 2026 Stéphane Wegener and the Onyx contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
// BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ---------------------------------------------------------------------------------------------
//
#ifndef ONYX_LIB_H
#define ONYX_LIB_H

#include "appkit/appkit.h"

typedef __SIZE_TYPE__ lib_size_t;

// What a library takes from the process that opens it. Append-only (size says how much of it the
// importer has).
struct TLibImports
{
	unsigned size;				// sizeof (struct TLibImports) of the importer
	unsigned ndata;				// the entries of data (0: none)
	void *(*alloc) (lib_size_t n);		// the process's allocator (a C++ program: operator new)
	void  (*free) (void *p);
	// The variables the library shares with the program: they are the PROGRAM's (it is linked at a
	// fixed address: its code reads them directly), the library reaches them through these
	// addresses. What they are is the library's business (uikit: uikit/globals.inc); append-only.
	void *const *data;
};

// The first fields of every library's export table.
struct TLibHeader
{
	unsigned version;			// goes up when entries are appended
	unsigned size;				// the table's size in bytes
	// Once per process, before any other entry: the imports taken, the library's constructors
	// run, the libraries it uses itself opened. Called again: nothing done -> 0, < 0: failed.
	int (*init) (const struct TLibImports *imp);
};

#define LIB_EXIT_STATUS		126		// a program that could not bind a library ends with it

static inline int lib__cat (char *b, int n, int cap, const char *s)
{
	while (*s != '\0' && n < cap - 1) b[n++] = *s++;
	b[n] = '\0';
	return n;
}

// The library `name` opened and initialised -> its table. A failure ends the program -- it cannot
// run without it -- after saying why: on its output if it has one (a command), in the kernel log
// (`kmsg`), and as a desktop notification when the notification service runs.
static inline const void *lib_bind (const char *name, unsigned min_version, const struct TLibImports *imp)
{
	int err = 0;
	const struct TLibHeader *t = (const struct TLibHeader *) kapi_lib_open (name, min_version, &err);
	if (t != 0 && t->init (imp) >= 0) return t;

	char num[12]; int k = 0;
	unsigned v = min_version;
	do { num[k++] = (char) ('0' + v % 10); v /= 10; } while (v != 0);
	char ver[12]; int j = 0;
	while (k > 0) ver[j++] = num[--k];
	ver[j] = '\0';
	char what[96], why[96], msg[200];
	int n = lib__cat (what, 0, sizeof what, "needs the shared library \"");
	n = lib__cat (what, n, sizeof what, name);
	n = lib__cat (what, n, sizeof what, "\" (version ");
	n = lib__cat (what, n, sizeof what, ver);
	lib__cat (what, n, sizeof what, " or later)");
	lib__cat (why, 0, sizeof why,
		  t != 0 ? "its start failed"
		  : err == -KAPI_ENOSYS ? "this kernel has no shared libraries (kapi 83): update the system"
		  : err == -KAPI_ENOENT ? "it is not in SD:/lib: install its package"
		  : err == -KAPI_ENOTSUP ? "the one installed is older: update its package"
		  : err == -KAPI_ENOMEM ? "out of memory"
		  : "it cannot be loaded (see the kernel log)");
	n = lib__cat (msg, 0, sizeof msg, "this program ");
	n = lib__cat (msg, n, sizeof msg, what);
	n = lib__cat (msg, n, sizeof msg, ": ");
	n = lib__cat (msg, n, sizeof msg, why);
	n = lib__cat (msg, n, sizeof msg, "\n");
	if (kapi_stdout () != 0) kapi_stdout_write (msg, (unsigned) n);
	{	// the kernel log: a line each (128 characters at most)
		int l = 0; while (what[l]) l++;
		kapi_write (1, what, (unsigned) l);
		l = 0; while (why[l]) l++;
		kapi_write (1, why, (unsigned) l);
	}
	int pid = kapi_ipc_lookup ("notify");		// (notifyd, if it runs: never started from here)
	if (pid != 0)
	{
		char note[300];
		int m = lib__cat (note, 0, 80, "A program cannot start") + 1;
		int e = lib__cat (note + m, 0, 200, "It ");
		e = lib__cat (note + m, e, 200, what);
		e = lib__cat (note + m, e, 200, ": ");
		e = lib__cat (note + m, e, 200, why);
		kapi_mailbox_send (pid, 1, note, (unsigned) (m + e + 1));	// (notify.h: NOTIFY_MSG_SHOW, title, text)
	}
	kapi_exit (LIB_EXIT_STATUS);
	for (;;) {}
}

#ifdef __cplusplus
// A C++ program's imports: its operator new / delete (onyxpp.hpp's, or the hosted runtime's).
void *operator new (lib_size_t n);
void operator delete (void *p) noexcept;
static inline void *lib__cxx_alloc (lib_size_t n)	{ return ::operator new (n); }
static inline void  lib__cxx_free (void *p)		{ ::operator delete (p); }
static inline const struct TLibImports *lib_cxx_imports (void)
{
	static const struct TLibImports imp = { sizeof (struct TLibImports), 0, lib__cxx_alloc, lib__cxx_free, 0 };
	return &imp;
}
// ... with the variables the program shares with the library (the bind object of such a library).
static inline const struct TLibImports *lib_cxx_imports_data (void *const *data, unsigned ndata)
{
	static struct TLibImports imp;
	imp.size = sizeof (struct TLibImports); imp.ndata = ndata;
	imp.alloc = lib__cxx_alloc; imp.free = lib__cxx_free; imp.data = data;
	return &imp;
}
#endif

#endif // ONYX_LIB_H
