#
# tools/tests/netsurf/host.mk -- NetSurf for Onyx built for the PC (x86 Linux), to see what it
# draws without a Pi: the same sources as user/netsurf/netsurf-app.mk (the library stack, the
# core, the framebuffer frontend, the Onyx glue: onyx_main.c, onyx_fetch.c, onyx_chrome.cpp,
# the "onyx" libnsfb surface), linked with the desktop simulator's stand-in kernel
# (tools/tests/desktop_sim/fakekapi.cpp) and wtk instead of newlib + the real kapi. The app then
# runs through a script of events and its window is dumped (run.sh does that).
#
#   make -f tools/tests/netsurf/host.mk [OUT=/tmp/nshost] [-j8]      (from the repo root)
#
# Differences with the Pi build: the host's libc (no user/netsurf/compat headers but curl/, no
# onyx_compat.c, no newlib glue), the host's libpng + zlib (JPEG and WebP: the vendored
# sources), https through the PC's OpenSSL (host_stubs.c, with SIM_REALNET=1: the real network).
# Objects go to $(OUT)/o only.
#
ROOT     := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../..)
OUT      ?= /tmp/nshost
TP       := $(ROOT)/third_party
NS       := $(TP)/netsurf
UN       := $(ROOT)/user/netsurf
ZUSER    := $(ROOT)/user
ZKINC    := $(ROOT)/kernel/include
SIM      := $(ROOT)/tools/tests/desktop_sim
HERE     := $(ROOT)/tools/tests/netsurf

CC       ?= gcc
CXX      ?= g++
BUILD_CC ?= gcc
AR       ?= ar

WAP  := $(TP)/libwapcaplet
PU   := $(TP)/libparserutils
CSS  := $(TP)/libcss
DOM  := $(TP)/libdom
HB   := $(TP)/libhubbub
NSU  := $(TP)/libnsutils
GIF  := $(TP)/libnsgif
BMP  := $(TP)/libnsbmp
NSFB := $(TP)/libnsfb
FT   := $(TP)/freetype-2.14.3
FONTS := $(TP)/dejavu-fonts-ttf-2.37
JPEG := $(TP)/jpeg-9f
WEBP := $(TP)/libwebp-1.4.0
# Onyx: PlutoVG (the vector rasteriser) and PlutoSVG: SVG images, inline <svg>, <canvas>
PVG  := $(TP)/plutovg-1.3.3
PSVG := $(TP)/plutosvg-0.0.8
PVG_CF := -std=gnu11 -DPLUTOVG_BUILD -DPLUTOVG_BUILD_STATIC -DPLUTOVG_DISABLE_FONT_FACE_CACHE_LOAD \
          -DSTBI_ONLY_PNG -DSTBI_ONLY_JPEG -I$(PVG)/include

# the resources NetSurf reads at run time (Messages, the UA stylesheets...): staged into $(OUT)/res
RESPATH := $(OUT)/res/

# -MMD -MP: each object's header dependencies ($(OUT)/o/*.d, included at the end)
BASEF = -O2 -g -fcommon -fno-strict-aliasing -w -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -DNDEBUG \
        -MMD -MP
CF    = $(BASEF) -std=c99

# -- NetSurf (as netsurf-app.mk; only compat/curl from the Onyx compat headers)
NS_CF = $(CF) -Dnsframebuffer -DWITH_PNG -DWITH_GIF -DWITH_BMP -DWITH_JPEG -DWITH_WEBP \
        -DNETSURF_FB_RESPATH=\"$(RESPATH)\" -DNETSURF_FB_FONTPATH=\"$(RESPATH)fonts\" \
        -DONYX_NS_DATAPATH=\"$(OUT)/data/\" -DONYX_HOST_SIM -include $(UN)/compat/onyx_nsconfig.h
NS_INC = -I$(NS) -I$(NS)/include -I$(NS)/content/handlers -I$(NS)/frontends \
         -I$(OUT)/hostinc -I$(UN) -I$(UN)/gen -I$(OUT) -I$(ZUSER) -I$(ZKINC) \
         -I$(WAP)/include -I$(PU)/include -I$(CSS)/include -I$(DOM)/include -I$(HB)/include \
         -I$(NSU)/include -I$(GIF)/include -I$(BMP)/include -I$(NSFB)/include \
         -I$(DOM)/bindings -I$(DOM)/src -I$(FT)/include -I$(UN)/freetype $(NS_FT_CF) \
         -I$(JPEG) -I$(WEBP)/src \
         -DPLUTOVG_BUILD_STATIC -DPLUTOSVG_BUILD_STATIC -I$(PVG)/include -I$(PSVG)/source \
         -DXML_STATIC -I$(TP)/expat-2.7.1/lib

# ---- sources -------------------------------------------------------------
WAP_SRC := $(shell find $(WAP)/src -name '*.c')
PU_SRC  := $(shell find $(PU)/src -name '*.c')
NSU_SRC := $(shell find $(NSU)/src -name '*.c')
GIF_SRC := $(shell find $(GIF)/src -name '*.c')
BMP_SRC := $(shell find $(BMP)/src -name '*.c')
HB_SRC  := $(shell find $(HB)/src -name '*.c')
# libcss's per-property parsers are generated from properties.gen by a host tool (gen_parser);
# the Pi build makes them in the source tree as make intermediates (deleted afterwards): here
# they go to $(OUT)/cssgen and are kept.
CSS_GENDIR := $(CSS)/src/parse/properties
CSS_AUTONAMES := $(shell perl -pe '$$_="" unless /^([^\#][^:]+):/;$$_=$$1 . " "' $(CSS_GENDIR)/properties.gen)
CSS_AUTO_C := $(addprefix $(OUT)/cssgen/autogenerated_,$(addsuffix .c,$(CSS_AUTONAMES)))
CSS_SRC := $(filter-out %css_property_parser_gen.c %/autogenerated_%.c,$(shell find $(CSS)/src -name '*.c')) $(CSS_AUTO_C)
DOM_SRC := $(shell find $(DOM)/src -name '*.c') $(wildcard $(DOM)/bindings/hubbub/*.c)
NSFB_SRC := $(addprefix $(NSFB)/src/,libnsfb.c cursor.c palette.c surface/surface.c surface/ram.c \
            plot/api.c plot/generic.c plot/util.c plot/8bpp.c plot/16bpp.c \
            plot/32bpp-xrgb8888.c plot/32bpp-xbgr8888.c) $(ROOT)/user/nsfb/onyx_surface.c

# JavaScript: QuickJS and the DOM on it (as netsurf-app.mk; the engine compiled here)
QJS := $(TP)/quickjs-ng-0.17.0
JSQ := $(NS)/content/handlers/javascript/quickjs
QJS_SRC := $(addprefix $(QJS)/,quickjs.c libregexp.c libunicode.c dtoa.c)
JS_SRC := $(JSQ)/qjs.c $(JSQ)/qjs_canvas.c $(JSQ)/qjs_net.c $(JSQ)/qjs_wasm.c $(JSQ)/qjs_crypto.c $(JSQ)/qjs_codecache.c $(JSQ)/qjs_frames.c $(JSQ)/qjs_xml.c
# Onyx: Web Crypto on mbedTLS -- its crypto library compiled here with the Pi's configuration
# (include/mbedtls/mbedtls_config.h; the bench's https is OpenSSL's, host_stubs.c)
MBEDTLS := $(TP)/mbedtls-3.6.3
MBED_SRC := $(filter-out %/net_sockets.c %/timing.c %/psa_its_file.c $(MBEDTLS)/library/ssl_% \
            $(MBEDTLS)/library/x509% $(MBEDTLS)/library/mps_% $(MBEDTLS)/library/pkcs7.c \
            $(MBEDTLS)/library/debug.c,$(wildcard $(MBEDTLS)/library/*.c))
# Onyx: WebAssembly on wasm3 (the interpreter compiled here, -O3 as the Pi's libm3.a)
W3 := $(TP)/wasm3-0.9.2
W3_SRC := $(wildcard $(W3)/src/*.c)

CORE_SRC := \
  $(wildcard $(NS)/utils/*.c) $(wildcard $(NS)/utils/http/*.c) $(wildcard $(NS)/utils/nsurl/*.c) \
  $(wildcard $(NS)/content/*.c) \
  $(wildcard $(NS)/content/fetchers/*.c) \
  $(wildcard $(NS)/content/fetchers/about/*.c) $(wildcard $(NS)/content/fetchers/file/*.c) \
  $(wildcard $(NS)/desktop/*.c) \
  $(wildcard $(NS)/content/handlers/css/*.c) $(wildcard $(NS)/content/handlers/html/*.c) \
  $(wildcard $(NS)/content/handlers/text/*.c) \
  $(addprefix $(NS)/content/handlers/image/,bmp.c gif.c ico.c image.c image_cache.c png.c jpeg.c webp.c onyx_svg.c onyx_vgfont.c) \
  $(wildcard $(NS)/content/handlers/javascript/*.c) $(JS_SRC)

FB := $(NS)/frontends/framebuffer
include $(UN)/netsurf-src.mk
FE_SRC := $(addprefix $(FB)/,$(NS_FB_FILES)) $(wildcard $(FB)/fbtk/*.c)

ONYX_SRC   := $(UN)/onyx_fetch.c $(UN)/onyx_cache.c $(UN)/onyx_ws.c $(UN)/onyx_main.c $(HERE)/host_stubs.c
ONYX_CXX   := $(ONYX_CXX_FILES)

FB_IMG := $(NS_FB_IMAGES)
IMG_C  := $(foreach p,$(FB_IMG),$(OUT)/image-$(word 1,$(subst :, ,$(p))).c)

# FreeType: the modules of the Pi build (user/netsurf/Makefile's FT_FILES)
FT_SRC := $(addprefix $(FT)/src/,base/ftsystem.c base/ftinit.c base/ftdebug.c base/ftbase.c \
          base/ftbbox.c base/ftbitmap.c base/ftglyph.c base/ftsynth.c base/ftmm.c autofit/autofit.c \
          truetype/truetype.c sfnt/sfnt.c smooth/smooth.c psnames/psnames.c cache/ftcache.c \
          cff/cff.c psaux/psaux.c pshinter/pshinter.c gzip/ftgzip.c)
BRO := $(TP)/brotli-1.1.0
BRO_SRC := $(wildcard $(BRO)/c/common/*.c $(BRO)/c/dec/*.c)
I_BRO := -I$(BRO)/c/include
# (zlib: the PC's own, as the link's -lz)
# JPEG (the IJG's libjpeg 9f) and WebP's decoder, as the Pi build links them
JPEG_SRC := $(addprefix $(JPEG)/,$(addsuffix .c,jaricom jcapimin jcapistd jcarith jccoefct jccolor \
            jcdctmgr jchuff jcinit jcmainct jcmarker jcmaster jcomapi jcparam jcprepct jcsample \
            jctrans jdapimin jdapistd jdarith jdatadst jdatasrc jdcoefct jdcolor jddctmgr jdhuff \
            jdinput jdmainct jdmarker jdmaster jdmerge jdpostct jdsample jdtrans jerror jfdctflt \
            jfdctfst jfdctint jidctflt jidctfst jidctint jquant1 jquant2 jutils jmemmgr jmemnobs))
WEBP_SRC := $(wildcard $(WEBP)/src/dec/*.c $(WEBP)/src/dsp/*.c $(WEBP)/src/utils/*.c)
I_FT := -DFT2_BUILD_LIBRARY '-DFT_CONFIG_MODULES_H=<onyx_ftmodule.h>' \
        '-DFT_CONFIG_OPTIONS_H=<onyx_ftoption.h>' -I$(UN)/freetype -I$(FT)/include $(I_BRO)

PVG_SRC := $(wildcard $(PVG)/source/plutovg-*.c)
PSVG_SRC := $(PSVG)/source/plutosvg.c

# Onyx: expat, the XML parser (XML documents, DOMParser's XML: docs/06 section 43)
EXPAT := $(TP)/expat-2.7.1
EXPAT_SRC := $(EXPAT)/lib/xmlparse.c $(EXPAT)/lib/xmlrole.c $(EXPAT)/lib/xmltok.c

# Onyx: the GPU compositing service (user/gpucomp: its CPU path here -- fakekapi has no GPU)
GPC_SRC := $(ZUSER)/gpucomp/gpucomp.c

# Onyx: mbedTLS (the Pi's TLS) for NS_MBEDTLS=1 (host_stubs.c) and the certificate viewer
MBED := $(TP)/mbedtls-3.6.3
MBED_SRC := $(wildcard $(MBED)/library/*.c)

# Onyx: the fetcher's zstd decoder and HTTP/2 (as user/netsurf/Makefile builds them)
ZSTD := $(TP)/zstd-1.5.7
ZSTD_SRC := $(wildcard $(ZSTD)/lib/common/*.c $(ZSTD)/lib/decompress/*.c)
NGH := $(TP)/nghttp2-1.70.0
NGH_SRC := $(wildcard $(NGH)/lib/*.c)

LIB_ALL := $(EXPAT_SRC) $(W3_SRC) $(GPC_SRC) $(ZSTD_SRC) $(NGH_SRC) $(MBED_SRC) $(PVG_SRC) $(PSVG_SRC) $(JPEG_SRC) $(WEBP_SRC) $(QJS_SRC) $(FT_SRC) $(BRO_SRC) $(WAP_SRC) $(PU_SRC) $(NSU_SRC) $(GIF_SRC) $(BMP_SRC) $(HB_SRC) $(CSS_SRC) $(DOM_SRC)
NS_ALL  := $(CORE_SRC) $(FE_SRC) $(ONYX_SRC) $(IMG_C)

obj = $(OUT)/o/$(subst /,_,$(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(1))))
LIB_OBJ  := $(foreach s,$(LIB_ALL),$(call obj,$(s)))
NSFB_OBJ := $(foreach s,$(NSFB_SRC),$(call obj,$(s)))
NS_OBJ   := $(foreach s,$(NS_ALL),$(call obj,$(s)))
CXX_OBJ  := $(foreach s,$(ONYX_CXX),$(call obj,$(s)))
WTK_SRC  := $(filter-out %imgload.cpp,$(wildcard $(ZUSER)/wtk/*.cpp)) $(SIM)/imgstub.cpp $(SIM)/fakekapi.cpp
WTK_OBJ  := $(foreach s,$(WTK_SRC),$(call obj,$(s)))

.PHONY: all
all: $(OUT)/netsurf res

# ---- code generation (host tools) --------------------------------------------
$(OUT)/tools/convert_image: $(NS)/tools/convert_image.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -I$(FB) -o $@ $< -lpng
define IMG_RULE
$(OUT)/image-$(word 1,$(subst :, ,$(1))).c: $(FB)/res/$(word 2,$(subst :, ,$(1))) $(OUT)/tools/convert_image
	@mkdir -p $(OUT)
	$(OUT)/tools/convert_image $(FB)/res/$(word 2,$(subst :, ,$(1))) $$@ $(word 1,$(subst :, ,$(1)))
endef
$(foreach p,$(FB_IMG),$(eval $(call IMG_RULE,$(p))))

$(OUT)/cssgen/gen_parser: $(CSS_GENDIR)/css_property_parser_gen.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -o $@ $<
$(OUT)/cssgen/autogenerated_%.c: $(OUT)/cssgen/gen_parser $(CSS_GENDIR)/properties.gen
	cd $(CSS) && $(OUT)/cssgen/gen_parser -o $@ "$$(grep "^$*:" $(CSS_GENDIR)/properties.gen)"
.SECONDARY: $(CSS_AUTO_C)

$(OUT)/hostinc/curl/curl.h: $(UN)/compat/curl/curl.h
	@mkdir -p $(dir $@)
	cp $< $@

# ---- compilation -------------------------------------------------------------
# each library with its OWN include set (as user/netsurf/Makefile): their src/ trees have
# same-named headers (utils/*.h) that must not see each other.
I_WAP := -I$(WAP)/include -I$(WAP)/src
I_PU  := -I$(PU)/include -I$(PU)/src -DWITHOUT_ICONV_FILTER
I_NSU := -I$(NSU)/include -I$(NSU)/src
I_GIF := -I$(GIF)/include -I$(GIF)/src
I_BMP := -I$(BMP)/include -I$(BMP)/src
I_HB  := -I$(HB)/include -I$(HB)/src -I$(PU)/include
I_CSS := -I$(CSS)/include -I$(CSS)/src -I$(WAP)/include -I$(PU)/include
I_DOM := -I$(DOM)/include -I$(DOM)/src -I$(WAP)/include -I$(PU)/include -I$(HB)/include
define LIB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CC) $$(CF) $(2) -c $$< -o $$@
endef
$(foreach s,$(QJS_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(QJS))))
$(foreach s,$(GPC_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -ffp-contract=off -I$(ZUSER) -I$(ZKINC))))
$(foreach s,$(MBED_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(MBED)/include -I$(MBED)/library)))
$(foreach s,$(ZSTD_SRC),$(eval $(call LIB_RULE,$(s),-DZSTD_DISABLE_ASM -DZSTD_LEGACY_SUPPORT=0 -DDEBUGLEVEL=0 -DZSTD_NO_TRACE -I$(ZSTD)/lib -I$(ZSTD)/lib/common)))
$(foreach s,$(NGH_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu99 -DHAVE_CONFIG_H -DNGHTTP2_STATICLIB -I$(NGH)/lib -I$(NGH)/lib/includes)))
$(foreach s,$(W3_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -O3 -I$(W3)/src)))
$(foreach s,$(JPEG_SRC),$(eval $(call LIB_RULE,$(s),-I$(JPEG))))
$(foreach s,$(PVG_SRC),$(eval $(call LIB_RULE,$(s),$(PVG_CF))))
$(foreach s,$(PSVG_SRC),$(eval $(call LIB_RULE,$(s),$(PVG_CF) -DPLUTOSVG_BUILD -DPLUTOSVG_BUILD_STATIC -I$(PSVG)/source)))
$(foreach s,$(EXPAT_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu99 -DXML_STATIC -I$(EXPAT)/lib)))
$(foreach s,$(WEBP_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(WEBP) -I$(WEBP)/src)))
$(foreach s,$(FT_SRC),$(eval $(call LIB_RULE,$(s),$(I_FT))))
$(foreach s,$(BRO_SRC),$(eval $(call LIB_RULE,$(s),$(I_BRO))))
$(foreach s,$(WAP_SRC),$(eval $(call LIB_RULE,$(s),$(I_WAP))))
$(foreach s,$(PU_SRC),$(eval $(call LIB_RULE,$(s),$(I_PU))))
$(foreach s,$(NSU_SRC),$(eval $(call LIB_RULE,$(s),$(I_NSU))))
$(foreach s,$(GIF_SRC),$(eval $(call LIB_RULE,$(s),$(I_GIF))))
$(foreach s,$(BMP_SRC),$(eval $(call LIB_RULE,$(s),$(I_BMP))))
$(foreach s,$(HB_SRC),$(eval $(call LIB_RULE,$(s),$(I_HB))))
$(foreach s,$(CSS_SRC),$(eval $(call LIB_RULE,$(s),$(I_CSS))))
$(foreach s,$(DOM_SRC),$(eval $(call LIB_RULE,$(s),$(I_DOM))))

define NSFB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CC) $$(CF) -D_BSD_SOURCE -I$(NSFB)/include -I$(NSFB)/src -I$(ZUSER) -I$(ZKINC) -DONYX_HOST_SIM -c $$< -o $$@
endef
$(foreach s,$(NSFB_SRC),$(eval $(call NSFB_RULE,$(s))))

define NS_RULE
$(call obj,$(1)): $(1) $(OUT)/hostinc/curl/curl.h
	@mkdir -p $(OUT)/o
	$$(CC) $$(NS_CF) $$(NS_INC) -c $$< -o $$@
endef
$(foreach s,$(NS_ALL),$(eval $(call NS_RULE,$(s))))
$(call obj,$(FB)/gui.c): NS_CF += -Dmain=netsurf_main
# Onyx: the fetcher's decoders (br, zstd) and HTTP/2 (nghttp2)
$(call obj,$(UN)/onyx_fetch.c): NS_CF += $(I_BRO) -I$(ZSTD)/lib -I$(NGH)/lib/includes -DNGHTTP2_STATICLIB
# Onyx: the certificate viewer (about:certificate) on mbedTLS, as on the Pi
$(call obj,$(NS)/content/fetchers/about/certificate.c): NS_CF += -DWITH_MBEDTLS -I$(MBED)/include

# dom.js as a C string for qjs.c (as netsurf-app.mk)
$(OUT)/qjsgen/qjs_dom_js.h: $(JSQ)/dom.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from dom.js by host.mk */'; echo 'static const char qjs_dom_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
# Onyx: html5.js too (the HTML5 DOM: namespaces, fragments, forms, messaging...)
$(OUT)/qjsgen/qjs_html5_js.h: $(JSQ)/html5.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from html5.js by host.mk */'; echo 'static const char qjs_html5_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs.c): $(OUT)/qjsgen/qjs_dom_js.h $(OUT)/qjsgen/qjs_html5_js.h
$(call obj,$(JSQ)/qjs.c): $(OUT)/qjsgen/qjs_dom_js.h
$(call obj,$(JSQ)/qjs.c): $(OUT)/qjsgen/qjs_intl_js.h
# Onyx: intl.js (Intl) and its locale data (CLDR) as C strings for qjs_intl.h
$(OUT)/qjsgen/qjs_intl_js.h: $(JSQ)/intl.js $(TP)/cldr-48/intl-data.txt
	@mkdir -p $(dir $@)
	{ echo '/* generated from intl.js and intl-data.txt by host.mk */'; echo 'static const char qjs_intl_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; \
	  echo 'static const char qjs_intl_data[] ='; \
	  sed -e 's/\r$$//' -e '/^#/d' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $(TP)/cldr-48/intl-data.txt; echo ';'; } > $@
$(call obj,$(JSQ)/qjs.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
# Onyx: <canvas> 2D -- canvas.js as a C string for qjs_canvas.c (as dom.js)
$(OUT)/qjsgen/qjs_canvas_js.h: $(JSQ)/canvas.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from canvas.js by host.mk */'; echo 'static const char qjs_canvas_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_canvas.c): $(OUT)/qjsgen/qjs_canvas_js.h
$(call obj,$(JSQ)/qjs_canvas.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
# Onyx: WebSocket, EventSource, streamed fetch, Workers -- net.js as a C string for qjs_net.c
$(OUT)/qjsgen/qjs_net_js.h: $(JSQ)/net.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from net.js by host.mk */'; echo 'static const char qjs_net_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_net.c): $(OUT)/qjsgen/qjs_net_js.h
$(call obj,$(JSQ)/qjs_net.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
# Onyx: WebAssembly -- wasm.js as a C string for qjs_wasm.c (on wasm3's headers)
$(OUT)/qjsgen/qjs_wasm_js.h: $(JSQ)/wasm.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from wasm.js by host.mk */'; echo 'static const char qjs_wasm_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_wasm.c): $(OUT)/qjsgen/qjs_wasm_js.h
$(call obj,$(JSQ)/qjs_wasm.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen -I$(W3)/src
# Onyx: Web Crypto -- crypto.js as a C string for qjs_crypto.c (on mbedTLS)
$(OUT)/qjsgen/qjs_crypto_js.h: $(JSQ)/crypto.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from crypto.js by host.mk */'; echo 'static const char qjs_crypto_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_crypto.c): $(OUT)/qjsgen/qjs_crypto_js.h
$(call obj,$(JSQ)/qjs_crypto.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen -I$(MBEDTLS)/include
# Onyx: the code cache (the scripts' bytecode on the card; SHA-256 from mbedTLS)
$(call obj,$(JSQ)/qjs_codecache.c): NS_INC += -I$(QJS) -I$(MBEDTLS)/include
# Onyx: the frames' windows, postMessage between them, MessagePort across realms
$(call obj,$(JSQ)/qjs_frames.c): NS_INC += -I$(QJS)
# Onyx: XPath / XSLT (docs/06 section 43) -- xslt.js as a C string for qjs_xml.c (loaded on demand)
$(OUT)/qjsgen/qjs_xslt_js.h: $(JSQ)/xslt.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from xslt.js by host.mk */'; echo 'static const char qjs_xslt_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_xml.c): $(OUT)/qjsgen/qjs_xslt_js.h
$(call obj,$(JSQ)/qjs_xml.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen

CXXF = -std=gnu++17 -O1 -g -w -fno-exceptions -fno-rtti -I$(ZUSER) -I$(ZKINC) -DIMG_HOST_TEST -DONYX_HOST_SIM \
       -MMD -MP
define CXX_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CXX) $$(CXXF) -I$(UN) -I$(NS) -I$(NS)/include -I$(NS)/frontends -c $$< -o $$@
endef
$(foreach s,$(ONYX_CXX) $(WTK_SRC),$(eval $(call CXX_RULE,$(s))))

# ---- link --------------------------------------------------------------------
# Onyx: SOFTGPU=1 -- the software V3D linked in (tools/tests/gpucomp/hostkapi.cpp: the kernel's FS_TEX in
# the QPU simulator; GPC_SOFTGPU=1 at run time): the compositor's GPU path, slowly (a small window)
ifneq ($(SOFTGPU),)
QPU := $(ROOT)/tools/qpu
SG_OBJ := $(OUT)/sg/hostkapi.o $(OUT)/sg/qpusim.o $(addprefix $(OUT)/sg/,qpulib.o ralloc_stub.o qpu_instr.o qpu_pack.o qpu_disasm.o)
$(OUT)/sg/hostkapi.o: $(ROOT)/tools/tests/gpucomp/hostkapi.cpp
	@mkdir -p $(OUT)/sg
	$(CXX) -std=gnu++20 -O2 -w -DHOSTKAPI_GPU_ONLY -I$(ROOT)/tools/tests/fs/stub -I$(ZKINC) -I$(QPU) -I$(QPU)/mesa -c $< -o $@
$(OUT)/sg/qpusim.o: $(QPU)/qpusim.cpp
	@mkdir -p $(OUT)/sg
	$(CXX) -std=gnu++17 -O2 -w -I$(QPU) -I$(QPU)/mesa -c $< -o $@
$(OUT)/sg/%.o: $(QPU)/%.c
	@mkdir -p $(OUT)/sg
	$(CC) -std=gnu11 -O1 -w -I$(QPU)/mesa -I$(QPU) -c $< -o $@
$(OUT)/sg/%.o: $(QPU)/mesa/broadcom/qpu/%.c
	@mkdir -p $(OUT)/sg
	$(CC) -std=gnu11 -O1 -w -I$(QPU)/mesa -I$(QPU) -c $< -o $@
endif


# Onyx: the Pi's TLS glue (onyx_nstls.cpp: mbedTLS over the simulator's sockets), its calls
# renamed onyx_mb_* -- host_stubs.c uses it with NS_MBEDTLS=1
MB_REN := -Donyx_tls_sess=onyx_mb_sess -Donyx_nstls_connect=onyx_mb_connect \
	-Donyx_nstls_ca_bundle=onyx_mb_ca_bundle -Donyx_nstls_send=onyx_mb_send \
	-Donyx_nstls_recv=onyx_mb_recv -Donyx_nstls_close=onyx_mb_close -Donyx_nstls_alpn=onyx_mb_alpn -Donyx_nstls_version=onyx_mb_version \
	-Donyx_nstls_chain_free=onyx_mb_chain_free -Donyx_nstls_start=onyx_mb_start \
	-Donyx_nstls_open=onyx_mb_open -Donyx_nstls_cancel_flag=onyx_mb_cancel_flag \
	-Donyx_nstls_resumed=onyx_mb_resumed -Donyx_nstls_sessions_load=onyx_mb_sessions_load \
	-Donyx_nstls_sessions_save=onyx_mb_sessions_save
MB_OBJ := $(OUT)/o/onyx_nstls_mb.o
$(MB_OBJ): $(UN)/onyx_nstls.cpp $(UN)/onyx_nstls.h $(ZUSER)/tls/onyx_tls.hpp
	@mkdir -p $(OUT)/o
	$(CXX) $(CXXF) $(MB_REN) -I$(UN) -I$(ZUSER)/tls -I$(MBED)/include -c $< -o $@

$(OUT)/netsurf: $(LIB_OBJ) $(NSFB_OBJ) $(NS_OBJ) $(CXX_OBJ) $(WTK_OBJ) $(MB_OBJ) $(SG_OBJ)
	$(CXX) -o $@ $^ -lpng -lz -lm -lssl -lcrypto -lpthread
	@echo "host netsurf: $@"

# ---- the resources (as netsurf-app.mk's stage, into $(OUT)/res) ------------------
.PHONY: res
res:
	@mkdir -p $(OUT)/res/en $(OUT)/data
	grep -E '^en\.(all|framebuffer)\.' $(NS)/resources/FatMessages | sed -E 's/^en\.(all|framebuffer)\.//' > $(OUT)/res/Messages
	for f in default.css quirks.css adblock.css internal.css; do cp $(NS)/resources/$$f $(OUT)/res/; done
	: > $(OUT)/res/user.css
	for f in welcome.html credits.html licence.html; do cp $(NS)/resources/en/$$f $(OUT)/res/; cp $(NS)/resources/en/$$f $(OUT)/res/en/; done
	@mkdir -p $(OUT)/res/icons
	for f in arrow-l content directory directory2 hotlist-add hotlist-rmv search; do cp $(NS)/resources/icons/$$f.png $(OUT)/res/icons/ 2>/dev/null || true; done
	-cp $(NS)/resources/favicon.png $(NS)/resources/netsurf.png $(OUT)/res/
	# Onyx: the trusted roots -- the card's bundle, and this machine's proxy CA when it has one
	# (an HTTPS proxy that re-terminates TLS: /root/.ccr/agent-proxy-ca.crt, or CA_EXTRA=<pem>)
	cat $(NS)/resources/ca-bundle > $(OUT)/res/ca-bundle
	-for f in $(CA_EXTRA) /root/.ccr/agent-proxy-ca.crt; do [ -f "$$f" ] && cat "$$f" >> $(OUT)/res/ca-bundle; done; true
	@mkdir -p $(OUT)/res/fonts
	cp $(FONTS)/ttf/*.ttf $(OUT)/res/fonts/
	cp $(TP)/fonts/*/*.ttf $(OUT)/res/fonts/
	printf 'foreground_images:1\nbackground_images:1\nenable_javascript:1\n' > $(OUT)/res/Choices

-include $(wildcard $(OUT)/o/*.d)

# ---- libcss's own selection tests (its test/select.c on test/data/select/*.dat): a check of
# the cascade after changing libcss --  make -f tools/tests/netsurf/host.mk libcss-test
CSS_TEST_OBJ := $(foreach s,$(CSS_SRC) $(WAP_SRC) $(PU_SRC),$(call obj,$(s)))
$(OUT)/libcss-select-test: $(CSS)/test/select.c $(CSS)/test/dump_computed.h $(CSS_TEST_OBJ)
	@$(CC) $(CF) $(I_CSS) -I$(CSS)/test -o $@ $< $(CSS_TEST_OBJ) -lm
.PHONY: libcss-test
libcss-test: $(OUT)/libcss-select-test
	@for t in $(CSS)/test/data/select/*.dat; do \
		echo "$$(basename $$t): $$($(OUT)/libcss-select-test $$t 2>&1 | tail -1)"; done

# ---- what libcss keeps (tools/tests/netsurf/csscheck.c on css-values.txt): the parser's
# answers to CSS.supports() -- make -f tools/tests/netsurf/host.mk css-check
$(OUT)/csscheck: $(HERE)/csscheck.c $(CSS_TEST_OBJ)
	@$(CC) $(CF) $(I_CSS) -o $@ $< $(CSS_TEST_OBJ) -lm
.PHONY: css-check
css-check: $(OUT)/csscheck
	@$(OUT)/csscheck $(HERE)/css-values.txt
