#
# tools/tests/netsurf/host.mk -- NetSurf for Onyx built for the PC (x86 Linux), to see what it
# draws without a Pi: the same sources as user/netsurf/netsurf-app.mk (the library stack, the
# core, the framebuffer frontend, the Onyx glue: onyx_main.c, onyx_fetch.c, onyx_chrome.cpp,
# the "onyx" libnsfb surface), linked with the desktop simulator's stand-in kernel
# (tools/tests/desktop_sim/fakekapi.cpp) and wtk instead of newlib + the real kapi. The app then
# runs through a script of events and its window is dumped (run.sh does that).
#
#   make -f tools/tests/netsurf/host.mk [OUT=/tmp/nshost] [-j8]      (from the repo root)
#
# Differences with the Pi build: the host's libc (no user/netsurf/compat headers but curl/, no
# onyx_compat.c, no newlib glue), the host's libpng + zlib (JPEG and WebP: the vendored
# sources), https through the PC's OpenSSL (host_stubs.c, with SIM_REALNET=1: the real network).
# Objects go to $(OUT)/o only.
#
ROOT     := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../..)
OUT      ?= /tmp/nshost
TP       := $(ROOT)/third_party
NS       := $(TP)/netsurf
UN       := $(ROOT)/user/netsurf
ZUSER    := $(ROOT)/user
ZKINC    := $(ROOT)/kernel/include
SIM      := $(ROOT)/tools/tests/desktop_sim
HERE     := $(ROOT)/tools/tests/netsurf

CC       ?= gcc
CXX      ?= g++
BUILD_CC ?= gcc
AR       ?= ar

WAP  := $(TP)/libwapcaplet
PU   := $(TP)/libparserutils
CSS  := $(TP)/libcss
DOM  := $(TP)/libdom
HB   := $(TP)/libhubbub
NSU  := $(TP)/libnsutils
GIF  := $(TP)/libnsgif
BMP  := $(TP)/libnsbmp
NSFB := $(TP)/libnsfb
FT   := $(TP)/freetype-2.14.3
FONTS := $(TP)/dejavu-fonts-ttf-2.37
JPEG := $(TP)/jpeg-9f
WEBP := $(TP)/libwebp-1.4.0

# the resources NetSurf reads at run time (Messages, the UA stylesheets...): staged into $(OUT)/res
RESPATH := $(OUT)/res/

# -MMD -MP: each object's header dependencies ($(OUT)/o/*.d, included at the end)
BASEF = -O2 -g -fcommon -fno-strict-aliasing -w -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -DNDEBUG \
        -MMD -MP
CF    = $(BASEF) -std=c99

# -- NetSurf (as netsurf-app.mk; only compat/curl from the Onyx compat headers)
NS_CF = $(CF) -Dnsframebuffer -DWITH_PNG -DWITH_GIF -DWITH_BMP -DWITH_JPEG -DWITH_WEBP \
        -DNETSURF_FB_RESPATH=\"$(RESPATH)\" -DNETSURF_FB_FONTPATH=\"$(RESPATH)fonts\" \
        -DONYX_NS_DATAPATH=\"$(OUT)/data/\" -DONYX_HOST_SIM -include $(UN)/compat/onyx_nsconfig.h
NS_INC = -I$(NS) -I$(NS)/include -I$(NS)/content/handlers -I$(NS)/frontends \
         -I$(OUT)/hostinc -I$(UN) -I$(UN)/gen -I$(OUT) -I$(ZUSER) -I$(ZKINC) \
         -I$(WAP)/include -I$(PU)/include -I$(CSS)/include -I$(DOM)/include -I$(HB)/include \
         -I$(NSU)/include -I$(GIF)/include -I$(BMP)/include -I$(NSFB)/include \
         -I$(DOM)/bindings -I$(DOM)/src -I$(FT)/include -I$(UN)/freetype $(NS_FT_CF) \
         -I$(JPEG) -I$(WEBP)/src

# ---- sources -------------------------------------------------------------
WAP_SRC := $(shell find $(WAP)/src -name '*.c')
PU_SRC  := $(shell find $(PU)/src -name '*.c')
NSU_SRC := $(shell find $(NSU)/src -name '*.c')
GIF_SRC := $(shell find $(GIF)/src -name '*.c')
BMP_SRC := $(shell find $(BMP)/src -name '*.c')
HB_SRC  := $(shell find $(HB)/src -name '*.c' ! -name 'autogenerated-element-type.c')
# libcss's per-property parsers are generated from properties.gen by a host tool (gen_parser);
# the Pi build makes them in the source tree as make intermediates (deleted afterwards): here
# they go to $(OUT)/cssgen and are kept.
CSS_GENDIR := $(CSS)/src/parse/properties
CSS_AUTONAMES := $(shell perl -pe '$$_="" unless /^([^\#][^:]+):/;$$_=$$1 . " "' $(CSS_GENDIR)/properties.gen)
CSS_AUTO_C := $(addprefix $(OUT)/cssgen/autogenerated_,$(addsuffix .c,$(CSS_AUTONAMES)))
CSS_SRC := $(filter-out %css_property_parser_gen.c %/autogenerated_%.c,$(shell find $(CSS)/src -name '*.c')) $(CSS_AUTO_C)
DOM_SRC := $(shell find $(DOM)/src -name '*.c') $(wildcard $(DOM)/bindings/hubbub/*.c)
NSFB_SRC := $(addprefix $(NSFB)/src/,libnsfb.c cursor.c palette.c surface/surface.c surface/ram.c \
            plot/api.c plot/generic.c plot/util.c plot/8bpp.c plot/16bpp.c \
            plot/32bpp-xrgb8888.c plot/32bpp-xbgr8888.c) $(ROOT)/user/nsfb/onyx_surface.c

# JavaScript: QuickJS and the DOM on it (as netsurf-app.mk; the engine compiled here)
QJS := $(TP)/quickjs-ng-0.17.0
JSQ := $(NS)/content/handlers/javascript/quickjs
QJS_SRC := $(addprefix $(QJS)/,quickjs.c libregexp.c libunicode.c dtoa.c)
JS_SRC := $(JSQ)/qjs.c

CORE_SRC := \
  $(wildcard $(NS)/utils/*.c) $(wildcard $(NS)/utils/http/*.c) $(wildcard $(NS)/utils/nsurl/*.c) \
  $(wildcard $(NS)/content/*.c) \
  $(filter-out %/curl.c,$(wildcard $(NS)/content/fetchers/*.c)) \
  $(wildcard $(NS)/content/fetchers/about/*.c) $(wildcard $(NS)/content/fetchers/file/*.c) \
  $(wildcard $(NS)/desktop/*.c) \
  $(wildcard $(NS)/content/handlers/css/*.c) $(wildcard $(NS)/content/handlers/html/*.c) \
  $(wildcard $(NS)/content/handlers/text/*.c) \
  $(addprefix $(NS)/content/handlers/image/,bmp.c gif.c ico.c image.c image_cache.c png.c jpeg.c webp.c) \
  $(wildcard $(NS)/content/handlers/javascript/*.c) $(JS_SRC)

FB := $(NS)/frontends/framebuffer
include $(UN)/netsurf-src.mk
FE_SRC := $(addprefix $(FB)/,$(NS_FB_FILES)) $(wildcard $(FB)/fbtk/*.c)

ONYX_SRC   := $(UN)/onyx_fetch.c $(UN)/onyx_main.c $(HERE)/host_stubs.c
ONYX_CXX   := $(ONYX_CXX_FILES)

GENFONT := $(OUT)/font-ns-sans.c
FB_IMG := $(NS_FB_IMAGES)
IMG_C  := $(foreach p,$(FB_IMG),$(OUT)/image-$(word 1,$(subst :, ,$(p))).c)

# FreeType: the modules of the Pi build (user/netsurf/Makefile's FT_FILES)
FT_SRC := $(addprefix $(FT)/src/,base/ftsystem.c base/ftinit.c base/ftdebug.c base/ftbase.c \
          base/ftbbox.c base/ftbitmap.c base/ftglyph.c base/ftsynth.c base/ftmm.c autofit/autofit.c \
          truetype/truetype.c sfnt/sfnt.c smooth/smooth.c psnames/psnames.c cache/ftcache.c \
          cff/cff.c psaux/psaux.c pshinter/pshinter.c gzip/ftgzip.c)
BRO := $(TP)/brotli-1.1.0
BRO_SRC := $(wildcard $(BRO)/c/common/*.c $(BRO)/c/dec/*.c)
I_BRO := -I$(BRO)/c/include
# (zlib: the PC's own, as the link's -lz)
# JPEG (the IJG's libjpeg 9f) and WebP's decoder, as the Pi build links them
JPEG_SRC := $(addprefix $(JPEG)/,$(addsuffix .c,jaricom jcapimin jcapistd jcarith jccoefct jccolor \
            jcdctmgr jchuff jcinit jcmainct jcmarker jcmaster jcomapi jcparam jcprepct jcsample \
            jctrans jdapimin jdapistd jdarith jdatadst jdatasrc jdcoefct jdcolor jddctmgr jdhuff \
            jdinput jdmainct jdmarker jdmaster jdmerge jdpostct jdsample jdtrans jerror jfdctflt \
            jfdctfst jfdctint jidctflt jidctfst jidctint jquant1 jquant2 jutils jmemmgr jmemnobs))
WEBP_SRC := $(wildcard $(WEBP)/src/dec/*.c $(WEBP)/src/dsp/*.c $(WEBP)/src/utils/*.c)
I_FT := -DFT2_BUILD_LIBRARY '-DFT_CONFIG_MODULES_H=<onyx_ftmodule.h>' \
        '-DFT_CONFIG_OPTIONS_H=<onyx_ftoption.h>' -I$(UN)/freetype -I$(FT)/include $(I_BRO)

LIB_ALL := $(JPEG_SRC) $(WEBP_SRC) $(QJS_SRC) $(FT_SRC) $(BRO_SRC) $(WAP_SRC) $(PU_SRC) $(NSU_SRC) $(GIF_SRC) $(BMP_SRC) $(HB_SRC) $(CSS_SRC) $(DOM_SRC)
NS_ALL  := $(CORE_SRC) $(FE_SRC) $(ONYX_SRC) $(GENFONT) $(IMG_C)

obj = $(OUT)/o/$(subst /,_,$(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(1))))
LIB_OBJ  := $(foreach s,$(LIB_ALL),$(call obj,$(s)))
NSFB_OBJ := $(foreach s,$(NSFB_SRC),$(call obj,$(s)))
NS_OBJ   := $(foreach s,$(NS_ALL),$(call obj,$(s)))
CXX_OBJ  := $(foreach s,$(ONYX_CXX),$(call obj,$(s)))
WTK_SRC  := $(filter-out %imgload.cpp,$(wildcard $(ZUSER)/wtk/*.cpp)) $(SIM)/imgstub.cpp $(SIM)/fakekapi.cpp
WTK_OBJ  := $(foreach s,$(WTK_SRC),$(call obj,$(s)))

.PHONY: all
all: $(OUT)/netsurf res

# ---- code generation (host tools) --------------------------------------------
$(OUT)/tools/convert_font: $(NS)/tools/convert_font.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -o $@ $<
$(GENFONT) $(OUT)/font-ns-sans.h: $(OUT)/tools/convert_font $(FB)/res/fonts/glyph_data
	@mkdir -p $(OUT)
	$(OUT)/tools/convert_font -H $(OUT)/font-ns-sans.h $(FB)/res/fonts/glyph_data $(GENFONT)
$(OUT)/tools/convert_image: $(NS)/tools/convert_image.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -I$(FB) -o $@ $< -lpng
define IMG_RULE
$(OUT)/image-$(word 1,$(subst :, ,$(1))).c: $(FB)/res/$(word 2,$(subst :, ,$(1))) $(OUT)/tools/convert_image
	@mkdir -p $(OUT)
	$(OUT)/tools/convert_image $(FB)/res/$(word 2,$(subst :, ,$(1))) $$@ $(word 1,$(subst :, ,$(1)))
endef
$(foreach p,$(FB_IMG),$(eval $(call IMG_RULE,$(p))))

$(OUT)/cssgen/gen_parser: $(CSS_GENDIR)/css_property_parser_gen.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -o $@ $<
$(OUT)/cssgen/autogenerated_%.c: $(OUT)/cssgen/gen_parser $(CSS_GENDIR)/properties.gen
	cd $(CSS) && $(OUT)/cssgen/gen_parser -o $@ "$$(grep "^$*:" $(CSS_GENDIR)/properties.gen)"
.SECONDARY: $(CSS_AUTO_C)

$(OUT)/hostinc/curl/curl.h: $(UN)/compat/curl/curl.h
	@mkdir -p $(dir $@)
	cp $< $@

# ---- compilation -------------------------------------------------------------
# each library with its OWN include set (as user/netsurf/Makefile): their src/ trees have
# same-named headers (utils/*.h) that must not see each other.
I_WAP := -I$(WAP)/include -I$(WAP)/src
I_PU  := -I$(PU)/include -I$(PU)/src -DWITHOUT_ICONV_FILTER
I_NSU := -I$(NSU)/include -I$(NSU)/src
I_GIF := -I$(GIF)/include -I$(GIF)/src
I_BMP := -I$(BMP)/include -I$(BMP)/src
I_HB  := -I$(HB)/include -I$(HB)/src -I$(PU)/include
I_CSS := -I$(CSS)/include -I$(CSS)/src -I$(WAP)/include -I$(PU)/include
I_DOM := -I$(DOM)/include -I$(DOM)/src -I$(WAP)/include -I$(PU)/include -I$(HB)/include
define LIB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CC) $$(CF) $(2) -c $$< -o $$@
endef
$(foreach s,$(QJS_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(QJS))))
$(foreach s,$(JPEG_SRC),$(eval $(call LIB_RULE,$(s),-I$(JPEG))))
$(foreach s,$(WEBP_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(WEBP) -I$(WEBP)/src)))
$(foreach s,$(FT_SRC),$(eval $(call LIB_RULE,$(s),$(I_FT))))
$(foreach s,$(BRO_SRC),$(eval $(call LIB_RULE,$(s),$(I_BRO))))
$(foreach s,$(WAP_SRC),$(eval $(call LIB_RULE,$(s),$(I_WAP))))
$(foreach s,$(PU_SRC),$(eval $(call LIB_RULE,$(s),$(I_PU))))
$(foreach s,$(NSU_SRC),$(eval $(call LIB_RULE,$(s),$(I_NSU))))
$(foreach s,$(GIF_SRC),$(eval $(call LIB_RULE,$(s),$(I_GIF))))
$(foreach s,$(BMP_SRC),$(eval $(call LIB_RULE,$(s),$(I_BMP))))
$(foreach s,$(HB_SRC),$(eval $(call LIB_RULE,$(s),$(I_HB))))
$(foreach s,$(CSS_SRC),$(eval $(call LIB_RULE,$(s),$(I_CSS))))
$(foreach s,$(DOM_SRC),$(eval $(call LIB_RULE,$(s),$(I_DOM))))

define NSFB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CC) $$(CF) -D_BSD_SOURCE -I$(NSFB)/include -I$(NSFB)/src -I$(ZUSER) -I$(ZKINC) -DONYX_HOST_SIM -c $$< -o $$@
endef
$(foreach s,$(NSFB_SRC),$(eval $(call NSFB_RULE,$(s))))

define NS_RULE
$(call obj,$(1)): $(1) $(OUT)/font-ns-sans.h $(OUT)/hostinc/curl/curl.h
	@mkdir -p $(OUT)/o
	$$(CC) $$(NS_CF) $$(NS_INC) -c $$< -o $$@
endef
$(foreach s,$(NS_ALL),$(eval $(call NS_RULE,$(s))))
$(call obj,$(FB)/gui.c): NS_CF += -Dmain=netsurf_main

# dom.js as a C string for qjs.c (as netsurf-app.mk)
$(OUT)/qjsgen/qjs_dom_js.h: $(JSQ)/dom.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from dom.js by host.mk */'; echo 'static const char qjs_dom_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs.c): $(OUT)/qjsgen/qjs_dom_js.h
$(call obj,$(JSQ)/qjs.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen

CXXF = -std=gnu++17 -O1 -g -w -fno-exceptions -fno-rtti -I$(ZUSER) -I$(ZKINC) -DIMG_HOST_TEST -DONYX_HOST_SIM \
       -MMD -MP
define CXX_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	$$(CXX) $$(CXXF) -I$(UN) -I$(NS) -I$(NS)/include -I$(NS)/frontends -c $$< -o $$@
endef
$(foreach s,$(ONYX_CXX) $(WTK_SRC),$(eval $(call CXX_RULE,$(s))))

# ---- link --------------------------------------------------------------------
$(OUT)/netsurf: $(LIB_OBJ) $(NSFB_OBJ) $(NS_OBJ) $(CXX_OBJ) $(WTK_OBJ)
	$(CXX) -o $@ $^ -lpng -lz -lm -lssl -lcrypto
	@echo "host netsurf: $@"

# ---- the resources (as netsurf-app.mk's stage, into $(OUT)/res) ------------------
.PHONY: res
res:
	@mkdir -p $(OUT)/res/en $(OUT)/data
	grep -E '^en\.(all|framebuffer)\.' $(NS)/resources/FatMessages | sed -E 's/^en\.(all|framebuffer)\.//' > $(OUT)/res/Messages
	for f in default.css quirks.css adblock.css internal.css; do cp $(NS)/resources/$$f $(OUT)/res/; done
	: > $(OUT)/res/user.css
	for f in welcome.html credits.html licence.html; do cp $(NS)/resources/en/$$f $(OUT)/res/; cp $(NS)/resources/en/$$f $(OUT)/res/en/; done
	@mkdir -p $(OUT)/res/icons
	for f in arrow-l content directory directory2 hotlist-add hotlist-rmv search; do cp $(NS)/resources/icons/$$f.png $(OUT)/res/icons/ 2>/dev/null || true; done
	-cp $(NS)/resources/favicon.png $(NS)/resources/netsurf.png $(OUT)/res/
	@mkdir -p $(OUT)/res/fonts
	cp $(FONTS)/ttf/*.ttf $(OUT)/res/fonts/
	cp $(TP)/fonts/*/*.ttf $(OUT)/res/fonts/
	printf 'foreground_images:1\nbackground_images:1\nenable_javascript:1\n' > $(OUT)/res/Choices

-include $(wildcard $(OUT)/o/*.d)

# ---- libcss's own selection tests (its test/select.c on test/data/select/*.dat): a check of
# the cascade after changing libcss --  make -f tools/tests/netsurf/host.mk libcss-test
CSS_TEST_OBJ := $(foreach s,$(CSS_SRC) $(WAP_SRC) $(PU_SRC),$(call obj,$(s)))
$(OUT)/libcss-select-test: $(CSS)/test/select.c $(CSS)/test/dump_computed.h $(CSS_TEST_OBJ)
	@$(CC) $(CF) $(I_CSS) -I$(CSS)/test -o $@ $< $(CSS_TEST_OBJ) -lm
.PHONY: libcss-test
libcss-test: $(OUT)/libcss-select-test
	@for t in $(CSS)/test/data/select/*.dat; do \
		echo "$$(basename $$t): $$($(OUT)/libcss-select-test $$t 2>&1 | tail -1)"; done
