#
# pc/Jet/jet.mk -- Jet Browser (NetSurf on Onyx) for Windows x64, cross-built on Linux with MinGW-w64 from
# the Onyx sources: the same library stack, core, framebuffer frontend and Onyx glue as the Pi's
# (user/netsurf/netsurf-app.mk) and the PC bench's (tools/tests/netsurf/host.mk) -- QuickJS, libcss, libdom,
# libhubbub, FreeType, PlutoVG/SVG, wasm3, mbedTLS (the Pi's TLS: onyx_nstls.cpp), nghttp2, zstd, brotli,
# libpng, zlib, libjpeg, libwebp, wtk -- over pc/Jet/winkapi.cpp (the Onyx kernel's table on Win32).
# Every library is compiled from its source here (nothing taken from the system). Statically linked.
#
#   make -f pc/Jet/jet.mk [OUT=/home/user/jetwin-build] [-j8]      (from the repo root; pc/Jet/build.sh)
#
# Differences with the Pi build: not newlib + crt0libc but MinGW's C library, its file calls wrapped at the
# link (WRAP below: winkapi.cpp's __wrap_fopen... take the same Onyx paths as the Pi's), no JIT (AArch64 only: QuickJS's interpreter), no GPU
# (gpu_compositing's CPU path), no ONYX_HOST_SIM (the Pi's code paths, not the bench's).
#
ROOT     := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../..)
OUT      ?= /home/user/jetwin-build
TP       := $(ROOT)/third_party
NS       := $(TP)/netsurf
UN       := $(ROOT)/user/netsurf
ZUSER    := $(ROOT)/user
ZKINC    := $(ROOT)/kernel/include
HERE     := $(ROOT)/pc/Jet

MINGW    ?= x86_64-w64-mingw32
CC       := $(shell command -v $(MINGW)-gcc-posix || echo $(MINGW)-gcc)
CXX      := $(shell command -v $(MINGW)-g++-posix || echo $(MINGW)-g++)
AR       := $(MINGW)-ar
WINDRES  := $(MINGW)-windres
BUILD_CC ?= gcc

WAP  := $(TP)/libwapcaplet
PU   := $(TP)/libparserutils
CSS  := $(TP)/libcss
DOM  := $(TP)/libdom
HB   := $(TP)/libhubbub
NSU  := $(TP)/libnsutils
GIF  := $(TP)/libnsgif
BMP  := $(TP)/libnsbmp
NSFB := $(TP)/libnsfb
FT   := $(TP)/freetype-2.14.3
FONTS := $(TP)/dejavu-fonts-ttf-2.37
JPEG := $(TP)/jpeg-9f
WEBP := $(TP)/libwebp-1.4.0
PNG  := $(TP)/libpng-1.6.44
ZLIB := $(TP)/zlib-1.3.1
PVG  := $(TP)/plutovg-1.3.3
PSVG := $(TP)/plutosvg-0.0.8
QJS  := $(TP)/quickjs-ng-0.17.0
W3   := $(TP)/wasm3-0.9.2
MBED := $(TP)/mbedtls-3.6.3
ZSTD := $(TP)/zstd-1.5.7
NGH  := $(TP)/nghttp2-1.70.0
BRO  := $(TP)/brotli-1.1.0
JSQ  := $(NS)/content/handlers/javascript/quickjs
FB   := $(NS)/frontends/framebuffer

PVG_CF := -std=gnu11 -DPLUTOVG_BUILD -DPLUTOVG_BUILD_STATIC -DPLUTOVG_DISABLE_FONT_FACE_CACHE_LOAD \
          -DSTBI_ONLY_PNG -DSTBI_ONLY_JPEG -I$(PVG)/include

# pc/Jet/compat: regex.h (MinGW has none)
JW    := -I$(HERE)/compat
BASEF = -O2 -fcommon -fno-strict-aliasing -w -DNDEBUG -D_WIN32_WINNT=0x0A00 -D__USE_MINGW_ANSI_STDIO=1 -MMD -MP
CF    = $(BASEF) -std=gnu99 -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L

NS_CF = $(CF) $(JW) -Dnsframebuffer -DWITH_PNG -DWITH_GIF -DWITH_BMP -DWITH_JPEG -DWITH_WEBP \
        -DONYX_NS_DATAPATH=\"/data/\" -include $(UN)/compat/onyx_nsconfig.h
NS_INC = -I$(NS) -I$(NS)/include -I$(NS)/content/handlers -I$(NS)/frontends \
         -I$(OUT)/hostinc -I$(UN) -I$(UN)/gen -I$(OUT) -I$(ZUSER) -I$(ZKINC) \
         -I$(WAP)/include -I$(PU)/include -I$(CSS)/include -I$(DOM)/include -I$(HB)/include \
         -I$(NSU)/include -I$(GIF)/include -I$(BMP)/include -I$(NSFB)/include \
         -I$(DOM)/bindings -I$(DOM)/src -I$(FT)/include -I$(UN)/freetype $(NS_FT_CF) \
         -I$(PNG) -I$(ZLIB) -I$(JPEG) -I$(WEBP)/src \
         -DPLUTOVG_BUILD_STATIC -DPLUTOSVG_BUILD_STATIC -I$(PVG)/include -I$(PSVG)/source \
         -DXML_STATIC -I$(TP)/expat-2.7.1/lib

# ---- sources (as host.mk) -------------------------------------------------------------
WAP_SRC := $(shell find $(WAP)/src -name '*.c')
PU_SRC  := $(shell find $(PU)/src -name '*.c')
NSU_SRC := $(shell find $(NSU)/src -name '*.c')
GIF_SRC := $(shell find $(GIF)/src -name '*.c')
BMP_SRC := $(shell find $(BMP)/src -name '*.c')
HB_SRC  := $(shell find $(HB)/src -name '*.c')
CSS_GENDIR := $(CSS)/src/parse/properties
CSS_AUTONAMES := $(shell perl -pe '$$_="" unless /^([^\#][^:]+):/;$$_=$$1 . " "' $(CSS_GENDIR)/properties.gen)
CSS_AUTO_C := $(addprefix $(OUT)/cssgen/autogenerated_,$(addsuffix .c,$(CSS_AUTONAMES)))
CSS_SRC := $(filter-out %css_property_parser_gen.c %/autogenerated_%.c,$(shell find $(CSS)/src -name '*.c')) $(CSS_AUTO_C)
DOM_SRC := $(shell find $(DOM)/src -name '*.c') $(wildcard $(DOM)/bindings/hubbub/*.c)
NSFB_SRC := $(addprefix $(NSFB)/src/,libnsfb.c cursor.c palette.c surface/surface.c surface/ram.c \
            plot/api.c plot/generic.c plot/util.c plot/8bpp.c plot/16bpp.c \
            plot/32bpp-xrgb8888.c plot/32bpp-xbgr8888.c) $(ZUSER)/nsfb/onyx_surface.c

QJS_SRC := $(addprefix $(QJS)/,quickjs.c libregexp.c libunicode.c dtoa.c)
JS_SRC := $(JSQ)/qjs.c $(JSQ)/qjs_canvas.c $(JSQ)/qjs_net.c $(JSQ)/qjs_wasm.c $(JSQ)/qjs_crypto.c $(JSQ)/qjs_codecache.c $(JSQ)/qjs_frames.c $(JSQ)/qjs_xml.c
W3_SRC := $(wildcard $(W3)/src/*.c)

CORE_SRC := \
  $(wildcard $(NS)/utils/*.c) $(wildcard $(NS)/utils/http/*.c) $(wildcard $(NS)/utils/nsurl/*.c) \
  $(wildcard $(NS)/content/*.c) \
  $(filter-out %/curl.c,$(wildcard $(NS)/content/fetchers/*.c)) \
  $(wildcard $(NS)/content/fetchers/about/*.c) $(wildcard $(NS)/content/fetchers/file/*.c) \
  $(wildcard $(NS)/desktop/*.c) \
  $(wildcard $(NS)/content/handlers/css/*.c) $(wildcard $(NS)/content/handlers/html/*.c) \
  $(wildcard $(NS)/content/handlers/text/*.c) \
  $(addprefix $(NS)/content/handlers/image/,bmp.c gif.c ico.c image.c image_cache.c png.c jpeg.c webp.c onyx_svg.c onyx_vgfont.c) \
  $(wildcard $(NS)/content/handlers/javascript/*.c) $(JS_SRC)

include $(UN)/netsurf-src.mk
FE_SRC := $(addprefix $(FB)/,$(NS_FB_FILES)) $(wildcard $(FB)/fbtk/*.c)
ONYX_SRC := $(UN)/onyx_fetch.c $(UN)/onyx_cache.c $(UN)/onyx_ws.c $(UN)/onyx_main.c

GENFONT := $(OUT)/font-ns-sans.c
FB_IMG := $(NS_FB_IMAGES)
IMG_C  := $(foreach p,$(FB_IMG),$(OUT)/image-$(word 1,$(subst :, ,$(p))).c)

FT_SRC := $(addprefix $(FT)/src/,base/ftsystem.c base/ftinit.c base/ftdebug.c base/ftbase.c \
          base/ftbbox.c base/ftbitmap.c base/ftglyph.c base/ftsynth.c base/ftmm.c autofit/autofit.c \
          truetype/truetype.c sfnt/sfnt.c smooth/smooth.c psnames/psnames.c cache/ftcache.c \
          cff/cff.c psaux/psaux.c pshinter/pshinter.c gzip/ftgzip.c)
BRO_SRC := $(wildcard $(BRO)/c/common/*.c $(BRO)/c/dec/*.c)
I_BRO := -I$(BRO)/c/include
JPEG_SRC := $(addprefix $(JPEG)/,$(addsuffix .c,jaricom jcapimin jcapistd jcarith jccoefct jccolor \
            jcdctmgr jchuff jcinit jcmainct jcmarker jcmaster jcomapi jcparam jcprepct jcsample \
            jctrans jdapimin jdapistd jdarith jdatadst jdatasrc jdcoefct jdcolor jddctmgr jdhuff \
            jdinput jdmainct jdmarker jdmaster jdmerge jdpostct jdsample jdtrans jerror jfdctflt \
            jfdctfst jfdctint jidctflt jidctfst jidctint jquant1 jquant2 jutils jmemmgr jmemnobs))
WEBP_SRC := $(wildcard $(WEBP)/src/dec/*.c $(WEBP)/src/dsp/*.c $(WEBP)/src/utils/*.c)
PNG_SRC := $(addprefix $(PNG)/,png.c pngerror.c pngget.c pngmem.c pngpread.c pngread.c pngrio.c pngrtran.c \
           pngrutil.c pngset.c pngtrans.c pngwio.c pngwrite.c pngwtran.c pngwutil.c)
ZLIB_SRC := $(addprefix $(ZLIB)/,adler32.c compress.c crc32.c deflate.c gzclose.c gzlib.c gzread.c gzwrite.c \
            infback.c inffast.c inflate.c inftrees.c trees.c uncompr.c zutil.c)
I_FT := -DFT2_BUILD_LIBRARY '-DFT_CONFIG_MODULES_H=<onyx_ftmodule.h>' \
        '-DFT_CONFIG_OPTIONS_H=<onyx_ftoption.h>' -I$(UN)/freetype -I$(FT)/include $(I_BRO) -I$(ZLIB)
PVG_SRC := $(wildcard $(PVG)/source/plutovg-*.c)
PSVG_SRC := $(PSVG)/source/plutosvg.c
# Onyx: expat, the XML parser (XML documents, DOMParser's XML: docs/06 section 43)
EXPAT := $(TP)/expat-2.7.1
EXPAT_SRC := $(EXPAT)/lib/xmlparse.c $(EXPAT)/lib/xmlrole.c $(EXPAT)/lib/xmltok.c
GPC_SRC := $(ZUSER)/gpucomp/gpucomp.c
MBED_SRC := $(wildcard $(MBED)/library/*.c)
ZSTD_SRC := $(wildcard $(ZSTD)/lib/common/*.c $(ZSTD)/lib/decompress/*.c)
NGH_SRC := $(wildcard $(NGH)/lib/*.c)

LIB_ALL := $(EXPAT_SRC) $(W3_SRC) $(GPC_SRC) $(ZSTD_SRC) $(NGH_SRC) $(MBED_SRC) $(PVG_SRC) $(PSVG_SRC) $(JPEG_SRC) $(WEBP_SRC) \
           $(PNG_SRC) $(ZLIB_SRC) $(QJS_SRC) $(FT_SRC) $(BRO_SRC) $(WAP_SRC) $(PU_SRC) $(NSU_SRC) $(GIF_SRC) $(BMP_SRC) \
           $(HB_SRC) $(CSS_SRC) $(DOM_SRC)
NS_ALL  := $(CORE_SRC) $(FE_SRC) $(ONYX_SRC) $(GENFONT) $(IMG_C)

obj = $(OUT)/o/$(subst /,_,$(patsubst $(ROOT)/%,%,$(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(1)))))
LIB_OBJ  := $(foreach s,$(LIB_ALL),$(call obj,$(s)))
NSFB_OBJ := $(foreach s,$(NSFB_SRC),$(call obj,$(s)))
NS_OBJ   := $(foreach s,$(NS_ALL),$(call obj,$(s)))
CXX_OBJ  := $(foreach s,$(ONYX_CXX_FILES),$(call obj,$(s)))
WTK_SRC  := $(filter-out %imgload.cpp,$(wildcard $(ZUSER)/wtk/*.cpp)) $(ROOT)/tools/tests/desktop_sim/imgstub.cpp
WTK_OBJ  := $(foreach s,$(WTK_SRC),$(call obj,$(s)))
KAPI_OBJ := $(OUT)/o/winkapi.o
TLS_OBJ  := $(OUT)/o/onyx_nstls.o
RES_OBJ  := $(OUT)/o/jet_res.o

.PHONY: all
all: $(OUT)/Jet.exe

# ---- code generation (host tools, the build machine's compiler) ------------------------------
$(OUT)/tools/convert_font: $(NS)/tools/convert_font.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -o $@ $<
$(GENFONT) $(OUT)/font-ns-sans.h: $(OUT)/tools/convert_font $(FB)/res/fonts/glyph_data
	@mkdir -p $(OUT)
	$(OUT)/tools/convert_font -H $(OUT)/font-ns-sans.h $(FB)/res/fonts/glyph_data $(GENFONT)
$(OUT)/tools/convert_image: $(NS)/tools/convert_image.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -I$(FB) -o $@ $< -lpng
define IMG_RULE
$(OUT)/image-$(word 1,$(subst :, ,$(1))).c: $(FB)/res/$(word 2,$(subst :, ,$(1))) $(OUT)/tools/convert_image
	@mkdir -p $(OUT)
	$(OUT)/tools/convert_image $(FB)/res/$(word 2,$(subst :, ,$(1))) $$@ $(word 1,$(subst :, ,$(1)))
endef
$(foreach p,$(FB_IMG),$(eval $(call IMG_RULE,$(p))))

$(OUT)/cssgen/gen_parser: $(CSS_GENDIR)/css_property_parser_gen.c
	@mkdir -p $(dir $@)
	$(BUILD_CC) -O2 -o $@ $<
$(OUT)/cssgen/autogenerated_%.c: $(OUT)/cssgen/gen_parser $(CSS_GENDIR)/properties.gen
	cd $(CSS) && $(OUT)/cssgen/gen_parser -o $@ "$$(grep "^$*:" $(CSS_GENDIR)/properties.gen)"
.SECONDARY: $(CSS_AUTO_C)

$(OUT)/hostinc/curl/curl.h: $(UN)/compat/curl/curl.h
	@mkdir -p $(dir $@)
	cp $< $@

# the JavaScript of the DOM, Intl, canvas, the network APIs, WebAssembly, Web Crypto as C strings
define JS_STR
$(OUT)/qjsgen/qjs_$(1)_js.h: $(JSQ)/$(1).js
	@mkdir -p $$(dir $$@)
	{ echo '/* generated from $(1).js by pc/Jet/jet.mk */'; echo 'static const char qjs_$(1)_js[] ='; \
	  sed -e 's/\r$$$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$$$/\\n"/' $$<; echo ';'; } > $$@
endef
$(foreach j,dom html5 canvas net wasm crypto,$(eval $(call JS_STR,$(j))))
$(OUT)/qjsgen/qjs_intl_js.h: $(JSQ)/intl.js $(TP)/cldr-48/intl-data.txt
	@mkdir -p $(dir $@)
	{ echo '/* generated from intl.js and intl-data.txt by pc/Jet/jet.mk */'; echo 'static const char qjs_intl_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; \
	  echo 'static const char qjs_intl_data[] ='; \
	  sed -e 's/\r$$//' -e '/^#/d' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $(TP)/cldr-48/intl-data.txt; echo ';'; } > $@

# ---- compilation -------------------------------------------------------------
I_WAP := -I$(WAP)/include -I$(WAP)/src
I_PU  := -I$(PU)/include -I$(PU)/src -DWITHOUT_ICONV_FILTER
I_NSU := -I$(NSU)/include -I$(NSU)/src
I_GIF := -I$(GIF)/include -I$(GIF)/src
I_BMP := -I$(BMP)/include -I$(BMP)/src
I_HB  := -I$(HB)/include -I$(HB)/src -I$(PU)/include
I_CSS := -std=c99 -I$(CSS)/include -I$(CSS)/src -I$(WAP)/include -I$(PU)/include
I_DOM := -I$(DOM)/include -I$(DOM)/src -I$(WAP)/include -I$(PU)/include -I$(HB)/include
define LIB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	@echo "  CC $(notdir $(1))"
	@$$(CC) $$(CF) $(2) -c $$< -o $$@
endef
$(foreach s,$(QJS_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(QJS))))
$(foreach s,$(EXPAT_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu99 -DXML_STATIC -I$(EXPAT)/lib)))
$(foreach s,$(GPC_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -ffp-contract=off -I$(ZUSER) -I$(ZKINC))))
$(foreach s,$(MBED_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(MBED)/include -I$(MBED)/library)))
$(foreach s,$(ZSTD_SRC),$(eval $(call LIB_RULE,$(s),-DZSTD_DISABLE_ASM -DZSTD_LEGACY_SUPPORT=0 -DDEBUGLEVEL=0 -DZSTD_NO_TRACE -I$(ZSTD)/lib -I$(ZSTD)/lib/common)))
$(foreach s,$(NGH_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu99 -DHAVE_CONFIG_H -DNGHTTP2_STATICLIB -I$(NGH)/lib -I$(NGH)/lib/includes)))
$(foreach s,$(W3_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -O3 -I$(W3)/src)))
# (wasm3's default m3_Yield is weak elsewhere, not on Windows: qjs_wasm.c's is the one)
$(call obj,$(W3)/src/m3_core.c): CF += -Dm3_Yield=m3_Yield_default
$(foreach s,$(JPEG_SRC),$(eval $(call LIB_RULE,$(s),-I$(JPEG))))
$(foreach s,$(PNG_SRC),$(eval $(call LIB_RULE,$(s),-I$(PNG) -I$(ZLIB) -DPNG_ARM_NEON_OPT=0 -DPNG_INTEL_SSE_OPT=0)))
$(foreach s,$(ZLIB_SRC),$(eval $(call LIB_RULE,$(s),-I$(ZLIB))))
$(foreach s,$(PVG_SRC),$(eval $(call LIB_RULE,$(s),$(JW) $(PVG_CF))))
$(foreach s,$(PSVG_SRC),$(eval $(call LIB_RULE,$(s),$(JW) $(PVG_CF) -DPLUTOSVG_BUILD -DPLUTOSVG_BUILD_STATIC -I$(PSVG)/source)))
$(foreach s,$(WEBP_SRC),$(eval $(call LIB_RULE,$(s),-std=gnu11 -I$(WEBP) -I$(WEBP)/src)))
$(foreach s,$(FT_SRC),$(eval $(call LIB_RULE,$(s),$(JW) $(I_FT))))
$(foreach s,$(BRO_SRC),$(eval $(call LIB_RULE,$(s),$(I_BRO))))
$(foreach s,$(WAP_SRC),$(eval $(call LIB_RULE,$(s),$(I_WAP))))
$(foreach s,$(PU_SRC),$(eval $(call LIB_RULE,$(s),$(I_PU))))
$(foreach s,$(NSU_SRC),$(eval $(call LIB_RULE,$(s),$(I_NSU))))
$(foreach s,$(GIF_SRC),$(eval $(call LIB_RULE,$(s),$(I_GIF))))
$(foreach s,$(BMP_SRC),$(eval $(call LIB_RULE,$(s),$(I_BMP))))
$(foreach s,$(HB_SRC),$(eval $(call LIB_RULE,$(s),$(I_HB))))
$(foreach s,$(CSS_SRC),$(eval $(call LIB_RULE,$(s),$(I_CSS))))
$(foreach s,$(DOM_SRC),$(eval $(call LIB_RULE,$(s),$(I_DOM))))

define NSFB_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	@echo "  CC $(notdir $(1))"
	@$$(CC) $$(CF) -I$(NSFB)/include -I$(NSFB)/src -I$(ZUSER) -I$(ZKINC) -c $$< -o $$@
endef
$(foreach s,$(NSFB_SRC),$(eval $(call NSFB_RULE,$(s))))

define NS_RULE
$(call obj,$(1)): $(1) $(OUT)/font-ns-sans.h $(OUT)/hostinc/curl/curl.h
	@mkdir -p $(OUT)/o
	@echo "  CC $(notdir $(1))"
	@$$(CC) $$(NS_CF) $$(NS_INC) -c $$< -o $$@
endef
$(foreach s,$(NS_ALL),$(eval $(call NS_RULE,$(s))))
$(call obj,$(FB)/gui.c): NS_CF += -Dmain=netsurf_main
# (Windows' ws2_32 has inet_pton: NetSurf's own, for systems without, renamed out of its way)
$(call obj,$(NS)/utils/utils.c): NS_CF += -Dinet_pton=netsurf_inet_pton
$(call obj,$(UN)/onyx_fetch.c): NS_CF += $(I_BRO) -I$(ZSTD)/lib -I$(NGH)/lib/includes -DNGHTTP2_STATICLIB
$(call obj,$(NS)/content/fetchers/about/certificate.c): NS_CF += -DWITH_MBEDTLS -I$(MBED)/include
$(call obj,$(JSQ)/qjs.c): $(OUT)/qjsgen/qjs_dom_js.h $(OUT)/qjsgen/qjs_html5_js.h $(OUT)/qjsgen/qjs_intl_js.h
$(call obj,$(JSQ)/qjs.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
$(call obj,$(JSQ)/qjs_canvas.c): $(OUT)/qjsgen/qjs_canvas_js.h
$(call obj,$(JSQ)/qjs_canvas.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
$(call obj,$(JSQ)/qjs_net.c): $(OUT)/qjsgen/qjs_net_js.h
$(call obj,$(JSQ)/qjs_net.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen
$(call obj,$(JSQ)/qjs_wasm.c): $(OUT)/qjsgen/qjs_wasm_js.h
$(call obj,$(JSQ)/qjs_wasm.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen -I$(W3)/src
$(call obj,$(JSQ)/qjs_crypto.c): $(OUT)/qjsgen/qjs_crypto_js.h
$(call obj,$(JSQ)/qjs_crypto.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen -I$(MBED)/include
$(call obj,$(JSQ)/qjs_codecache.c): NS_INC += -I$(QJS) -I$(MBED)/include
$(call obj,$(JSQ)/qjs_frames.c): NS_INC += -I$(QJS)
# Onyx: XPath / XSLT (docs/06 section 43) -- xslt.js as a C string for qjs_xml.c (loaded on demand)
$(OUT)/qjsgen/qjs_xslt_js.h: $(JSQ)/xslt.js
	@mkdir -p $(dir $@)
	{ echo '/* generated from xslt.js by jet.mk */'; echo 'static const char qjs_xslt_js[] ='; \
	  sed -e 's/\r$$//' -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/?/\\?/g' -e 's/^/"/' -e 's/$$/\\n"/' $<; echo ';'; } > $@
$(call obj,$(JSQ)/qjs_xml.c): $(OUT)/qjsgen/qjs_xslt_js.h
$(call obj,$(JSQ)/qjs_xml.c): NS_INC += -I$(QJS) -I$(OUT)/qjsgen

# C++: wtk, the window (onyx_chrome.cpp), the kapi's table, the Pi's TLS glue (onyx_nstls.cpp)
CXXF = -std=gnu++17 -O2 -w -fno-exceptions -fno-rtti -I$(ZUSER) -I$(ZKINC) -DIMG_HOST_TEST -D_WIN32_WINNT=0x0A00 -D_POSIX_THREAD_SAFE_FUNCTIONS \
       -include $(ROOT)/pc/Koton/onyxwin.h -MMD -MP
define CXX_RULE
$(call obj,$(1)): $(1)
	@mkdir -p $(OUT)/o
	@echo "  C++ $(notdir $(1))"
	@$$(CXX) $$(CXXF) -I$(UN) -I$(NS) -I$(NS)/include -I$(NS)/frontends -c $$< -o $$@
endef
$(foreach s,$(ONYX_CXX_FILES) $(WTK_SRC),$(eval $(call CXX_RULE,$(s))))
$(KAPI_OBJ): $(HERE)/winkapi.cpp
	@mkdir -p $(OUT)/o
	$(CXX) $(CXXF) -I$(HERE) -I$(HERE)/compat -c $< -o $@
$(TLS_OBJ): $(UN)/onyx_nstls.cpp $(UN)/onyx_nstls.h $(ZUSER)/tls/onyx_tls.hpp
	@mkdir -p $(OUT)/o
	$(CXX) $(CXXF) $(JW) -I$(UN) -I$(ZUSER)/tls -I$(MBED)/include -c $< -o $@

# the icon: the Pi's (sdcard/apps/jet.app/icon.bmp, its magenta see-through)
$(OUT)/jet.ico: $(ROOT)/sdcard/apps/jet.app/icon.bmp
	@mkdir -p $(OUT)
	python3 -c "import sys; from PIL import Image; im = Image.open (sys.argv[1]).convert ('RGBA'); \
	  im.putdata ([(0, 0, 0, 0) if p[:3] == (255, 0, 255) else p for p in im.getdata ()]); \
	  im.resize ((64, 64), Image.NEAREST).save (sys.argv[2], sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64)])" $< $@
$(RES_OBJ): $(OUT)/jet.ico
	printf '1 ICON "%s"\n' "$(OUT)/jet.ico" > $(OUT)/jet.rc
	$(WINDRES) $(OUT)/jet.rc -O coff -o $@

# ---- link: the C library's file calls (and the clock) wrapped: winkapi.cpp's __wrap_* take Onyx paths ----
WRAP := $(foreach f,fopen open stat access mkdir rmdir unlink remove rename opendir readdir closedir gettimeofday,-Wl,--wrap=$(f))
$(OUT)/Jet.exe: $(LIB_OBJ) $(NSFB_OBJ) $(NS_OBJ) $(CXX_OBJ) $(WTK_OBJ) $(KAPI_OBJ) $(TLS_OBJ) $(RES_OBJ)
	@echo "  LINK $@"
	@rm -f $(OUT)/objs.rsp; for o in $^; do echo "$$o" >> $(OUT)/objs.rsp; done
	$(CXX) -mwindows -static -static-libgcc -static-libstdc++ -Wl,--stack,16777216 $(WRAP) -o $@ @$(OUT)/objs.rsp \
	  -lws2_32 -lbcrypt -lgdi32 -luser32 -lshell32 -lwinmm -lsynchronization -lpthread
	@echo "Jet.exe: $$(stat -c %s $@) bytes"

-include $(wildcard $(OUT)/o/*.d)
