//
// pack_test -- kern/v3d_pack42.h (generated by tools/v3d/genpackets.py from Mesa's v3d_packet.xml) against
// kern/v3d_cl.h's hand-written V3D 4.2 packets, the ones that run on the Pi 4: every packet the kernel
// builds, with random values in its fields, must give the same bytes both ways. That validates the
// generator -- whose V3D 7.1 output (kern/v3d_pack71.h, the Pi 5) cannot be compared with a GPU here.
// Also: each field of every generated packet / record of both versions, set alone to all ones, sets
// exactly its bits (an address its top-aligned ones). sh tools/tests/run_v3d_cl_test.sh
//
// MIT licence (docs/LICENSING.md).
//
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <kern/v3d_cl.h>
#include <kern/v3d_pack42.h>
#include <kern/v3d_pack71.h>

static int s_fail = 0, s_tests = 0;
static unsigned R (unsigned bits) { unsigned long long v = ((unsigned long long) rand () << 31) ^ (unsigned long long) rand (); return bits >= 32 ? (unsigned) v : (unsigned) (v & ((1ull << bits) - 1)); }
static float RF () { return (float) (rand () % 20001 - 10000) / 64.0f; }

template <class H> static void same (const char *what, const H &h, const unsigned char *g, unsigned glen)
{
	s_tests++;
	unsigned char b[64]; memcpy (b, &h, sizeof h);
	if (sizeof h != glen || memcmp (b, g, glen) != 0)
	{
		s_fail++;
		printf ("FAIL %s: hand-written %u bytes, generated %u\n  hand:", what, (unsigned) sizeof h, glen);
		for (unsigned i = 0; i < sizeof h; i++) printf (" %02x", b[i]);
		printf ("\n  gen: ");
		for (unsigned i = 0; i < glen; i++) printf (" %02x", g[i]);
		printf ("\n");
	}
}
#define GEN(T, ...) unsigned char g[V3D42_##T##_length]; struct V3D42_##T v = { V3D42_##T##_header }; __VA_ARGS__; V3D42_##T##_pack (g, &v)

static void round_once ()
{
	{ unsigned a = R (2), b = R (2), n = 1 + R (2), m = R (1), d = R (1), w = 1 + R (12), h = 1 + R (12);
	  TileBinningModeCfg H (a, b, n, 0, m, d, w, h);
	  GEN (TILE_BINNING_MODE_CFG, v.tile_allocation_initial_block_size = a; v.tile_allocation_block_size = b; v.number_of_render_targets = n;
	       v.maximum_bpp_of_all_render_targets = 0; v.multisample_mode_4x = m; v.double_buffer_in_non_ms_mode = d; v.width_in_pixels = w; v.height_in_pixels = h);
	  same ("Tile Binning Mode Cfg", H, g, sizeof g); }
	{ unsigned n = 1 + R (2), w = R (12), h = R (12), bpp = R (2), m = R (1), d = R (1), z = R (1), e = R (1), t = R (2), c = R (1);
	  TileRenderingModeCfgCommon H (n, w, h, bpp, m, d, z, e, t, c);
	  GEN (TILE_RENDERING_MODE_CFG_COMMON, v.number_of_render_targets = n; v.image_width_pixels = w; v.image_height_pixels = h;
	       v.maximum_bpp_of_all_render_targets = bpp; v.multisample_mode_4x = m; v.double_buffer_in_non_ms_mode = d;
	       v.early_z_test_and_update_direction = z; v.early_z_disable = e; v.internal_depth_type = t; v.early_depth_stencil_clear = c);
	  same ("Tile Rendering Mode Cfg (Common)", H, g, sizeof g); }
	{ unsigned x[12]; for (int i = 0; i < 12; i++) x[i] = R (i % 3 == 1 ? 4 : 2);
	  TileRenderingModeCfgColor H (x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10], x[11]);
	  GEN (TILE_RENDERING_MODE_CFG_COLOR, v.render_target_0_internal_bpp = x[0]; v.render_target_0_internal_type = x[1]; v.render_target_0_clamp = x[2];
	       v.render_target_1_internal_bpp = x[3]; v.render_target_1_internal_type = x[4]; v.render_target_1_clamp = x[5];
	       v.render_target_2_internal_bpp = x[6]; v.render_target_2_internal_type = x[7]; v.render_target_2_clamp = x[8];
	       v.render_target_3_internal_bpp = x[9]; v.render_target_3_internal_type = x[10]; v.render_target_3_clamp = x[11]);
	  same ("Tile Rendering Mode Cfg (Color)", H, g, sizeof g); }
	{ unsigned s = R (8); float z = RF ();
	  TileRenderingModeCfgZSClearValues H (s, z);
	  GEN (TILE_RENDERING_MODE_CFG_ZS_CLEAR_VALUES, v.stencil_clear_value = s; v.z_clear_value = z);
	  same ("Tile Rendering Mode Cfg (ZS Clear Values)", H, g, sizeof g); }
	{ unsigned n = R (2), lo = R (32), nx = R (24);
	  TileRenderingModeCfgClearColorsPart1 H (n, lo, nx);
	  GEN (TILE_RENDERING_MODE_CFG_CLEAR_COLORS_PART1, v.render_target_number = n; v.clear_color_low_32_bits = lo; v.clear_color_next_24_bits = nx);
	  same ("Tile Rendering Mode Cfg (Clear Colors Part1)", H, g, sizeof g); }
	{ unsigned s = R (2), a = R (1); TileListInitialBlockSize H (s, a);
	  GEN (TILE_LIST_INITIAL_BLOCK_SIZE, v.size_of_first_block_in_chained_tile_lists = s; v.use_auto_chained_tile_lists = a);
	  same ("Tile List Initial Block Size", H, g, sizeof g); }
	{ unsigned a = R (32) & ~0x3Fu; MulticoreRenderingTileListSetBase H (a);
	  GEN (MULTICORE_RENDERING_TILE_LIST_SET_BASE, v.address = a; v.tile_list_set_number = 0);
	  same ("Multicore Rendering Tile List Set Base", H, g, sizeof g); }
	{ unsigned sw = 1 + R (7), sh = 1 + R (7), fw = R (8), fh = R (8), tw = R (12), th = R (12), nb = 1 + R (2), ro = R (1), me = R (1);
	  MulticoreRenderingSupertileCfg H (sw, sh, fw, fh, tw, th, nb, ro, me);
	  GEN (MULTICORE_RENDERING_SUPERTILE_CFG, v.supertile_width_in_tiles = sw; v.supertile_height_in_tiles = sh; v.total_frame_width_in_supertiles = fw;
	       v.total_frame_height_in_supertiles = fh; v.total_frame_width_in_tiles = tw; v.total_frame_height_in_tiles = th; v.number_of_bin_tile_lists = nb;
	       v.supertile_raster_order = ro; v.multicore_enable = me);
	  same ("Multicore Rendering Supertile Cfg", H, g, sizeof g); }
	{ unsigned c = R (12), r = R (12); TileCoordinates H (c, r);
	  GEN (TILE_COORDINATES, v.tile_column_number = c; v.tile_row_number = r); same ("Tile Coordinates", H, g, sizeof g); }
	{ unsigned bt = R (4), mf = R (3), fy = R (1), dm = R (2), de = R (2), of = R (6), cl = R (1), cr = R (1), rb = R (1), st = R (20), h = R (16), a = R (32);
	  StoreTileBufferGeneral H (bt, mf, fy, dm, de, of, cl, cr, rb, st, h, a);
	  GEN (STORE_TILE_BUFFER_GENERAL, v.buffer_to_store = bt; v.memory_format = mf; v.flip_y = fy; v.dither_mode = dm; v.decimate_mode = de;
	       v.output_image_format = of; v.clear_buffer_being_stored = cl; v.channel_reverse = cr; v.r_b_swap = rb; v.height_in_ub_or_stride = st;
	       v.height = h; v.address = a);
	  same ("Store Tile Buffer General", H, g, sizeof g); }
	{ unsigned bt = R (4), mf = R (3), fy = R (1), de = R (2), f = R (6), fa = R (1), cr = R (1), rb = R (1), st = R (20), h = R (16), a = R (32);
	  LoadTileBufferGeneral H (bt, mf, fy, de, f, fa, cr, rb, st, h, a);
	  GEN (LOAD_TILE_BUFFER_GENERAL, v.buffer_to_load = bt; v.memory_format = mf; v.flip_y = fy; v.decimate_mode = de; v.input_image_format = f;
	       v.force_alpha_1 = fa; v.channel_reverse = cr; v.r_b_swap = rb; v.height_in_ub_or_stride = st; v.height = h; v.address = a);
	  same ("Load Tile Buffer General", H, g, sizeof g); }
	{ unsigned a = R (1), z = R (1); ClearTileBuffers H (a, z);
	  GEN (CLEAR_TILE_BUFFERS, v.clear_all_render_targets = a; v.clear_z_stencil_buffer = z); same ("Clear Tile Buffers", H, g, sizeof g); }
	{ unsigned s = R (32), e = R (32); StartAddressOfGenericTileList H (s, e);
	  GEN (START_ADDRESS_OF_GENERIC_TILE_LIST, v.start = s; v.end = e); same ("Start Address of Generic Tile List", H, g, sizeof g); }
	{ unsigned t = R (6), s = R (1); PrimListFormat H (t, s);
	  GEN (PRIM_LIST_FORMAT, v.primitive_type = t; v.tri_strip_or_fan = s); same ("Prim List Format", H, g, sizeof g); }
	{ unsigned n = R (8); BranchToImplicitTileList H (n);
	  GEN (BRANCH_TO_IMPLICIT_TILE_LIST, v.tile_list_set_number = n); same ("Branch to Implicit Tile List", H, g, sizeof g); }
	{ unsigned x = R (8), y = R (8); SupertileCoorinates H (x, y);
	  GEN (SUPERTILE_COORDINATES, v.column_number_in_supertiles = x; v.row_number_in_supertiles = y); same ("Supertile Coordinates", H, g, sizeof g); }
	{ unsigned l = R (16), b = R (16), w = R (16), h = R (16); ClipWindow H (l, b, w, h);
	  GEN (CLIP_WINDOW, v.clip_window_left_pixel_coordinate = l; v.clip_window_bottom_pixel_coordinate = b; v.clip_window_width_in_pixels = w;
	       v.clip_window_height_in_pixels = h); same ("Clip Window", H, g, sizeof g); }
	{ unsigned x[15]; for (int i = 0; i < 15; i++) x[i] = R (i == 4 || i == 5 ? 2 : i == 7 ? 3 : 1);
	  CfgBits H (x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10], x[11], x[12], x[13], x[14]);
	  GEN (CFG_BITS, v.enable_forward_facing_primitive = x[0]; v.enable_reverse_facing_primitive = x[1]; v.clockwise_primitives = x[2];
	       v.enable_depth_offset = x[3]; v.line_rasterization = x[4]; v.rasterizer_oversample_mode = x[5]; v.direct3d_wireframe_triangles_mode = x[6];
	       v.depth_test_function = x[7]; v.z_updates_enable = x[8]; v.early_z_enable = x[9]; v.early_z_updates_enable = x[10]; v.stencil_enable = x[11];
	       v.blend_enable = x[12]; v.direct3d_point_fill_mode = x[13]; v.direct3d_provoking_vertex = x[14]);
	  same ("Cfg Bits", H, g, sizeof g); }
	{ float w = RF (), h = RF (); ClipperXYScaling H (w, h);
	  GEN (CLIPPER_XY_SCALING, v.viewport_half_width_in_1_256th_of_pixel = w; v.viewport_half_height_in_1_256th_of_pixel = h); same ("Clipper XY Scaling", H, g, sizeof g); }
	{ float s = RF (), o = RF (); ClipperZScaleAndOffset H (s, o);
	  GEN (CLIPPER_Z_SCALE_AND_OFFSET, v.viewport_z_scale_zc_to_zs = s; v.viewport_z_offset_zc_to_zs = o); same ("Clipper Z Scale and Offset", H, g, sizeof g); }
	{ float a = RF (), b = RF (); CLipperZMinMaxClippingPlanes H (a, b);
	  GEN (CLIPPER_Z_MIN_MAX_CLIPPING_PLANES, v.minimum_zw = a; v.maximum_zw = b); same ("Clipper Z min/max clipping planes", H, g, sizeof g); }
	{ int x = (int) R (12), y = (int) R (12); unsigned cx = R (10), cy = R (10); ViewportOffset H ((float) x, (float) y, cx, cy);
	  GEN (VIEWPORT_OFFSET, v.fine_x = (float) x; v.fine_y = (float) y; v.coarse_x = cx; v.coarse_y = cy); same ("Viewport Offset", H, g, sizeof g); }
	{ unsigned m = R (32); ColorWriteMasks H (m); GEN (COLOR_WRITE_MASKS, v.mask = m); same ("Color Write Masks", H, g, sizeof g); }
	{ unsigned x[7]; for (int i = 0; i < 7; i++) x[i] = R (4); BlendCfg H (x[0], x[1], x[2], x[3], x[4], x[5], x[6]);
	  GEN (BLEND_CFG, v.alpha_blend_mode = x[0]; v.alpha_blend_src_factor = x[1]; v.alpha_blend_dst_factor = x[2]; v.color_blend_mode = x[3];
	       v.color_blend_src_factor = x[4]; v.color_blend_dst_factor = x[5]; v.render_target_mask = x[6]); same ("Blend Cfg", H, g, sizeof g); }
	{ unsigned m = R (8); BlendEnables H (m); GEN (BLEND_ENABLES, v.mask = m); same ("Blend Enables", H, g, sizeof g); }
	{ unsigned r = R (16), gg = R (16), b = R (16), a = R (16); BlendConstantColor H (r, gg, b, a);
	  GEN (BLEND_CONSTANT_COLOR, v.red_f16 = r; v.green_f16 = gg; v.blue_f16 = b; v.alpha_f16 = a); same ("Blend Constant Color", H, g, sizeof g); }
	{ unsigned m = R (4); float c = RF (); SampleState H (m, c);
	  GEN (SAMPLE_STATE, v.mask = m; v.coverage = c); same ("Sample State", H, g, sizeof g); }
	{ unsigned b = R (4), r = R (4); VcmCacheSize H (b, r);
	  GEN (VCM_CACHE_SIZE, v.number_of_16_vertex_batches_for_binning = b; v.number_of_16_vertex_batches_for_rendering = r); same ("VCM Cache Size", H, g, sizeof g); }
	{ unsigned a = R (32) & ~0x1Fu, n = R (4); GlShaderState H (a, n);
	  GEN (GL_SHADER_STATE, v.address = a; v.number_of_attribute_arrays = n); same ("GL Shader State (32-byte aligned)", H, g, sizeof g); }
	{ unsigned m = R (8), l = R (32), f = R (32); VertexArrayPrims H (m, l, f);
	  GEN (VERTEX_ARRAY_PRIMS, v.mode = m; v.length = l; v.index_of_first_vertex = f); same ("Vertex Array Prims", H, g, sizeof g); }
	{ unsigned c = R (5), e = R (1); TransformFeedbackSpecs H (c, e);
	  GEN (TRANSFORM_FEEDBACK_SPECS, v.number_of_16_bit_output_data_specs_following = c; v.enable = e); same ("Transform Feedback Specs", H, g, sizeof g); }
	{ unsigned a = R (32); OcclusionQueryCounter H (a); GEN (OCCLUSION_QUERY_COUNTER, v.address = a); same ("Occlusion Query Counter", H, g, sizeof g); }
	{ float s = RF (); PointSize H (s); GEN (POINT_SIZE, v.point_size = s); same ("Point size", H, g, sizeof g); }
	{ float s = RF (); LineWidth H (s); GEN (LINE_WIDTH, v.line_width = s); same ("Line width", H, g, sizeof g); }
	{ unsigned n = 1 + R (7); NumberOfLayers H (n); GEN (NUMBER_OF_LAYERS, v.number_of_layers = n); same ("Number of Layers", H, g, sizeof g); }
	{
		GLShaderStateRecord H; memset (&H, 0, sizeof H);
		unsigned f[20]; for (int i = 0; i < 20; i++) f[i] = R (1);
		unsigned nv = R (8), seg[8]; for (int i = 0; i < 8; i++) seg[i] = R (4);
		unsigned dflt = R (32), fsa = R (32) & ~7u, fsu = R (32), vsa = R (32) & ~7u, vsu = R (32), csa = R (32) & ~7u, csu = R (32), t[9]; for (int i = 0; i < 9; i++) t[i] = R (1);
		H.point_size_in_shaded_vertex_data = f[0]; H.enable_clipping = f[1]; H.vertex_id_read_by_coordinate_shader = f[2]; H.instance_id_read_by_coordinate_shader = f[3];
		H.base_instance_id_read_by_coordinate_shader = f[4]; H.vertex_id_read_by_vertex_shader = f[5]; H.instance_id_read_by_vertex_shader = f[6];
		H.base_instance_id_read_by_vertex_shader = f[7]; H.fragment_shader_does_z_writes = f[8]; H.turn_off_early_z_test = f[9];
		H.coordinate_shader_has_separate_input_and_output_vpm_blocks = f[10]; H.vertex_shader_has_separate_input_and_output_vpm_blocks = f[11];
		H.fragment_shader_uses_real_pixel_centre_w_in_addition_to_centroid_w2 = f[12]; H.enable_sample_rate_shading = f[13];
		H.any_shader_reads_hardware_written_primitive_id = f[14]; H.insert_primitive_id_as_first_varying_to_fragment_shader = f[15];
		H.turn_off_scoreboard = f[16]; H.do_scoreboard_wait_on_first_thread_switch = f[17]; H.disable_implicit_point_line_varyings = f[18]; H.no_prim_pack = f[19];
		H.number_of_varyings_in_fragment_shader = nv;
		H.coordinate_shader_output_vpm_segment_size = seg[0]; H.min_coord_shader_output_segments_required_in_play_in_addition_to_vcm_cache_size = seg[1];
		H.coordinate_shader_input_vpm_segment_size = seg[2]; H.min_coord_shader_input_segments_required_in_play = seg[3];
		H.vertex_shader_output_vpm_segment_size = seg[4]; H.min_vertex_shader_output_segments_required_in_play_in_addition_to_vcm_cache_size = seg[5];
		H.vertex_shader_input_vpm_segment_size = seg[6]; H.min_vertex_shader_input_segments_required_in_play = seg[7];
		H.address_of_default_attribute_values = dflt;
		H.fragment_shader_4_way_threadable = t[0]; H.fragment_shader_start_in_final_thread_section = t[1]; H.fragment_shader_propagate_nans = t[2]; H.fragment_shader_code_address = fsa >> 3;
		H.fragment_shader_uniforms_address = fsu;
		H.vertex_shader_4_way_threadable = t[3]; H.vertex_shader_start_in_final_thread_section = t[4]; H.vertex_shader_propagate_nans = t[5]; H.vertex_shader_code_address = vsa >> 3;
		H.vertex_shader_uniforms_address = vsu;
		H.coordinate_shader_4_way_threadable = t[6]; H.coordinate_shader_start_in_final_thread_section = t[7]; H.coordinate_shader_propagate_nans = t[8]; H.coordinate_shader_code_address = csa >> 3;
		H.coordinate_shader_uniforms_address = csu;
		unsigned char g[V3D42_GL_SHADER_STATE_RECORD_length]; struct V3D42_GL_SHADER_STATE_RECORD v; memset (&v, 0, sizeof v);
		v.point_size_in_shaded_vertex_data = f[0]; v.enable_clipping = f[1]; v.vertex_id_read_by_coordinate_shader = f[2]; v.instance_id_read_by_coordinate_shader = f[3];
		v.base_instance_id_read_by_coordinate_shader = f[4]; v.vertex_id_read_by_vertex_shader = f[5]; v.instance_id_read_by_vertex_shader = f[6];
		v.base_instance_id_read_by_vertex_shader = f[7]; v.fragment_shader_does_z_writes = f[8]; v.turn_off_early_z_test = f[9];
		v.coordinate_shader_has_separate_input_and_output_vpm_blocks = f[10]; v.vertex_shader_has_separate_input_and_output_vpm_blocks = f[11];
		v.fragment_shader_uses_real_pixel_centre_w_in_addition_to_centroid_w2 = f[12]; v.enable_sample_rate_shading = f[13];
		v.any_shader_reads_hardware_written_primitive_id = f[14]; v.insert_primitive_id_as_first_varying_to_fragment_shader = f[15];
		v.turn_off_scoreboard = f[16]; v.do_scoreboard_wait_on_first_thread_switch = f[17]; v.disable_implicit_point_line_varyings = f[18]; v.no_prim_pack = f[19];
		v.number_of_varyings_in_fragment_shader = nv;
		v.coordinate_shader_output_vpm_segment_size = seg[0]; v.min_coord_shader_output_segments_required_in_play_in_addition_to_vcm_cache_size = seg[1];
		v.coordinate_shader_input_vpm_segment_size = seg[2]; v.min_coord_shader_input_segments_required_in_play = seg[3] + 1;	// (minus one: the hand-written one holds the stored value)
		v.vertex_shader_output_vpm_segment_size = seg[4]; v.min_vertex_shader_output_segments_required_in_play_in_addition_to_vcm_cache_size = seg[5];
		v.vertex_shader_input_vpm_segment_size = seg[6]; v.min_vertex_shader_input_segments_required_in_play = seg[7] + 1;
		v.address_of_default_attribute_values = dflt;
		v.fragment_shader_4_way_threadable = t[0]; v.fragment_shader_start_in_final_thread_section = t[1]; v.fragment_shader_propagate_nans = t[2]; v.fragment_shader_code_address = fsa;
		v.fragment_shader_uniforms_address = fsu;
		v.vertex_shader_4_way_threadable = t[3]; v.vertex_shader_start_in_final_thread_section = t[4]; v.vertex_shader_propagate_nans = t[5]; v.vertex_shader_code_address = vsa;
		v.vertex_shader_uniforms_address = vsu;
		v.coordinate_shader_4_way_threadable = t[6]; v.coordinate_shader_start_in_final_thread_section = t[7]; v.coordinate_shader_propagate_nans = t[8]; v.coordinate_shader_code_address = csa;
		v.coordinate_shader_uniforms_address = csu;
		V3D42_GL_SHADER_STATE_RECORD_pack (g, &v);
		same ("GL Shader State Record", H, g, sizeof g);
	}
	{
		GlShaderStateAttributeRecord H; memset (&H, 0, sizeof H);
		unsigned a = R (32), vs = R (2), ty = R (3), si = R (1), ni = R (1), ri = R (1), nc = R (4), nvs = R (4), d = R (16), st = R (32), mi = R (32);
		H.address = a; H.vec_size = vs; H.type = ty; H.signed_int_type = si; H.normalized_int_type = ni; H.read_as_int_uint = ri;
		H.number_of_values_read_by_coordinate_shader = nc; H.number_of_values_read_by_vertex_shader = nvs; H.instance_divisor = d; H.stride = st; H.maximum_index = mi;
		unsigned char g[V3D42_GL_SHADER_STATE_ATTRIBUTE_RECORD_length]; struct V3D42_GL_SHADER_STATE_ATTRIBUTE_RECORD v; memset (&v, 0, sizeof v);
		v.address = a; v.vec_size = vs; v.type = ty; v.signed_int_type = si; v.normalized_int_type = ni; v.read_as_int_uint = ri;
		v.number_of_values_read_by_coordinate_shader = nc; v.number_of_values_read_by_vertex_shader = nvs; v.instance_divisor = d; v.stride = st; v.maximum_index = mi;
		V3D42_GL_SHADER_STATE_ATTRIBUTE_RECORD_pack (g, &v);
		same ("GL Shader State Attribute Record", H, g, sizeof g);
	}
}

// ---- each field alone: exactly its bits, both versions (the generator's packing itself) ------------------------------
// the packet with the field at all ones, XORed with the packet with it at 0 (the other fields as they are, the
// minus-one ones too): exactly the field's bits
static bool bit (const unsigned char *b, unsigned i) { return (b[i / 8] >> (i % 8)) & 1; }
static void field_alone (const char *what, const unsigned char *zero, const unsigned char *ones, unsigned len, unsigned start, unsigned size)
{
	s_tests++;
	unsigned bad = 0;
	for (unsigned i = 0; i < len * 8; i++)
		if ((bit (zero, i) != bit (ones, i)) != (i >= start && i < start + size)) bad++;
	if (bad) { s_fail++; printf ("FAIL %s: %u bits wrong\n", what, bad); }
}
#define ALONE(V, T, F, START, SIZE, ONES) { unsigned char z[V##_##T##_length], c[V##_##T##_length]; struct V##_##T v; memset (&v, 0, sizeof v); \
	V##_##T##_pack (z, &v); ONES; V##_##T##_pack (c, &v); field_alone (#V " " #T "." #F, z, c, V##_##T##_length, START, SIZE); }
static float allOnesF () { unsigned u = 0xFFFFFFFFu; float f; memcpy (&f, &u, 4); return f; }

int main ()
{
	srand (3);
	for (int i = 0; i < 2000; i++) round_once ();
	// the generated packing, a field alone (a sample of every kind: uint, bool, address, float, minus one)
	ALONE (V3D42, TILE_COORDINATES, tile_row_number, 20, 12, v.tile_row_number = 0xFFF);
	ALONE (V3D71, TILE_BINNING_MODE_CFG, log2_tile_width, 16, 3, v.log2_tile_width = 7);
	ALONE (V3D71, TILE_BINNING_MODE_CFG, width_in_pixels, 40, 16, v.width_in_pixels = 1);	// (minus one: 1 - 1 = 0 against 0 - 1)
	ALONE (V3D71, GL_SHADER_STATE_RECORD, fragment_shader_code_address, 67, 29, v.fragment_shader_code_address = 0xFFFFFFF8u);
	ALONE (V3D71, CLIPPER_XY_SCALING, viewport_half_width_in_1_64th_of_pixel, 8, 32, v.viewport_half_width_in_1_64th_of_pixel = allOnesF ());
	ALONE (V3D71, TILE_RENDERING_MODE_CFG_RENDER_TARGET_PART1, base_address, 15, 11, v.base_address = 0x7FF);
	printf ("pack_test: %d of %d failed\n", s_fail, s_tests);
	return s_fail != 0;
}
