#!/usr/bin/env python3
"""genpackets.py -- the V3D control-list packets and state records, as C pack functions, from Mesa's
v3d_packet.xml (tools/v3d/v3d_packet.xml, Mesa src/broadcom/cle at 5a85b3d9, MIT) for one GPU version.

    python3 tools/v3d/genpackets.py 42 > kernel/include/kern/v3d_pack42.h   (V3D 4.2, the Pi 4)
    python3 tools/v3d/genpackets.py 71 > kernel/include/kern/v3d_pack71.h   (V3D 7.1, the Pi 5)
    (or: make -C tools/v3d)

The layout rules are Mesa's own generator's (src/broadcom/cle/gen_pack_header.py): a packet's field
starts count from the bit after its opcode; "Nb" is N bytes; a packet's length is its last field's
byte + 1; minus_one fields store value - 1; an address field holds the address top-aligned at its last
bit (its low bits are the alignment's); f187 is a float's high 16 bits; uA.B / sA.B fixed point;
min_ver / max_ver keep a packet, a struct, an enum or a value to the versions they name.

Each packet / struct NAME gives `struct V3Dxx_NAME` (its fields, plain values: an address is a u32 bus
address), `V3Dxx_NAME_length`, `V3Dxx_NAME_opcode` (a packet), `V3Dxx_NAME_header` (its defaults: the
opcode, the sub-ids), and `V3Dxx_NAME_pack (u8 *cl, const struct V3Dxx_NAME *v)`. Freestanding C/C++:
the kernel includes it (kern/v3d_pack71.h). tools/tests/v3d/pack_test.cpp checks the 4.2 output against
kern/v3d_cl.h's hand-written packets, byte for byte.

MIT licence (docs/LICENSING.md).
"""
import re, sys, xml.etree.ElementTree as ET

HERE = __import__ ("os").path.dirname (__import__ ("os").path.abspath (__file__))

def to_alphanum (name):
	for a, b in ((' ', '_'), ('/', '_'), ('[', ''), (']', ''), ('(', ''), (')', ''), ('-', '_'), (':', ''), ('.', ''),
		     (',', ''), ('=', ''), ('>', ''), ('#', ''), ('&', ''), ('*', ''), ('"', ''), ('+', ''), ("'", '')):
		name = name.replace (a, b)
	return name

def safe_name (name):
	name = to_alphanum (name)
	return name if name[0].isalpha () else '_' + name

def valid (attrs, ver):
	if "min_ver" in attrs and ver < int (attrs["min_ver"]): return False
	if "max_ver" in attrs and ver > int (attrs["max_ver"]): return False
	return True

UFIX = re.compile (r"u(\d+)\.(\d+)$"); SFIX = re.compile (r"s(\d+)\.(\d+)$")

def main ():
	ver = int (sys.argv[1]) if len (sys.argv) > 1 else 42
	xmlpath = sys.argv[2] if len (sys.argv) > 2 else HERE + "/v3d_packet.xml"
	root = ET.parse (xmlpath).getroot ()
	P = "V3D%d" % ver
	out = []
	w = out.append
	w ("// Generated by tools/v3d/genpackets.py %d from Mesa's v3d_packet.xml (MIT) -- do not edit." % ver)
	w ("// The V3D %d.%d control-list packets and state records (docs/02 §15, docs/PI5-PORT.md §9)." % (ver // 10, ver % 10))
	w ("#ifndef _kern_v3d_pack%d_h" % ver)
	w ("#define _kern_v3d_pack%d_h" % ver)
	w ("")
	w ("#ifndef V3DPACK_HELPERS")
	w ("#define V3DPACK_HELPERS")
	w ("// v's low `size` bits ORed into cl at bit `start` (little-endian, bit 0 = cl[0]'s bit 0)")
	w ("static inline void v3dpack_bits (unsigned char *cl, unsigned start, unsigned size, unsigned long long v)")
	w ("{")
	w ("\tif (size < 64) v &= (1ull << size) - 1;")
	w ("\tfor (unsigned i = 0; i < size; )")
	w ("\t{")
	w ("\t\tunsigned bit = start + i, n = 8 - bit % 8;")
	w ("\t\tif (n > size - i) n = size - i;")
	w ("\t\tcl[bit / 8] |= (unsigned char) (((v >> i) & ((1u << n) - 1)) << (bit % 8));")
	w ("\t\ti += n;")
	w ("\t}")
	w ("}")
	w ("static inline unsigned v3dpack_fui (float f) { union { float f; unsigned u; } x; x.f = f; return x.u; }")
	w ("static inline long long v3dpack_round (float f) { return (long long) (f < 0 ? f - 0.5f : f + 0.5f); }")
	w ("#endif")
	w ("")
	enums = {}
	for e in root.findall ("enum"):
		enums[e.get ("name")] = e
		if not valid (e.attrib, ver): continue
		pre = e.get ("prefix")
		vals = [v for v in e.findall ("value") if valid (v.attrib, ver)]
		if not vals: continue
		w ("// enum %s" % e.get ("name"))
		for v in vals:
			n = safe_name (((pre + "_") if pre else (e.get ("name") + "_")) + v.get ("name")).upper ()
			n = re.sub (r"^V3D_", "", n)
			w ("#define %s_%s %s" % (P, n, v.get ("value")))
		w ("")
	seen = set ()
	for g in root:
		if g.tag not in ("packet", "struct"): continue
		if not valid (g.attrib, ver): continue
		name = P + "_" + safe_name (g.get ("name").upper ())
		if name in seen: sys.exit ("genpackets: %s twice for version %d" % (name, ver))
		seen.add (name)
		fields = []
		base = 0 if g.tag == "struct" else 8
		if g.tag == "packet":
			fields.append (dict (name = "opcode", start = 0, size = 8, type = "uint", default = int (g.get ("code")), minus = False))
		names = set ()
		for f in g.findall ("field"):
			st = f.get ("start")
			start = int (st[:-1]) * 8 if st.endswith ("b") else int (st)
			fn = safe_name (f.get ("name")).lower ()
			k = 2
			while fn in names: fn = "%s_%d" % (safe_name (f.get ("name")).lower (), k); k += 1
			names.add (fn)
			fields.append (dict (name = fn, start = start + base, size = int (f.get ("size")), type = f.get ("type"),
					     default = int (f.get ("default"), 0) if f.get ("default") is not None else None,
					     minus = f.get ("minus_one") == "true",
					     values = [(v.get ("name"), v.get ("value")) for v in f.findall ("value") if valid (v.attrib, ver)]))
		length = max ((x["start"] + x["size"] - 1) // 8 for x in fields) + 1 if fields else (1 if g.tag == "packet" else 0)
		w ("// %s %s%s" % (g.tag, g.get ("name"), (" (code %s)" % g.get ("code")) if g.tag == "packet" else ""))
		w ("#define %s_length %d" % (name, length))
		if g.tag == "packet": w ("#define %s_opcode %s" % (name, g.get ("code")))
		for x in fields:
			for vn, vv in x.get ("values", []):
				w ("#define %s_%s_%s %s" % (name, x["name"].upper (), safe_name (vn).upper (), vv))
		w ("struct %s" % name)
		w ("{")
		for x in fields:
			t = x["type"]
			if t == "float" or t == "f187" or UFIX.match (t) or SFIX.match (t): ct = "float"
			elif t == "int": ct = "int"
			elif t == "address": ct = "unsigned"	# the bus address (u32)
			elif t in ("uint", "bool") or t in enums:
				ct = "unsigned long long" if x["size"] > 32 else "unsigned"
			else: sys.exit ("genpackets: %s.%s: type %s not handled" % (name, x["name"], t))
			w ("\t%s %s;%s" % (ct, x["name"], ("\t// %s bits at %d%s" % (x["size"], x["start"], ", minus one" if x["minus"] else ""))))
		w ("};")
		hd = ["." + x["name"] + " = " + str (x["default"]) for x in fields if x["default"] is not None]
		w ("#define %s_header %s" % (name, ", ".join (hd)))
		w ("static inline void %s_pack (unsigned char *cl, const struct %s *v)" % (name, name))
		w ("{")
		w ("\tfor (unsigned i = 0; i < %s_length; i++) cl[i] = 0;" % name)
		for x in fields:
			t, n, s, z = x["type"], x["name"], x["start"], x["size"]
			if t == "float":
				if s % 8 or z != 32: sys.exit ("genpackets: %s.%s: a float not on 32 whole bits" % (name, n))
				val = "v3dpack_fui (v->%s)" % n
			elif t == "f187": val = "(v3dpack_fui (v->%s) >> 16)" % n
			elif UFIX.match (t): val = "(unsigned long long) v3dpack_round (v->%s * %d.0f)" % (n, 1 << int (UFIX.match (t).group (2)))
			elif SFIX.match (t): val = "(unsigned long long) v3dpack_round (v->%s * %d.0f)" % (n, 1 << int (SFIX.match (t).group (2)))
			elif t == "address": val = "((unsigned long long) v->%s >> %d)" % (n, 32 - z) if z < 32 else "(unsigned long long) v->%s" % n
			elif t == "int": val = "(unsigned long long) (long long) v->%s" % n
			else: val = "(unsigned long long) (v->%s%s)" % (n, " - 1" if x["minus"] else "")
			w ("\tv3dpack_bits (cl, %d, %d, %s);" % (s, z, val))
		w ("}")
		w ("")
	w ("#endif")
	print ("\n".join (out))

if __name__ == "__main__":
	main ()
