#!/bin/sh
# gen_blob.sh -- tools/onyxrun/el0blob.inc from the kernel's kernel/arch/aarch64/el0blob.S: the user-side part of
# the kapi table (memcpy & co., the event pump, the return paths) as bytes, and its labels' offsets -- the runner
# maps them at KAPI_STUBS_VA + EL0_BLOB_OFFSET as the kernel does (kernel/sys/el0.cpp El0Init). Needs an AArch64
# assembler (aarch64-linux-gnu-gcc or aarch64-none-elf-gcc); run it after el0blob.S changes, commit the .inc.
# MIT licence (Onyx). Copyright (c) 2026 Stephane Wegener and the Onyx contributors.
set -e
cd "$(dirname "$0")/../.."
CC=${A64_GCC:-$(command -v aarch64-linux-gnu-gcc || command -v aarch64-none-elf-gcc)}
PFX=${CC%gcc}
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
$CC -c -I kernel/include -D__ASSEMBLER__ kernel/arch/aarch64/el0blob.S -o "$T/blob.o"
# linked at 0 (its branches between its own global labels resolved: all PC-relative)
echo 'SECTIONS { . = 0; .blob : { *(.rodata.el0blob) } /DISCARD/ : { *(*) } }' > "$T/blob.ld"
${PFX}ld -o "$T/blob.elf" -T "$T/blob.ld" -e 0 "$T/blob.o"
${PFX}objcopy -O binary -j .blob "$T/blob.elf" "$T/blob.bin"
{
	echo "// GENERATED by tools/onyxrun/gen_blob.sh from kernel/arch/aarch64/el0blob.S -- do not edit."
	${PFX}nm "$T/blob.elf" | grep " El0" | sort | awk '{ printf "#define BLOB_%s 0x%sULL\n", $3, $1 }' | sed 's/0x0*\([0-9a-f]\)/0x\1/'
	echo "static const unsigned char s_El0Blob[] = {"
	od -An -v -tx1 "$T/blob.bin" | sed 's/ \([0-9a-f][0-9a-f]\)/0x\1,/g'
	echo "};"
} > tools/onyxrun/el0blob.inc
echo "gen_blob: tools/onyxrun/el0blob.inc ($(wc -c < "$T/blob.bin") bytes)"
