/*
 * tools/tests/netsurf/intl/cases.js -- expressions run in Node (full ICU) and in qjsintl
 * (NetSurf's Intl); compare.sh prints the differences. One line per case: "expr => result".
 * The same list drives pages/js-intl.html's expected values (mkpage.js).
 */
var d = new Date(Date.UTC(2023, 2, 5, 13, 2, 3, 45));
var d2 = new Date(Date.UTC(2023, 6, 14, 1, 9, 0, 5));
var UTC = { timeZone: 'UTC' };
function o(x) { var r = { timeZone: 'UTC' }; for (var k in x) r[k] = x[k]; return r; }
var CASES = [
	"typeof Intl",
	"Object.prototype.toString.call(Intl)",
	/* numbers */
	"new Intl.NumberFormat('en').format(1234567.891)",
	"new Intl.NumberFormat('fr').format(1234567.891)",
	"new Intl.NumberFormat('de').format(-1234567.891)",
	"new Intl.NumberFormat('es').format(1234)",
	"new Intl.NumberFormat('es').format(12345)",
	"new Intl.NumberFormat('en-IN').format(123456789)",
	"new Intl.NumberFormat('pt-PT').format(1234567.5)",
	"new Intl.NumberFormat('nl').format(0.5)",
	"(1.005).toLocaleString('en', {maximumFractionDigits: 2})",
	"(0.125).toLocaleString('en', {maximumFractionDigits: 2, roundingMode: 'halfEven'})",
	"(1234.5678).toLocaleString('en', {maximumSignificantDigits: 3})",
	"(0.000123456).toLocaleString('en', {maximumSignificantDigits: 2})",
	"(5).toLocaleString('en', {minimumFractionDigits: 2})",
	"(5).toLocaleString('en', {minimumIntegerDigits: 3})",
	"(1234.5).toLocaleString('en', {useGrouping: false})",
	"(-0).toLocaleString('en')",
	"(NaN).toLocaleString('fr')",
	"(-Infinity).toLocaleString('en')",
	"(0.256).toLocaleString('en', {style: 'percent'})",
	"(0.256).toLocaleString('fr', {style: 'percent', maximumFractionDigits: 1})",
	"(-0.5).toLocaleString('de', {style: 'percent'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'USD'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'EUR'})",
	"(1234.5).toLocaleString('en-GB', {style: 'currency', currency: 'GBP'})",
	"(1234.5).toLocaleString('fr', {style: 'currency', currency: 'EUR'})",
	"(1234.5).toLocaleString('fr', {style: 'currency', currency: 'USD'})",
	"(1234.5).toLocaleString('de', {style: 'currency', currency: 'EUR'})",
	"(1234.5).toLocaleString('nl', {style: 'currency', currency: 'EUR'})",
	"(-1234.5).toLocaleString('nl', {style: 'currency', currency: 'EUR'})",
	"(1234.5).toLocaleString('pt', {style: 'currency', currency: 'BRL'})",
	"(1234.5).toLocaleString('ja', {style: 'currency', currency: 'JPY'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'JPY'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'CHF'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'USD', currencyDisplay: 'code'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'USD', currencyDisplay: 'name'})",
	"(1).toLocaleString('en', {style: 'currency', currency: 'USD', currencyDisplay: 'name'})",
	"(2).toLocaleString('fr', {style: 'currency', currency: 'EUR', currencyDisplay: 'name'})",
	"(1234.5).toLocaleString('en', {style: 'currency', currency: 'CAD', currencyDisplay: 'narrowSymbol'})",
	"(-5).toLocaleString('en', {style: 'currency', currency: 'USD', currencySign: 'accounting'})",
	"(5).toLocaleString('en', {signDisplay: 'always'})",
	"(0).toLocaleString('en', {signDisplay: 'exceptZero'})",
	"(-5).toLocaleString('en', {signDisplay: 'never'})",
	"(1234).toLocaleString('en', {notation: 'compact'})",
	"(1234567).toLocaleString('en', {notation: 'compact'})",
	"(999999).toLocaleString('en', {notation: 'compact'})",
	"(1234).toLocaleString('en', {notation: 'compact', compactDisplay: 'long'})",
	"(1234).toLocaleString('fr', {notation: 'compact'})",
	"(2e6).toLocaleString('fr', {notation: 'compact', compactDisplay: 'long'})",
	"(1e6).toLocaleString('fr', {notation: 'compact', compactDisplay: 'long'})",
	"(1234).toLocaleString('de', {notation: 'compact'})",
	"(1500000).toLocaleString('de', {notation: 'compact'})",
	"(12345).toLocaleString('es', {notation: 'compact'})",
	"(12345).toLocaleString('ja', {notation: 'compact'})",
	"(15300).toLocaleString('en', {notation: 'compact', style: 'currency', currency: 'USD'})",
	"(123456).toLocaleString('en', {notation: 'scientific'})",
	"(0.00123).toLocaleString('en', {notation: 'scientific'})",
	"(123456).toLocaleString('en', {notation: 'engineering'})",
	"(5).toLocaleString('en', {style: 'unit', unit: 'kilometer'})",
	"(5).toLocaleString('en', {style: 'unit', unit: 'kilometer', unitDisplay: 'long'})",
	"(1).toLocaleString('en', {style: 'unit', unit: 'kilometer', unitDisplay: 'long'})",
	"(5).toLocaleString('en', {style: 'unit', unit: 'kilometer-per-hour'})",
	"(5).toLocaleString('fr', {style: 'unit', unit: 'kilometer-per-hour', unitDisplay: 'long'})",
	"(5).toLocaleString('en', {style: 'unit', unit: 'gigabyte-per-second', unitDisplay: 'long'})",
	"(2.5).toLocaleString('de', {style: 'unit', unit: 'megabyte'})",
	"(50).toLocaleString('en', {style: 'unit', unit: 'percent'})",
	"(21).toLocaleString('en', {style: 'unit', unit: 'celsius'})",
	"(3).toLocaleString('en', {style: 'unit', unit: 'hour', unitDisplay: 'narrow'})",
	"(12345678901234567890n).toLocaleString('en')",
	"new Intl.NumberFormat('en').format('1234567890123456789.25')",
	"new Intl.NumberFormat('en', {maximumFractionDigits: 0, roundingIncrement: 5}).format(12)",
	"new Intl.NumberFormat('en', {maximumFractionDigits: 2, trailingZeroDisplay: 'stripIfInteger', minimumFractionDigits: 2}).format(5)",
	"new Intl.NumberFormat('en', {maximumSignificantDigits: 2, maximumFractionDigits: 2, roundingPriority: 'lessPrecision'}).format(1.2345)",
	"new Intl.NumberFormat('ar-EG', {numberingSystem: 'arab'}).resolvedOptions().numberingSystem",
	"new Intl.NumberFormat('en-u-nu-arab').format(123)",
	"new Intl.NumberFormat('en').formatRange(3, 5)",
	"new Intl.NumberFormat('en').formatRange(3, 3)",
	"new Intl.NumberFormat('en', {style: 'currency', currency: 'USD'}).formatRange(3, 5)",
	"new Intl.NumberFormat('fr', {style: 'currency', currency: 'EUR'}).formatRange(3, 5)",
	"new Intl.NumberFormat('en', {style: 'percent'}).formatRange(0.03, 0.05)",
	"new Intl.NumberFormat('en', {style: 'unit', unit: 'kilometer'}).formatRange(3, 5)",
	"new Intl.NumberFormat('en').formatRange(-5, -3)",
	"new Intl.NumberFormat('de', {notation: 'compact'}).formatRange(3000, 5e6)",
	"JSON.stringify(new Intl.NumberFormat('en').formatToParts(-1234.5))",
	"JSON.stringify(new Intl.NumberFormat('en', {style: 'currency', currency: 'EUR'}).resolvedOptions())",
	"JSON.stringify(new Intl.NumberFormat('de', {notation: 'compact'}).resolvedOptions())",
	/* plural rules */
	"new Intl.PluralRules('en').select(1)",
	"new Intl.PluralRules('en').select(1.0.toFixed(1) * 1)",
	"new Intl.PluralRules('en', {minimumFractionDigits: 1}).select(1)",
	"new Intl.PluralRules('en', {type: 'ordinal'}).select(22)",
	"new Intl.PluralRules('en', {type: 'ordinal'}).select(13)",
	"new Intl.PluralRules('fr').select(1.5)",
	"new Intl.PluralRules('fr').select(1000000)",
	"new Intl.PluralRules('ru').select(22)",
	"new Intl.PluralRules('ru').select(25)",
	"new Intl.PluralRules('pl').select(12)",
	"new Intl.PluralRules('it', {type: 'ordinal'}).select(8)",
	"JSON.stringify(new Intl.PluralRules('fr').resolvedOptions().pluralCategories)",
	/* dates */
	"d.toLocaleString('en-US', UTC)",
	"d.toLocaleString('en-GB', UTC)",
	"d.toLocaleString('fr', UTC)",
	"d.toLocaleString('de', UTC)",
	"d.toLocaleString('es', UTC)",
	"d.toLocaleString('it', UTC)",
	"d.toLocaleString('nl', UTC)",
	"d.toLocaleString('pt', UTC)",
	"d.toLocaleString('ja', UTC)",
	"d.toLocaleDateString('en-US', UTC)",
	"d.toLocaleDateString('fr-FR', UTC)",
	"d.toLocaleTimeString('en-US', UTC)",
	"d.toLocaleTimeString('fr', UTC)",
	"d.toLocaleDateString('en-GB', o({day: 'numeric', month: 'long', year: 'numeric'}))",
	"d.toLocaleDateString('en-US', o({weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'}))",
	"d.toLocaleDateString('fr', o({weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'}))",
	"d.toLocaleDateString('de', o({weekday: 'short', day: 'numeric', month: 'short'}))",
	"d.toLocaleDateString('es', o({month: 'long', year: 'numeric'}))",
	"d.toLocaleDateString('en', o({month: 'short', day: 'numeric'}))",
	"d.toLocaleDateString('en', o({year: '2-digit', month: '2-digit', day: '2-digit'}))",
	"d.toLocaleDateString('en', o({weekday: 'narrow'}))",
	"d.toLocaleDateString('en', o({month: 'narrow'}))",
	"d.toLocaleDateString('en', o({era: 'short', year: 'numeric'}))",
	"d.toLocaleTimeString('en', o({hour: '2-digit', minute: '2-digit'}))",
	"d.toLocaleTimeString('en', o({hour: 'numeric', minute: '2-digit', hour12: false}))",
	"d.toLocaleTimeString('fr', o({hour: 'numeric', minute: '2-digit', hour12: true}))",
	"d.toLocaleTimeString('en', o({hour: 'numeric'}))",
	"d.toLocaleTimeString('de', o({hour: 'numeric'}))",
	"d.toLocaleTimeString('en', o({hour: 'numeric', minute: 'numeric', second: 'numeric', fractionalSecondDigits: 3}))",
	"d.toLocaleTimeString('en', o({hour: 'numeric', dayPeriod: 'long'}))",
	"d.toLocaleTimeString('en', o({hourCycle: 'h11', hour: 'numeric', minute: 'numeric'}))",
	"d.toLocaleTimeString('en', o({hourCycle: 'h24', hour: 'numeric', minute: 'numeric'}))",
	"d.toLocaleString('en', {timeZone: 'America/New_York'})",
	"d2.toLocaleString('en', {timeZone: 'America/New_York'})",
	"d.toLocaleString('fr', {timeZone: 'Europe/Paris'})",
	"d2.toLocaleString('fr', {timeZone: 'Europe/Paris'})",
	"d2.toLocaleString('en-AU', {timeZone: 'Australia/Sydney'})",
	"d.toLocaleString('en-AU', {timeZone: 'Australia/Sydney'})",
	"d.toLocaleString('en', {timeZone: 'Asia/Kolkata'})",
	"d.toLocaleString('en', {timeZone: 'Asia/Tokyo', timeZoneName: 'short'})",
	"d.toLocaleString('en', {timeZone: 'America/Los_Angeles', timeZoneName: 'short'})",
	"d2.toLocaleString('en', {timeZone: 'America/Los_Angeles', timeZoneName: 'long'})",
	"d.toLocaleString('en-GB', {timeZone: 'Europe/London', timeZoneName: 'short'})",
	"d2.toLocaleString('en-GB', {timeZone: 'Europe/London', timeZoneName: 'short'})",
	"d.toLocaleString('fr', {timeZone: 'Europe/Paris', timeZoneName: 'long'})",
	"d.toLocaleString('de', {timeZone: 'Europe/Berlin', timeZoneName: 'short'})",
	"d.toLocaleString('en', {timeZone: 'Europe/Paris', timeZoneName: 'shortOffset'})",
	"d.toLocaleString('en', {timeZone: 'Asia/Kolkata', timeZoneName: 'longOffset'})",
	"d.toLocaleDateString('en', {timeZone: 'UTC', timeZoneName: 'short'})",
	"d.toLocaleString('en', {timeZone: '+05:30'})",
	"new Intl.DateTimeFormat('en', {timeZone: 'europe/paris'}).resolvedOptions().timeZone",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'full'})).format(d)",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'long'})).format(d)",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'medium'})).format(d)",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'short'})).format(d)",
	"new Intl.DateTimeFormat('en-GB', o({dateStyle: 'medium', timeStyle: 'short'})).format(d)",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'long', timeStyle: 'short'})).format(d)",
	"new Intl.DateTimeFormat('fr', o({dateStyle: 'full', timeStyle: 'long'})).format(d)",
	"new Intl.DateTimeFormat('de', o({dateStyle: 'medium', timeStyle: 'medium'})).format(d)",
	"new Intl.DateTimeFormat('es', o({dateStyle: 'short', timeStyle: 'short'})).format(d)",
	"new Intl.DateTimeFormat('en', o({timeStyle: 'short', hour12: false})).format(d)",
	"JSON.stringify(new Intl.DateTimeFormat('en', UTC).formatToParts(d))",
	"JSON.stringify(new Intl.DateTimeFormat('fr', o({day: 'numeric'})).resolvedOptions())",
	"JSON.stringify(new Intl.DateTimeFormat('en', o({hour: 'numeric'})).resolvedOptions())",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'medium'})).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2023, 0, 10))",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'medium'})).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2023, 1, 10))",
	"new Intl.DateTimeFormat('en', o({dateStyle: 'medium'})).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2024, 1, 10))",
	"new Intl.DateTimeFormat('fr', o({dateStyle: 'long'})).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2023, 0, 10))",
	"new Intl.DateTimeFormat('en', o({hour: 'numeric', minute: 'numeric'})).formatRange(Date.UTC(2023, 0, 5, 10), Date.UTC(2023, 0, 5, 14))",
	"new Intl.DateTimeFormat('en', o({hour: 'numeric', minute: 'numeric'})).formatRange(Date.UTC(2023, 0, 5, 10), Date.UTC(2023, 0, 5, 11))",
	"new Intl.DateTimeFormat('en', UTC).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2023, 0, 10))",
	"new Intl.DateTimeFormat('en', o({year: 'numeric', month: 'short'})).formatRange(Date.UTC(2023, 0, 5), Date.UTC(2023, 3, 5))",
	/* relative time */
	"new Intl.RelativeTimeFormat('en').format(-1, 'day')",
	"new Intl.RelativeTimeFormat('en', {numeric: 'auto'}).format(-1, 'day')",
	"new Intl.RelativeTimeFormat('en', {numeric: 'auto'}).format(0, 'year')",
	"new Intl.RelativeTimeFormat('en').format(3, 'hours')",
	"new Intl.RelativeTimeFormat('en', {style: 'short'}).format(-5, 'minute')",
	"new Intl.RelativeTimeFormat('en', {style: 'narrow'}).format(-5, 'minute')",
	"new Intl.RelativeTimeFormat('fr').format(-3, 'hour')",
	"new Intl.RelativeTimeFormat('fr', {numeric: 'auto'}).format(-2, 'day')",
	"new Intl.RelativeTimeFormat('de').format(2, 'week')",
	"new Intl.RelativeTimeFormat('es', {numeric: 'auto'}).format(1, 'day')",
	"new Intl.RelativeTimeFormat('en').format(1.5, 'month')",
	"new Intl.RelativeTimeFormat('en').format(-1234, 'second')",
	"JSON.stringify(new Intl.RelativeTimeFormat('en').formatToParts(-3.5, 'hour'))",
	/* lists */
	"new Intl.ListFormat('en').format(['a', 'b', 'c'])",
	"new Intl.ListFormat('en-GB').format(['a', 'b', 'c'])",
	"new Intl.ListFormat('en', {type: 'disjunction'}).format(['a', 'b', 'c'])",
	"new Intl.ListFormat('en').format(['a', 'b'])",
	"new Intl.ListFormat('fr').format(['a', 'b', 'c', 'd'])",
	"new Intl.ListFormat('de', {type: 'unit', style: 'narrow'}).format(['a', 'b', 'c'])",
	"new Intl.ListFormat('es').format(['agua', 'hielo'])",
	"new Intl.ListFormat('es').format(['aceite', 'agua'])",
	/* collation */
	"['b', 'a', 'é', 'E', 'e', 'z', 'Z', 'É'].sort(new Intl.Collator('fr').compare).join()",
	"['item10', 'item2', 'item1'].sort(new Intl.Collator('en', {numeric: true}).compare).join()",
	"['b', 'a', 'B', 'A'].sort(new Intl.Collator('en', {caseFirst: 'upper'}).compare).join()",
	"'a'.localeCompare('B')",
	"'a'.localeCompare('A')",
	"'résumé'.localeCompare('resume')",
	"'résumé'.localeCompare('resume', 'en', {sensitivity: 'base'})",
	"'a'.localeCompare('á', 'en', {sensitivity: 'accent'})",
	"'a'.localeCompare('A', 'en', {sensitivity: 'accent'})",
	"['ñ', 'n', 'o'].sort(new Intl.Collator('es').compare).join()",
	"['straße', 'strasse', 'strase'].sort(new Intl.Collator('de').compare).join()",
	"['_a', 'a', '1', ' b', 'B'].sort(new Intl.Collator('en').compare).join('|')",
	/* segmenter */
	"[...new Intl.Segmenter('en').segment('éa👨‍👩‍👧🇫🇷')].length",
	"[...new Intl.Segmenter('en', {granularity: 'word'}).segment('Hello, world!')].map(function (s) { return s.segment + (s.isWordLike ? '*' : ''); }).join('|')",
	"[...new Intl.Segmenter('fr', {granularity: 'word'}).segment(\"l'homme est là\")].filter(function (s) { return s.isWordLike; }).length",
	"[...new Intl.Segmenter('en', {granularity: 'sentence'}).segment('Hi there. How are you? Fine!')].map(function (s) { return s.segment; }).join('|')",
	"new Intl.Segmenter('en').segment('abc').containing(1).segment",
	/* display names, locales */
	"new Intl.DisplayNames('en', {type: 'region'}).of('FR')",
	"new Intl.DisplayNames('fr', {type: 'region'}).of('US')",
	"new Intl.DisplayNames('de', {type: 'language'}).of('fr')",
	"new Intl.DisplayNames('en', {type: 'language'}).of('en-GB')",
	"new Intl.DisplayNames('en', {type: 'language', languageDisplay: 'standard'}).of('en-GB')",
	"new Intl.DisplayNames('en', {type: 'language'}).of('fr-BE')",
	"new Intl.DisplayNames('es', {type: 'currency'}).of('EUR')",
	"new Intl.DisplayNames('en', {type: 'script'}).of('Latn')",
	"new Intl.DisplayNames('en', {type: 'dateTimeField'}).of('month')",
	"new Intl.DisplayNames('en', {type: 'region', fallback: 'none'}).of('XX')",
	"new Intl.Locale('fr').maximize().toString()",
	"new Intl.Locale('en-Latn-US').minimize().toString()",
	"new Intl.Locale('zh-TW').maximize().toString()",
	"new Intl.Locale('en-US', {hourCycle: 'h23', calendar: 'gregory'}).toString()",
	"new Intl.Locale('fr-CA-u-nu-latn').numberingSystem",
	"new Intl.Locale('de-AT').baseName",
	"JSON.stringify(Intl.getCanonicalLocales(['EN-us', 'Fr', 'zh-hant-tw']))",
	"JSON.stringify(Intl.getCanonicalLocales('iw'))",
	"JSON.stringify(Intl.getCanonicalLocales('en-u-kn-true-ca-gregory'))",
	"JSON.stringify(Intl.NumberFormat.supportedLocalesOf(['fr-FR', 'xx', 'de']))",
	"new Intl.NumberFormat('fr-FR').resolvedOptions().locale",
	"new Intl.DateTimeFormat('en-u-hc-h23', o({hour: 'numeric'})).resolvedOptions().locale",
	"Intl.supportedValuesOf('currency').includes('EUR')",
	"Intl.supportedValuesOf('timeZone').includes('Europe/Paris')",
	"[1234.5, d].toLocaleString('en', o({}))",
	"'istanbul'.toLocaleUpperCase('tr')",
	"'I'.toLocaleLowerCase('tr')",
];
var out = typeof print === 'function' ? print : function (s) { console.log(s); };
for (var i = 0; i < CASES.length; i++) {
	var r;
	try { r = String(eval(CASES[i])); } catch (e) { r = 'THROWS ' + e.name; }
	out(CASES[i] + ' => ' + r);
}
