# installed by tools/pkg/mkrepo.py
[package]
name = archiver
title = Archiver
version = 1.0.26
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, filekit >= 1.78, kapi >= 97
config = 
assoc = zip=archiver jar=archiver tar=archiver tgz=archiver gz=archiver

[files]
apps/archiver.app/app.txt = de83a8318782cd70b93501ce1dc13078c0ab747091d7549dc1fce01aeeb02206
apps/archiver.app/icon.bmp = c0d3d930ddd41f5405cc7f806f29a9cd4d3c5fb9034ef85c72eef6c7ede7ca34
apps/archiver.app/main = 89b4ef38829c5d3aa07eb4400784b503f567c0573356a48e5562ad2538fed960
