# installed by tools/pkg/mkrepo.py
[package]
name = archiver
title = Archiver
version = 1.0.15
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, filekit >= 1.63, kapi >= 86
config = 
assoc = zip=archiver jar=archiver tar=archiver tgz=archiver gz=archiver

[files]
apps/archiver.app/app.txt = de83a8318782cd70b93501ce1dc13078c0ab747091d7549dc1fce01aeeb02206
apps/archiver.app/icon.bmp = c0d3d930ddd41f5405cc7f806f29a9cd4d3c5fb9034ef85c72eef6c7ede7ca34
apps/archiver.app/main = 14cc50d5bcd6d62553b7318caa4a64b653c10a257587342ebd793f36a4ed15d3
