# installed by tools/pkg/mkrepo.py
[package]
name = arkanoid
title = Arkanoid
version = 1.0.0
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 77
config = 

[files]
apps/arkanoid.app/app.txt = 1ee4c17f840a103bee1aa3d16356cccaa2d338abcb7c36d0e2c7b6b95def3cdb
apps/arkanoid.app/icon.bmp = 20bece67839bb652dbd8e1c00a6f495deedf647153e8f473050cf8af085f4309
apps/arkanoid.app/main.bax = a4e1b25f14048ae09c3be382eb22694156adbfeebb244682a21b6304cc4c63b0
