# installed by tools/pkg/mkrepo.py
[package]
name = arkanoid
title = Arkanoid
version = 1.0.2
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = wtk >= 1.683, ft, kapi >= 83
config = 

[files]
apps/arkanoid.app/app.txt = 1ee4c17f840a103bee1aa3d16356cccaa2d338abcb7c36d0e2c7b6b95def3cdb
apps/arkanoid.app/icon.bmp = 20bece67839bb652dbd8e1c00a6f495deedf647153e8f473050cf8af085f4309
apps/arkanoid.app/main.bax = fc2a8936d78799a8dd9510fa9024b336c307f6bc4790cc15a207cbb90f5c7d44
