# installed by tools/pkg/mkrepo.py
[package]
name = cardfile
title = Cardfile
version = 1.0.4
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 74
config = 

[files]
apps/cardfile.app/app.txt = 64e2fbe4eaf0d19b5decb1df452f9f35854669ec669497171b89ec3b9ac1d76b
apps/cardfile.app/icon.bmp = faacaece38df3acd7afcd09bcc171469e4c4743c4fbec7059f199b7845f72839
apps/cardfile.app/main = c8e9fd52618870e7033d95d87f75ebf124e7958809e9cc32048821ec6dc8d286
