# installed by tools/pkg/mkrepo.py
[package]
name = cardfile
title = Cardfile
version = 1.0.23
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 93
config = 
assoc = card=cardfile

[files]
apps/cardfile.app/app.txt = 64e2fbe4eaf0d19b5decb1df452f9f35854669ec669497171b89ec3b9ac1d76b
apps/cardfile.app/icon.bmp = faacaece38df3acd7afcd09bcc171469e4c4743c4fbec7059f199b7845f72839
apps/cardfile.app/main = 75db964e4941925d420126d731cbd448409a72eaaa2678287a7832f697ec9272
