# installed by tools/pkg/mkrepo.py
[package]
name = cardfile
title = Cardfile
version = 1.0.0
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 71
config = 

[files]
apps/cardfile.app/app.txt = 64e2fbe4eaf0d19b5decb1df452f9f35854669ec669497171b89ec3b9ac1d76b
apps/cardfile.app/icon.bmp = faacaece38df3acd7afcd09bcc171469e4c4743c4fbec7059f199b7845f72839
apps/cardfile.app/main = c8d26d505fa62872b7f27ae2545562898ddf92ba504bdc97dc83f7825d0026ff
