# installed by tools/pkg/mkrepo.py
[package]
name = courier
title = Courier
version = 1.0.19
category = Internet
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, uikit >= 1.722, kapi >= 97
config = 

[files]
apps/courier.app/app.txt = ffb1d224ba02f9e90701cb45a8fc4ad919fe372cdf39bf7fa478da985903924b
apps/courier.app/icon.bmp = 7ff61cd7635820caba5af7019307851098ac6d3b06fcb1bbee7ff96cb69cfcec
apps/courier.app/main = b2483b61c60ec45be18722d7a3908bca77ac809a4bb84668ae376e0acdcd507e
courier/collections/courier-examples.postman_collection.json = c5caaca64f5e695480add4d21a3c941a38a176b25494d44a2d828bc7c34ee159
