# installed by tools/pkg/mkrepo.py
[package]
name = gbaemu
title = Game Boy Advance
version = 1.0.25
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, gamelib, audiokit >= 1.232, kapi >= 96
config = 

[files]
apps/gbaemu.app/app.txt = d7820c5ff4fe43ba8c471bcd5f3705d84fbf9309058c52f5405189b89543ed25
apps/gbaemu.app/icon.bmp = a3acec19a1c919833d84b991d92c4a353ed83b280028ba60f91d0d053fdaa02c
apps/gbaemu.app/main = b19fad97b45a028f3c8eaec1fa15f23346dd0acb2d698b43eb9bd571479a7f71
