# installed by tools/pkg/mkrepo.py
[package]
name = gbaemu
title = Game Boy Advance
version = 1.0.0
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = gamelib, kapi >= 71
config = 

[files]
apps/gbaemu.app/app.txt = a555aed149b87130773b85d70960deef4afeb6a63426a6bf09d3bd05ec4bee5c
apps/gbaemu.app/icon.bmp = a3acec19a1c919833d84b991d92c4a353ed83b280028ba60f91d0d053fdaa02c
apps/gbaemu.app/main = 53c1698102b8dbc60f28b0f0f4458561c4de23743a862ce138ebab2048118c7a
