# installed by tools/pkg/mkrepo.py
[package]
name = gcemu
title = GameCube
version = 1.0.0
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 71
config = 

[files]
apps/gcemu.app/app.txt = 47c5349797e81f28e4ecbbb8eabda0059379d36a6ebc5c420319f139e779068c
apps/gcemu.app/icon.bmp = 8c58540cb2ee6975f731a0fa0cd0fc5f8bb25ddd56d4a37e81e4d83f0c72ef28
apps/gcemu.app/main = c4cca9eeb4a4a28bfdf2f38a596e82c4ca2e06c3884526a48e5fec0c14cab021
