# installed by tools/pkg/mkrepo.py
[package]
name = gcemu
title = GameCube
version = 1.0.6
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = gamelib, kapi >= 74
config = 

[files]
apps/gcemu.app/app.txt = 57b9445d0a7b228bfca1ac6ef6a6c2bf44bd618426e856ca1e58cae9735d7c2f
apps/gcemu.app/icon.bmp = 8c58540cb2ee6975f731a0fa0cd0fc5f8bb25ddd56d4a37e81e4d83f0c72ef28
apps/gcemu.app/main = 06f7ac0ad8c76d4b79d0251878ef504d6807f376a890eea1d0332fb21f927968
