# installed by tools/pkg/mkrepo.py
[package]
name = gpiolab
title = GPIO Lab
version = 1.0.2
category = System
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 93
config = 

[files]
apps/gpiolab.app/app.txt = bfe8b648b4ddee9bacd4796dbac444678028ab535cf868351bcbf3a09c2ee8c9
apps/gpiolab.app/icon.bmp = d22c486af8154c37d213c36b0b63d7c23d2932c32f10e8c9c94630fd615aa319
apps/gpiolab.app/main = 1f6d88f5ec2cdc825f870ad8505dfb85bc16e25d2d4ad564e0cca693464f0715
