# installed by tools/pkg/mkrepo.py
[package]
name = graphcalc
title = Graphing Calculator
version = 1.0.13
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = wtk >= 1.683, ft, kapi >= 84
config = 

[files]
apps/graphcalc.app/app.txt = dbdcc4fded4a77bf4ad7bb13eb45f24fafe7f0f4f703f3da28fdc9cc309bdb22
apps/graphcalc.app/icon.bmp = 8334df67024fc8d37b667dfb3f49f1335473885aac80b5535561686f210c6fdd
apps/graphcalc.app/main = 721bfea37e1bb4ae37e4281498e49949bc2922f8d729b86e68cafad1a3306a3c
