# installed by tools/pkg/mkrepo.py
[package]
name = graphcalc
title = Graphing Calculator
version = 1.0.2
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 72
config = 

[files]
apps/graphcalc.app/app.txt = dbdcc4fded4a77bf4ad7bb13eb45f24fafe7f0f4f703f3da28fdc9cc309bdb22
apps/graphcalc.app/icon.bmp = 8334df67024fc8d37b667dfb3f49f1335473885aac80b5535561686f210c6fdd
apps/graphcalc.app/main = b125f5b8b643159f8ff57307900ed1d7524161c58a78cbefb8687a8ed49ff003
