# installed by tools/pkg/mkrepo.py
[package]
name = graphcalc
title = Graphing Calculator
version = 1.0.9
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 78
config = 

[files]
apps/graphcalc.app/app.txt = dbdcc4fded4a77bf4ad7bb13eb45f24fafe7f0f4f703f3da28fdc9cc309bdb22
apps/graphcalc.app/icon.bmp = 8334df67024fc8d37b667dfb3f49f1335473885aac80b5535561686f210c6fdd
apps/graphcalc.app/main = 1e813d8398d87bc018dad3d68beb44bd707439eef79e6a7b22a5e0ac6d8174af
