# installed by tools/pkg/mkrepo.py
[package]
name = imageview
title = Image Viewer
version = 1.0.0
category = Graphics
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 71
config = 

[files]
apps/imageview.app/app.txt = e74fb113ff05d5d9fbb817ef6f7c59047edd19f2d9f1195fd9cc20162f6ba140
apps/imageview.app/icon.bmp = c7429fb4af7550946b598e713bdc48c660b45dcef4fead8511f0328094b4eb80
apps/imageview.app/main = 55bbd8c7fe612441c14ae3b32b0512ae1468fd08e1a872195e4ccc77899dfc78
