# installed by tools/pkg/mkrepo.py
[package]
name = invaders
title = Invaders
version = 1.0.23
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, audiokit >= 1.232, kapi >= 94
config = 

[files]
apps/invaders.app/app.txt = ddb51edc43dc66347c6bda03b4218e8e8874b2a5df7be2266ca9eb0b58232a80
apps/invaders.app/icon.bmp = 068d0bebe3387ee7e21e99eed7b5433a50da887b3f479198ea325dd76cfa0315
apps/invaders.app/main = d94dbc5fb5183d45c78a522c25ee6391627580fcba2a6a73fbbff91d90041397
