# installed by tools/pkg/mkrepo.py
[package]
name = letters
title = Letters
version = 1.0.20
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, cardfile, printerkit, imagekit >= 1.46, kapi >= 86
config = 
assoc = doc=letters rtf=letters docx=letters odt=letters

[files]
apps/letters.app/app.txt = b1a5f55c0db62bc4456299f4ae1741fd696aceac3edf84d2077ca948f4ae0b3f
apps/letters.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/letters.app/main = 6ed5759809158148d4b1e02be28c9e08acef132d3f42f1ff64b49c31dd187392
