# installed by tools/pkg/mkrepo.py
[package]
name = letters
title = Letters
version = 1.0.15
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, cardfile, print, kapi >= 84
config = 

[files]
apps/letters.app/app.txt = b1a5f55c0db62bc4456299f4ae1741fd696aceac3edf84d2077ca948f4ae0b3f
apps/letters.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/letters.app/main = ef06efdd1d6bd10d0bd2142c41229a35e57e5352553f881930805f2e7ce12284
