# installed by tools/pkg/mkrepo.py
[package]
name = letters
title = Letters
version = 1.0.27
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, cardfile, printerkit, imagekit >= 1.46, kapi >= 97
config = 
assoc = doc=letters rtf=letters docx=letters odt=letters

[files]
apps/letters.app/app.txt = b1a5f55c0db62bc4456299f4ae1741fd696aceac3edf84d2077ca948f4ae0b3f
apps/letters.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/letters.app/main = 78390a32af6fb0ccbc91d1f8987d1a17615d5702e14ec711a0b7df1a07d51af4
