# installed by tools/pkg/mkrepo.py
[package]
name = mandelbrot
title = Mandelbrot
version = 1.0.30
category = Graphics
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 97
config = 

[files]
apps/mandelbrot.app/app.txt = b89dff2627f822d78105ed44c7b1e1e96b0541a9c3a4fa25b83a814406cc68fa
apps/mandelbrot.app/icon.bmp = b26de29057bc5f2dd0202faf5d2d3119a0298092981772ccb76b9ddcdc5a51b3
apps/mandelbrot.app/main = f7ee1f75b765d84fff4c1539a22fe815e501256a8cba26f5a9f0e9ba1aceb24e
