# installed by tools/pkg/mkrepo.py
[package]
name = media
title = Media Player
version = 1.0.27
category = Multimedia
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.686, fontkit, generaluser-gs, audiokit >= 1.232, imagekit >= 1.46, kapi >= 88
config = 
assoc = mp3=media ogg=media oga=media flac=media wav=media mid=media midi=media kar=media rmi=media m3u=media m3u8=media webm=media mkv=media mp4=media m4v=media mov=media avi=media divx=media mpg=media mpeg=media vob=media ts=media m2ts=media mts=media flv=media wmv=media asf=media ogv=media 3gp=media

[files]
apps/media.app/app.txt = e3d967c49a1d055310bbac4c77b815f450112ee4dc4eb99ef83dbd5ca6561fd6
apps/media.app/icon.bmp = b25763764bc96b2a4d32d425860e4e3f4fad279dd3b2563f52fdb1c7f23ea027
apps/media.app/main = 4e797bf3837aa6bc54117e48b39e0f363eeda3abc7152b0ef701e5a3fe54424c
