# installed by tools/pkg/mkrepo.py
[package]
name = memmon
title = Memory Monitor
version = 1.0.9
category = System
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 78
config = 

[files]
apps/memmon.app/app.txt = fa8dad8d43b3244bc13f34cc07bf20be8848642dd3d6f9bc213640224283bcdd
apps/memmon.app/main = 8dcbe103959ea6b9515586d17fea20fc91a3d0092d5b472cf276c5fb80a2b3a0
