# installed by tools/pkg/mkrepo.py
[package]
name = memmon
title = Memory Monitor
version = 1.0.4
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 74
config = 

[files]
apps/memmon.app/app.txt = 43042f4cb275cd2d8391a9019e9a0c94481c4756e5fbfbb1dbc4591f5fda1955
apps/memmon.app/main = bb308ecd1335111b2855391c0cbb4e8c34bb1db0a26e8f61acc4d2aa2e482ac5
