# installed by tools/pkg/mkrepo.py
[package]
name = memmon
title = Memory Monitor
version = 1.0.2
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 72
config = 

[files]
apps/memmon.app/app.txt = 43042f4cb275cd2d8391a9019e9a0c94481c4756e5fbfbb1dbc4591f5fda1955
apps/memmon.app/main = 36d85d8e96c70e43a0ee0c6aa35073945b8d17d5018716b2866f276c16a55e29
