# installed by tools/pkg/mkrepo.py
[package]
name = minesweeper
title = Minesweeper
version = 1.0.15
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, kapi >= 86
config = 

[files]
apps/minesweeper.app/app.txt = b6b932d0df486a36ff44b2a752c2e4b764cbd375fb55127ad4d2cacf4e4251a7
apps/minesweeper.app/icon.bmp = 9aeaa1e6bcf8436ea88f62822a872039d006a74461fdaa6a73a1acd7eaa7e781
apps/minesweeper.app/main = 3eaa9b2bd0d4e72b931170683aaab8954a9b1864b9e22713574b5fbb16646c1a
