# installed by tools/pkg/mkrepo.py
[package]
name = minesweeper
title = Minesweeper
version = 1.0.21
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 94
config = 

[files]
apps/minesweeper.app/app.txt = b6b932d0df486a36ff44b2a752c2e4b764cbd375fb55127ad4d2cacf4e4251a7
apps/minesweeper.app/icon.bmp = 9aeaa1e6bcf8436ea88f62822a872039d006a74461fdaa6a73a1acd7eaa7e781
apps/minesweeper.app/main = cc06e848fbf015f737c6f42556dbc45b0246edbd7fec0890bf00e04edd67e05d
