# installed by tools/pkg/mkrepo.py
[package]
name = minesweeper
title = Minesweeper
version = 1.0.17
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, fontkit, kapi >= 87
config = 

[files]
apps/minesweeper.app/app.txt = b6b932d0df486a36ff44b2a752c2e4b764cbd375fb55127ad4d2cacf4e4251a7
apps/minesweeper.app/icon.bmp = 9aeaa1e6bcf8436ea88f62822a872039d006a74461fdaa6a73a1acd7eaa7e781
apps/minesweeper.app/main = d0964cd137fcd4e8c8a00a42a19bd72f4d80c8675c9a37ad51b8bf8000f9497d
