# installed by tools/pkg/mkrepo.py
[package]
name = nesemu
title = NES
version = 1.0.0
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = gamelib, kapi >= 71
config = 

[files]
apps/nesemu.app/app.txt = 2c8b25871a3abddb5390f4efa086ef794478d2a9b9bc699116566bdf36dd3054
apps/nesemu.app/icon.bmp = ef2a007b5d32cfab5180304527b4210c4f189b56c8e52f04d857651b779a096e
apps/nesemu.app/main = c3c2ffcc6790deb924ec804bde265aa5a17bea157f8ebcde2376e10b1f6bf1ce
