# installed by tools/pkg/mkrepo.py
[package]
name = pdf
title = PDF Viewer
version = 1.0.15
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, printerkit, kapi >= 85
config = 
assoc = pdf=pdf

[files]
apps/pdf.app/app.txt = 2c4d83a4afeedb837f790d274b7a930c6e6a9b8491239a1e21438d6972416fab
apps/pdf.app/icon.bmp = 0ff92880196cc48758c942f609f23a17c4097f34ef63c8f8ad0c6bd3faa96bb7
apps/pdf.app/main = 954cbefc5cc44fa47f682ae8d05b2d4b4ee2656ba1bcec09dd305fce7c34d1e5
