# installed by tools/pkg/mkrepo.py
[package]
name = pdf
title = PDF Viewer
version = 1.0.21
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, printerkit, kapi >= 92
config = 
assoc = pdf=pdf

[files]
apps/pdf.app/app.txt = 2c4d83a4afeedb837f790d274b7a930c6e6a9b8491239a1e21438d6972416fab
apps/pdf.app/icon.bmp = 0ff92880196cc48758c942f609f23a17c4097f34ef63c8f8ad0c6bd3faa96bb7
apps/pdf.app/main = 6ba1dda513da6c85f55ee90fd7b30e98d203ba830bb13c4276266ddac4858e3b
