# installed by tools/pkg/mkrepo.py
[package]
name = screenshot
title = Screenshot
version = 1.0.6
category = Graphics
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 78
config = 

[files]
apps/screenshot.app/app.txt = d762054db17213d605ec1e601babe1b665ae1cd0ab8d95c4e657c00e8359bc7e
apps/screenshot.app/icon.bmp = 9f2b56e64ad609fdf54331b3a8a395bbb635ef31a03a08ae76a2aa92970fe523
apps/screenshot.app/main = b49cd6e3090115b7d7419a309d2ec34e8ed899067ffeee16b62230e817b4e7d0
