# installed by tools/pkg/mkrepo.py
[package]
name = screenshot
title = Screenshot
version = 1.0.19
category = Graphics
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, imagekit >= 1.46, kapi >= 94
config = 

[files]
apps/screenshot.app/app.txt = d762054db17213d605ec1e601babe1b665ae1cd0ab8d95c4e657c00e8359bc7e
apps/screenshot.app/icon.bmp = 9f2b56e64ad609fdf54331b3a8a395bbb635ef31a03a08ae76a2aa92970fe523
apps/screenshot.app/main = c96cfe2eae9671fb4ddb33ef0cb5f39fe21c6fff6f33602313dc21b6e37e1e04
