# installed by tools/pkg/mkrepo.py
[package]
name = sheet
title = Spreadsheet
version = 1.0.16
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.683, ft, cardfile, printerkit, kapi >= 86
config = 
assoc = xlsx=sheet ods=sheet csv=sheet tsv=sheet

[files]
apps/sheet.app/app.txt = e2e7ab41f95e17766c022029cf255d9ac3c751e2b1482292fd0fd58f6dcede2d
apps/sheet.app/icon.bmp = 201c0d7b2aa57fa84d1246f83eaa167db5123c605be7dd2995c0264c1e687405
apps/sheet.app/main = d10412ab2dd85e08b16d507b1707e3b7591cb7f38ae48e285ecc102397508c2e
