# installed by tools/pkg/mkrepo.py
[package]
name = sheet
title = Spreadsheet
version = 1.0.6
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = cardfile, kapi >= 76
config = 

[files]
apps/sheet.app/app.txt = e2e7ab41f95e17766c022029cf255d9ac3c751e2b1482292fd0fd58f6dcede2d
apps/sheet.app/icon.bmp = 201c0d7b2aa57fa84d1246f83eaa167db5123c605be7dd2995c0264c1e687405
apps/sheet.app/main = 4ef27f5bb72b8a877199ae27f32c756e06e98875ba4d6e0ff594d2faedcda013
