# installed by tools/pkg/mkrepo.py
[package]
name = slides-samples
title = Slides samples
version = 1.0.0
category = Productivity
author = Onyx
summary = A presentation to try Slides with
mode = manual
required = 0
restart = 0
needs = slides, kapi >= 80
config = docs/cafe-2026.odp

[files]
docs/cafe-2026.odp = 1afd604cca5e5d8cb0621902fe794a0cd80cd028ce264262ff24ee6a3683462e
