# installed by tools/pkg/mkrepo.py
[package]
name = slides
title = Slides
version = 1.0.5
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 82
config = 

[files]
apps/slides.app/app.txt = face55f6fb78ccbcb39132a68fb3263663357a9039c125684ba3265661ea5d4f
apps/slides.app/icon.bmp = 3dee8862be5a2ac2717f576b5f94cff4f5ed1ae08c30d2cdedbd33de3bf90fbb
apps/slides.app/main = 950a42a5fa5fc03c287b20d40c8f3168940d6b371f6f5df63925bdb58cda6b61
