# installed by tools/pkg/mkrepo.py
[package]
name = slides-samples
title = Slides samples
version = 1.0.2
category = Productivity
author = Onyx
summary = A presentation to try Slides with (OpenDocument and PowerPoint)
mode = manual
required = 0
restart = 0
needs = slides, kapi >= 88
config = docs/cafe-2026.odp docs/cafe-2026.pptx

[files]
docs/cafe-2026.odp = ea5f58aee1b73aea16d09f734c1c97288ffc6758f488906cdb9c52d981ccce50
docs/cafe-2026.pptx = cac0b3dab47ce1bf3f5b5385a9f24b05e6c0b71f1d973ddaf98983fad4b990e6
