# installed by tools/pkg/mkrepo.py
[package]
name = slides
title = Slides
version = 1.0.18
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, printerkit, imagekit >= 1.46, kapi >= 94
config = 
assoc = odp=slides pptx=slides

[files]
apps/slides.app/app.txt = face55f6fb78ccbcb39132a68fb3263663357a9039c125684ba3265661ea5d4f
apps/slides.app/icon.bmp = 3dee8862be5a2ac2717f576b5f94cff4f5ed1ae08c30d2cdedbd33de3bf90fbb
apps/slides.app/main = d4c871a40a77eaa75ff05b8ceead0a6ecf6620210181b84036f1329f718185a1
