# installed by tools/pkg/mkrepo.py
[package]
name = snesemu
title = Super Nintendo
version = 1.0.0
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 71
config = 

[files]
apps/snesemu.app/app.txt = f3c27d33c9cbf859ad2abc57baba3ff9b3119a934fa2ed9d9046290130aecb68
apps/snesemu.app/icon.bmp = 420dd98f050d25df4e0a3eea619e37a391b327de11617308cb471cda093cd055
apps/snesemu.app/main = 1289a1e833aca212b36eb14bc6eff4b58bcf205b9268fcb93b1c69d29673fde2
