# installed by tools/pkg/mkrepo.py
[package]
name = snesemu
title = Super Nintendo
version = 1.0.5
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = gamelib, kapi >= 74
config = 

[files]
apps/snesemu.app/app.txt = f09261aba357f41b3a5a347054aafa37af4f1a4f6bc8fd468ea1fd400dd7eaba
apps/snesemu.app/icon.bmp = 420dd98f050d25df4e0a3eea619e37a391b327de11617308cb471cda093cd055
apps/snesemu.app/main = 89165e61c409efa16e9832eb2f350cff9b2370154a285f1beb2b949bd60458d5
