# installed by tools/pkg/mkrepo.py
[package]
name = snesemu
title = Super Nintendo
version = 1.0.41
category = Emulators
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, gamelib, audiokit >= 1.232, kapi >= 97
config = 

[files]
apps/snesemu.app/app.txt = e59ab69653dca3961085c528797a585706d6a63858543d7fcbbb53a898fd44d9
apps/snesemu.app/icon.bmp = 420dd98f050d25df4e0a3eea619e37a391b327de11617308cb471cda093cd055
apps/snesemu.app/main = 7880ea30adeac5ca41aa8d22d77dcfd6148adfaa693561269e1dff8cdedc9bb1
