# installed by tools/pkg/mkrepo.py
[package]
name = solitaire
title = Solitaire
version = 1.0.8
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 78
config = 

[files]
apps/solitaire.app/app.txt = 1625a682fa90bdfa08c1190d8e5df837b2844b45b5d7f7ef155f93b74ea707f7
apps/solitaire.app/icon.bmp = 936f02ab52a83cce45edcac4ce249a81c6e74697951edf17e72e73d384a9d3ec
apps/solitaire.app/main = fd948aaf2bbc00a21ea8c69a348fe845ac2bbca4c7e630a7df402d940809c0bf
