# installed by tools/pkg/mkrepo.py
[package]
name = solitaire
title = Solitaire
version = 1.0.9
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 78
config = 

[files]
apps/solitaire.app/app.txt = 1625a682fa90bdfa08c1190d8e5df837b2844b45b5d7f7ef155f93b74ea707f7
apps/solitaire.app/icon.bmp = 936f02ab52a83cce45edcac4ce249a81c6e74697951edf17e72e73d384a9d3ec
apps/solitaire.app/main = 796b08268edba88fc67eeda5abd24928e273e6f9516db20cc7cc5348eb371776
