# installed by tools/pkg/mkrepo.py
[package]
name = tetris
title = Tetris
version = 1.0.13
category = Games
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = wtk >= 1.683, ft, kapi >= 84
config = 

[files]
apps/tetris.app/app.txt = ada849f9e35cdacfe3e7345f5e59bafb260990677ac95d6b66c4b804da4f4b98
apps/tetris.app/icon.bmp = 22447b701d6de50994d497c8d9a448a79cb6d4fc2ce6d719da23b29dfebff301
apps/tetris.app/main = 0c280d02b1310ff43c47a5ab9fdb744c78f32eabf895239048ce0df8b2a12d5b
