# installed by tools/pkg/mkrepo.py
[package]
name = tinycalc
title = Calculator
version = 1.0.6
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 75
config = 

[files]
apps/tinycalc.app/app.txt = 92ff9d7982fe6dad2d8f98a2aa6cf3702ac2ac7a7206fd710aa46b7ab1520d98
apps/tinycalc.app/icon.bmp = 99a8ea3df7476338242badfe797a3323e4f3a3199f2788c2c323f60a34ada5f2
apps/tinycalc.app/main = c6ee079b4054b3f9c847abef7e5e3dfe306b445d716fa4df6c379868eb260136
