# installed by tools/pkg/mkrepo.py
[package]
name = tinypad
title = Text Editor
version = 1.0.0
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = kapi >= 71
config = 

[files]
apps/tinypad.app/app.txt = 72ad8f225e0967dcd19ee5d6d9404b4782771a105fd0d34ddb1201a4e5938e70
apps/tinypad.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/tinypad.app/main = d29f3fdc602d006d82d0c60363069f054d5f99e189d6f6ab9cf6b39da5e3f744
