# installed by tools/pkg/mkrepo.py
[package]
name = tinycalc
title = Calculator
version = 1.0.27
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = uikit >= 1.729, fontkit, kapi >= 97
config = 

[files]
apps/tinycalc.app/app.txt = 92ff9d7982fe6dad2d8f98a2aa6cf3702ac2ac7a7206fd710aa46b7ab1520d98
apps/tinycalc.app/icon.bmp = 99a8ea3df7476338242badfe797a3323e4f3a3199f2788c2c323f60a34ada5f2
apps/tinycalc.app/main = ff18f326ae1156ca7852d5a2b1a151a2afe347510faf1a283fc3b8644ebbf884
