# installed by tools/pkg/mkrepo.py
[package]
name = writer
title = Writer
version = 1.0.6
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = cardfile, kapi >= 74
config = 

[files]
apps/writer.app/app.txt = b3b41370e2a51b1bc9356cd484f6bd85f339b4cf77b2cd35cd1ee6de06656dfd
apps/writer.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/writer.app/main = 647342312bea3f543d806c641b4cb4cc20f7cbe522a336020dcfcb080988acac
