# installed by tools/pkg/mkrepo.py
[package]
name = writer
title = Letters
version = 1.0.10
category = Productivity
author = Onyx
summary = 
mode = manual
required = 0
restart = 0
needs = cardfile, kapi >= 80
config = 

[files]
apps/writer.app/app.txt = b1a5f55c0db62bc4456299f4ae1741fd696aceac3edf84d2077ca948f4ae0b3f
apps/writer.app/icon.bmp = 48548e1a29d9ecfdbc35bf7e0bcebfbe4f5d1d5a58f6efbec930fa70a0778d42
apps/writer.app/main = 346f36e28d9e04eabe665a39d3a61e2811994fb07d575aa6b89fe4b327d419df
