#!/usr/bin/env python3
#
# tools/telegram/mkschema.py -- the Telegram API's TL schema (tools/telegram/scheme/: api.tl and
# mtproto.tl, as Telegram Desktop ships them -- the layer is api.tl's last line) made into the
# compact text the Telegram app parses when it starts (user/Apps/telegram/schema.inc):
#
#   one line a combinator:  [F ]<id hex> <name> <param:type>... = <Result type>
#
# F marks a function. Comments, the built-in types (int, long, vector...), the generic "{X:Type}"
# and the combinators without an id (parsed by hand: message, msg_container, gzip_packed) are
# left out. Run it again after the schema files are replaced by a newer layer's.
#
#   python3 tools/telegram/mkschema.py
#
# MIT licence (docs/LICENSING.md).
import os, re, sys

here = os.path.dirname (os.path.abspath (__file__))
root = os.path.normpath (os.path.join (here, '..', '..'))
out_path = os.path.join (root, 'user', 'Apps', 'telegram', 'schema.inc')

def read (name):
	with open (os.path.join (here, 'scheme', name), encoding = 'utf-8') as f:
		return f.read ()

layer = None
lines = []
seen = set ()
for name in ('mtproto.tl', 'api.tl'):
	text = read (name)
	m = re.search (r'//\s*LAYER\s+(\d+)', text)
	if m: layer = int (m.group (1))
	fn = False
	for raw in text.split ('\n'):
		line = raw.strip ()
		if line.startswith ('---functions---'): fn = True; continue
		if line.startswith ('---types---'): fn = False; continue
		if not line or line.startswith ('//'): continue
		line = line.split ('//')[0].strip ()
		if not line.endswith (';'): continue
		line = line[:-1].strip ()
		m = re.match (r'^([A-Za-z_][\w.]*)#([0-9a-fA-F]+)\s*(.*?)\s*=\s*(.+)$', line)
		if not m: continue			# (no id: a built-in or parsed by hand)
		cname, cid, params, result = m.groups ()
		if cname in ('vector',): continue
		params = re.sub (r'\{[^}]*\}', '', params).split ()
		if any ('[' in p for p in params): continue
		cid = int (cid, 16)
		if cid in seen: continue
		seen.add (cid)
		lines.append (('F ' if fn else '') + '%08x %s%s = %s' % (cid, cname, ''.join (' ' + p for p in params), result.strip ()))

if layer is None: sys.exit ('mkschema: no "// LAYER n" in api.tl')

with open (out_path, 'w', encoding = 'utf-8', newline = '\n') as f:
	f.write ('// Generated by tools/telegram/mkschema.py from tools/telegram/scheme/*.tl -- do not edit.\n')
	f.write ('#define TL_LAYER %d\n' % layer)
	f.write ('static const char tl_schema_text[] =\n')
	for l in lines:
		f.write ('\t"%s\\n"\n' % l.replace ('\\', '\\\\').replace ('"', '\\"'))
	f.write (';\n')
print ('mkschema: layer %d, %d combinators -> %s' % (layer, len (lines), os.path.relpath (out_path, root)))
