# -*- coding: utf-8 -*-
"""Onyx web site -- the captures' alt texts (French, English), from the asset curator's assets.md.
Keyed by the capture's base name; build.py uses them wherever the capture is shown. MIT licence (ours)."""

ALTS = {
    'desktop': ("Le bureau d'Onyx : la barre de menus, les prochains rendez-vous sur le fond d'écran, une calculatrice, un terminal et le dock.",
        'The Onyx desktop: the menu bar, the next appointments on the wallpaper, a calculator, a terminal and the dock.'),
    'milk': ("Le thème clair Milk d'Onyx : le calendrier en vue semaine et une fenêtre présentant boutons, listes, curseurs et calendriers.",
        "Onyx in its light Milk theme: the calendar's week view and a window showing buttons, lists, sliders and date pickers."),
    'dock': ("Le dock d'Onyx avec le tiroir Jeux ouvert, listant quinze jeux, de 2048 à Tetris.",
        'The Onyx dock with its Games drawer open, listing fifteen games from 2048 to Tetris.'),
    'menubar': ("La barre de menus d'Onyx, le menu Fichier d'une application ouvert, avec le son, le Wi-Fi et l'heure à droite.",
        "The Onyx menu bar with an app's File menu open, and the sound, Wi-Fi and clock on the right."),
    'letters': ("Letters, le traitement de texte d'Onyx, affichant un document avec un titre, une image et une table des matières.",
        'Letters, the Onyx word processor, showing a document with a title, a picture and a table of contents.'),
    'sheet': ("Le tableur d'Onyx : un tableau de ventes mensuelles avec des barres de données et un graphique en colonnes.",
        'The Onyx spreadsheet: a monthly sales table with data bars and a column chart.'),
    'slides': ("Slides, l'application de présentations d'Onyx : la liste des diapositives, une diapositive avec un graphique et le panneau de mise en forme.",
        'Slides, the Onyx presentation app: the slide list, a slide with a chart and the formatting panel.'),
    'letters-table': ('Letters affichant une page de texte avec un tableau des formats de fichier pris en charge.',
        'Letters showing a page of text with a table of the file formats it reads and writes.'),
    'slides-show': ('Une présentation Slides en plein écran, pendant la transition entre la diapositive de titre et la suivante.',
        'A Slides presentation running full screen, caught during the transition from the title slide to the next one.'),
    'jet': ("Jet Browser, le navigateur d'Onyx, affichant un site web moderne au fond sombre avec son menu, un grand titre et une capture d'application.",
        'Jet Browser, the Onyx web browser, showing a modern dark-themed website with its menu, a large headline and an app screenshot.'),
    'pi-jet-programmez-window': ("Le bureau d'Onyx sur un Raspberry Pi, avec Jet Browser affichant le site d'un magazine de programmation.",
        "The Onyx desktop on a Raspberry Pi, with Jet Browser showing a programming magazine's website."),
    'mail': ("Mail, le courrier d'Onyx : les comptes à gauche, la liste des conversations et un message ouvert avec deux pièces jointes.",
        'Mail on Onyx: the accounts on the left, the conversation list and an open message with two attachments.'),
    'telegram': ('Telegram sur Onyx : la liste des conversations et une discussion avec une photo de montagne et des émoticônes.',
        'Telegram on Onyx: the conversation list and a chat with a mountain photo and emoticons.'),
    'paint': ("Paint, l'application de dessin d'Onyx : un paysage au coucher du soleil et le panneau des calques.",
        'Paint, the Onyx drawing app: a sunset landscape on the canvas and the layers panel.'),
    'koton': ("Koton, le studio de musique d'Onyx : cinq pistes colorées, la piste d'accords et l'éditeur d'accord avec son clavier.",
        'Koton, the Onyx music studio: five coloured tracks, the chord track and the chord editor with its keyboard.'),
    '3dforge': ("3DForge sur Onyx : une équerre percée en 3D sur une grille, avec ses mesures et l'historique des étapes.",
        '3DForge on Onyx: a 3D bracket with holes on a grid, with its measurements and the history of steps.'),
    'photos-edit': ("L'éditeur de Photos sur Onyx : une image de lac et de sapins avec les curseurs d'exposition, de contraste et de saturation.",
        'The Photos editor on Onyx: a lake-and-pines picture with the exposure, contrast and saturation sliders.'),
    'media-home': ("L'accueil du lecteur multimédia d'Onyx : un film à reprendre, les albums écoutés récemment et les vidéos.",
        "The Onyx Media Player's home page: a film to resume, recently played albums and videos."),
    'photos': ("La photothèque d'Onyx : les images rangées par jour, les albums dans la colonne de gauche.",
        'The Onyx photo library: pictures grouped by day, with the albums in the left column.'),
    'media-nowplaying': ("Le lecteur multimédia d'Onyx en cours de lecture : la pochette de l'album, le titre et la file d'attente.",
        "The Onyx Media Player's now-playing page: the album cover, the track title and the queue."),
    'media-watch': ("Le lecteur multimédia d'Onyx pendant un film : un coucher de soleil sur l'eau et les commandes de lecture.",
        'The Onyx Media Player playing a film: a sunset over water with the playback controls.'),
    'pinball-play': ("Le flipper d'Onyx, table Volcan : la bille près des bumpers, le score et les touches à droite.",
        'Onyx Pinball on the Volcano table: the ball near the bumpers, with the score and the keys on the right.'),
    'solitaire': ("Le Solitaire d'Onyx : sept colonnes de cartes sur un tapis vert en début de partie.",
        'Onyx Solitaire: seven columns of cards on green felt at the start of a game.'),
    'critters-play': ('Critters sur Onyx : de petites créatures orange traversent un terrain de sable vers la sortie, sous la barre des rôles.',
        'Critters on Onyx: little orange creatures cross sandy ground towards the exit, above the row of jobs.'),
    'tetris': ('Tetris sur Onyx : une pièce violette descend vers quatre rangées de blocs colorés, le score à droite.',
        'Tetris on Onyx: a purple piece falls towards four rows of coloured blocks, with the score on the right.'),
    'gamelib': ("La Ludothèque d'Onyx : les consoles dans la colonne de gauche et une vignette par jeu, classées par console.",
        'The Onyx Game Library: the consoles in the left column and one tile per game, sorted by console.'),
    'theme': ("Le réglage du thème d'Onyx : un aperçu des fenêtres, les ambiances Pêche, Acier, Sauge, Brique et Ardoise, et le choix du fond d'écran.",
        'The Onyx theme settings: a preview of the windows, the Peach, Steel, Sage, Brick and Slate schemes, and the wallpaper choice.'),
    'wallpapers': ("Les huit motifs de fond d'écran d'Onyx, en bleu, pêche, vert et violet.",
        'The eight Onyx wallpaper patterns, in blue, peach, green and purple tints.'),
    'pkgman': ("Le Gestionnaire de paquets d'Onyx, onglet Mises à jour, avant la première vérification.",
        'The Onyx Package Manager on its Updates tab, before the first check.'),
    'turtle': ('Turtle Quest sur Onyx : la liste des niveaux, un programme en BASIC et une tortue dans un labyrinthe.',
        'Turtle Quest on Onyx: the level list, a short program and a turtle finding its way through a maze.'),
    'turtle-fr': ('Turtle Quest en français : un programme REPETER / AVANCER et la tortue qui vient de tracer une étoile rouge à cinq branches.',
        'Turtle Quest in French: a REPETER / AVANCER program and the turtle that has just drawn a red five-pointed star.'),
    'circuits': ('Circuits sur Onyx : un additionneur complet fait de portes logiques, les fils allumés en vert et la table de vérité.',
        'Circuits on Onyx: a full adder built from logic gates, live wires lit in green, and the truth table.'),
    'gpiolab': ("GPIO Lab sur Onyx : les 40 broches du Raspberry Pi, les réglages d'une broche et un chronogramme de quatre signaux.",
        "GPIO Lab on Onyx: the Raspberry Pi's 40 pins, one pin's settings and a timing chart of four signals."),
    'media-albums': ("Les albums dans le lecteur multimédia d'Onyx : une grille de pochettes colorées et la barre de lecture.",
        'Albums in the Onyx Media Player: a grid of colourful covers above the playback bar.'),
    'calendar': ("Le calendrier d'Onyx en vue semaine : les rendez-vous colorés, les calendriers et la liste des tâches à gauche.",
        'The Onyx calendar in week view: colour-coded appointments, with the calendars and the task list on the left.'),
    'letters-merge': ("La fenêtre de publipostage de Letters : les champs d'un fichier Cardfile à insérer dans la lettre.",
        'The Mail Merge dialog in Letters: the fields of a Cardfile list, ready to insert into the letter.'),
    'ledger-print': ("Un devis créé par Ledger et ouvert dans le traitement de texte d'Onyx : le client, trois lignes de prestations et les totaux avec TVA.",
        'A quote made by Ledger and opened in the Onyx word processor: the client, three lines of services and the totals with VAT.'),
    'photos-menu': ("Le menu d'une photo dans Photos : l'ajouter aux favoris, l'envoyer par Mail, en faire le fond d'écran ou l'ouvrir dans Paint.",
        "A photo's menu in Photos: add it to the favourites, send it by Mail, set it as the wallpaper or open it in Paint."),
    'clock': ("Un clic sur l'heure dans la barre de menus d'Onyx ouvre le calendrier du mois.",
        "Clicking the time in the Onyx menu bar opens the month's calendar."),
    'volume': ("Le réglage du volume d'Onyx, ouvert depuis la barre de menus : un curseur et une case Muet.",
        'The Onyx volume control opened from the menu bar: a slider and a Mute box.'),
    'wifimenu': ("La liste des réseaux Wi-Fi d'Onyx, ouverte depuis la barre de menus, avec le réseau connecté en tête.",
        'The Onyx Wi-Fi list opened from the menu bar, with the connected network at the top.'),
    'usbmenu': ("Le menu USB d'Onyx : deux volumes d'une clé, un bouton pour l'éjecter et un accès à Disques.",
        "The Onyx USB menu: a stick's two volumes, an Eject button and a shortcut to Disks."),
    'menubar-tray': ("Une icône dans la barre de menus d'Onyx signale deux messages Telegram non lus.",
        'An icon in the Onyx menu bar reports two unread Telegram messages.'),
    'notes-desktop': ("Le bureau d'Onyx avec Notes ouvert, les prochains rendez-vous à gauche et trois notes épinglées à droite du fond d'écran.",
        'The Onyx desktop with Notes open, the next appointments on the left and three pinned notes on the right of the wallpaper.'),
    'agenda': ("Les prochains rendez-vous affichés sur le fond d'écran d'Onyx : dentiste, loyer, fête d'anniversaire.",
        'The next appointments shown on the Onyx wallpaper: dentist, rent, birthday party.'),
    'stickies': ("Trois notes épinglées sur le fond d'écran d'Onyx : une liste de tâches, une liste de courses et un pense-bête.",
        'Three notes pinned to the Onyx wallpaper: a to-do list, a shopping list and a reminder.'),
    'fileviewer': ("Le gestionnaire de fichiers d'Onyx : les dossiers en colonnes et, à droite, l'aperçu d'un fichier texte.",
        'The Onyx File Viewer: folders in columns and, on the right, a preview of a text file.'),
    'archiver': ("L'Archiveur d'Onyx : l'arborescence d'un fichier ZIP, ses fichiers avec leur taux de compression et les informations de l'archive.",
        "The Onyx Archiver: a ZIP file's folder tree, its files with their compression ratios and the archive's details."),
    'disks': ("Disques sur Onyx : la liste des volumes de la carte et de la clé USB, l'espace libre et les boutons Éjecter et Formater.",
        'Disks on Onyx: the volumes of the card and the USB stick, the free space, and the Eject and Format buttons.'),
    'setup-4': ("L'assistant d'installation d'Onyx, étape Apparence : un aperçu du bureau, les sept ambiances et le choix du fond d'écran et de sa teinte.",
        'Onyx Setup at its Appearance step: a preview of the desktop, the seven colour schemes and the wallpaper and tint pickers.'),
    'control': ("Le Panneau de configuration d'Onyx : douze réglages, du thème aux imprimantes, chacun avec son icône.",
        'The Onyx Control Panel: twelve settings, from the theme to the printers, each with its icon.'),
    'displayconf': ("Le réglage de l'écran d'Onyx : la liste des résolutions, de 1024 x 768 à 1920 x 1200.",
        'The Onyx display settings: the list of resolutions, from 1024 x 768 to 1920 x 1200.'),
    'soundconf': ("Le réglage du son d'Onyx : la sortie audio, le volume général et un bouton pour jouer un son d'essai.",
        'The Onyx sound settings: the audio output, the master volume and a button to play a test sound.'),
    'langconf': ("Le réglage Langue et région d'Onyx : le choix entre l'anglais et le français, et le fuseau horaire.",
        'The Onyx Language & Region settings: the choice between English and French, and the time zone.'),
    'letters-pdf': ('La fenêtre « Exporter en PDF » de Letters : le nom du fichier, les pages à exporter et les options.',
        'The "Export as PDF" dialog in Letters: the file name, the pages to export and the options.'),
    'sheet-pdf': ("La fenêtre « Exporter en PDF » du tableur d'Onyx : la feuille, l'orientation de la page et la mise à l'échelle.",
        'The "Export as PDF" dialog in the Onyx spreadsheet: the sheet, the page orientation and the fit-to-width option.'),
    'pkgman-available': ("Le Gestionnaire de paquets d'Onyx, onglet Disponibles, avant la première vérification.",
        'The Onyx Package Manager on its Available tab, before the first check.'),
    'pkgman-installed': ("Le Gestionnaire de paquets d'Onyx : les applications installées, chacune avec son choix de mise à jour — manuelle, automatique ou jamais.",
        'The Onyx Package Manager: the installed apps, each with its update choice — manual, automatic or never.'),
    'pkgman-restart': ("Le Gestionnaire de paquets d'Onyx propose une mise à jour du système, à installer en un clic et appliquée au redémarrage.",
        'The Onyx Package Manager offers a system update, installed in one click and applied at the next restart.'),
    'setup-0': ("L'écran d'accueil de l'assistant d'Onyx : le choix de la langue et les quatre réglages à venir.",
        'The welcome page of Onyx Setup: the language choice and the four settings to come.'),
    'setup-1': ("L'assistant d'Onyx, étape Région et clavier : le pays, la disposition du clavier, le fuseau horaire et une zone pour l'essayer.",
        'Onyx Setup at its Region & keyboard step: the country, the keyboard layout, the time zone and a field to try it.'),
    'setup-2': ("L'assistant d'Onyx, étape Wi-Fi : les réseaux à portée et le mot de passe du réseau choisi.",
        'Onyx Setup at its Wi-Fi step: the networks nearby and the password field of the chosen one.'),
    'setup-6': ("La dernière page de l'assistant d'Onyx : le résumé des réglages et le bouton pour démarrer Onyx.",
        'The last page of Onyx Setup: a summary of the settings and the button to start Onyx.'),
    'sheet-filter': ("Le tableur d'Onyx avec un filtre de colonne ouvert : tri croissant ou décroissant et la liste des mois à cocher.",
        'The Onyx spreadsheet with a column filter open: sort ascending or descending, and a checklist of months.'),
    'slides-sorter': ("La trieuse de Slides : les huit diapositives d'une présentation, rangées par sections, avec leur transition.",
        "The slide sorter in Slides: a presentation's eight slides, grouped in sections, each with its transition."),
    'slides-animate': ("Slides et son panneau d'animation : la transition de la diapositive et la liste de ses effets.",
        "Slides with its animation panel: the slide's transition and the list of its effects."),
    'slides-pptx': ('Slides affichant une présentation PowerPoint importée : une diapositive avec un graphique et le panneau des thèmes.',
        'Slides showing an imported PowerPoint presentation: a chart slide and the theme panel.'),
    'calendar-month': ("Le calendrier d'Onyx en vue mois : les rendez-vous de septembre, chacun à la couleur de son calendrier.",
        "The Onyx calendar in month view: September's appointments, each in its calendar's colour."),
    'calendar-day': ("Le calendrier d'Onyx en vue jour : quatre rendez-vous, du point d'équipe au dentiste.",
        'The Onyx calendar in day view: four appointments, from the team stand-up to the dentist.'),
    'calendar-event': ("La fiche d'un rendez-vous dans le calendrier d'Onyx : répétition chaque semaine, rappel 30 minutes avant, catégorie Sport.",
        "An appointment's form in the Onyx calendar: a weekly repeat, a reminder 30 minutes before, the Sport category."),
    'ledger': ('Le tableau de bord de Ledger sur Onyx : les montants à recevoir et à payer, un graphique des ventes et des achats, la prochaine déclaration de TVA.',
        'The Ledger dashboard on Onyx: amounts to receive and to pay, a chart of sales and purchases, the next VAT return.'),
    'ledger-invoice': ("Une facture de vente dans Ledger : le client, la ligne avec sa TVA, l'écriture comptable générée et le total à payer.",
        'A sales invoice in Ledger: the customer, a line with its VAT, the accounting entry it makes and the total to pay.'),
    'ledger-quote': ('Un devis dans Ledger : le client, trois lignes de prestations avec leur TVA et le total.',
        'A quote in Ledger: the customer, three lines of services with their VAT, and the total.'),
    'ledger-reports': ('Les rapports de Ledger : le grand livre, compte par compte, avec les soldes reportés.',
        "Ledger's reports: the general ledger, account by account, with the balances brought forward."),
    'ledger-vat': ('La déclaration de TVA dans Ledger : les quatre trimestres et les grilles de la déclaration belge remplies automatiquement.',
        'The VAT return in Ledger: the four quarters and the boxes of the Belgian return, filled in automatically.'),
    'cardfile': ("Cardfile sur Onyx en vue fiche : la fiche d'un livre avec son titre, son auteur, son genre et des notes.",
        "Cardfile on Onyx in form view: a book's card with its title, author, genre and notes."),
    'cardfile-list': ('Cardfile en vue liste : douze livres triés par titre, avec auteur, genre et année.',
        'Cardfile in list view: twelve books sorted by title, with author, genre and year.'),
    'cardfile-design': ("La vue Conception de Cardfile : les dix champs de la fiche, leur type et les choix d'une liste.",
        "Cardfile's Design view: the card's ten fields, their types and a choice list's entries."),
    'cardfile-merge': ('La fenêtre de publipostage de Cardfile : une lettre de Letters à remplir avec une fiche ou avec toutes.',
        "Cardfile's Mail Merge dialog: a Letters document to fill with one record or all of them."),
    'pdf': ("Le lecteur PDF d'Onyx : les miniatures des pages à gauche et une page du manuel de Ledger au centre.",
        'The Onyx PDF Viewer: page thumbnails on the left and a page of the Ledger manual in the centre.'),
    'pdf-contents': ("Le lecteur PDF d'Onyx : le sommaire du document à gauche, un passage sélectionné et le menu pour le copier ou le chercher dans Jet Browser.",
        "The Onyx PDF Viewer: the document's contents on the left, a selected passage and the menu to copy it or look it up in Jet Browser."),
    'pdf-find': ("La recherche dans le lecteur PDF d'Onyx : le mot cherché surligné dans la page et la liste des résultats par page.",
        'Search in the Onyx PDF Viewer: the word highlighted in the page and the results listed page by page.'),
    'pdf-home': ("L'accueil du lecteur PDF d'Onyx : les documents récents en vignettes, avec la page où vous vous étiez arrêté.",
        "The Onyx PDF Viewer's home page: recent documents as thumbnails, each with the page you stopped at."),
    'notes': ('Notes sur Onyx : la liste des notes à gauche et une liste de courses sur fond jaune, épinglée au bureau.',
        'Notes on Onyx: the list of notes on the left and a shopping list on a yellow page, pinned to the desktop.'),
    'tinypad': ("L'éditeur de texte d'Onyx avec un court fichier de notes.",
        'The Onyx text editor with a short file of notes.'),
    'tinycalc': ("La calculatrice scientifique d'Onyx : l'affichage et les touches sin, cos, tan, racine et puissances.",
        'The Onyx scientific calculator: the display and the sin, cos, tan, square-root and power keys.'),
    'graphcalc': ("La calculatrice graphique d'Onyx : une sinusoïde rouge et une parabole bleue tracées sur une grille.",
        'The Onyx Graphing Calculator: a red sine wave and a blue parabola plotted on a grid.'),
    'archiver-welcome': ("L'accueil de l'Archiveur d'Onyx : une zone où déposer une archive et les boutons pour en ouvrir ou en créer une.",
        "The Archiver's start page on Onyx: a zone to drop an archive on, and buttons to open or create one."),
    'archiver-extract': ("La fenêtre d'extraction de l'Archiveur d'Onyx : quoi extraire, vers quel dossier et que faire des fichiers existants.",
        'The Extract dialog of the Onyx Archiver: what to extract, to which folder, and what to do with existing files.'),
    'rtfview': ("Le lecteur RTF d'Onyx affichant un document d'essai avec du gras, des couleurs et plusieurs tailles de texte.",
        'The Onyx RTF Reader showing a sample document with bold, colours and several text sizes.'),
    'pi-jet-programmez': ("Jet Browser en plein écran sur un Raspberry Pi, affichant la page d'accueil d'un magazine de programmation.",
        'Jet Browser full screen on a Raspberry Pi, showing the home page of a programming magazine.'),
    'mail-thread': ('Une conversation dans Mail sur Onyx : cinq messages regroupés, le dernier ouvert, et un champ pour répondre.',
        'A conversation in Mail on Onyx: five messages grouped together, the last one open, and a quick-reply field.'),
    'mail-compose': ("La rédaction d'une réponse dans Mail sur Onyx : l'expéditeur, le destinataire, l'objet et le message cité.",
        'Writing a reply in Mail on Onyx: the sender, the recipient, the subject and the quoted message.'),
    'mail-contacts': ("Le carnet d'adresses de Mail sur Onyx : six contacts et la fiche de l'un d'eux, avec un bouton pour l'ouvrir dans Cardfile.",
        "The contacts in Mail on Onyx: six contacts and one contact's card, with a button to open it in Cardfile."),
    'mail-wizard': ("L'ajout d'un compte Gmail dans Mail sur Onyx : la saisie d'un mot de passe d'application.",
        'Adding a Gmail account in Mail on Onyx: the app-password step.'),
    'telegram-windows': ('Telegram sur Onyx : la liste des contacts dans une fenêtre et une conversation dans une autre, avec une photo et des émoticônes.',
        'Telegram on Onyx: the contact list in one window and a conversation in another, with a photo and emoticons.'),
    'telegram-group': ('Une discussion de groupe dans Telegram sur Onyx : trois messages et la liste des conversations à gauche.',
        'A group chat in Telegram on Onyx: three messages, with the conversation list on the left.'),
    'telegram-emoticons': ("Le sélecteur d'émoticônes de Telegram sur Onyx : trente-deux émoticônes dessinées, ouvertes au-dessus de la conversation.",
        'The emoticon picker in Telegram on Onyx: thirty-two hand-drawn emoticons, open over the conversation.'),
    'irc': ('IRC sur Onyx : les salons à gauche, la discussion du salon #onyx en bulles et la liste des participants.',
        "IRC on Onyx: the rooms on the left, the #onyx channel's chat in bubbles and the list of people."),
    'irc-rooms': ('La liste des salons IRC sur Onyx : quatorze salons, leur nombre de participants et leur sujet.',
        'The IRC room list on Onyx: fourteen rooms with their number of users and their topic.'),
    'irc-pm': ('Une conversation privée dans IRC sur Onyx, présentée en bulles comme une messagerie moderne.',
        'A private conversation in IRC on Onyx, shown in bubbles like a modern messenger.'),
    'paint-brushes': ("La galerie de pinceaux de Paint sur Onyx : crayon, pinceau, aérographe, marqueur, calligraphie et motifs, au-dessus d'un paysage de montagne.",
        'The brush gallery in Paint on Onyx: pencil, brush, airbrush, marker, calligraphy and patterns, over a mountain landscape.'),
    'paint-fade': ("Paint sur Onyx : deux paysages fondus l'un dans l'autre grâce à un masque en dégradé, avec les trois calques à droite.",
        'Paint on Onyx: two landscapes faded into each other through a gradient mask, with the three layers on the right.'),
    'paint-grid': ('Paint sur Onyx zoomé à 600 %, la grille des pixels affichée sur un dégradé orange.',
        'Paint on Onyx zoomed to 600 %, with the pixel grid shown over an orange gradient.'),
    'koton-drums': ("Koton sur Onyx : l'arrangement en haut et, en bas, la grille de batterie où l'on dessine le rythme.",
        'Koton on Onyx: the arrangement on top and, below, the drum grid where the groove is drawn.'),
    'koton-riff': ("Koton sur Onyx : l'arrangement et l'éditeur de riff, une grille où l'on dessine les notes de la mélodie.",
        "Koton on Onyx: the arrangement and the riff editor, a grid where the melody's notes are drawn."),
    'koton-accomp': ("Koton sur Onyx : l'arrangement et l'éditeur d'accompagnement, qui règle la façon de jouer les accords.",
        'Koton on Onyx: the arrangement and the accompaniment editor, which sets how the chords are played.'),
    'koton-rings': ("Koton sur Onyx : l'arrangement et l'éditeur de polyrythmie, trois anneaux de percussions dessinés en cercle.",
        'Koton on Onyx: the arrangement and the polyrhythm editor, three percussion rings drawn as a circle.'),
    '3dforge-sketch': ('Le mode esquisse de 3DForge sur Onyx : un rectangle, un cercle et une ligne cotée dessinés sur une face de la pièce.',
        'Sketch mode in 3DForge on Onyx: a rectangle, a circle and a dimensioned line drawn on a face of the part.'),
    '3dforge-fillet': ("3DForge sur Onyx arrondissant une arête de l'équerre : l'arête surlignée, son rayon de 4 mm et le panneau Congé.",
        '3DForge on Onyx rounding an edge of the bracket: the highlighted edge, its 4 mm radius and the Fillet panel.'),
    '3dforge-print': ("La préparation à l'impression 3D dans 3DForge : la pièce posée sur le plateau de l'imprimante et ses réglages de position.",
        "Getting ready to 3D print in 3DForge: the part on the printer's plate, with its position settings."),
    '3dforge-shapes': ('Le menu des formes de 3DForge sur Onyx : boîte, cylindre, sphère, tore, pyramide, prisme et cône tronqué.',
        'The Shapes menu in 3DForge on Onyx: box, cylinder, sphere, torus, pyramid, prism and taper.'),
    'screenshot-edit': ("L'outil Capture d'écran d'Onyx : une fenêtre capturée, annotée au surligneur et au crayon rouge.",
        'The Onyx Screenshot tool: a captured window, marked up with a highlighter and a red pen.'),
    'screenshot': ("La fenêtre d'accueil de l'outil Capture d'écran d'Onyx, qui invite à appuyer sur Impr. écran.",
        'The start window of the Onyx Screenshot tool, inviting you to press Print Screen.'),
    'screenshot-pen': ("L'outil Capture d'écran d'Onyx avec la palette du crayon ouverte : huit couleurs et quatre épaisseurs.",
        'The Onyx Screenshot tool with the pen palette open: eight colours and four widths.'),
    'iconedit': ("L'éditeur d'icônes d'Onyx : une grille de pixels où est dessiné un petit envahisseur bleu, avec les outils et la palette.",
        'The Onyx Icon Editor: a pixel grid with a small blue invader drawn on it, beside the tools and the palette.'),
    'fmtracker': ('FM Tracker sur Onyx : une grille de notes sur huit voies, la liste des motifs et un clavier de piano.',
        'FM Tracker on Onyx: a grid of notes on eight channels, the pattern list and a piano keyboard.'),
    'fmtracker-instrument': ("L'éditeur d'instrument de FM Tracker sur Onyx : deux opérateurs, leurs enveloppes et l'onde du son obtenu.",
        'The instrument editor of FM Tracker on Onyx: two operators, their envelopes and the resulting sound wave.'),
    'mandelbrot': ("L'ensemble de Mandelbrot affiché par Onyx, en noir sur fond bleu, avec ses franges colorées.",
        'The Mandelbrot set drawn by Onyx, black on blue, with its coloured fringes.'),
    'photos-viewer': ('La visionneuse de Photos sur Onyx : une image de montagnes, la bande de vignettes et le panneau des détails.',
        'The viewer in Photos on Onyx: a mountain picture, the filmstrip and the details panel.'),
    'photos-crop': ("Le recadrage dans Photos sur Onyx : un cadre 3:2 posé sur l'image, avec la rotation et le redressement.",
        'Cropping in Photos on Onyx: a 3:2 frame over the picture, with rotate and straighten controls.'),
    'photos-filters': ("Les filtres de Photos sur Onyx : six aperçus, de Noir et blanc à Éclatant, le filtre Chaud appliqué à l'image.",
        'The filters in Photos on Onyx: six previews, from Black and white to Vivid, with Warm applied to the picture.'),
    'photos-albums': ("Les albums de Photos sur Onyx : cinq albums présentés comme des piles de photos, avec leur nombre d'images.",
        'The albums in Photos on Onyx: five albums shown as stacks of pictures, each with its count.'),
    'media-videos': ("Les clips et séries dans le lecteur multimédia d'Onyx : six vidéos en vignettes, avec leur durée.",
        'Clips and series in the Onyx Media Player: six video thumbnails with their durations.'),
    'media-mini': ("Le mini-lecteur d'Onyx : la pochette, le titre du morceau et les trois boutons de lecture.",
        'The Onyx mini player: the cover, the track title and the three playback buttons.'),
    'imageview': ("La visionneuse d'images d'Onyx affichant un coucher de soleil sur des montagnes.",
        'The Onyx Image Viewer showing a sunset over mountains.'),
    'pinball': ("Le choix de la table dans le flipper d'Onyx : trois tables, un aperçu de la station spatiale et les meilleurs scores.",
        'Choosing a table in Onyx Pinball: three tables, a preview of the Space Station and the best scores.'),
    'pinball-multiball': ("Le flipper d'Onyx, table Station spatiale, en mode multibille : deux billes en jeu et le panneau des scores.",
        'Onyx Pinball on the Space Station table in multiball: two balls in play beside the score panel.'),
    'pinball-fr': ("Le choix de la table dans le flipper d'Onyx, en français : le Manoir hanté sélectionné, avec son aperçu et ses meilleurs scores.",
        'Choosing a table in Onyx Pinball, in French: the Haunted Manor selected, with its preview and best scores.'),
    'critters': ('Le choix du niveau dans Critters sur Onyx : douze niveaux en deux séries, un aperçu du terrain et les rôles disponibles.',
        'Choosing a level in Critters on Onyx: twelve levels in two sets, a preview of the ground and the jobs on offer.'),
    'critters-play-fr': ("Bestioles sur Onyx : la consigne d'un niveau — en sauver 8 sur 10 — au-dessus de la barre des rôles.",
        "Critters in French on Onyx: a level's briefing — save 8 out of 10 — above the row of jobs."),
    'critters-fr': ("Le choix du niveau dans Bestioles sur Onyx : les niveaux d'entraînement et d'expédition, avec un aperçu.",
        'The level chooser of Critters in French on Onyx: the training and expedition levels, with a preview.'),
    'freecell': ('FreeCell sur Onyx : huit colonnes de cartes visibles sur un tapis vert, la partie numéro 507.',
        'FreeCell on Onyx: eight columns of face-up cards on green felt, game number 507.'),
    'arkanoid': ("Le casse-briques d'Onyx : six rangées de briques colorées, la raquette et la balle.",
        'The Onyx brick breaker: six rows of coloured bricks, the paddle and the ball.'),
    'invaders': ("Invaders sur Onyx : cinq rangées d'envahisseurs en pixels, quatre boucliers verts et le canon du joueur.",
        "Invaders on Onyx: five rows of pixel aliens, four green shields and the player's cannon."),
    'pipes': ("Pipes sur Onyx en début de manche : une grille vide, la source d'eau et la file des tuyaux à poser.",
        'Pipes on Onyx at the start of a round: an empty grid, the water source and the queue of pipes to lay.'),
    '2048': ('2048 sur Onyx : une grille de quatre sur quatre avec des tuiles 2, 4 et 16.',
        '2048 on Onyx: a four-by-four board with 2, 4 and 16 tiles.'),
    'minesweeper': ("Le Démineur d'Onyx en cours de partie : des cases ouvertes avec leurs chiffres et un drapeau.",
        'Onyx Minesweeper mid-game: opened cells with their numbers and one flag.'),
    'sokoban': ('Sokoban sur Onyx : un petit niveau avec deux caisses à pousser vers leurs emplacements.',
        'Sokoban on Onyx: a small level with two crates to push onto their spots.'),
    'snake': ('Snake sur Onyx : un serpent vert de sept cases et une pomme rouge sur fond noir.',
        'Snake on Onyx: a seven-square green snake and a red apple on a black field.'),
    'same': ('SameGame sur Onyx : une grille pleine de carrés rouges, jaunes, verts et bleus à faire disparaître par groupes.',
        'SameGame on Onyx: a board full of red, yellow, green and blue squares to clear in groups.'),
    'pong': ('Pong sur Onyx : deux raquettes blanches, une balle verte et le score, 3 à 5.',
        'Pong on Onyx: two white paddles, a green ball and the score, 3 to 5.'),
    'life': ('Le Jeu de la vie sur Onyx : des cellules vertes en évolution sur un fond noir.',
        'The Game of Life on Onyx: green cells evolving on a black field.'),
    'turtle-fractal': ('Turtle Quest sur Onyx : un programme récursif et le flocon de Koch bleu que la tortue vient de tracer, avec trois étoiles.',
        'Turtle Quest on Onyx: a recursive program and the blue Koch snowflake the turtle has just drawn, with three stars.'),
    'turtle-rainbow': ("Turtle Quest sur Onyx : une boucle et la spirale carrée multicolore qu'elle dessine.",
        'Turtle Quest on Onyx: a loop and the multicoloured square spiral it draws.'),
    'turtle-portals': ("Turtle Quest sur Onyx : un niveau avec des gemmes, des portails, une clé et une porte à franchir jusqu'au drapeau.",
        'Turtle Quest on Onyx: a level with gems, portals, a key and a door to pass on the way to the flag.'),
    'turtle-fr-gems': ('Turtle Quest en français : un programme TANTQUE / SI et la tortue qui ramasse des gemmes numérotées dans un couloir.',
        'Turtle Quest in French: a TANTQUE / SI program and the turtle collecting numbered gems along a corridor.'),
    'circuits-step': ('Circuits sur Onyx en mode pas à pas : les portes numérotées par profondeur et une sortie encore inconnue.',
        'Circuits on Onyx in step mode: the gates numbered by depth and one output still unknown.'),
    'circuits-check': ('Circuits sur Onyx après vérification : la table de vérité signale une ligne fausse et explique pourquoi.',
        'Circuits on Onyx after a check: the truth table marks one wrong row and explains why.'),
    'circuits-fr': ('Circuits en français sur Onyx : un additionneur complet fait de portes ET, OU et OUX, avec sa table de vérité.',
        'Circuits in French on Onyx: a full adder built from ET, OU and OUX gates, with its truth table.'),
    'qbstudio': ('QBStudio sur Onyx : une fenêtre « convertisseur de température » en cours de dessin, la boîte à outils, le code et les propriétés du bouton.',
        'QBStudio on Onyx: a "Temperature converter" window being designed, with the toolbox, the code and the button\'s properties.'),
    'qbstudio-code': ("L'éditeur de code de QBStudio sur Onyx : le programme BASIC du convertisseur et une liste de complétion ouverte.",
        "The code editor of QBStudio on Onyx: the converter's BASIC program with a completion list open."),
    'basicdemo': ('Une petite application écrite en BASIC sur Onyx : des champs, un curseur et une cible de cercles bleus et jaunes.',
        'A small app written in BASIC on Onyx: fields, a slider and a target of blue and yellow rings.'),
    'gpiolab-code': ("L'onglet Code de GPIO Lab sur Onyx : un programme BASIC qui fait clignoter une LED et compte les appuis sur un bouton.",
        'The Code tab of GPIO Lab on Onyx: a BASIC program that blinks an LED and counts button presses.'),
    'courier': ('Courier sur Onyx : une requête POST avec son corps JSON et la réponse « 201 Created » mise en forme.',
        'Courier on Onyx: a POST request with its JSON body and the pretty-printed "201 Created" response.'),
    'courier-tests': ("Les tests d'une réponse dans Courier sur Onyx : deux vérifications réussies et une variable enregistrée.",
        "A response's tests in Courier on Onyx: two checks passed and one variable stored."),
    'filedialog': ("La fenêtre « Ouvrir un fichier » d'Onyx : les disques à gauche et la liste des dossiers.",
        'The Onyx "Open file" dialog: the drives on the left and the list of folders.'),
    'taskman': ("Le Gestionnaire des tâches d'Onyx : la liste de ce qui tourne, la mémoire utilisée par chacun et un bouton pour arrêter une tâche.",
        'The Onyx Task Manager: the list of what is running, the memory each one uses and a button to end a task.'),
    'taskman-memory': ("L'onglet Mémoire du Gestionnaire des tâches d'Onyx : la mémoire utilisée, libre, et sa répartition par application.",
        'The Memory tab of the Onyx Task Manager: memory in use, free, and its split by app.'),
    'terminal': ("Le Terminal d'Onyx : trois onglets et quelques commandes tapées, en blanc sur fond bleu-vert foncé.",
        'The Onyx Terminal: three tabs and a few typed commands, white on dark teal.'),
}
