//
// pcmn.h -- Ledger's default chart of accounts: the Belgian PCMN (French) / MAR (Dutch): its headings
// (classes, two- and three-digit groups) and the working accounts, six digits. Made by
// tools/ledger/gen_pcmn.py from tools/ledger/pcmn.tsv -- do not edit by hand.
//
#ifndef _ledger_pcmn_h
#define _ledger_pcmn_h

namespace lg {

struct PcmnRow { const char *code, *fr, *nl; };
static const PcmnRow PCMN[] = {
	{ "0", "Droits et engagements hors bilan", "Niet in de balans opgenomen rechten en verplichtingen" },
	{ "00", "Garanties constitu\xE9""es par des tiers pour compte de l'entreprise", "Zekerheden door derden gesteld voor rekening van de onderneming" },
	{ "000", "Cr\xE9""anciers de l'entreprise, b\xE9""n\xE9""ficiaires de garanties de tiers", "Crediteuren van de onderneming, houders van door derden gestelde zekerheden" },
	{ "001", "Tiers constituants de garanties pour compte de l'entreprise", "Derden, stellers van zekerheden gesteld voor rekening van de onderneming" },
	{ "01", "Garanties personnelles constitu\xE9""es pour compte de tiers", "Persoonlijke zekerheden gesteld voor rekening van derden" },
	{ "010", "D\xE9""biteurs pour engagements sur effets en circulation", "Debiteuren wegens verplichtingen uit wissels in omloop" },
	{ "011", "Cr\xE9""anciers d'engagements sur effets en circulation", "Crediteuren wegens verplichtingen uit wissels in omloop" },
	{ "012", "D\xE9""biteurs pour autres garanties personnelles", "Debiteuren wegens andere persoonlijke zekerheden" },
	{ "013", "Cr\xE9""anciers d'autres garanties personnelles", "Crediteuren wegens andere persoonlijke zekerheden" },
	{ "02", "Garanties r\xE9""elles constitu\xE9""es sur avoirs propres", "Zakelijke zekerheden gesteld op eigen activa" },
	{ "020", "Cr\xE9""anciers de l'entreprise, b\xE9""n\xE9""ficiaires de garanties r\xE9""elles", "Crediteuren van de onderneming, houders van zakelijke zekerheden" },
	{ "021", "Garanties r\xE9""elles constitu\xE9""es pour compte propre", "Zakelijke zekerheden gesteld voor eigen rekening" },
	{ "022", "Cr\xE9""anciers de tiers, b\xE9""n\xE9""ficiaires de garanties r\xE9""elles", "Crediteuren van derden, houders van zakelijke zekerheden" },
	{ "023", "Garanties r\xE9""elles constitu\xE9""es pour compte de tiers", "Zakelijke zekerheden gesteld voor rekening van derden" },
	{ "03", "Garanties re\xE7""ues", "Ontvangen zekerheden" },
	{ "030", "D\xE9""p\xF4""ts statutaires", "Statutaire bewaargevingen" },
	{ "031", "D\xE9""posants statutaires", "Statutaire bewaargevers" },
	{ "032", "Garanties re\xE7""ues", "Ontvangen zekerheden" },
	{ "033", "Constituant de garanties", "Zekerheidsstellers" },
	{ "04", "Biens et valeurs d\xE9""tenus par des tiers en leur nom mais aux risques et profits de l'entreprise", "Goederen en waarden gehouden door derden in hun naam, maar ten bate en voor risico van de onderneming" },
	{ "040", "Tiers, d\xE9""tenteurs en leur nom mais aux risques et profits de l'entreprise de biens et de valeurs", "Derden, houders in hun naam, maar ten bate en voor risico van de onderneming van goederen en waarden" },
	{ "041", "Biens et valeurs d\xE9""tenus par des tiers en leur nom mais aux risques et profits de l'entreprise", "Goederen en waarden gehouden door derden in hun naam, maar ten bate en voor risico van de onderneming" },
	{ "05", "Engagements d'acquisition et de cession d'immobilisations", "Verplichtingen tot aan- en verkoop van vaste activa" },
	{ "050", "Engagements d'acquisition", "Verplichtingen tot aankoop" },
	{ "051", "Cr\xE9""anciers d'engagements d'acquisition", "Crediteuren wegens verplichtingen tot aankoop" },
	{ "052", "D\xE9""biteurs pour engagements de cession", "Debiteuren wegens verplichtingen tot verkoop" },
	{ "053", "Engagements de cession", "Verplichtingen tot verkoop" },
	{ "06", "March\xE9""s \xE0"" terme", "Termijnovereenkomsten" },
	{ "060", "Marchandises achet\xE9""es \xE0"" terme - \xE0"" recevoir", "Op termijn gekochte goederen - te ontvangen" },
	{ "061", "Cr\xE9""anciers pour marchandises achet\xE9""es \xE0"" terme", "Crediteuren wegens op termijn gekochte goederen" },
	{ "062", "D\xE9""biteurs pour marchandises vendues \xE0"" terme", "Debiteuren wegens op termijn verkochte goederen" },
	{ "063", "Marchandises vendues \xE0"" terme - \xE0"" livrer", "Op termijn verkochte goederen - te leveren" },
	{ "064", "Devises achet\xE9""es \xE0"" terme - \xE0"" recevoir", "Op termijn gekochte deviezen - te ontvangen" },
	{ "065", "Cr\xE9""anciers pour devises achet\xE9""es \xE0"" terme", "Crediteuren wegens op termijn gekochte deviezen" },
	{ "066", "D\xE9""biteurs pour devises vendues \xE0"" terme", "Debiteuren wegens op termijn verkochte deviezen" },
	{ "067", "Devises vendues \xE0"" terme - \xE0"" livrer", "Op termijn verkochte deviezen - te leveren" },
	{ "07", "Biens et valeurs de tiers d\xE9""tenus par l'\xE9""tablissement", "Goederen en waarden van derden gehouden door de onderneming" },
	{ "070", "Droits d'usage \xE0"" long terme", "Gebruiksrechten op lange termijn" },
	{ "071", "Cr\xE9""anciers de loyers et redevances", "Crediteuren wegens huurgelden en vergoedingen" },
	{ "072", "Biens et valeurs de tiers re\xE7""us en d\xE9""p\xF4""t, en consignation ou \xE0"" fa\xE7""on", "Goederen en waarden door derden in bewaring, in consignatie of in bewerking gegeven" },
	{ "073", "Commettants et d\xE9""posants de biens et de valeurs", "Committenten en deponenten van goederen en waarden" },
	{ "074", "Biens et valeurs d\xE9""tenus pour compte ou aux risques et profits de tiers", "Goederen en waarden gehouden voor rekening of ten bate en voor risico van derden" },
	{ "075", "Cr\xE9""anciers de biens et valeurs d\xE9""tenus pour compte de tiers ou \xE0"" leurs risques et profits", "Crediteuren wegens goederen en waarden gehouden voor rekening of ten bate en voor risico van derden" },
	{ "09", "Droits et engagements divers", "Diverse rechten en verplichtingen" },
	{ "1", "Fonds propres, provisions pour risques et charges et dettes \xE0"" plus d'un an", "Eigen vermogen, voorzieningen voor risico's en kosten en schulden op meer dan \xE9""\xE9""n jaar" },
	{ "10", "Capital", "Kapitaal" },
	{ "100", "Capital souscrit", "Geplaatst kapitaal" },
	{ "100000", "Capital souscrit", "Geplaatst kapitaal" },
	{ "101", "Capital non appel\xE9"" (-)", "Niet opgevraagd kapitaal (-)" },
	{ "101000", "Capital non appel\xE9"" (-)", "Niet opgevraagd kapitaal (-)" },
	{ "11", "Apport hors capital", "Inbreng buiten kapitaal" },
	{ "110", "Apport disponible hors capital", "Beschikbare inbreng buiten kapitaal" },
	{ "110000", "Apport disponible hors capital - Prime d'\xE9""mission", "Beschikbare inbreng buiten kapitaal - Uitgiftepremie" },
	{ "110900", "Apport disponible hors capital - Autres", "Beschikbare inbreng buiten kapitaal - Andere" },
	{ "111", "Apport indisponible hors capital", "Onbeschikbare inbreng buiten kapitaal" },
	{ "111000", "Apport indisponible hors capital - Prime d'\xE9""mission", "Onbeschikbare inbreng buiten kapitaal - Uitgiftepremie" },
	{ "111900", "Apport indisponible hors capital - Autres", "Onbeschikbare inbreng buiten kapitaal - Andere" },
	{ "12", "Plus-values de r\xE9""\xE9""valuation", "Herwaarderingsmeerwaarden" },
	{ "120", "Plus-values de r\xE9""\xE9""valuation sur immobilisations incorporelles", "Herwaarderingsmeerwaarden op immateri\xEB""le vaste activa" },
	{ "120000", "Plus-values de r\xE9""\xE9""valuation sur immobilisations incorporelles", "Herwaarderingsmeerwaarden op immateri\xEB""le vaste activa" },
	{ "121", "Plus-values de r\xE9""\xE9""valuation sur immobilisations corporelles", "Herwaarderingsmeerwaarden op materi\xEB""le vaste activa" },
	{ "121000", "Plus-values de r\xE9""\xE9""valuation sur immobilisations corporelles", "Herwaarderingsmeerwaarden op materi\xEB""le vaste activa" },
	{ "122", "Plus-values de r\xE9""\xE9""valuation sur immobilisations financi\xE8""res", "Herwaarderingsmeerwaarden op financi\xEB""le vaste activa" },
	{ "122000", "Plus-values de r\xE9""\xE9""valuation sur immobilisations financi\xE8""res", "Herwaarderingsmeerwaarden op financi\xEB""le vaste activa" },
	{ "123", "Plus-values de r\xE9""\xE9""valuation sur stocks", "Herwaarderingsmeerwaarden op voorraden" },
	{ "123000", "Plus-values de r\xE9""\xE9""valuation sur stocks", "Herwaarderingsmeerwaarden op voorraden" },
	{ "124", "Reprises de r\xE9""ductions de valeur sur placements de tr\xE9""sorerie", "Terugneming van waardeverminderingen op geldbeleggingen" },
	{ "124000", "Reprises de r\xE9""ductions de valeur sur placements de tr\xE9""sorerie", "Terugneming van waardeverminderingen op geldbeleggingen" },
	{ "13", "R\xE9""serves", "Reserves" },
	{ "130", "R\xE9""serves l\xE9""gales", "Wettelijke reserves" },
	{ "130000", "R\xE9""serves l\xE9""gales", "Wettelijke reserves" },
	{ "131", "Autres r\xE9""serves indisponibles", "Andere onbeschikbare reserves" },
	{ "131100", "R\xE9""serves statutairement indisponibles", "Statutair onbeschikbare reserves" },
	{ "131200", "R\xE9""serve pour actions propres", "Reserve voor eigen aandelen" },
	{ "131300", "Soutien financier", "Financi\xEB""le steunverlening" },
	{ "131900", "Autres r\xE9""serves indisponibles", "Andere onbeschikbare reserves" },
	{ "132", "R\xE9""serves immunis\xE9""es", "Belastingvrije reserves" },
	{ "132000", "R\xE9""serves immunis\xE9""es", "Belastingvrije reserves" },
	{ "133", "R\xE9""serves disponibles", "Beschikbare reserves" },
	{ "133000", "R\xE9""serves disponibles", "Beschikbare reserves" },
	{ "14", "B\xE9""n\xE9""fice report\xE9"" ou perte report\xE9""e (-)", "Overgedragen winst of Overgedragen verlies (-)" },
	{ "140", "B\xE9""n\xE9""fice report\xE9""", "Overgedragen winst" },
	{ "140000", "B\xE9""n\xE9""fice report\xE9""", "Overgedragen winst" },
	{ "141", "Perte report\xE9""e (-)", "Overgedragen verlies (-)" },
	{ "141000", "Perte report\xE9""e (-)", "Overgedragen verlies (-)" },
	{ "149", "R\xE9""partition des profits et des pertes", "Winst-/verliesverdeling" },
	{ "149000", "R\xE9""partition des profits et des pertes", "Winst-/verliesverdeling" },
	{ "15", "Subsides en capital", "Kapitaalsubsidies" },
	{ "150000", "Subsides en capital", "Kapitaalsubsidies" },
	{ "16", "Provisions et imp\xF4""ts diff\xE9""r\xE9""s", "Voorzieningen en uitgestelde belastingen" },
	{ "160", "Provisions pour pensions et obligations similaires", "Voorzieningen voor pensioenen en soortgelijke verplichtingen" },
	{ "160000", "Provisions pour pensions et obligations similaires", "Voorzieningen voor pensioenen en soortgelijke verplichtingen" },
	{ "161", "Provisions pour charges fiscales", "Voorzieningen voor belastingen" },
	{ "161000", "Provisions pour charges fiscales", "Voorzieningen voor belastingen" },
	{ "162", "Provisions pour grosses r\xE9""parations et gros entretien", "Voorzieningen voor grote herstellingswerken en grote onderhoudswerken" },
	{ "162000", "Provisions pour grosses r\xE9""parations et gros entretien", "Voorzieningen voor grote herstellings- en onderhoudswerken" },
	{ "163", "Provisions pour obligations environnementales", "Voorzieningen voor milieuverplichtingen" },
	{ "163000", "Provisions pour obligations environnementales", "Voorzieningen voor milieuverplichtingen" },
	{ "164", "Provisions pour autres risques et charges", "Voorzieningen voor overige risico's en kosten" },
	{ "164000", "Provisions pour autres risques et charges", "Voorzieningen voor overige risico's en kosten" },
	{ "168", "Imp\xF4""ts diff\xE9""r\xE9""s", "Uitgestelde belastingen" },
	{ "168000", "Imp\xF4""ts diff\xE9""r\xE9""s aff\xE9""rents \xE0"" des subsides en capital", "Uitgestelde belastingen op kapitaalsubsidies" },
	{ "168100", "Imp\xF4""ts diff\xE9""r\xE9""s aff\xE9""rents \xE0"" des plus-values r\xE9""alis\xE9""es sur immobilisations incorporelles", "Uitgestelde belastingen op gerealiseerde meerwaarden op immateri\xEB""le vaste activa" },
	{ "168200", "Imp\xF4""ts diff\xE9""r\xE9""s aff\xE9""rents \xE0"" des plus-values r\xE9""alis\xE9""es sur immobilisations corporelles", "Uitgestelde belastingen op gerealiseerde meerwaarden op materi\xEB""le vaste activa" },
	{ "168700", "Imp\xF4""ts diff\xE9""r\xE9""s aff\xE9""rents \xE0"" des plus-values r\xE9""alis\xE9""es sur titres \xE9""mis par le secteur public belge", "Uitgestelde belastingen op gerealiseerde meerwaarden op effecten die zijn uitgegeven door de Belgische openbare sector" },
	{ "168800", "Imp\xF4""ts diff\xE9""r\xE9""s \xE9""trangers", "Buitenlandse uitgestelde belastingen" },
	{ "17", "Dettes \xE0"" plus d'un an", "Schulden op meer dan \xE9""\xE9""n jaar" },
	{ "170", "Emprunts subordonn\xE9""s", "Achtergestelde leningen" },
	{ "170000", "Emprunts subordonn\xE9""s - Convertibles (> 1 an)", "Achtergestelde leningen - Converteerbaar (> 1 jaar)" },
	{ "170100", "Emprunts subordonn\xE9""s - Non convertibles (> 1 an)", "Achtergestelde leningen - Niet converteerbaar (> 1 jaar)" },
	{ "171", "Emprunts obligataires non subordonn\xE9""s", "Niet-achtergestelde obligatieleningen" },
	{ "171000", "Emprunts obligataires non subordonn\xE9""s - Convertibles (> 1 an)", "Niet-achtergestelde obligatieleningen - Converteerbaar (> 1 jaar)" },
	{ "171100", "Emprunts obligataires non subordonn\xE9""s - Non convertibles (> 1 an)", "Niet-achtergestelde obligatieleningen - Niet converteerbaar (> 1 jaar)" },
	{ "172", "Dettes de location-financement et assimil\xE9""es", "Leasingschulden en soortgelijke schulden" },
	{ "172000", "Dettes de location-financement et assimil\xE9""es (> 1 an)", "Leasingschulden en soortgelijke schulden (> 1 jaar)" },
	{ "173", "\xC9""tablissements de cr\xE9""dit", "Kredietinstellingen" },
	{ "173000", "Etablissements de cr\xE9""dit - Dettes en compte (> 1 an)", "Kredietinstellingen - Schulden op rekening (> 1 jaar)" },
	{ "173100", "Etablissements de cr\xE9""dit - Promesses (> 1 an)", "Kredietinstellingen - Promessen (> 1 jaar)" },
	{ "173200", "Etablissements de cr\xE9""dit - Cr\xE9""dits d'acceptation (> 1 an)", "Kredietinstellingen - Acceptkredieten (> 1 jaar)" },
	{ "174", "Autres emprunts", "Overige leningen" },
	{ "174000", "Autres emprunts (> 1 an)", "Overige leningen (> 1 jaar)" },
	{ "175", "Dettes commerciales", "Handelsschulden" },
	{ "175000", "Fournisseurs (> 1 an)", "Leveranciers (> 1 jaar)" },
	{ "175100", "Effets \xE0"" payer (> 1 an)", "Te betalen wissels (> 1 jaar)" },
	{ "176", "Acomptes sur commandes", "Vooruitbetalingen op bestellingen" },
	{ "176000", "Acomptes sur commandes (> 1 an)", "Vooruitbetalingen op bestellingen (> 1 jaar)" },
	{ "178", "Cautionnements re\xE7""us en num\xE9""raire", "Borgtochten ontvangen in contanten" },
	{ "178000", "Cautionnements re\xE7""us en num\xE9""raire (> 1 an)", "Borgtochten ontvangen in contanten (> 1 jaar)" },
	{ "179", "Dettes diverses", "Overige schulden" },
	{ "179000", "Dettes diverses (> 1 an)", "Overige schulden (> 1 jaar)" },
	{ "19", "Acompte aux associ\xE9""s sur le partage de l'actif net (-)", "Voorschot aan de vennoten op de verdeling van het netto-actief (-)" },
	{ "190000", "Acompte aux associ\xE9""s sur le partage de l'actif net (-)", "Voorschot aan de vennoten op de verdeling van het netto-actief (-)" },
	{ "2", "Frais d'\xE9""tablissement, actifs immobilis\xE9""s et cr\xE9""ances \xE0"" plus d'un an", "Oprichtingskosten, vaste activa en vorderingen op meer dan \xE9""\xE9""n jaar" },
	{ "20", "Frais d'\xE9""tablissement", "Oprichtingskosten" },
	{ "200", "Frais de constitution, d'augmentation de capital ou d'augmentation de l'apport", "Kosten van oprichting, kapitaalverhoging of verhoging van de inbreng" },
	{ "200000", "Frais de constitution, d'augmentation de capital ou d'augmentation de l'apport", "Kosten van oprichting, kapitaalverhoging of verhoging van de inbreng" },
	{ "201", "Frais d'\xE9""mission d'emprunts", "Kosten bij uitgifte van leningen" },
	{ "201000", "Frais d'\xE9""mission d'emprunts", "Kosten bij uitgifte van leningen" },
	{ "202", "Autres frais d'\xE9""tablissement", "Overige oprichtingskosten" },
	{ "202000", "Autres frais d'\xE9""tablissement", "Overige oprichtingskosten" },
	{ "204", "Frais de restructuration", "Herstructureringskosten" },
	{ "204000", "Frais de restructuration", "Herstructureringskosten" },
	{ "21", "Immobilisations incorporelles", "Immateri\xEB""le vaste activa" },
	{ "210", "Frais de recherche et de d\xE9""veloppement", "Kosten van onderzoek en ontwikkeling" },
	{ "210000", "Frais de recherche et de d\xE9""veloppement - Valeur d'acquisition", "Kosten van onderzoek en ontwikkeling - Aanschaffingswaarde" },
	{ "210008", "Frais de recherche et de d\xE9""veloppement - Plus-values", "Kosten van onderzoek en ontwikkeling - Meerwaarden" },
	{ "210009", "Frais de recherche et de d\xE9""veloppement - Amortissements ou r\xE9""ductions de valeur (-)", "Kosten van onderzoek en ontwikkeling - Afschrijvingen of waardeverminderingen (-)" },
	{ "211", "Concessions, brevets, licences, savoir-faire, marques et droits similaires", "Concessies, octrooien, licenties, know-how, merken en soortgelijke rechten" },
	{ "211000", "Concessions, brevets, licences, savoir-faire, marques et droits similaires - Valeur d'acquisition", "Concessies, octrooien, licenties, know-how, merken en soortgelijke rechten - Aanschaffingswaarde" },
	{ "211008", "Concessions, brevets, licences, savoir-faire, marques et droits similaires - Plus-values", "Concessies, octrooien, licenties, know-how, merken en soortgelijke rechten - Meerwaarden" },
	{ "211009", "Concessions, brevets, licences, savoir-faire, marques et droits similaires - Amortissements ou r\xE9""ductions de valeur (-)", "Concessies, octrooien, licenties, know-how, merken en soortgelijke rechten - Afschrijvingen of waardeverminderingen (-)" },
	{ "212", "Goodwill", "Goodwill" },
	{ "212000", "Goodwill - Valeur d'acquisition", "Goodwill - Aanschaffingswaarde" },
	{ "212008", "Goodwill - Plus-values", "Goodwill - Meerwaarden" },
	{ "212009", "Goodwill - Amortissements ou r\xE9""ductions de valeur (-)", "Goodwill - Afschrijvingen of waardeverminderingen (-)" },
	{ "213", "Acomptes vers\xE9""s", "Vooruitbetalingen" },
	{ "213000", "Acomptes vers\xE9""s pour immobilisations incorporelles", "Vooruitbetalingen voor immateri\xEB""le vaste activa" },
	{ "215000", "Logiciels - Valeur d'acquisition", "Software - Aanschaffingswaarde" },
	{ "215008", "Logiciels - Plus-values", "Software - Meerwaarden" },
	{ "215009", "Logiciels - Amortissements ou r\xE9""ductions de valeur (-)", "Software - Afschrijvingen of waardeverminderingen (-)" },
	{ "22", "Terrains et constructions", "Terreinen en gebouwen" },
	{ "220", "Terrains", "Terreinen" },
	{ "220000", "Terrains - Valeur d'acquisition", "Terreinen - Aanschaffingswaarde" },
	{ "220008", "Terrains - Plus-values", "Terreinen - Meerwaarden" },
	{ "220009", "Terrains - Amortissements ou r\xE9""ductions de valeur (-)", "Terreinen - Afschrijvingen of waardeverminderingen (-)" },
	{ "221", "Constructions", "Gebouwen" },
	{ "221000", "Constructions - Valeur d'acquisition", "Gebouwen - Aanschaffingswaarde" },
	{ "221008", "Constructions - Plus-values", "Gebouwen - Meerwaarden" },
	{ "221009", "Constructions - Amortissements ou r\xE9""ductions de valeur (-)", "Gebouwen - Afschrijvingen of waardeverminderingen (-)" },
	{ "222", "Terrains b\xE2""tis", "Bebouwde terreinen" },
	{ "222000", "Terrains b\xE2""tis - Valeur d'acquisition", "Bebouwde terreinen - Aanschaffingswaarde" },
	{ "222008", "Terrains b\xE2""tis - Plus-values", "Bebouwde terreinen - Meerwaarden" },
	{ "222009", "Terrains b\xE2""tis - Amortissements ou r\xE9""ductions de valeur (-)", "Bebouwde terreinen - Afschrijvingen of waardeverminderingen (-)" },
	{ "223", "Autres droits r\xE9""els sur des immeubles", "Overige zakelijke rechten op onroerende goederen" },
	{ "223000", "Autres droits r\xE9""els sur des immeubles - Valeur d'acquisition", "Overige zakelijke rechten op onroerende goederen - Aanschaffingswaarde" },
	{ "223008", "Autres droits r\xE9""els sur des immeubles - Plus-values", "Overige zakelijke rechten op onroerende goederen - Meerwaarden" },
	{ "223009", "Autres droits r\xE9""els sur des immeubles - Amortissements ou r\xE9""ductions de valeur (-)", "Overige zakelijke rechten op onroerende goederen - Afschrijvingen of waardeverminderingen (-)" },
	{ "23", "Installations, machines et outillage", "Installaties, machines en uitrusting" },
	{ "230000", "Installations, machines et outillage - Valeur d'acquisition", "Installaties, machines en uitrusting - Aanschaffingswaarde" },
	{ "230008", "Installations, machines et outillage - Plus-values", "Installaties, machines en uitrusting - Meerwaarden" },
	{ "230009", "Installations, machines et outillage - Amortissements ou r\xE9""ductions de valeur (-)", "Installaties, machines en uitrusting - Afschrijvingen of waardeverminderingen (-)" },
	{ "24", "Mobilier et mat\xE9""riel roulant", "Meubilair en rollend materieel" },
	{ "240000", "Mobilier et mat\xE9""riel de bureau", "Kantoormeubilair en -uitrusting - Aanschaffingswaarde" },
	{ "240008", "Mobilier et mat\xE9""riel de bureau - Plus-values", "Kantoormeubilair en -uitrusting - Meerwaarden" },
	{ "240009", "Mobilier et mat\xE9""riel de bureau - Amortissements ou r\xE9""ductions de valeur (-)", "Kantoormeubilair en -uitrusting - Afschrijvingen of waardeverminderingen (-)" },
	{ "241000", "Voitures - Valeur d'acquisition", "Auto's - Aanschaffingswaarde" },
	{ "241001", "Voitures - Accessoires", "Auto's - Accessoires" },
	{ "241008", "Voitures - Plus-values", "Auto's - Meerwaarden" },
	{ "241009", "Voitures - Amortissements ou r\xE9""ductions de valeur (-)", "Auto's - Afschrijvingen of waardeverminderingen (-)" },
	{ "241100", "Motos - Valeur d'acquisition", "Motorfietsen - Aanschaffingswaarde" },
	{ "241101", "Motos - Accessoires", "Motorfietsen - Accessoires" },
	{ "241108", "Motos - Plus-values", "Motorfietsen - Meerwaarden" },
	{ "241109", "Motos - Amortissements ou r\xE9""ductions de valeur (-)", "Motorfietsen - Afschrijvingen of waardeverminderingen (-)" },
	{ "241200", "V\xE9""los - Valeur d'acquisition", "Fietsen - Aanschaffingswaarde" },
	{ "241201", "V\xE9""los - Accessoires", "Fietsen - Accessoires" },
	{ "241208", "V\xE9""los - Plus-values", "Fietsen - Meerwaarden" },
	{ "241209", "V\xE9""los - Amortissements ou r\xE9""ductions de valeur (-)", "Fietsen - Afschrijvingen of waardeverminderingen (-)" },
	{ "241300", "V\xE9""los \xE9""lectriques - Valeur d'acquisition", "Elektrische fietsen - Aanschaffingswaarde" },
	{ "241301", "V\xE9""los \xE9""lectriques - Accessoires", "Elektrische fietsen - Accessoires" },
	{ "241308", "V\xE9""los \xE9""lectriques - Plus-values", "Elektrische fietsen - Meerwaarden" },
	{ "241309", "V\xE9""los \xE9""lectriques - Amortissements ou r\xE9""ductions de valeur (-)", "Elektrische fietsen - Afschrijvingen of waardeverminderingen (-)" },
	{ "241400", "V\xE9""hicules utilitaires - Valeur d'acquisition", "Bedrijfsvoertuigen - Aanschaffingswaarde" },
	{ "241401", "V\xE9""hicules utilitaires - Accessoires", "Bedrijfsvoertuigen - Accessoires" },
	{ "241408", "V\xE9""hicules utilitaires - Plus-values", "Bedrijfsvoertuigen - Meerwaarden" },
	{ "241409", "V\xE9""hicules utilitaires - Amortissements ou r\xE9""ductions de valeur (-)", "Bedrijfsvoertuigen - Afschrijvingen of waardeverminderingen (-)" },
	{ "25", "Immobilisations d\xE9""tenues en location-financement et droits similaires", "Vaste activa in leasing of op grond van een soortgelijk recht" },
	{ "250", "Terrains et constructions", "Terreinen en gebouwen" },
	{ "250000", "Terrains et constructions en leasing financier - Valeur d'acquisition", "Terreinen en gebouwen in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "250008", "Terrains et constructions en leasing financier - Plus-values", "Terreinen en gebouwen in financi\xEB""le leasing - Meerwaarden" },
	{ "250009", "Terrains et constructions en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Terreinen en gebouwen in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "251", "Installations, machines et outillage", "Installaties, machines en uitrusting" },
	{ "251000", "Installations, machines et outillage en leasing financier - Valeur d'acquisition", "Installaties, machines en uitrusting in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "251008", "Installations, machines et outillage en leasing financier - Plus-values", "Installaties, machines en uitrusting in financi\xEB""le leasing - Meerwaarden" },
	{ "251009", "Installations, machines et outillage en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Installaties, machines en uitrusting in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "252", "Mobilier et mat\xE9""riel roulant", "Meubilair en rollend materieel" },
	{ "252000", "Voitures en leasing financier - Valeur d'acquisition", "Auto's in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "252008", "Voitures en leasing financier - Plus-values", "Auto's in financi\xEB""le leasing - Meerwaarden" },
	{ "252009", "Voitures en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Auto's in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "252100", "Motos en leasing financier - Valeur d'acquisition", "Motorfietsen in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "252108", "Motos en leasing financier - Plus-values", "Motorfietsen in financi\xEB""le leasing - Meerwaarden" },
	{ "252109", "Motos en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Motorfietsen in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "252200", "V\xE9""los en leasing financier - Valeur d'acquisition", "Fietsen in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "252208", "V\xE9""los en leasing financier - Plus-values", "Fietsen in financi\xEB""le leasing - Meerwaarden" },
	{ "252209", "V\xE9""los en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Fietsen in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "252300", "V\xE9""los \xE9""lectriques en leasing financier - Valeur d'acquisition", "Elektrische fietsen in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "252308", "V\xE9""los \xE9""lectriques en leasing financier - Plus-values", "Elektrische fietsen in financi\xEB""le leasing - Meerwaarden" },
	{ "252309", "V\xE9""los \xE9""lectriques en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Elektrische fietsen in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "252400", "V\xE9""hicules utilitaires en leasing financier - Valeur d'acquisition", "Bedrijfsvoertuigen in financi\xEB""le leasing - Aanschaffingswaarde" },
	{ "252408", "V\xE9""hicules utilitaires en leasing financier - Plus-values", "Bedrijfsvoertuigen in financi\xEB""le leasing - Meerwaarden" },
	{ "252409", "V\xE9""hicules utilitaires en leasing financier - Amortissements ou r\xE9""ductions de valeur (-)", "Bedrijfsvoertuigen in financi\xEB""le leasing - Afschrijvingen of waardeverminderingen (-)" },
	{ "26", "Autres immobilisations corporelles", "Overige materi\xEB""le vaste activa" },
	{ "260000", "Autres immobilisations corporelles - Valeur d'acquisition", "Overige materi\xEB""le vaste activa - Aanschaffingswaarde" },
	{ "260008", "Autres immobilisations corporelles - Plus-values", "Overige materi\xEB""le vaste activa - Meerwaarden" },
	{ "260009", "Autres immobilisations corporelles - Amortissements ou r\xE9""ductions de valeur (-)", "Overige materi\xEB""le vaste activa - Afschrijvingen of waardeverminderingen (-)" },
	{ "27", "Immobilisations corporelles en cours et acomptes vers\xE9""s", "Vaste activa in aanbouw en vooruitbetalingen" },
	{ "270000", "Immobilisations corporelles en cours et acomptes vers\xE9""s - Valeur d'acquisition", "Vaste activa in aanbouw en vooruitbetalingen - Aanschaffingswaarde" },
	{ "270008", "Immobilisations corporelles en cours et acomptes vers\xE9""s - Plus-values", "Vaste activa in aanbouw en vooruitbetalingen - Meerwaarden" },
	{ "270009", "Immobilisations corporelles en cours et acomptes vers\xE9""s - Amortissements ou r\xE9""ductions de valeur (-)", "Vaste activa in aanbouw en vooruitbetalingen - Afschrijvingen of waardeverminderingen (-)" },
	{ "28", "Immobilisations financi\xE8""res", "Financi\xEB""le vaste activa" },
	{ "280", "Participations dans des entreprises li\xE9""es", "Deelnemingen in verbonden ondernemingen" },
	{ "280000", "Participations dans des entreprises li\xE9""es - Valeur d'acquisition", "Deelnemingen in verbonden ondernemingen - Aanschaffingswaarde" },
	{ "280100", "Participations dans des entreprises li\xE9""es - Montants non appel\xE9""s (-)", "Deelnemingen in verbonden ondernemingen - Nog te storten bedragen (-)" },
	{ "280800", "Participations dans des entreprises li\xE9""es - Plus-values", "Deelnemingen in verbonden ondernemingen - Meerwaarden" },
	{ "280900", "Participations dans des entreprises li\xE9""es - R\xE9""ductions de valeur (-)", "Deelnemingen in verbonden vennootschappen - Waardeverminderingen (-)" },
	{ "281", "Cr\xE9""ances sur des entreprises li\xE9""es", "Vorderingen op verbonden ondernemingen" },
	{ "281000", "Cr\xE9""ances sur des entreprises li\xE9""es - Cr\xE9""ances en compte", "Vorderingen op verbonden ondernemingen - Vorderingen op rekening" },
	{ "281100", "Cr\xE9""ances sur des entreprises li\xE9""es - Effets \xE0"" recevoir", "Vorderingen op verbonden ondernemingen - Te innen wissels" },
	{ "281200", "Cr\xE9""ances sur des entreprises li\xE9""es - Titres \xE0"" revenu fixe", "Vorderingen op verbonden ondernemingen - Vastrentende effecten" },
	{ "281700", "Cr\xE9""ances sur des entreprises li\xE9""es - Cr\xE9""ances douteuses", "Vorderingen op verbonden ondernemingen - Dubieuze debiteuren" },
	{ "281900", "Cr\xE9""ances sur des entreprises li\xE9""es - R\xE9""ductions de valeur (-)", "Vorderingen op verbonden ondernemingen - Waardeverminderingen (-)" },
	{ "282", "Participations dans des entreprises avec lesquelles il existe un lien de participation", "Deelnemingen in ondernemingen waarmee een deelnemingsverhouding bestaat" },
	{ "282000", "Participations dans des entreprises avec lesquelles il existe un lien de participation - Valeur d'acquisition", "Deelnemingen in ondernemingen waarmee een deelnemingsverhouding bestaat - Aanschaffingswaarde" },
	{ "282100", "Participations dans des entreprises avec lesquelles il existe un lien de participation - Montants non appel\xE9""s (-)", "Deelnemingen in ondernemingen waarmee een deelnemingsverhouding bestaat - Nog te storten bedragen (-)" },
	{ "282800", "Participations dans des entreprises avec lesquelles il existe un lien de participation - Plus-values", "Deelnemingen in ondernemingen waarmee een deelnemingsverhouding bestaat - Meerwaarden" },
	{ "282900", "Participations dans des entreprises avec lesquelles il existe un lien de participation - R\xE9""ductions de valeur (-)", "Deelnemingen in ondernemingen waarmee een deelnemingsverhouding bestaat - Waardeverminderingen (-)" },
	{ "283", "Cr\xE9""ances sur des entreprises avec lesquelles il existe un lien de participation", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat" },
	{ "283000", "Cr\xE9""ances sur des entreprises avec lesquelles il existe un lien de participation - Cr\xE9""ances en compte", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat - Vorderingen op rekening" },
	{ "283100", "Cr\xE9""ances sur des entreprises avec lesquelles il existe un lien de participation - Effets \xE0"" recevoir", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat - Te innen wissels" },
	{ "283200", "Cr\xE9""ances sur des entreprises avec lesquelles il existe un lien de participation - Titres \xE0"" revenu fixe", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat - Vastrentende effecten" },
	{ "283700", "Cr\xE9""ances sur des entreprises avec lesquelles il existe un lien de participation - Cr\xE9""ances douteuses", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat - Dubieuze debiteuren" },
	{ "283900", "Cr\xE9""ances sur les entreprises avec lesquelles il existe un lien de participation - R\xE9""ductions de valeur (-)", "Vorderingen op ondernemingen waarmee een deelnemingsverhouding bestaat - Waardeverminderingen (-)" },
	{ "284", "Autres actions et parts", "Andere aandelen" },
	{ "284000", "Autres actions et parts - Valeur d'acquisition", "Andere aandelen - Aanschaffingswaarde" },
	{ "284100", "Autres actions et parts - Montants non appel\xE9""s (-)", "Andere aandelen - Nog te storten bedragen (-)" },
	{ "284800", "Autres actions et parts - Plus-values", "Andere aandelen - Meerwaarden" },
	{ "284900", "Autres actions et parts - R\xE9""ductions de valeur (-)", "Andere aandelen - Waardeverminderingen (-)" },
	{ "285", "Autres cr\xE9""ances", "Overige vorderingen" },
	{ "285000", "Autres cr\xE9""ances - Cr\xE9""ances en compte", "Overige vorderingen - Vorderingen op rekening" },
	{ "285100", "Autres cr\xE9""ances - Effets \xE0"" recevoir", "Overige vorderingen - Te innen wissels" },
	{ "285200", "Autres cr\xE9""ances - Titres \xE0"" revenu fixe", "Overige vorderingen - Vastrentende effecten" },
	{ "285700", "Autres cr\xE9""ances - Cr\xE9""ances douteuses", "Overige vorderingen - Dubieuze debiteuren" },
	{ "285900", "Autres cr\xE9""ances - R\xE9""ductions de valeur (-)", "Overige vorderingen - Waardeverminderingen (-)" },
	{ "288", "Cautionnements vers\xE9""s en num\xE9""raire", "Borgtochten betaald in contanten" },
	{ "288000", "Cautionnements vers\xE9""s en num\xE9""raire", "Borgtochten betaald in contanten" },
	{ "29", "Cr\xE9""ances \xE0"" plus d'un an", "Vorderingen op meer dan \xE9""\xE9""n jaar" },
	{ "290", "Cr\xE9""ances commerciales", "Handelsvorderingen" },
	{ "290000", "Clients (> 1 an)", "Klanten (> 1 jaar)" },
	{ "290100", "Cr\xE9""ances commerciales - Effets \xE0"" recevoir (> 1 an)", "Handelsvorderingen - Te innen wissels (> 1 jaar)" },
	{ "290600", "Cr\xE9""ances commerciales - Acomptes vers\xE9""s (> 1 an)", "Handelsvorderingen - Vooruitbetalingen (> 1 jaar)" },
	{ "290700", "Cr\xE9""ances commerciales - Cr\xE9""ances douteuses (> 1 an)", "Handelsvorderingen - Dubieuze debiteuren (> 1 jaar)" },
	{ "290900", "Cr\xE9""ances commerciales - R\xE9""ductions de valeur (> 1 an) (-)", "Handelsvorderingen - Waardeverminderingen (> 1 jaar) (-)" },
	{ "291", "Autres cr\xE9""ances", "Overige vorderingen" },
	{ "291000", "Cr\xE9""ances en compte (> 1 an)", "Vorderingen op rekening (> 1 jaar)" },
	{ "291100", "Autres cr\xE9""ances - Effets \xE0"" recevoir (> 1 an)", "Overige vorderingen - Te innen wissels (> 1 jaar)" },
	{ "291700", "Autres cr\xE9""ances - Cr\xE9""ances douteuses (> 1 an)", "Overige vorderingen - Dubieuze debiteuren (> 1 jaar)" },
	{ "291900", "Autres cr\xE9""ances - R\xE9""ductions de valeur (> 1 an) (-)", "Overige vorderingen - Waardeverminderingen (> 1 jaar) (-)" },
	{ "3", "Stocks et commandes en cours d'ex\xE9""cution", "Voorraden en bestellingen in uitvoering" },
	{ "30", "Mati\xE8""res premi\xE8""res", "Grondstoffen" },
	{ "300", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "300000", "Mati\xE8""res premi\xE8""res - Valeur d'acquisition", "Grondstoffen - Aanschaffingswaarde" },
	{ "309", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "309000", "Mati\xE8""res premi\xE8""res - R\xE9""ductions de valeur (-)", "Grondstoffen - Waardeverminderingen (-)" },
	{ "31", "Approvisionnements et fournitures", "Hulpstoffen" },
	{ "310", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "310000", "Approvisionnements et fournitures - Valeur d'acquisition", "Hulpstoffen - Aanschaffingswaarde" },
	{ "319", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waarde verminderingen (-)" },
	{ "319000", "Approvisionnements et fournitures - R\xE9""ductions de valeur (-)", "Hulpstoffen - Waardeverminderingen (-)" },
	{ "32", "En-cours de fabrication", "Goederen in bewerking" },
	{ "320", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "320000", "En-cours de fabrication - Valeur d'acquisition", "Goederen in bewerking - Aanschaffingswaarde" },
	{ "329", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "329000", "En-cours de fabrication - R\xE9""ductions de valeur (-)", "Goederen in bewerking - Waardeverminderingen (-)" },
	{ "33", "Produits finis", "Gereed product" },
	{ "330", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "330000", "Produits finis - Valeur d'acquisition", "Gereed product - Aanschaffingswaarde" },
	{ "339", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "339000", "Produits finis - R\xE9""ductions de valeur (-)", "Gereed product - Waardeverminderingen (-)" },
	{ "34", "Marchandises", "Handelsgoederen" },
	{ "340", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "340000", "Marchandises - Valeur d'acquisition", "Handelsgoederen - Aanschaffingswaarde" },
	{ "349", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "349000", "Marchandises - R\xE9""ductions de valeur (-)", "Handelsgoederen - Waardeverminderingen (-)" },
	{ "35", "Immeubles destin\xE9""s \xE0"" la vente", "Onroerende goederen bestemd voor verkoop" },
	{ "350", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "350000", "Immeubles destin\xE9""s \xE0"" la vente - Valeur d'acquisition", "Onroerende goederen bestemd voor verkoop - Aanschaffingswaarde" },
	{ "359", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "359000", "Immeubles destin\xE9""s \xE0"" la vente - R\xE9""ductions de valeur (-)", "Onroerende goederen bestemd voor verkoop - Waardeverminderingen (-)" },
	{ "36", "Acomptes vers\xE9""s sur achats pour stocks", "Vooruitbetalingen op voorraadinkopen" },
	{ "360", "Acomptes vers\xE9""s", "Vooruitbetalingen" },
	{ "360000", "Acomptes vers\xE9""s sur achats pour stocks - Acomptes vers\xE9""s", "Vooruitbetalingen op voorraadinkopen - Vooruitbetalingen" },
	{ "369", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "369000", "Acomptes vers\xE9""s sur achats pour stocks - R\xE9""ductions de valeur (-)", "Vooruitbetalingen op voorraadinkopen - Waardeverminderingen (-)" },
	{ "37", "Commandes en cours d'ex\xE9""cution", "Bestellingen in uitvoering" },
	{ "370", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "370000", "Commandes en cours d'ex\xE9""cution - Valeur d'acquisition", "Bestellingen in uitvoering - Aanschaffingswaarde" },
	{ "371", "B\xE9""n\xE9""fice pris en compte", "Toegerekende winst" },
	{ "371000", "Commandes en cours d'ex\xE9""cution - B\xE9""n\xE9""fice pris en compte", "Bestellingen in uitvoering - Toegerekende winst" },
	{ "379", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "379000", "Commandes en cours d'ex\xE9""cution - R\xE9""ductions de valeur (-)", "Bestellingen in uitvoering - Waardeverminderingen (-)" },
	{ "4", "Cr\xE9""ances et dettes \xE0"" un an au plus", "Vorderingen en schulden op ten hoogste \xE9""\xE9""n jaar" },
	{ "40", "Cr\xE9""ances commerciales", "Handelsvorderingen" },
	{ "400", "Clients", "Handelsdebiteuren" },
	{ "400000", "Clients", "Klanten" },
	{ "401", "Effets \xE0"" recevoir", "Te innen wissels" },
	{ "401000", "Cr\xE9""ances commerciales - Effets \xE0"" recevoir", "Handelsvorderingen - Te innen wissels" },
	{ "404", "Produits \xE0"" recevoir", "Te innen opbrengsten" },
	{ "404000", "Cr\xE9""ances commerciales - Produits \xE0"" recevoir", "Handelsvorderingen - Te innen opbrengsten" },
	{ "406", "Acomptes vers\xE9""s", "Vooruitbetalingen" },
	{ "406000", "Cr\xE9""ances commerciales - Acomptes vers\xE9""s", "Handelsvorderingen - Vooruitbetalingen" },
	{ "407", "Cr\xE9""ances douteuses", "Dubieuze debiteuren" },
	{ "407000", "Cr\xE9""ances commerciales - Cr\xE9""ances douteuses", "Handelsvorderingen - Dubieuze debiteuren" },
	{ "409", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "409000", "Cr\xE9""ances commerciales - R\xE9""ductions de valeur (-)", "Handelsvorderingen - Waardeverminderingen (-)" },
	{ "41", "Autres cr\xE9""ances", "Overige vorderingen" },
	{ "410", "Capital ou apport appel\xE9"", non vers\xE9""", "Opgevraagd, niet gestort kapitaal of inbreng" },
	{ "410000", "Capital ou apport appel\xE9"", non vers\xE9""", "Opgevraagd, niet gestort kapitaal of inbreng" },
	{ "411", "TVA \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen btw" },
	{ "411000", "TVA \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen btw" },
	{ "411200", "TVA \xE0"" r\xE9""cup\xE9""rer : Compte courant TVA (C/C)", "Terug te vorderen btw: Rekening-courant btw (RC)" },
	{ "411800", "Compte de provision TVA", "Provisierekening btw" },
	{ "412", "Imp\xF4""ts et pr\xE9""comptes \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen belastingen en voorheffingen" },
	{ "412000", "Imp\xF4""ts belges sur le r\xE9""sultat \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen Belgische winstbelastingen" },
	{ "412100", "Paiement anticip\xE9"" de l'imp\xF4""t", "Vooruitbetaling van belasting" },
	{ "412500", "Autres imp\xF4""ts et taxes belges \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen andere Belgische belastingen" },
	{ "412800", "Imp\xF4""ts et taxes \xE9""trangers \xE0"" r\xE9""cup\xE9""rer", "Terug te vorderen buitenlandse belastingen" },
	{ "414", "Produits \xE0"" recevoir", "Te innen opbrengsten" },
	{ "414000", "Produits \xE0"" recevoir", "Te innen opbrengsten" },
	{ "416", "Cr\xE9""ances diverses", "Diverse vorderingen" },
	{ "416000", "Cr\xE9""ances diverses", "Diverse vorderingen" },
	{ "417", "Cr\xE9""ances douteuses", "Dubieuze debiteuren" },
	{ "417000", "Cr\xE9""ances diverses - Cr\xE9""ances douteuses", "Overige vorderingen - Dubieuze debiteuren" },
	{ "418", "Cautionnements vers\xE9""s en num\xE9""raire", "Borgtochten betaald in contanten" },
	{ "418000", "Cr\xE9""ances diverses - Cautionnements vers\xE9""s en num\xE9""raire", "Overige vorderingen - Borgtochten betaald in contanten" },
	{ "419", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "419000", "Cr\xE9""ances diverses - R\xE9""ductions de valeur (-)", "Overige vorderingen - Waardeverminderingen (-)" },
	{ "42", "Dettes \xE0"" plus d'un an \xE9""ch\xE9""ant dans l'ann\xE9""e (m\xEA""me subdivision que le compte 17)", "Schulden op meer dan \xE9""\xE9""n jaar die binnen het jaar vervallen (zelfde onderverdeling als 17)" },
	{ "420", "Emprunts subordonn\xE9""s (> 1 an \xE9""cheant < 1 an)", "Achtergestelde leningen (> 1 jaar vervallend < 1 jaar)" },
	{ "420000", "Emprunts subordonn\xE9""s - Convertibles (> 1 an \xE9""cheant < 1 an)", "Achtergestelde leningen - Converteerbaar (> 1 jaar vervallend < 1 jaar)" },
	{ "420100", "Emprunts subordonn\xE9""s - Non convertibles (> 1 an \xE9""cheant < 1 an)", "Achtergestelde leningen - Niet converteerbaar (> 1 jaar vervallend < 1 jaar)" },
	{ "421", "Emprunts obligataires non subordonn\xE9""s (> 1 an \xE9""cheant < 1 an)", "Niet-achtergestelde obligatieleningen (> 1 jaar vervallend < 1 jaar)" },
	{ "421000", "Emprunts obligataires non subordonn\xE9""s - Convertibles (> 1 an \xE9""cheant < 1 an)", "Niet-achtergestelde obligatieleningen - Converteerbaar (> 1 jaar vervallend < 1 jaar)" },
	{ "421100", "Emprunts obligataires non subordonn\xE9""s - Non convertibles (> 1 an \xE9""cheant < 1 an)", "Niet-achtergestelde obligatieleningen - Niet converteerbaar (> 1 jaar vervallend < 1 jaar)" },
	{ "422", "Dettes de location-financement et dettes assimil\xE9""es (> 1 an \xE9""cheant < 1 an)", "Leasingschulden en soortgelijke schulden (> 1 jaar vervallend < 1 jaar)" },
	{ "422000", "Dettes de location-financement et dettes assimil\xE9""es (> 1 an \xE9""cheant < 1 an)", "Leasingschulden en soortgelijke schulden (> 1 jaar vervallend < 1 jaar)" },
	{ "423", "Etablissements de cr\xE9""dit (> 1 an \xE9""cheant < 1 an)", "Kredietinstellingen (> 1 jaar vervallend < 1 jaar)" },
	{ "423000", "Etablissements de cr\xE9""dit - Dettes en compte (> 1 an \xE9""cheant < 1 an)", "Kredietinstellingen - Schulden op rekening (> 1 jaar vervallend < 1 jaar)" },
	{ "423100", "Etablissements de cr\xE9""dit - Promesses (> 1 an \xE9""cheant < 1 an)", "Kredietinstellingen - Promessen (> 1 jaar vervallend < 1 jaar)" },
	{ "423200", "Etablissements de cr\xE9""dit - Cr\xE9""dits d'acceptation (> 1 an \xE9""cheant < 1 an)", "Kredietinstellingen - Acceptkredieten (> 1 jaar vervallend < 1 jaar)" },
	{ "424", "Autres emprunts (> 1 an \xE9""cheant < 1 an)", "Overige leningen (> 1 jaar vervallend < 1 jaar)" },
	{ "424000", "Autres emprunts (> 1 an \xE9""cheant < 1 an)", "Overige leningen (> 1 jaar vervallend < 1 jaar)" },
	{ "425", "Dettes commerciales (> 1 an \xE9""cheant < 1 an)", "Handelsschulden (> 1 jaar vervallend < 1 jaar)" },
	{ "425000", "Fournisseurs (> 1 an \xE9""cheant < 1 an)", "Leveranciers (> 1 jaar vervallend < 1 jaar)" },
	{ "425100", "Effets \xE0"" payer (> 1 an \xE9""cheant < 1 an)", "Te betalen wissels (> 1 jaar vervallend < 1 jaar)" },
	{ "426", "Acomptes sur commandes (> 1 an \xE9""cheant < 1 an)", "Vooruitbetalingen op bestellingen (> 1 jaar vervallend < 1 jaar)" },
	{ "426000", "Acomptes sur commandes (> 1 an \xE9""cheant < 1 an)", "Vooruitbetalingen op bestellingen (> 1 jaar vervallend < 1 jaar)" },
	{ "428", "Cautionnements re\xE7""us en num\xE9""raire (> 1 an \xE9""cheant < 1 an)", "Borgtochten ontvangen in contanten (> 1 jaar vervallend < 1 jaar)" },
	{ "428000", "Cautionnements re\xE7""us en num\xE9""raire (> 1 an \xE9""cheant < 1 an)", "Borgtochten ontvangen in contanten (> 1 jaar vervallend < 1 jaar)" },
	{ "429", "Autres dettes (> 1 an \xE9""cheant < 1 an)", "Overige schulden (> 1 jaar vervallend < 1 jaar)" },
	{ "429000", "Dettes diverses (> 1 an \xE9""cheant < 1 an)", "Overige schulden (> 1 jaar vervallend < 1 jaar)" },
	{ "43", "Dettes financi\xE8""res", "Financi\xEB""le schulden" },
	{ "430", "\xC9""tablissements de cr\xE9""dit - Emprunts en compte \xE0"" terme fixe", "Kredietinstellingen - Leningen op rekening met vaste termijn" },
	{ "430000", "Etablissements de cr\xE9""dit - Emprunts en compte \xE0"" terme fixe", "Kredietinstellingen - Leningen op rekening met vaste termijn" },
	{ "431", "\xC9""tablissements de cr\xE9""dit - Promesses", "Kredietinstellingen - Promessen" },
	{ "431000", "Etablissements de cr\xE9""dit - Promesses", "Kredietinstellingen - Promessen" },
	{ "432", "\xC9""tablissements de cr\xE9""dit - Cr\xE9""dits d'acceptation", "Kredietinstellingen - Acceptkredieten" },
	{ "432000", "Etablissements de cr\xE9""dit - Cr\xE9""dits d'acceptation", "Kredietinstellingen - Acceptkredieten" },
	{ "433", "\xC9""tablissements de cr\xE9""dit - Dettes en compte courant", "Kredietinstellingen - Schulden in rekening-courant" },
	{ "433000", "Etablissements de cr\xE9""dit - Dettes en compte courant", "Kredietinstellingen - Schulden in rekening-courant" },
	{ "439", "Autres emprunts", "Overige leningen" },
	{ "439000", "Autres emprunts", "Overige leningen" },
	{ "44", "Dettes commerciales", "Handelsschulden" },
	{ "440", "Fournisseurs", "Leveranciers" },
	{ "440000", "Fournisseurs", "Leveranciers" },
	{ "441", "Effets \xE0"" payer", "Te betalen wissels" },
	{ "441000", "Effets \xE0"" payer", "Te betalen wissels" },
	{ "444", "Factures \xE0"" recevoir", "Te ontvangen facturen" },
	{ "444000", "Factures \xE0"" recevoir", "Te ontvangen facturen" },
	{ "45", "Dettes fiscales, salariales et sociales", "Schulden met betrekking tot belastingen, bezoldigingen en sociale lasten" },
	{ "450", "Dettes fiscales estim\xE9""es", "Geraamd bedrag der belastingschulden" },
	{ "450000", "Dettes fiscales estim\xE9""es - Imp\xF4""ts belges sur le r\xE9""sultat", "Geraamd bedrag der belastingschulden - Belgische winstbelastingen" },
	{ "450500", "Dettes fiscales estim\xE9""es - Autres imp\xF4""ts et taxes belges", "Geraamd bedrag der belastingschulden - Andere Belgische belastingen en taksen" },
	{ "450800", "Dettes fiscales estim\xE9""es - Imp\xF4""ts et taxes \xE9""trangers", "Geraamd bedrag der belastingschulden - Buitenlandse belastingen en taksen" },
	{ "451", "TVA \xE0"" payer", "Te betalen btw" },
	{ "451000", "TVA \xE0"" payer", "Te betalen btw" },
	{ "451054", "TVA \xE0"" payer (Grille 54)", "Te betalen btw (Rooster 54)" },
	{ "451055", "TVA \xE0"" payer sur op\xE9""rations intracommunautaires (Grille 55)", "Te betalen btw op intracommunautaire verrichtingen (Rooster 55)" },
	{ "451056", "TVA \xE0"" payer sur op\xE9""rations co-contractant (Grille 56)", "Te betalen btw op verrichtingen medecontractant (Rooster 56)" },
	{ "451057", "TVA \xE0"" payer : Report de paiement sur importations (Grille 57)", "Te betalen btw: Uitgestelde betaling op invoer (Rooster 57)" },
	{ "451063", "TVA \xE0"" payer sur notes de cr\xE9""dit (Grille 63)", "Te betalen btw op creditnota's (Rooster 63)" },
	{ "451200", "TVA \xE0"" payer : Compte courant TVA (C/C)", "Te betalen btw: Rekening-courant btw (RC)" },
	{ "451800", "TVA \xE0"" payer - Taxation insuffisante", "Te betalen btw - Ontoereikende heffing" },
	{ "451820", "TVA \xE0"" payer - R\xE9""visions des d\xE9""ductions", "Te betalen btw - Herzieningen aftrek" },
	{ "451830", "TVA \xE0"" payer - R\xE9""gularisations", "Te betalen btw - Regularisaties" },
	{ "452", "Imp\xF4""ts et taxes \xE0"" payer", "Te betalen belastingen en taksen" },
	{ "452000", "Imp\xF4""ts belges \xE0"" payer sur le r\xE9""sultat", "Te betalen Belgische winstbelastingen" },
	{ "452100", "Paiement anticip\xE9"" de l'imp\xF4""t", "Vooruitbetaling van belasting" },
	{ "452500", "Autres imp\xF4""ts et taxes belges \xE0"" payer", "Andere te betalen Belgische belastingen en taksen" },
	{ "452800", "Imp\xF4""ts et taxes \xE9""trangers \xE0"" payer", "Te betalen buitenlandse belastingen en taksen" },
	{ "453", "Pr\xE9""comptes retenus", "Ingehouden voorheffingen" },
	{ "453000", "Pr\xE9""comptes retenus", "Ingehouden voorheffingen" },
	{ "454", "Office national de la S\xE9""curit\xE9"" sociale", "Rijksdienst voor Sociale Zekerheid" },
	{ "454000", "Office National de S\xE9""curit\xE9"" Sociale (ONSS)", "Rijksdienst voor Sociale Zekerheid (RSZ)" },
	{ "455", "R\xE9""mun\xE9""rations", "Bezoldigingen" },
	{ "455000", "R\xE9""mun\xE9""rations", "Bezoldigingen" },
	{ "456", "P\xE9""cules de vacances", "Vakantiegeld" },
	{ "456000", "P\xE9""cules de vacances", "Vakantiegeld" },
	{ "459", "Autres dettes sociales", "Andere sociale schulden" },
	{ "459000", "Autres dettes sociales", "Andere sociale schulden" },
	{ "46", "Acomptes sur commandes", "Vooruitbetalingen op bestellingen" },
	{ "460", "Acomptes sur commandes", "Vooruitbetalingen op bestellingen" },
	{ "460000", "Acomptes sur commandes", "Vooruitbetalingen op bestellingen" },
	{ "47", "Dettes d\xE9""coulant de l'affectation du r\xE9""sultat", "Schulden uit de bestemming van het resultaat" },
	{ "470", "Dividendes et tanti\xE8""mes d'exercices ant\xE9""rieurs", "Dividenden en tanti\xE8""mes over vorige boekjaren" },
	{ "470000", "Dividendes et tanti\xE8""mes d'exercices ant\xE9""rieurs", "Dividenden en tanti\xE8""mes over vorige boekjaren" },
	{ "471", "Dividendes de l'exercice", "Dividenden over het boekjaar" },
	{ "471000", "Dividendes de l'exercice", "Dividenden over het boekjaar" },
	{ "472", "Tanti\xE8""mes de l'exercice", "Tanti\xE8""mes over het boekjaar" },
	{ "472000", "Tanti\xE8""mes de l'exercice", "Tanti\xE8""mes over het boekjaar" },
	{ "473", "Autres allocataires", "Andere rechthebbenden" },
	{ "473000", "Autres allocataires", "Andere rechthebbenden" },
	{ "48", "Dettes diverses", "Diverse schulden" },
	{ "480", "Obligations et coupons \xE9""chus", "Vervallen obligaties en coupons" },
	{ "480000", "Obligations et coupons \xE9""chus", "Vervallen obligaties en coupons" },
	{ "488", "Cautionnements re\xE7""us en num\xE9""raire", "Borgtochten ontvangen in contanten" },
	{ "488000", "Cautionnements re\xE7""us en num\xE9""raire", "Borgtochten ontvangen in contanten" },
	{ "489", "Autres dettes diverses", "Andere diverse schulden" },
	{ "489000", "Autres dettes diverses", "Andere diverse schulden" },
	{ "49", "Comptes de r\xE9""gularisation et d'attente", "Overlopende rekeningen" },
	{ "490", "Charges \xE0"" reporter", "Over te dragen kosten" },
	{ "490000", "Charges \xE0"" reporter", "Over te dragen kosten" },
	{ "491", "Produits acquis", "Verkregen opbrengsten" },
	{ "491000", "Produits acquis", "Verkregen opbrengsten" },
	{ "492", "Charges \xE0"" imputer", "Toe te rekenen kosten" },
	{ "492000", "Charges \xE0"" imputer", "Toe te rekenen kosten" },
	{ "493", "Produits \xE0"" reporter", "Over te dragen opbrengsten" },
	{ "493000", "Produits \xE0"" reporter", "Over te dragen opbrengsten" },
	{ "499", "Comptes d'attente", "Wachtrekeningen" },
	{ "499000", "Comptes d'attente", "Wachtrekeningen" },
	{ "5", "Placements de tr\xE9""sorerie et valeurs disponibles", "Geldbeleggingen en liquide middelen" },
	{ "50", "Actions propres", "Eigen aandelen" },
	{ "500000", "Actions propres", "Eigen aandelen" },
	{ "51", "Actions, parts et placements de tr\xE9""sorerie autres que placements \xE0"" revenu fixe", "Aandelen en geldbeleggingen andere dan vastrentende beleggingen" },
	{ "510", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "510000", "Actions et parts - Valeur d'acquisition", "Aandelen - Aanschaffingswaarde" },
	{ "510100", "Placements de tr\xE9""sorerie autres que placements \xE0"" revenu fixe - Valeur d'acquisition", "Geldbeleggingen andere dan vastrentende beleggingen - Aanschaffingswaarde" },
	{ "511", "Montants non appel\xE9""s (-)", "Niet-opgevraagde bedragen (-)" },
	{ "511000", "Actions et parts - Montants non appel\xE9""s (-)", "Aandelen - Niet-opgevraagde bedragen (-)" },
	{ "519", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "519000", "Actions et parts - R\xE9""ductions de valeur act\xE9""es (-)", "Aandelen - Geboekte waardeverminderingen (-)" },
	{ "519100", "Placements de tr\xE9""sorerie autres que placements \xE0"" revenu fixe - R\xE9""ductions de valeur act\xE9""es (-)", "Geldbeleggingen andere dan vastrentende beleggingen - Geboekte waardeverminderingen (-)" },
	{ "52", "Titres \xE0"" revenu fixe", "Vastrentende effecten" },
	{ "520", "Valeur d'acquisition", "Aanschaffingswaarde" },
	{ "520000", "Titres \xE0"" revenu fixe - Valeur d'acquisition", "Vastrentende effecten - Aanschaffingswaarde" },
	{ "529", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "529000", "Titres \xE0"" revenu fixe - R\xE9""ductions de valeur (-)", "Vastrentende effecten - Waardeverminderingen (-)" },
	{ "53", "D\xE9""p\xF4""ts \xE0"" terme", "Termijndeposito's" },
	{ "530", "De plus d'un an", "Op meer dan een jaar" },
	{ "530000", "D\xE9""p\xF4""ts \xE0"" terme de plus d'un an", "Termijndeposito's op meer dan \xE9""\xE9""n jaar" },
	{ "531", "De plus d'un mois et \xE0"" un an au plus", "Op meer dan een maand en op ten hoogste een jaar" },
	{ "531000", "D\xE9""p\xF4""ts \xE0"" terme de plus d'un mois et \xE0"" un an au plus", "Termijndeposito's op meer dan \xE9""\xE9""n maand en hoogstens \xE9""\xE9""n jaar" },
	{ "532", "D'un mois au plus", "Op ten hoogste een maand" },
	{ "532000", "D\xE9""p\xF4""ts \xE0"" terme d'un mois au plus", "Termijndeposito's op hoogstens \xE9""\xE9""n maand" },
	{ "539", "R\xE9""ductions de valeur act\xE9""es (-)", "Geboekte waardeverminderingen (-)" },
	{ "539000", "D\xE9""p\xF4""ts \xE0"" terme - R\xE9""ductions de valeur (-)", "Termijndeposito's - Waardeverminderingen (-)" },
	{ "54", "Valeurs \xE9""chues \xE0"" l'encaissement", "Te incasseren vervallen waarden" },
	{ "540000", "Valeurs \xE9""chues \xE0"" l'encaissement", "Te incasseren vervallen waarden" },
	{ "55", "\xC9""tablissements de cr\xE9""dit", "Kredietinstellingen" },
	{ "550", "Etablissements de cr\xE9""dit", "Kredietinstellingen" },
	{ "550000", "Etablissements de cr\xE9""dit", "Kredietinstellingen" },
	{ "57", "Caisses", "Kassen" },
	{ "570", "Caisses - Esp\xE8""ces", "Kassen - Contanten" },
	{ "570000", "Caisses - Esp\xE8""ces", "Kassen - Contanten" },
	{ "578", "Caisses-timbres", "Kassen-zegels" },
	{ "578000", "Caisses - Timbres", "Kassen - Zegels" },
	{ "58", "Virements internes", "Interne overboekingen" },
	{ "580000", "Virements internes", "Interne overboekingen" },
	{ "6", "Charges", "Kosten" },
	{ "60", "Approvisionnements et marchandises", "Handelsgoederen, grond- en hulpstoffen" },
	{ "600", "Achats de mati\xE8""res premi\xE8""res", "Aankopen van grondstoffen" },
	{ "600000", "Mati\xE8""res premi\xE8""res", "Grondstoffen" },
	{ "601", "Achats de fournitures", "Aankopen van hulpstoffen" },
	{ "601000", "Fournitures", "Hulpstoffen" },
	{ "602", "Achats de services, travaux et \xE9""tudes", "Aankopen van diensten, werk en studies" },
	{ "602000", "Services, travaux et \xE9""tudes", "Diensten, werk en studies" },
	{ "603", "Sous-traitances g\xE9""n\xE9""rales", "Algemene onderaannemingen" },
	{ "603000", "Sous-traitances g\xE9""n\xE9""rales", "Algemene onderaannemingen" },
	{ "604", "Achats de marchandises", "Aankopen van handelsgoederen" },
	{ "604000", "Marchandises", "Handelsgoederen" },
	{ "605", "Achats d'immeubles destin\xE9""s \xE0"" la vente", "Aankopen van onroerende goederen bestemd voor verkoop" },
	{ "605000", "Achats d'immeubles destin\xE9""s \xE0"" la vente", "Aankopen van onroerende goederen bestemd voor verkoop" },
	{ "608", "Remises, ristournes et rabais (-)", "Ontvangen kortingen, ristorno's en rabatten (-)" },
	{ "608000", "Remises, ristournes et rabais (-)", "Ontvangen kortingen, ristorno's en rabatten (-)" },
	{ "609", "Variations des stocks", "Voorraadwijzigingen" },
	{ "609000", "Variations des stocks de mati\xE8""res premi\xE8""res", "Voorraadwijzigingen van grondstoffen" },
	{ "609100", "Variations des stocks de fournitures", "Voorraadwijzigingen van hulpstoffen" },
	{ "609400", "Variations des stocks de marchandises", "Voorraadwijzigingen van handelsgoederen" },
	{ "609500", "Variations des stocks d'immeubles achet\xE9""s destin\xE9""s \xE0"" la vente", "Voorraadwijzigingen van gekochte onroerende goederen bestemd voor verkoop" },
	{ "61", "Services et biens divers", "Diensten en diverse goederen" },
	{ "610000", "Loyers", "Huur" },
	{ "610100", "Location de machines, d'\xE9""quipements et de mat\xE9""riel", "Huurkosten machines, materieel en uitrusting" },
	{ "610200", "Location de voitures", "Huurkosten auto's" },
	{ "610201", "Location de motos", "Huurkosten motorfietsen" },
	{ "610202", "Location de v\xE9""los", "Huurkosten fietsen" },
	{ "610203", "Location de v\xE9""los \xE9""lectriques", "Huurkosten elektrische fietsen" },
	{ "610210", "Leasing financier de voitures", "Financi\xEB""le leasing van auto's" },
	{ "610211", "Leasing financier de motos", "Financi\xEB""le leasing van motorfietsen" },
	{ "610212", "Leasing financier de v\xE9""los", "Financi\xEB""le leasing van fietsen" },
	{ "610213", "Leasing financier de v\xE9""los \xE9""lectriques", "Financi\xEB""le leasing van elektrische fietsen" },
	{ "610220", "Leasing op\xE9""rationnel de voitures", "Operationele leasing van auto's" },
	{ "610221", "Leasing op\xE9""rationnel de motos", "Operationele leasing van motorfietsen" },
	{ "610222", "Leasing op\xE9""rationnel de v\xE9""los", "Operationele leasing van fietsen" },
	{ "610223", "Leasing op\xE9""rationnel de v\xE9""los \xE9""lectriques", "Operationele leasing van elektrische fietsen" },
	{ "610300", "Location de v\xE9""hicules utilitaires", "Huurkosten bedrijfsvoertuigen" },
	{ "610310", "Leasing financier de v\xE9""hicules utilitaires", "Financi\xEB""le leasing van bedrijfsvoertuigen" },
	{ "610320", "Leasing op\xE9""rationnel de v\xE9""hicules utilitaires", "Operationele leasing van bedrijfsvoertuigen" },
	{ "611", "Charges d'entretien et de r\xE9""paration", "Onderhoudskosten en herstellingen" },
	{ "611000", "Charges d'entretien et de r\xE9""paration", "Onderhoudskosten en herstellingen" },
	{ "611201", "Entretien des voitures", "Onderhoud van auto's" },
	{ "611202", "Entretien des motos", "Onderhoud van motorfietsen" },
	{ "611203", "Entretien des v\xE9""los", "Onderhoud van fietsen" },
	{ "611204", "Entretien des v\xE9""los \xE9""lectriques", "Onderhoud van elektrische fietsen" },
	{ "611300", "Entretien des v\xE9""hicules utilitaires", "Onderhoud van bedrijfsvoertuigen" },
	{ "612000", "Fournitures de bureau et impressions", "Kantoorbenodigdheden en drukwerk" },
	{ "612200", "Petit mat\xE9""riel", "Klein materiaal" },
	{ "612500", "Eau, \xE9""lectricit\xE9"" et gaz", "Water, elektriciteit en gas" },
	{ "612901", "Carburant pour voitures", "Brandstof voor auto's" },
	{ "612902", "Carburant pour motos", "Brandstof voor motorfietsen" },
	{ "612903", "Carburant pour v\xE9""hicules utilitaires", "Brandstof voor bedrijfsvoertuigen" },
	{ "612910", "\xC9""lectricit\xE9"" pour voitures", "Elektriciteit voor auto's" },
	{ "612911", "\xC9""lectricit\xE9"" pour motos", "Elektriciteit voor motorfietsen" },
	{ "612912", "\xC9""lectricit\xE9"" pour v\xE9""hicules utilitaires", "Elektriciteit voor bedrijfsvoertuigen" },
	{ "613200", "Experts-comptables ou conseillers fiscaux", "Accountants of belastingadviseurs" },
	{ "613250", "Frais juridiques", "Juridische kosten" },
	{ "613290", "Autres honoraires", "Andere erelonen" },
	{ "613310", "Logiciels et services informatiques", "Software en IT-diensten" },
	{ "613311", "Logiciels de facturation \xE9""lectronique", "Software voor e-facturatie" },
	{ "614000", "Assurance incendie", "Brandverzekering" },
	{ "614200", "Assurance revenu garanti", "Verzekering voor gewaarborgd inkomen" },
	{ "614400", "Assurance voitures", "Verzekering auto's" },
	{ "614410", "Assurance motos", "Verzekering motorfietsen" },
	{ "614420", "Assurance v\xE9""los \xE9""lectriques", "Verzekering elektrische fietsen" },
	{ "614430", "Assurance v\xE9""los", "Verzekering fietsen" },
	{ "614500", "Assurance v\xE9""hicules utilitaires", "Verzekering bedrijfsvoertuigen" },
	{ "614600", "Autres assurances professionnelles", "Andere beroepsverzekeringen" },
	{ "616200", "Internet et t\xE9""l\xE9""phone", "Internet en telefoon" },
	{ "616500", "Vols", "Vluchten" },
	{ "616501", "H\xF4""tels", "Hotels" },
	{ "616502", "Indemnit\xE9""s journali\xE8""res et r\xE9""mun\xE9""ration", "Dagvergoedingen" },
	{ "616503", "Transports en commun", "Openbaar vervoer" },
	{ "616505", "Autres frais de d\xE9""placement", "Overige verplaatsingskosten" },
	{ "616506", "Parking pour voitures", "Parking voor auto's" },
	{ "616507", "Parking pour motos", "Parking voor motorfietsen" },
	{ "616508", "Parking pour v\xE9""hicules utilitaires", "Parking voor bedrijfsvoertuigen" },
	{ "616510", "Taxi", "Taxi" },
	{ "616520", "Publicit\xE9"" et annonces", "Publiciteit en reclame" },
	{ "616530", "Salons et conf\xE9""rences", "Beurzen en conferenties" },
	{ "616540", "Cadeaux d'affaires (<= 50 \x80"")", "Relatiegeschenken (<= \x80"" 50)" },
	{ "616541", "Cadeaux d'affaires (> 50 \x80"")", "Relatiegeschenken (> \x80"" 50)" },
	{ "616550", "Cotisations professionnelles", "Beroepsbijdragen en lidgelden" },
	{ "616580", "Restaurants et bars", "Restaurants en bars" },
	{ "617", "Personnel int\xE9""rimaire et personnes mises \xE0"" la disposition de l'entreprise", "Uitzendkrachten en personen ter beschikking gesteld van de onderneming" },
	{ "617000", "Personnel int\xE9""rimaire et personnes mises \xE0"" la disposition de l'entreprise", "Uitzendkrachten en personen ter beschikking gesteld van de onderneming" },
	{ "618", "R\xE9""mun\xE9""rations, primes pour assurances extral\xE9""gales, pensions de retraite et de survie des administrateurs, g\xE9""rants et...", "Bezoldigingen, premies voor buitenwettelijke verzekeringen, ouderdoms- en overlevingspensioenen van bestuurders..." },
	{ "618000", "R\xE9""mun\xE9""rations, primes pour assurances extral\xE9""gales, pensions de retraite et de survie des administrateurs, g\xE9""rants et...", "Bezoldigingen, premies voor buitenwettelijke verzekeringen, ouderdoms- en overlevingspensioenen van bestuurders..." },
	{ "62", "R\xE9""mun\xE9""rations, charges sociales et pensions", "Bezoldigingen, sociale lasten en pensioenen" },
	{ "620", "R\xE9""mun\xE9""rations et avantages sociaux directs", "Bezoldigingen en rechtstreekse sociale voordelen" },
	{ "620000", "R\xE9""mun\xE9""rations des administrateurs ou g\xE9""rants", "Bezoldigingen bestuurders of zaakvoerder" },
	{ "620100", "R\xE9""mun\xE9""rations du personnel de direction", "Bezoldigingen directiepersoneel" },
	{ "620200", "R\xE9""mun\xE9""rations des employ\xE9""s", "Bezoldigingen bedienden" },
	{ "620300", "R\xE9""mun\xE9""rations des ouvriers", "Bezoldigingen arbeiders" },
	{ "620400", "R\xE9""mun\xE9""rations des autres membres du personnel", "Bezoldigingen andere personeelsleden" },
	{ "621", "Cotisations patronales pour assurances sociales", "Werkgeversbijdragen voor sociale verzekeringen" },
	{ "621000", "Cotisations patronales ONSS", "Werkgeversbijdragen RSZ" },
	{ "622", "Primes patronales pour assurances extra-l\xE9""gales", "Werkgeverspremies voor bovenwettelijke verzekeringen" },
	{ "622000", "Primes patronales pour assurances extra-l\xE9""gales", "Werkgeverspremies voor bovenwettelijke verzekeringen" },
	{ "623", "Autres frais du personnel", "Andere personeelskosten" },
	{ "623000", "Autres frais de personnel", "Overige personeelskosten" },
	{ "623401", "Nourriture et boissons pour le personnel", "Eten en drinken voor personeel" },
	{ "623600", "Frais de formation", "Opleidingskosten" },
	{ "623610", "Frais de formation (nourriture et boissons incluses)", "Opleidingskosten (incl. eten en drinken)" },
	{ "623700", "Ch\xE8""ques-repas", "Maaltijdcheques" },
	{ "624", "Pensions de retraite et de survie", "Ouderdoms- en overlevingspensioenen" },
	{ "624000", "Pensions des administrateurs ou g\xE9""rants", "Pensioenen voor bestuurders of zaakvoerders" },
	{ "624100", "Pensions du personnel", "Pensioenen voor personeel" },
	{ "63", "Amortissements, r\xE9""ductions de valeur et provisions pour risques", "Afschrijvingen, waardeverminderingen en voorzieningen voor risico's" },
	{ "630", "Dotations aux amortissements et aux r\xE9""ductions de valeur sur immobilisations", "Afschrijvingen en waardeverminderingen op vaste activa-toevoeging" },
	{ "630000", "Dotations aux amortissements sur frais d'\xE9""tablissement", "Afschrijvingen op oprichtingskosten" },
	{ "630100", "Dotations aux amortissements sur immobilisations incorporelles", "Afschrijvingen op immateri\xEB""le vaste activa" },
	{ "630200", "Dotations aux amortissements sur immobilisations corporelles", "Afschrijvingen op materi\xEB""le vaste activa" },
	{ "630800", "Dotations aux r\xE9""ductions de valeur sur immobilisations incorporelles", "Waardeverminderingen op immateri\xEB""le vaste activa" },
	{ "630900", "Dotations aux r\xE9""ductions de valeur sur immobilisations corporelles", "Waardeverminderingen op materi\xEB""le vaste activa" },
	{ "631", "R\xE9""ductions de valeur sur stocks", "Waardeverminderingen op voorraden" },
	{ "631000", "R\xE9""ductions de valeur sur stocks - Dotations", "Waardeverminderingen op voorraden - Toevoegingen" },
	{ "631100", "R\xE9""ductions de valeur sur stocks - Reprises (-)", "Waardeverminderingen op voorraden - Terugnemingen (-)" },
	{ "632", "R\xE9""ductions de valeur sur commandes en cours d'ex\xE9""cution", "Waardeverminderingen op bestellingen in uitvoering" },
	{ "632000", "R\xE9""ductions de valeur sur commandes en cours d'ex\xE9""cution - Dotations", "Waardeverminderingen op bestellingen in uitvoering - Toevoegingen" },
	{ "632100", "R\xE9""ductions de valeur sur commandes en cours d'ex\xE9""cution - Reprises (-)", "Waardeverminderingen op bestellingen in uitvoering - Terugnemingen (-)" },
	{ "633", "R\xE9""ductions de valeur sur cr\xE9""ances commerciales \xE0"" plus d'un an", "Waardeverminderingen op handelsvorderingen op meer dan een jaar" },
	{ "633000", "R\xE9""ductions de valeur sur cr\xE9""ances commerciales (> 1 an) - Dotations", "Waardeverminderingen op handelsvorderingen (> 1 jaar) - Toevoegingen" },
	{ "633100", "R\xE9""ductions de valeur sur cr\xE9""ances commerciales (> 1 an) - Reprises (-)", "Waardeverminderingen op handelsvorderingen (> 1 jaar) - Terugnemingen (-)" },
	{ "634", "R\xE9""ductions de valeur sur cr\xE9""ances \xE0"" un an au plus", "Waardeverminderingen op handelsvorderingen op ten hoogste \xE9""\xE9""n jaar" },
	{ "634000", "R\xE9""ductions de valeur sur cr\xE9""ances commerciales - Dotations", "Waardeverminderingen op handelsvorderingen - Toevoegingen" },
	{ "634100", "R\xE9""ductions de valeur sur cr\xE9""ances commerciales - Reprises (-)", "Waardeverminderingen op handelsvorderingen - Terugnemingen (-)" },
	{ "635", "Provisions pour pensions et obligations similaires", "Voorzieningen voor pensioenen en soortgelijke verplichtingen" },
	{ "635000", "Provisions pour pensions et obligations similaires - Dotations", "Voorzieningen voor pensioenen en soortgelijke verplichtingen - Toevoegingen" },
	{ "635100", "Provisions pour pensions et obligations similaires - Utilisations et reprises (-)", "Voorzieningen voor pensioenen en soortgelijke verplichtingen - Bestedingen en terugnemingen (-)" },
	{ "636", "Provisions pour grosses r\xE9""parations et gros entretiens", "Voorzieningen voor grote herstellingswerken en grote onderhoudswerken" },
	{ "636000", "Provisions pour grosses r\xE9""parations et gros entretien - Dotations", "Voorzieningen voor grote herstellings- en onderhoudswerken - Toevoegingen" },
	{ "636100", "Provisions pour grosses r\xE9""parations et gros entretien - Utilisations et reprises (-)", "Voorzieningen voor grote herstellings- en onderhoudswerken - Bestedingen en terugnemingen (-)" },
	{ "637", "Provisions pour obligations environnementales", "Voorzieningen voor milieuverplichtingen" },
	{ "637000", "Provisions pour obligations environnementales - Dotations", "Voorzieningen voor milieuverplichtingen - Toevoegingen" },
	{ "637100", "Provisions pour obligations environnementales - Utilisations et reprises (-)", "Voorzieningen voor milieuverplichtingen - Bestedingen en terugnemingen (-)" },
	{ "638", "Provisions pour autres risques et charges", "Voorzieningen voor andere risico's en kosten" },
	{ "638000", "Provisions pour autres risques et charges - Dotations", "Voorzieningen voor andere risico's en kosten - Toevoegingen" },
	{ "638100", "Provisions pour autres risques et charges - Utilisations et reprises (-)", "Voorzieningen voor andere risico's en kosten - Bestedingen en terugnemingen (-)" },
	{ "64", "Autres charges d'exploitation", "Andere bedrijfskosten" },
	{ "640", "Charges fiscales d'exploitation", "Bedrijfsbelastingen" },
	{ "640000", "Charges fiscales d'exploitation", "Bedrijfsbelastingen" },
	{ "640200", "Taxes sur les voitures", "Belastingen op auto's" },
	{ "640201", "Taxes sur les motos", "Belastingen op motorfietsen" },
	{ "640202", "Taxes sur les v\xE9""hicules utilitaires", "Belastingen op bedrijfsvoertuigen" },
	{ "640400", "Taxes r\xE9""gionales", "Gewestbelastingen" },
	{ "640500", "Droits d'enregistrement et publications l\xE9""gales", "Registratierechten en wettelijke publicaties" },
	{ "640600", "Taxes provinciales et communales", "Provinciale en gemeentelijke belastingen" },
	{ "640800", "Droits de douane et accises", "Douanerechten en accijnzen" },
	{ "641", "Moins-values sur r\xE9""alisations courantes d'immobilisations corporelles", "Minderwaarden op de courante realisatie van vaste activa" },
	{ "641000", "Moins-values sur r\xE9""alisations courantes d'immobilisations corporelles", "Minderwaarden bij de courante realisatie van materi\xEB""le vaste activa" },
	{ "642", "Moins-values sur r\xE9""alisations de cr\xE9""ances commerciales", "Minderwaarden op de realisatie van handelsvorderingen" },
	{ "642000", "Moins-values sur r\xE9""alisations de cr\xE9""ances commerciales", "Minderwaarden op de realisatie van handelsvorderingen" },
	{ "643", "Charges d'exploitation diverses", "Diverse bedrijfskosten" },
	{ "643000", "Charges d'exploitation diverses", "Diverse bedrijfskosten" },
	{ "645000", "Amendes", "Boetes" },
	{ "649", "Charges d'exploitation port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde bedrijfskosten (-)" },
	{ "649000", "Charges d'exploitation port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde bedrijfskosten (-)" },
	{ "65", "Charges financi\xE8""res", "Financi\xEB""le kosten" },
	{ "650", "Charges des dettes", "Kosten van schulden" },
	{ "650000", "Int\xE9""r\xEA""ts, commissions et frais aff\xE9""rents aux dettes", "Rente, commissies en kosten verbonden aan schulden" },
	{ "650100", "Amortissement des frais d'\xE9""mission d'emprunts", "Afschrijving van kosten bij uitgifte van leningen" },
	{ "650200", "Int\xE9""r\xEA""ts intercalaires port\xE9""s \xE0"" l'actif (-)", "Geactiveerde intercalaire interesten (-)" },
	{ "651", "R\xE9""ductions de valeur sur actifs circulants", "Waardeverminderingen op vlottende activa" },
	{ "651000", "R\xE9""ductions de valeur sur actifs circulants - Dotations", "Waardeverminderingen op vlottende activa - Toevoegingen" },
	{ "651100", "R\xE9""ductions de valeur sur actifs circulants - Reprises (-)", "Waardeverminderingen op vlottende activa - Terugnemingen (-)" },
	{ "652", "Moins-values sur r\xE9""alisation d'actifs circulants", "Minderwaarden op de realisatie van vlottende activa" },
	{ "652000", "Moins-values sur r\xE9""alisation d'actifs circulants", "Minderwaarden bij de realisatie van vlottende activa" },
	{ "653", "Charges d'escompte de cr\xE9""ances", "Discontokosten op vorderingen" },
	{ "653000", "Charges d'escompte de cr\xE9""ances", "Discontokosten op vorderingen" },
	{ "654", "Diff\xE9""rences de change", "Wisselresultaten" },
	{ "654000", "Diff\xE9""rences de change", "Wisselresultaten" },
	{ "655", "\xC9""carts de conversion des devises", "Resultaten uit de omrekening van vreemde valuta" },
	{ "655000", "\xC9""carts de conversion des devises", "Resultaten uit de omrekening van vreemde valuta" },
	{ "656", "Provisions \xE0"" caract\xE8""re financier", "Voorzieningen met financieel karakter" },
	{ "656000", "Provisions \xE0"" caract\xE8""re financier - Dotations", "Voorzieningen met financieel karakter - Toevoegingen" },
	{ "656100", "Provisions \xE0"" caract\xE8""re financier - Utilisations et reprises (-)", "Voorzieningen met financieel karakter - Bestedingen en terugnemingen (-)" },
	{ "657000", "Escomptes financiers accord\xE9""s", "Toegekende financi\xEB""le kortingen" },
	{ "657100", "Diff\xE9""rences de paiement n\xE9""gatives", "Negatieve betalingsverschillen" },
	{ "657200", "Frais bancaires", "Bankkosten" },
	{ "659", "Charges financi\xE8""res port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde financi\xEB""le kosten (-)" },
	{ "659000", "Charges financi\xE8""res port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde financi\xEB""le kosten (-)" },
	{ "66", "Charges d'exploitation et charges financi\xE8""res non r\xE9""currentes", "Niet-recurrente bedrijfs- of financi\xEB""le kosten" },
	{ "660", "Amortissements et r\xE9""ductions de valeur non r\xE9""currents (dotations)", "Niet-recurrente afschrijvingen en waardeverminderingen (toevoeging)" },
	{ "660000", "Amortissements et r\xE9""ductions de valeur non r\xE9""currents (dotations) sur frais d'\xE9""tablissement", "Niet-recurrente afschrijvingen en waardeverminderingen (toevoeging) op oprichtingskosten" },
	{ "660100", "Amortissements et r\xE9""ductions de valeur non r\xE9""currents (dotations) sur immobilisations incorporelles", "Niet-recurrente afschrijvingen en waardeverminderingen (toevoeging) op immateri\xEB""le vaste activa" },
	{ "660200", "Amortissements et r\xE9""ductions de valeur non r\xE9""currents (dotations) sur immobilisations corporelles", "Niet-recurrente afschrijvingen en waardeverminderingen (toevoeging) op materi\xEB""le vaste activa" },
	{ "661", "R\xE9""duction de valeur sur immobilisations financi\xE8""res (dotation)", "Waardeverminderingen op financi\xEB""le vaste activa (toevoeging)" },
	{ "661000", "R\xE9""ductions de valeur sur immobilisations financi\xE8""res (dotation)", "Waardeverminderingen op financi\xEB""le vaste activa (toevoeging)" },
	{ "662", "Provisions pour risques et charges non r\xE9""currents", "Voorzieningen voor niet-recurrente risico's en kosten" },
	{ "662000", "Provisions pour risques et charges d'exploitation non r\xE9""currents - Dotations", "Voorzieningen voor niet-recurrente bedrijfsrisico's en -kosten - Toevoegingen" },
	{ "662010", "Provisions pour risques et charges d'exploitation non r\xE9""currents - Utilisations (-)", "Voorzieningen voor niet-recurrente bedrijfsrisico's en -kosten - Bestedingen (-)" },
	{ "662100", "Provisions pour risques et charges financiers non r\xE9""currents - Dotations", "Voorzieningen voor niet-recurrente financi\xEB""le risico's en kosten - Toevoegingen" },
	{ "662110", "Provisions pour risques et charges financiers non r\xE9""currents - Utilisations (-)", "Voorzieningen voor niet-recurrente financi\xEB""le risico's en kosten - Bestedingen (-)" },
	{ "663", "Moins-values sur r\xE9""alisation d'actifs immobilis\xE9""s", "Minderwaarden op de realisatie van vaste activa" },
	{ "663000", "Moins-values sur r\xE9""alisation d'immobilisations incorporelles et corporelles", "Minderwaarden op de realisatie van immateri\xEB""le en materi\xEB""le vaste activa" },
	{ "663100", "Moins-values sur r\xE9""alisation d'immobilisations financi\xE8""res", "Minderwaarden op de realisatie van financi\xEB""le vaste activa" },
	{ "664", "Autres charges d'exploitation non r\xE9""currentes", "Andere niet-recurrente bedrijfskosten" },
	{ "664000", "Autres charges d'exploitation non r\xE9""currentes", "Andere niet-recurrente bedrijfskosten" },
	{ "668", "Autres charges financi\xE8""res non r\xE9""currentes", "Andere niet-recurrente financi\xEB""le kosten" },
	{ "668000", "Autres charges financi\xE8""res non r\xE9""currentes", "Andere niet-recurrente financi\xEB""le kosten" },
	{ "669", "Charges non r\xE9""currentes port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde niet-recurrente kosten (-)" },
	{ "669000", "Charges d'exploitation non r\xE9""currentes port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde niet-recurrente bedrijfskosten (-)" },
	{ "669100", "Charges financi\xE8""res non r\xE9""currentes port\xE9""es \xE0"" l'actif au titre de frais de restructuration (-)", "Als herstructureringskosten geactiveerde niet-recurrente financi\xEB""le kosten (-)" },
	{ "67", "Imp\xF4""ts sur le r\xE9""sultat", "Belastingen op het resultaat" },
	{ "670", "Imp\xF4""ts belges sur le r\xE9""sultat de l'exercice", "Belgische belastingen op het resultaat van het boekjaar" },
	{ "670000", "Imp\xF4""ts et pr\xE9""comptes dus ou vers\xE9""s sur le r\xE9""sultat de l'exercice", "Verschuldigde of gestorte belastingen en voorheffingen op het resultaat van het boekjaar" },
	{ "670100", "Exc\xE9""dent de versements d'imp\xF4""ts et de pr\xE9""comptes port\xE9"" \xE0"" l'actif sur le r\xE9""sultat de l'exercice (-)", "Geactiveerde overschotten van betaalde belastingen en voorheffingen op het resultaat van het boekjaar (-)" },
	{ "670200", "Charges fiscales estim\xE9""es sur le r\xE9""sultat de l'exercice", "Geraamde belastingen op het resultaat van het boekjaar" },
	{ "671", "Imp\xF4""ts belges sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Belgische belastingen op het resultaat van vorige boekjaren" },
	{ "671000", "Suppl\xE9""ments d'imp\xF4""ts dus ou vers\xE9""s sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Verschuldigde of gestorte belastingsupplementen op het resultaat van vorige boekjaren" },
	{ "671100", "Suppl\xE9""ments d'imp\xF4""ts estim\xE9""s sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Geraamde belastingsupplementen op het resultaat van vorige boekjaren" },
	{ "671200", "Provisions fiscales constitu\xE9""es sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Gevormde fiscale voorzieningen op het resultaat van vorige boekjaren" },
	{ "672", "Imp\xF4""ts \xE9""trangers sur le r\xE9""sultat de l'exercice", "Buitenlandse belastingen op het resultaat van het boekjaar" },
	{ "672000", "Imp\xF4""ts \xE9""trangers sur le r\xE9""sultat de l'exercice", "Buitenlandse belastingen op het resultaat van het boekjaar" },
	{ "673", "Imp\xF4""ts \xE9""trangers sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Buitenlandse belastingen op het resultaat van vorige boekjaren" },
	{ "673000", "Imp\xF4""ts \xE9""trangers sur le r\xE9""sultat d'exercices ant\xE9""rieurs", "Buitenlandse belastingen op het resultaat van vorige boekjaren" },
	{ "68", "Transferts aux imp\xF4""ts diff\xE9""r\xE9""s et aux r\xE9""serves immunis\xE9""es", "Overboeking naar de uitgestelde belastingen en naar de belastingvrije reserves" },
	{ "680", "Transferts aux imp\xF4""ts diff\xE9""r\xE9""s", "Overboeking naar de uitgestelde belastingen" },
	{ "680000", "Transfert aux imp\xF4""ts diff\xE9""r\xE9""s", "Overboeking naar de uitgestelde belastingen" },
	{ "689", "Transferts aux r\xE9""serves immunis\xE9""es", "Overboeking naar de belastingvrije reserves" },
	{ "689000", "Transfert aux r\xE9""serves immunis\xE9""es", "Overboeking naar de belastingvrije reserves" },
	{ "69", "Affectations et pr\xE9""l\xE8""vements", "Resultatenverwerking" },
	{ "690", "Perte report\xE9""e de l'exercice pr\xE9""c\xE9""dent", "Overgedragen verlies van het vorige boekjaar" },
	{ "690000", "Perte report\xE9""e de l'exercice pr\xE9""c\xE9""dent", "Overgedragen verlies van het vorige boekjaar" },
	{ "691", "Affectations \xE0"" l'apport", "Toevoeging aan de inbreng" },
	{ "691000", "Affectations \xE0"" l'apport", "Toevoeging aan de inbreng" },
	{ "692", "Dotation aux r\xE9""serves", "Toevoeging aan de reserves" },
	{ "692000", "Dotation \xE0"" la r\xE9""serve l\xE9""gale", "Toevoeging aan de wettelijke reserve" },
	{ "692100", "Dotation aux autres r\xE9""serves", "Toevoeging aan de overige reserves" },
	{ "693", "B\xE9""n\xE9""fices \xE0"" reporter", "Over te dragen winst" },
	{ "693000", "B\xE9""n\xE9""fices \xE0"" reporter", "Over te dragen winst" },
	{ "694", "R\xE9""mun\xE9""ration de l'apport", "Vergoeding van de inbreng" },
	{ "694000", "R\xE9""mun\xE9""ration de l'apport", "Vergoeding van de inbreng" },
	{ "695", "Administrateurs ou g\xE9""rants", "Bestuurders of zaakvoerders" },
	{ "695000", "Distribution aux administrateurs ou g\xE9""rants", "Uitkering aan bestuurders of zaakvoerders" },
	{ "696", "Employ\xE9""s", "Werknemers" },
	{ "696000", "Distribution aux employ\xE9""s", "Uitkering aan werknemers" },
	{ "697", "Autres applications", "Andere rechthebbenden" },
	{ "697000", "Distribution aux autres allocataires", "Uitkering aan andere rechthebbenden" },
	{ "7", "Produits", "Opbrengsten" },
	{ "70", "Chiffre d'affaires", "Omzet" },
	{ "700000", "Ventes de marchandises en Belgique", "Verkoop van goederen in Belgi\xEB""" },
	{ "700100", "Services en Belgique", "Diensten in Belgi\xEB""" },
	{ "700500", "Ventes co-contractant", "Verkopen medecontractant" },
	{ "700600", "Ventes livraisons intracommunautaires", "Intracommunautaire leveringen" },
	{ "700610", "Ventes services intracommunautaires", "Intracommunautaire diensten" },
	{ "700700", "Ventes hors EU", "Verkopen buiten de EU" },
	{ "708", "Remises, ristournes et rabais accord\xE9""s (-)", "Toegekende kortingen, ristorno's en rabatten (-)" },
	{ "708000", "Remises, ristournes et rabais accord\xE9""s (-)", "Toegekende kortingen, ristorno's en rabatten (-)" },
	{ "709000", "Arrondissement des paiements en Euros", "Afronding van betalingen in euro" },
	{ "71", "Variation des stocks et des commandes en cours d'ex\xE9""cution", "Wijzigingen in de voorraden en in de bestellingen in uitvoering" },
	{ "712", "des en-cours de fabrication", "in de voorraad goederen in bewerking" },
	{ "712000", "Variations des stocks d'en-cours de fabrication", "Wijzigingen in de voorraad goederen in bewerking" },
	{ "713", "des produits finis", "in de voorraad gereed product" },
	{ "713000", "Variations des stocks de produits finis", "Wijzigingen in de voorraad gereed product" },
	{ "715", "des immeubles construits destin\xE9""s \xE0"" la vente", "in de voorraad onroerende goederen bestemd voor verkoop" },
	{ "715000", "Variations des stocks des immeubles construits destin\xE9""s \xE0"" la vente", "Wijzigingen in de voorraad onroerende goederen bestemd voor verkoop" },
	{ "717", "des commandes en cours d'ex\xE9""cution", "in de bestellingen in uitvoering" },
	{ "717000", "Variations des commandes en cours d'ex\xE9""cution - Valeur d'acquisition", "Wijzigingen in de bestellingen in uitvoering - Aanschaffingswaarde" },
	{ "717100", "Variations des commandes en cours d'ex\xE9""cution - B\xE9""n\xE9""fice pris en compte", "Wijzigingen in de bestellingen in uitvoering - Toegerekende winst" },
	{ "72", "Production immobilis\xE9""e", "Geproduceerde vaste activa" },
	{ "720000", "Production immobilis\xE9""e", "Geproduceerde vaste activa" },
	{ "74", "Autres produits d'exploitation", "Andere bedrijfsopbrengsten" },
	{ "740", "Subsides d'exploitation et montants compensatoires", "Bedrijfssubsidies en compenserende bedragen" },
	{ "740000", "Subsides d'exploitation et montants compensatoires", "Bedrijfssubsidies en compenserende bedragen" },
	{ "741", "Plus-values sur r\xE9""alisations courantes d'immobilisations corporelles", "Meerwaarden op de courante realisatie van materi\xEB""le vaste activa" },
	{ "741000", "Plus-values sur r\xE9""alisations courantes d'immobilisations corporelles", "Meerwaarden op de courante realisatie van materi\xEB""le vaste activa" },
	{ "742", "Plus-values sur r\xE9""alisations de cr\xE9""ances commerciales", "Meerwaarden op de realisatie van handelsvorderingen" },
	{ "742000", "Plus-values sur r\xE9""alisation de cr\xE9""ances commerciales", "Meerwaarden op de realisatie van handelsvorderingen" },
	{ "743", "Produits d'exploitation divers", "Diverse bedrijfsopbrengsten" },
	{ "743000", "Produits d'exploitation divers", "Diverse bedrijfsopbrengsten" },
	{ "75", "Produits financiers", "Financi\xEB""le opbrengsten" },
	{ "750", "Produits des immobilisations financi\xE8""res", "Opbrengsten uit financi\xEB""le vaste activa" },
	{ "750000", "Produits des immobilisations financi\xE8""res", "Opbrengsten uit financi\xEB""le vaste activa" },
	{ "751", "Produits des actifs circulants", "Opbrengsten uit vlottende activa" },
	{ "751000", "Produits des actifs circulants", "Opbrengsten uit vlottende activa" },
	{ "752", "Plus-values sur r\xE9""alisation d'actifs circulants", "Meerwaarden op de [...] realisatie van vlottende activa" },
	{ "752000", "Plus-values sur r\xE9""alisation d'actifs circulants", "Meerwaarden op de realisatie van vlottende activa" },
	{ "753", "Subsides en capital et en int\xE9""r\xEA""ts", "Kapitaal- en interestsubsidies" },
	{ "753000", "Subsides en capital et en int\xE9""r\xEA""ts", "Kapitaal- en interestsubsidies" },
	{ "754", "Diff\xE9""rences de change", "Wisselresultaten" },
	{ "754000", "Diff\xE9""rences de change", "Wisselresultaten" },
	{ "755", "\xC9""carts de conversion des devises", "Resultaten uit de omrekening van vreemde valuta" },
	{ "755000", "\xC9""carts de conversion des devises", "Resultaten uit de omrekening van vreemde valuta" },
	{ "756", "Produits financiers divers", "Diverse financi\xEB""le opbrengsten" },
	{ "756000", "Produits financiers divers", "Diverse financi\xEB""le opbrengsten" },
	{ "757000", "Escomptes financiers obtenus", "Verkregen financi\xEB""le kortingen" },
	{ "757100", "Diff\xE9""rences de paiement positives", "Positieve betalingsverschillen" },
	{ "76", "Produits d'exploitation ou financiers non r\xE9""currents", "Niet-recurrente bedrijfs- of financi\xEB""le opbrengsten" },
	{ "760", "Reprises d'amortissements et de r\xE9""ductions de valeur", "Terugneming van afschrijvingen en waardeverminderingen" },
	{ "760000", "Reprises d'amortissements et de r\xE9""ductions de valeur sur immobilisations incorporelles", "Terugneming van afschrijvingen en waardeverminderingen op immateri\xEB""le vaste activa" },
	{ "760100", "Reprises d'amortissements et de r\xE9""ductions de valeur sur immobilisations corporelles", "Terugneming van afschrijvingen en waardeverminderingen op materi\xEB""le vaste activa" },
	{ "761", "Reprises de r\xE9""ductions de valeur sur immobilisations financi\xE8""res", "Terugneming van waardeverminderingen op financi\xEB""le vaste activa" },
	{ "761000", "Reprises de r\xE9""ductions de valeur sur immobilisations financi\xE8""res", "Terugneming van waardeverminderingen op financi\xEB""le vaste activa" },
	{ "762", "Reprises de provisions pour risques et charges non r\xE9""currents", "Terugneming van voorzieningen voor niet-recurrente risico's en kosten" },
	{ "762000", "Reprises de provisions pour risques et charges d'exploitation non r\xE9""currents", "Terugneming van voorzieningen voor niet-recurrente bedrijfsrisico's en -kosten" },
	{ "762100", "Reprises de provisions pour risques et charges financiers non r\xE9""currents", "Terugneming van voorzieningen voor niet-recurrente financi\xEB""le risico's en kosten" },
	{ "763", "Plus-values sur r\xE9""alisation d'actifs immobilis\xE9""s", "Meerwaarden op de realisatie van vaste activa" },
	{ "763000", "Plus-values sur r\xE9""alisation d'immobilisations incorporelles et corporelles", "Meerwaarden op de realisatie van immateri\xEB""le en materi\xEB""le vaste activa" },
	{ "763100", "Plus-values sur r\xE9""alisation d'immobilisations financi\xE8""res", "Meerwaarden op de realisatie van financi\xEB""le vaste activa" },
	{ "764", "Autres b\xE9""n\xE9""fices d'exploitation non r\xE9""currents", "Andere niet-recurrente bedrijfsopbrengsten" },
	{ "764000", "Autres b\xE9""n\xE9""fices d'exploitation non r\xE9""currents", "Andere niet-recurrente bedrijfsopbrengsten" },
	{ "769", "Autres produits financiers non r\xE9""currents", "Andere niet-recurrente financi\xEB""le opbrengsten" },
	{ "769000", "Autres produits financiers non r\xE9""currents", "Andere niet-recurrente financi\xEB""le opbrengsten" },
	{ "77", "R\xE9""gularisations d'imp\xF4""ts et reprises de provisions fiscales", "Regularisering van belastingen en terugneming van fiscale voorzieningen" },
	{ "771", "Imp\xF4""ts belges sur le r\xE9""sultat", "Belgische belastingen op het resultaat" },
	{ "771000", "R\xE9""gularisations d'imp\xF4""ts dus ou vers\xE9""s", "Regularisering van verschuldigde of betaalde belastingen" },
	{ "771100", "R\xE9""gularisations d'imp\xF4""ts estim\xE9""s", "Regularisering van geraamde belastingen" },
	{ "771200", "Reprises de provisions fiscales", "Terugneming van fiscale voorzieningen" },
	{ "773", "Imp\xF4""ts \xE9""trangers sur le r\xE9""sultat", "Buitenlandse belastingen op het resultaat" },
	{ "773000", "R\xE9""gularisations d'imp\xF4""ts \xE9""trangers sur le r\xE9""sultat", "Regularisering van buitenlandse belastingen op het resultaat" },
	{ "78", "Pr\xE9""l\xE8""vements sur les r\xE9""serves immunis\xE9""es et les imp\xF4""ts diff\xE9""r\xE9""s", "Onttrekkingen aan de belastingvrije reserves en uitgestelde belastingen" },
	{ "780", "Pr\xE9""l\xE8""vements sur les imp\xF4""ts diff\xE9""r\xE9""s", "Onttrekkingen aan de uitgestelde belastingen" },
	{ "780000", "Pr\xE9""l\xE8""vement sur les imp\xF4""ts diff\xE9""r\xE9""s", "Onttrekking aan de uitgestelde belastingen" },
	{ "789", "Pr\xE9""l\xE8""vement sur les r\xE9""serves immunis\xE9""es", "Onttrekkingen aan de belastingvrije reserves" },
	{ "789000", "Pr\xE9""l\xE8""vement sur les r\xE9""serves immunis\xE9""es", "Onttrekking aan de belastingvrije reserves" },
	{ "79", "Affectations et pr\xE9""l\xE8""vements", "Resultaatverwerking" },
	{ "790", "B\xE9""n\xE9""fice report\xE9"" de l'exercice pr\xE9""c\xE9""dent", "Overgedragen winst van het vorige boekjaar" },
	{ "790000", "B\xE9""n\xE9""fice report\xE9"" de l'exercice pr\xE9""c\xE9""dent", "Overgedragen winst van het vorige boekjaar" },
	{ "791", "Pr\xE9""l\xE8""vements sur l'apport", "Onttrekking aan de inbreng" },
	{ "791000", "Pr\xE9""l\xE8""vements sur l'apport", "Onttrekking aan de inbreng" },
	{ "792", "Pr\xE9""l\xE8""vements sur les r\xE9""serves", "Onttrekking aan de reserves" },
	{ "792000", "Pr\xE9""l\xE8""vements sur les r\xE9""serves", "Onttrekking aan de reserves" },
	{ "793", "Perte \xE0"" reporter", "Over te dragen verlies" },
	{ "793000", "Perte \xE0"" reporter", "Over te dragen verlies" },
	{ "794", "Intervention d'associ\xE9""s (ou du propri\xE9""taire) dans la perte", "Tussenkomst van vennoten (of van de eigenaar) in het verlies" },
	{ "794000", "Intervention des associ\xE9""s (ou du propri\xE9""taire) dans la perte", "Tussenkomst van vennoten (of van de eigenaar) in het verlies" },
};
enum { NPCMN = sizeof PCMN / sizeof PCMN[0] };

} // namespace lg

#endif
