/*
 * tools/tests/netsurf/crypto/mkvectors.js -- the answers pages/js-crypto.html checks NetSurf's
 * Web Crypto against, made by Node's WebCrypto (the same API as Chromium's; V8 + BoringSSL):
 * keys generated here and exported in every format, signatures, ciphertexts and derived bits.
 * NetSurf must import these keys, verify these signatures, decrypt these ciphertexts and
 * derive the same bits. Prints the JavaScript object the page embeds (VECTORS = ...).
 *
 *   node tools/tests/netsurf/crypto/mkvectors.js > tools/tests/netsurf/pages/js-crypto-vectors.js
 */
'use strict';
const { subtle } = globalThis.crypto;
const hex = b => Buffer.from(b instanceof ArrayBuffer ? new Uint8Array(b) : b).toString('hex');
const enc = s => new TextEncoder().encode(s);
const msg = enc('Onyx: the message signed, encrypted and hashed by the test');

async function main() {
	const V = { msg: hex(msg) };
	/* ECDSA and ECDH on the three curves */
	for (const curve of ['P-256', 'P-384', 'P-521']) {
		const kp = await subtle.generateKey({ name: 'ECDSA', namedCurve: curve }, true, ['sign', 'verify']);
		const hash = curve === 'P-256' ? 'SHA-256' : curve === 'P-384' ? 'SHA-384' : 'SHA-512';
		const sig = await subtle.sign({ name: 'ECDSA', hash }, kp.privateKey, msg);
		V['ecdsa_' + curve] = {
			hash,
			spki: hex(await subtle.exportKey('spki', kp.publicKey)),
			raw: hex(await subtle.exportKey('raw', kp.publicKey)),
			pkcs8: hex(await subtle.exportKey('pkcs8', kp.privateKey)),
			jwk: await subtle.exportKey('jwk', kp.privateKey),
			sig: hex(sig),
		};
		const a = await subtle.generateKey({ name: 'ECDH', namedCurve: curve }, true, ['deriveBits']);
		const b = await subtle.generateKey({ name: 'ECDH', namedCurve: curve }, true, ['deriveBits']);
		V['ecdh_' + curve] = {
			a_jwk: await subtle.exportKey('jwk', a.privateKey),
			b_spki: hex(await subtle.exportKey('spki', b.publicKey)),
			bits: hex(await subtle.deriveBits({ name: 'ECDH', public: b.publicKey }, a.privateKey, null)),
		};
	}
	/* RSA: one 2048-bit key, used for PKCS #1 v1.5, PSS and OAEP */
	const rsa = await subtle.generateKey({ name: 'RSA-PSS', modulusLength: 2048,
		publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' }, true, ['sign', 'verify']);
	const pkcs8 = await subtle.exportKey('pkcs8', rsa.privateKey);
	const spki = await subtle.exportKey('spki', rsa.publicKey);
	const imp = (name, usage, der, fmt, hash) => subtle.importKey(fmt, der, { name, hash: hash || 'SHA-256' }, true, [usage]);
	V.rsa = {
		pkcs8: hex(pkcs8), spki: hex(spki),
		jwk: await subtle.exportKey('jwk', rsa.privateKey),
		pss: hex(await subtle.sign({ name: 'RSA-PSS', saltLength: 32 }, rsa.privateKey, msg)),
		pkcs1: hex(await subtle.sign({ name: 'RSASSA-PKCS1-v1_5' },
			await imp('RSASSA-PKCS1-v1_5', 'sign', pkcs8, 'pkcs8'), msg)),
		oaep: hex(await subtle.encrypt({ name: 'RSA-OAEP', label: enc('label') },
			await imp('RSA-OAEP', 'encrypt', spki, 'spki'), enc('secret for OAEP'))),
	};
	/* symmetric: a key, and what Node made with it */
	const key = new Uint8Array(32).map((_, i) => i * 7 + 1);
	const iv = new Uint8Array(12).map((_, i) => 0xa0 + i);
	const aes = name => subtle.importKey('raw', key, name, true, ['encrypt', 'decrypt']);
	V.aes = {
		key: hex(key), iv: hex(iv),
		gcm: hex(await subtle.encrypt({ name: 'AES-GCM', iv, additionalData: enc('aad') }, await aes('AES-GCM'), msg)),
		gcm96: hex(await subtle.encrypt({ name: 'AES-GCM', iv, tagLength: 96 }, await aes('AES-GCM'), msg)),
		cbc: hex(await subtle.encrypt({ name: 'AES-CBC', iv: new Uint8Array(16).fill(3) }, await aes('AES-CBC'), msg)),
		ctr: hex(await subtle.encrypt({ name: 'AES-CTR', counter: new Uint8Array(16).fill(0xff), length: 8 }, await aes('AES-CTR'), msg)),
	};
	const kek = await subtle.importKey('raw', key.slice(0, 16), 'AES-KW', true, ['wrapKey', 'unwrapKey']);
	V.aes.kw = hex(await subtle.wrapKey('raw', await aes('AES-GCM'), kek, 'AES-KW'));
	const hk = await subtle.importKey('raw', key, 'HKDF', false, ['deriveBits']);
	V.hkdf = hex(await subtle.deriveBits({ name: 'HKDF', hash: 'SHA-384', salt: enc('salt'), info: enc('info') }, hk, 336));
	const pb = await subtle.importKey('raw', enc('password'), 'PBKDF2', false, ['deriveBits']);
	V.pbkdf2 = hex(await subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-512', salt: enc('NaCl'), iterations: 1000 }, pb, 512));
	const hm = await subtle.importKey('raw', key, { name: 'HMAC', hash: 'SHA-384' }, true, ['sign']);
	V.hmac384 = hex(await subtle.sign('HMAC', hm, msg));
	V.hmacJwk = await subtle.exportKey('jwk', hm);
	console.log('/* generated by tools/tests/netsurf/crypto/mkvectors.js (Node\'s WebCrypto): the answers js-crypto.html checks */');
	console.log('const VECTORS = ' + JSON.stringify(V, null, 1) + ';');
}
main();
