#!/usr/bin/env python3
"""gen_basfont.py -- build user/basic/basfont.h: the BASIC runtime's text fonts.

Code page 437 (the IBM PC / QBasic character set: frames, blocks, card suits, accents)
in the three QBasic cell heights -- 8 x 8 (SCREEN 1, 2, 7, 8, 13), 8 x 14 (SCREEN 9, 10)
and 8 x 16 (SCREEN 0, 11, 12, DRAWTEXT) -- plus the Latin-1 <-> CP437 tables (Onyx is
Latin-1: the keyboard, the editor, the file names).

The glyphs come from the VGA console fonts of Debian's console-setup (*-VGA8/14/16.psf.gz;
the 8 x 16 one is u_vga16.bdf, (c) 2000-2001 Dmitry Bolkhovityanov, MIT licence; the
console fonts are public domain by nature). Get them with:
    apt-get download console-setup-linux && dpkg-deb -x console-setup-linux_*.deb cs
    python3 tools/gen_basfont.py cs/usr/share/consolefonts
"""
import glob, gzip, os, struct, sys

def load(path):
    d = gzip.open(path).read()
    uni = {}
    if d[:2] == b'\x36\x04':                                  # PSF1
        mode, h = d[2], d[3]; n = 512 if mode & 1 else 256
        glyphs = [d[4 + i * h: 4 + (i + 1) * h] for i in range(n)]
        if mode & 2:
            p = 4 + n * h
            for i in range(n):
                while True:
                    u = struct.unpack('<H', d[p:p + 2])[0]; p += 2
                    if u == 0xFFFF: break
                    if u != 0xFFFE: uni.setdefault(u, i)
        return h, glyphs, uni
    _, _, hs, flags, n, bpg, h, w = struct.unpack('<8I', d[:32])  # PSF2
    glyphs = [d[hs + i * bpg: hs + (i + 1) * bpg] for i in range(n)]
    if flags & 1:
        p = hs + n * bpg
        for i in range(n):
            while True:
                b = d[p]
                if b == 0xFF: p += 1; break
                if b == 0xFE: p += 1; continue
                l = 1 if b < 0x80 else 2 if b < 0xE0 else 3 if b < 0xF0 else 4
                uni.setdefault(ord(d[p:p + l].decode('utf-8', 'replace')), i); p += l
    return h, glyphs, uni

LOW = "\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼"
def cp437(i):
    if i < 32: return ord(LOW[i])
    if i == 127: return 0x2302
    return ord(bytes([i]).decode('cp437'))
ALT = { 16: [0x25B6, 0x25B8], 17: [0x25C0, 0x25C2] }
# The two VGA arrows no font here has (IBM's own shapes).
HAND16 = {
    16: [0x00, 0x80, 0xC0, 0xE0, 0xF0, 0xF8, 0xFE, 0xF8, 0xF0, 0xE0, 0xC0, 0x80, 0x00, 0x00, 0x00, 0x00],
    17: [0x00, 0x02, 0x06, 0x0E, 0x1E, 0x3E, 0xFE, 0x3E, 0x1E, 0x0E, 0x06, 0x02, 0x00, 0x00, 0x00, 0x00],
}

def build(src, h):
    fonts = glob.glob(os.path.join(src, '*-VGA%d.psf.gz' % h))
    rank = lambda f: (0 if 'Uni2' in f else 1 if 'Lat15' in f else 2 if 'Uni1' in f else 3, f)
    got = {}
    for f in sorted(fonts, key=rank):
        fh, g, uni = load(f)
        if fh != h: continue
        for i in range(1, 256):
            if i in got: continue
            for u in [cp437(i)] + ALT.get(i, []):
                if u in uni: got[i] = bytes(g[uni[u]][:h]); break
    got[0] = bytes(h)
    return got

def shrink(g16, h):                  # a missing small glyph from the 8 x 16 one
    if h == 14: return bytes(g16[1:15])
    return bytes(g16[2 * k] | g16[2 * k + 1] for k in range(8))

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'cs/usr/share/consolefonts'
    f16 = build(src, 16)
    for i, rows in HAND16.items():
        if i not in f16: f16[i] = bytes(rows)
    out = {16: f16}
    for h in (14, 8):
        f = build(src, h)
        for i in range(256):		# missing, or blank where the 8 x 16 glyph is not
            if i not in f or (not any (f[i]) and any (f16[i])): f[i] = shrink(f16[i], h)
        out[h] = f
    # Latin-1 -> CP437 (the accents CP437 lacks: the plain letter), and back ('?').
    to437 = list(range(256)); to1 = list(range(256))
    for i in range(128, 256): to1[i] = ord('?')
    for i in range(1, 32): to1[i] = i
    for i in range(128, 256):
        c = bytes([i]).decode('latin-1')
        try: to437[i] = c.encode('cp437')[0]
        except UnicodeEncodeError:
            import unicodedata
            base = unicodedata.normalize('NFD', c)[0]
            try: to437[i] = base.encode('cp437')[0] if ord(base) < 128 else ord('?')
            except UnicodeEncodeError: to437[i] = ord('?')
    for i in range(128, 256):
        c = bytes([i]).decode('cp437')
        try: to1[i] = c.encode('latin-1')[0]
        except UnicodeEncodeError:
            box = '─━│┃┄┅┆┇┈┉┊┋┌┐└┘├┤┬┴┼═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬'
            to1[i] = ord('-') if c in '─═' else ord('|') if c in '│║' else ord('+') if c in box else ord('#') if c in '░▒▓█▄▌▐▀■' else ord('?')
    to437[0xA0] = 255
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'user', 'basic', 'basfont.h')
    with open(path, 'w') as o:
        o.write('//\n// basfont.h -- GENERATED by tools/gen_basfont.py: do not edit.\n//\n')
        o.write('// The BASIC text fonts: code page 437 (QBasic\'s character set), 8 x 8, 8 x 14 and\n')
        o.write('// 8 x 16, one byte per row (bit 7 = the leftmost pixel); and the Latin-1 <-> CP437\n')
        o.write('// tables. Glyphs from the VGA console fonts of Debian console-setup (u_vga16.bdf\n')
        o.write('// (c) 2000, 2001 Dmitry Bolkhovityanov, MIT licence; console fonts: public domain).\n//\n')
        o.write('#ifndef ONYX_BASFONT_H\n#define ONYX_BASFONT_H\n\n')
        o.write('#ifndef BASFONT_TABLES_ONLY\t\t// (the VM and the compiler only need the tables)\n')
        for h in (8, 14, 16):
            o.write('static const unsigned char basFont%d[256 * %d] = {\n' % (h, h))
            for i in range(256):
                o.write('\t' + ', '.join('0x%02X' % b for b in out[h][i]) + ',\t// %d\n' % i)
            o.write('};\n\n')
        o.write('#endif\n\n')
        for name, t in (('basLatin1To437', to437), ('bas437ToLatin1', to1)):
            o.write('static const unsigned char %s[256] = {\n' % name)
            for r in range(0, 256, 16):
                o.write('\t' + ', '.join('%3d' % v for v in t[r:r + 16]) + ',\n')
            o.write('};\n\n')
        o.write('#endif\n')
    print('wrote', path)

if __name__ == '__main__':
    main()
