#!/usr/bin/env python3
# MIT License -- Copyright (c) 2026 Stéphane Wegener and the Onyx contributors
#
# gen_kapi_names.py -- user/kapi_names.h from kernel/include/kern/kapi_abi.h: the name of each kapi
# table slot (the index of a TKApiTable field in 8-byte words: version = 0, create_window = 1, ...
# -- the number an EL0 stub puts in x8, the slots proc_stats reports). Run it after adding a kapi:
#
#     python3 tools/gen_kapi_names.py
import os, re, sys

ROOT = os.path.dirname (os.path.dirname (os.path.abspath (__file__)))
src = open (os.path.join (ROOT, "kernel/include/kern/kapi_abi.h"), encoding = "utf-8").read ()
body = re.search (r"^struct TKApiTable\s*\{(.*?)^\};", src, re.S | re.M).group (1)
body = re.sub (r"//[^\n]*", "", body)
names = ["version"]
for stmt in body.split (";"):
	stmt = stmt.strip ()
	if not stmt or stmt.startswith ("unsigned version"):
		continue
	m = re.search (r"\(\s*\*\s*(\w+)\s*\)", stmt)
	if not m:
		sys.exit ("gen_kapi_names: not a function pointer: %r" % stmt[:60])
	names.append (m.group (1))
ver = re.search (r"#define\s+KAPI_ABI_VERSION\s+(\d+)", src).group (1)
out = ["// kapi_names.h -- GENERATED by tools/gen_kapi_names.py from kern/kapi_abi.h (v%s): do not edit." % ver,
       "// The name of each kapi table slot (proc_stats' slots; the x8 of an EL0 stub).",
       "#ifndef KAPI_NAMES_H", "#define KAPI_NAMES_H", "",
       "#define KAPI_NAMES_COUNT %d" % len (names), "",
       "static const char *const kapi_slot_names[KAPI_NAMES_COUNT] = {"]
for i, n in enumerate (names):
	out.append ("\t\"%s\",\t// %d" % (n, i))
out += ["};", "", "static inline const char *kapi_slot_name (unsigned slot)",
        "{", "\treturn slot < KAPI_NAMES_COUNT ? kapi_slot_names[slot] : \"?\";", "}", "", "#endif", ""]
open (os.path.join (ROOT, "user/kapi_names.h"), "w", encoding = "utf-8").write ("\n".join (out))
print ("kapi_names.h: %d slots (v%s)" % (len (names), ver))
