/*
 * qpuasm -- the V3D QPU assembler (host tool) for the kernel's hand-written shaders
 * (kernel/sys/v3d_shaders.qasm -> v3d_shaders.inc: V3D 4.2, the Pi 4; v3d_shaders71.qasm ->
 * v3d_shaders71.inc: V3D 7.1, the Pi 5). The assembler itself is qpulib.c (also used at run time by
 * the apps); this reads the file, splits it at ".name NAME vertex|coord|frag" and writes a C header of
 * u64 arrays, each word commented with its disassembly. ".version 71" (before the first .name) makes
 * the file V3D 7.1's.
 *
 *   qpuasm in.qasm out.inc      assemble
 *   qpuasm [-v71] -d HEX ...    disassemble words
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "qpulib.h"

static int flush (const char *file, const char *name, int kind, const char *text, int firstLine, char *out, size_t *no, size_t cap)
{
	static uint64_t w[4096]; char err[512];
	int n = qpu_assemble (text, kind, w, 4096, err, sizeof err);
	if (n < 0) { fprintf (stderr, "%s: %s (the shader at line %d): %s\n", file, name, firstLine, err); return -1; }
	*no += (size_t) snprintf (out + *no, cap - *no, "static const u64 %s[] = {\n", name);
	for (int i = 0; i < n; i++)
		*no += (size_t) snprintf (out + *no, cap - *no, "\t0x%016llXull,\t// %s\n", (unsigned long long) w[i], qpu_disassemble (w[i]));
	*no += (size_t) snprintf (out + *no, cap - *no, "};\n");
	return n;
}

int main (int argc, char **argv)
{
	if (argc >= 2 && strcmp (argv[1], "-v71") == 0) { qpu_set_version (71); argv++; argc--; }
	if (argc >= 2 && strcmp (argv[1], "-d") == 0)
	{
		for (int i = 2; i < argc; i++)
		{
			uint64_t v = strtoull (argv[i], 0, 16);
			printf ("%016llX  %s\n", (unsigned long long) v, qpu_disassemble (v));
		}
		return 0;
	}
	if (argc != 3) { fprintf (stderr, "usage: qpuasm in.qasm out.inc | qpuasm -d HEX...\n"); return 2; }
	FILE *f = fopen (argv[1], "r");
	if (!f) { perror (argv[1]); return 1; }
	static char out[1 << 20]; size_t no = 0;
	static char text[1 << 18]; size_t nt = 0;
	no += (size_t) snprintf (out + no, sizeof out - no, "// Generated by tools/qpu/qpuasm from %s -- do not edit.\n", argv[1]);
	char buf[512], name[128] = "", kindName[32]; int kind = 0, line = 0, first = 0, count = 0, open = 0;
	while (fgets (buf, sizeof buf, f))
	{
		line++;
		if (strncmp (buf, ".version", 8) == 0)
		{
			int v = atoi (buf + 8);
			if (open || (v != 42 && v != 71)) { fprintf (stderr, "%s:%d: .version 42|71, before the first .name\n", argv[1], line); return 1; }
			qpu_set_version (v);
			no += (size_t) snprintf (out + no, sizeof out - no, "// V3D %d.%d\n", v / 10, v % 10);
			continue;
		}
		if (strncmp (buf, ".name", 5) == 0)
		{
			if (open) { text[nt] = 0; int n = flush (argv[1], name, kind, text, first, out, &no, sizeof out); if (n < 0) return 1; count += n; }
			kindName[0] = 0;
			if (sscanf (buf + 5, "%127s %31s", name, kindName) < 2) { fprintf (stderr, "%s:%d: .name NAME vertex|coord|frag\n", argv[1], line); return 1; }
			kind = !strcmp (kindName, "frag") ? QPU_FRAG : !strcmp (kindName, "coord") ? QPU_COORD : QPU_VERTEX;
			open = 1; nt = 0; first = line + 1;
			continue;
		}
		if (!open) { char *s = buf; while (*s == ' ' || *s == '\t') s++; if (*s && *s != '#' && *s != '\n') { fprintf (stderr, "%s:%d: an instruction before the first .name\n", argv[1], line); return 1; } continue; }
		size_t l = strlen (buf);
		if (nt + l + 1 < sizeof text) { memcpy (text + nt, buf, l); nt += l; }
	}
	fclose (f);
	if (open) { text[nt] = 0; int n = flush (argv[1], name, kind, text, first, out, &no, sizeof out); if (n < 0) return 1; count += n; }
	FILE *o = fopen (argv[2], "w");
	if (!o) { perror (argv[2]); return 1; }
	fwrite (out, 1, no, o);
	fclose (o);
	printf ("qpuasm: %d instructions -> %s\n", count, argv[2]);
	return 0;
}
