// layout_lock.cpp -- GENERATED by tools/libgen/layout.py: the layout lock of the shared library.
// The programs built against the library allocate, derive and read these classes with THESE sizes
// and offsets (uikit/abi.h). A static_assert that fails here means the change breaks every program
// already built: put the new field in the reserve instead (Widget::reserved_ / ext...). Only a class
// ADDED is a reason to regenerate this file (make uikit-layout-update).
#ifdef ONYX_LIB_BUILD
#include "onyxpp.hpp"
#include "uikit/uikit.h"
#include "uikit/abi.h"
#include "uikit/button.h"
#include "uikit/calendar.h"
#include "uikit/canvas.h"
#include "uikit/checkbox.h"
#include "uikit/colorpick.h"
#include "uikit/combobox.h"
#include "uikit/datagrid.h"
#include "uikit/dialog.h"
#include "uikit/dropdown.h"
#include "uikit/font.h"
#include "uikit/global.h"
#include "uikit/groupbox.h"
#include "uikit/icon.h"
#include "uikit/imagebox.h"
#include "uikit/knob.h"
#include "uikit/label.h"
#include "uikit/lang.h"
#include "uikit/layout.h"
#include "uikit/lcd.h"
#include "uikit/listbox.h"
#include "uikit/menu.h"
#include "uikit/numeric.h"
#include "uikit/paint.h"
#include "uikit/panel.h"
#include "uikit/progress.h"
#include "uikit/radio.h"
#include "uikit/richtextbox.h"
#include "uikit/root.h"
#include "uikit/scrollbar.h"
#include "uikit/segmented.h"
#include "uikit/skin.h"
#include "uikit/slider.h"
#include "uikit/splitter.h"
#include "uikit/tabhost.h"
#include "uikit/text.h"
#include "uikit/textarea.h"
#include "uikit/textbox.h"
#include "uikit/theme.h"
#include "uikit/toggle.h"
#include "uikit/toolbar.h"
#include "uikit/treeview.h"
#include "uikit/uikit.h"
#include "uikit/vpaint.h"
#include "uikit/vumeter.h"
#include "uikit/widget.h"

static_assert (sizeof (uikit::Button) == 296, "sizeof (Button) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Calendar) == 256, "sizeof (Calendar) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Canvas) == 56, "sizeof (Canvas) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Checkbox) == 312, "sizeof (Checkbox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ColorDialog) == 272, "sizeof (ColorDialog) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ColorPicker) == 248, "sizeof (ColorPicker) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Combobox) == 1832, "sizeof (Combobox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::DataGrid) == 3960, "sizeof (DataGrid) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::DatePicker) == 272, "sizeof (DatePicker) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Dropdown) == 272, "sizeof (Dropdown) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::FileDialog) == 12968, "sizeof (FileDialog) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Font) == 40, "sizeof (Font) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::GroupBox) == 280, "sizeof (GroupBox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::HSplitter) == 280, "sizeof (HSplitter) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::HorizontalStackPanel) == 240, "sizeof (HorizontalStackPanel) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Icon) == 328, "sizeof (Icon) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ImageBox) == 256, "sizeof (ImageBox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Knob) == 320, "sizeof (Knob) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Label) == 360, "sizeof (Label) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::LcdDisplay) == 352, "sizeof (LcdDisplay) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ListBox) == 280, "sizeof (ListBox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Menu) == 3088, "sizeof (Menu) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::MessageBox) == 256, "sizeof (MessageBox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Modal) == 232, "sizeof (Modal) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::NumericUpDown) == 272, "sizeof (NumericUpDown) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Panel) == 232, "sizeof (Panel) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::PopupMenu) == 592, "sizeof (PopupMenu) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Progress) == 240, "sizeof (Progress) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::RadioButton) == 312, "sizeof (RadioButton) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::RichTextBox) == 312, "sizeof (RichTextBox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Root) == 336, "sizeof (Root) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::RtStyle) == 4, "sizeof (RtStyle) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Scrollbar) == 248, "sizeof (Scrollbar) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::SegmentedControl) == 696, "sizeof (SegmentedControl) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Skin) == 48, "sizeof (Skin) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Slider) == 256, "sizeof (Slider) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Splitter) == 280, "sizeof (Splitter) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::TabHost) == 632, "sizeof (TabHost) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::TextFace) == 8, "sizeof (TextFace) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Textarea) == 296, "sizeof (Textarea) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Textbox) == 776, "sizeof (Textbox) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ToggleSwitch) == 312, "sizeof (ToggleSwitch) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ToolBar) == 344, "sizeof (ToolBar) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::ToolButton) == 320, "sizeof (ToolButton) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::TreeView) == 288, "sizeof (TreeView) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkBarDrag) == 2, "sizeof (UkBarDrag) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkCorner) == 292, "sizeof (UkCorner) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkFaceScope) == 16, "sizeof (UkFaceScope) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkNamedTheme) == 24, "sizeof (UkNamedTheme) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkPalette) == 28, "sizeof (UkPalette) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkTheme) == 44, "sizeof (UkTheme) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UkThumb) == 12, "sizeof (UkThumb) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::UniformGridLayout) == 248, "sizeof (UniformGridLayout) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::VPath) == 40, "sizeof (VPath) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::VSplitter) == 280, "sizeof (VSplitter) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::VerticalStackPanel) == 240, "sizeof (VerticalStackPanel) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::VuMeter) == 312, "sizeof (VuMeter) changed: programs built before break (uikit/abi.h)");
static_assert (sizeof (uikit::Widget) == 224, "sizeof (Widget) changed: programs built before break (uikit/abi.h)");
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
static_assert (__builtin_offsetof (uikit::Widget, canvas) == 8, "Widget::canvas moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, left) == 64, "Widget::left moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, tag) == 88, "Widget::tag moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, anchor) == 100, "Widget::anchor moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, transparent) == 112, "Widget::transparent moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, tip) == 128, "Widget::tip moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, parent) == 136, "Widget::parent moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, prevHandled) == 176, "Widget::prevHandled moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, ext) == 184, "Widget::ext moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Widget, reserved_) == 192, "Widget::reserved_ moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, px) == 0, "Canvas::px moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, w) == 8, "Canvas::w moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, stride) == 16, "Canvas::stride moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, owns) == 20, "Canvas::owns moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, capH) == 24, "Canvas::capH moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Canvas, ext) == 32, "Canvas::ext moved: programs built before break (uikit/abi.h)");
static_assert (__builtin_offsetof (uikit::Root, bg) == 224, "Root::bg moved: programs built before break (uikit/abi.h)");
#endif
