//
// kapi.h -- kernel API for EL1 apps (Option C). These are NOT syscalls: the app
// calls the kernel functions directly; their addresses are resolved at link time
// against the kernel's exported symbols (user/kernel_syms.ld, generated by the
// kernel build). The kernel runs them in this app's context (kernel is mapped in).
//
#ifndef _kapi_h
#define _kapi_h

#ifdef __cplusplus
extern "C" {
#endif

// Windowing
unsigned *kapi_create_window (int w, int h, const char *title);  // -> canvas (u32 0x00RRGGBB)
void      kapi_present (void);
unsigned  kapi_get_ticks (void);				// HZ ticks since boot
void      kapi_msleep (unsigned ms);
void      kapi_yield (void);
void      kapi_exit (int status);

// Console
int       kapi_write (int fd, const void *buf, unsigned len);

// Files (read-only) -- the motivation for direct calls
void     *kapi_open (const char *path);				// 0 on failure
int       kapi_read (void *handle, void *buf, unsigned len);	// bytes read, <0 error
unsigned  kapi_fsize (void *handle);
void      kapi_close (void *handle);

#ifdef __cplusplus
}
#endif

// Friendly aliases used by the demos.
static inline unsigned *create_window (int w, int h, const char *t) { return kapi_create_window (w, h, t); }
static inline void      present (void)             { kapi_present (); }
static inline unsigned  get_ticks (void)           { return kapi_get_ticks (); }
static inline void      msleep (unsigned ms)       { kapi_msleep (ms); }

#endif
