//
// kapi.h -- kernel API for EL1 apps (Option C). These are NOT syscalls: the app
// calls the kernel functions directly; their addresses are resolved at link time
// against the kernel's exported symbols (user/kernel_syms.ld, generated by the
// kernel build). The kernel runs them in this app's context (kernel is mapped in).
//
#ifndef _kapi_h
#define _kapi_h

#ifdef __cplusplus
extern "C" {
#endif

// Windowing
unsigned *kapi_create_window (int w, int h, const char *title);  // -> canvas (u32 0x00RRGGBB)

// Window creation flags (must match kern/gui/window.h).
#define WIN_FLAG_BORDERLESS	(1u << 0)	// no title bar / border / close box

// Create a window at an explicit outer position with flags. Pass x<0 or y<0 to
// auto-place (like kapi_create_window). flags = WIN_FLAG_* (e.g. borderless for a
// panel / popup). Returns the canvas, or 0 on failure.
unsigned *kapi_create_window_ex (int x, int y, int w, int h, const char *title,
				 unsigned flags);

// Resize the window's logical client area (clamped to the size it was CREATED with;
// create at the max you'll need, then grow/shrink). Canvas/VA unchanged. For the
// taskbar panel that grows as apps open. Returns the canvas, or 0.
unsigned *kapi_resize_window (int w, int h);

// Spawn another app by folder name ("xxx" => apps/xxx.app/main.elf). The shell
// uses this for quicklaunch + the app-list popup. Returns 1 on success.
int       kapi_launch (const char *name);

// Toggle a named app: launch it if not running (returns 1), else ask it to close
// (returns 0; -1 on error). The "apps" button uses this so a re-click closes the
// popup.
int       kapi_toggle_app (const char *name);

// Raise the named running app's window to the front. Returns 1 if raised, 0 if it
// isn't running. The panel/taskbar uses this so clicking an already-open app's icon
// brings its window forward instead of launching a second instance.
int       kapi_raise_app (const char *name);

// List currently-open apps (folder names of running, windowed tasks), one per
// '\n'-separated line in buf. Returns the count. Backs the taskbar section.
int       kapi_list_windows (char *buf, unsigned buf_size);

// Set the desktop wallpaper from a 24-bpp BMP (drawn behind all windows). 0 clears
// it. Returns 1 on success.
int       kapi_set_wallpaper (const char *bmp_path);

void      kapi_present (void);
unsigned  kapi_get_ticks (void);				// HZ ticks since boot
void      kapi_msleep (unsigned ms);
void      kapi_yield (void);
void      kapi_exit (int status);

// Widgets + events ----------------------------------------------------------
// Event kinds (must match kern/gui/window.h).
#define GUI_EVENT_CLICK		1
#define GUI_EVENT_CHECK_CHANGED	2
#define GUI_EVENT_TEXT_CHANGED	3

// Widget event handler: sender = the widget handle returned at creation, event =
// GUI_EVENT_*, value = payload (0 for a click). The kernel runs it in THIS app's
// context when the app pumps events.
typedef void (*gui_handler) (unsigned long sender, int event, long value);

// Widgets (coords relative to the client area). Each returns an opaque handle
// (also passed back to the handler as `sender`), or 0 on failure.
unsigned long kapi_add_button   (int x, int y, int w, int h, const char *label,
				 gui_handler handler);	// fires GUI_EVENT_CLICK
unsigned long kapi_add_label    (int x, int y, int w, int h, const char *text);
unsigned long kapi_add_checkbox (int x, int y, int w, int h, const char *label,
				 gui_handler handler);	// fires GUI_EVENT_CHECK_CHANGED
unsigned long kapi_add_textbox  (int x, int y, int w, int h,
				 gui_handler handler);	// fires GUI_EVENT_TEXT_CHANGED
unsigned long kapi_add_progress (int x, int y, int w, int h);	// display only (0..100)
unsigned long kapi_add_slider   (int x, int y, int w, int h,
				 gui_handler handler);	// fires GUI_EVENT_VALUE_CHANGED
unsigned long kapi_add_textarea (int x, int y, int w, int h,
				 gui_handler handler);	// multi-line editable; TEXT_CHANGED
unsigned long kapi_add_scrollbar_v (int x, int y, int w, int h,
				    gui_handler handler);  // vertical; VALUE_CHANGED (0..100)
unsigned long kapi_add_scrollbar_h (int x, int y, int w, int h,
				    gui_handler handler);  // horizontal; VALUE_CHANGED
unsigned long kapi_add_icon     (int x, int y, int w, int h, const char *bmp_path,
				 const char *label, gui_handler handler); // CLICK; bmp may be 0

// Query / update widget state.
int  kapi_widget_get_text    (unsigned long widget, char *buf, unsigned max); // -> length
void kapi_widget_set_text    (unsigned long widget, const char *text);
int  kapi_widget_get_checked (unsigned long widget);	// checkbox: 1 = checked
int  kapi_widget_get_value   (unsigned long widget);	// slider/progress: 0..100
void kapi_widget_set_value   (unsigned long widget, int value);	// icon: !=0 => triangle badge
void kapi_widget_set_rect    (unsigned long widget, int x, int y, int w, int h); // move/resize/hide
void kapi_widget_set_icon    (unsigned long widget, const char *bmp_path); // reload icon image

void      kapi_pump_events (void);	// dispatch pending events, non-blocking
void      kapi_wait_for_exit (void);	// pump until the close box is clicked
int       kapi_should_exit (void);	// 1 if the app was asked to close

// App enumeration + clock
// List installed apps: app folder basenames under /apps, one per '\n'-separated
// line in buf (NUL-terminated). Returns the count. (For the app-list popup.)
int       kapi_list_apps (char *buf, unsigned buf_size);
// Current local date/time (any pointer may be 0). Returns 1 if a real wall-clock
// time, 0 if only uptime is available (no RTC/NTP yet).
int       kapi_get_datetime (int *year, int *month, int *day,
			     int *hour, int *minute, int *second);

// Console
int       kapi_write (int fd, const void *buf, unsigned len);

// Files (read-only) -- the motivation for direct calls
void     *kapi_open (const char *path);				// 0 on failure
int       kapi_read (void *handle, void *buf, unsigned len);	// bytes read, <0 error
unsigned  kapi_fsize (void *handle);
void      kapi_close (void *handle);

#ifdef __cplusplus
}
#endif

// Friendly aliases used by the demos.
static inline unsigned *create_window (int w, int h, const char *t) { return kapi_create_window (w, h, t); }
static inline void      present (void)             { kapi_present (); }
static inline unsigned  get_ticks (void)           { return kapi_get_ticks (); }
static inline void      msleep (unsigned ms)       { kapi_msleep (ms); }
static inline unsigned long add_button (int x, int y, int w, int h, const char *l, gui_handler h2) { return kapi_add_button (x, y, w, h, l, h2); }
static inline void      pump_events (void)         { kapi_pump_events (); }
static inline int       should_exit (void)         { return kapi_should_exit (); }

#endif
